### ISSUE TITLE
Cleanup Action Interface

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1009]
The actions are a rarely used feature, which needs a lot of maintainment. We want to use the 3.0.0 release for removing unneeded actions. Let's use this issue for collecting comments related to the action interface.

**Comment by BenjaminRodenberg** [comment]
[This code](https://github.com/precice/precice/pull/935/files/0ee5d5af9f5a1393c49812dd6869808a45ce6aeb#diff-77d4c4cc6ff34a09a88b532f34bf52b866f14df95ab2d29643121a460877410cR28-R30) needs an update, if #935 gets merged.

**Comment by fsimonis** [comment]
This also includes the deprecated vertex normals #1000

**Comment by fsimonis** [comment]
Related to #1438

**Comment by uekerman** [comment]
We should also remove the deprecated ones:

```
REGULAR_PRIOR
REGULAR_POST
ON_EXCHANGE_PRIOR
ON_EXCHANGE_POST
```

They still exist on config level.
