### ISSUE TITLE
macOS build fails due to `bits/c++config.h`

### ISSUE THREAD

**Issue by oguzziya** [precice/precice#1011]
**Describe your setup**

Operating system : macOS Big Sur 11.2
preCICE Version: develop

macOS build fails with the error that `<bits/c++config.h>` cannot be found. The source of the error comes from [this line](https://github.com/precice/precice/blob/813de05a87270ae9194bb4a499895a9fab4caef9/src/utils/fmtSTL.hpp#L2). 

Apparently, everything works when this include is removed. It is a known issue that on some systems `bits/c++config.h` cannot be found and should be patched manually. For the macOS, the suggested solution is to compile with clang++ then link with g++ which is extremely fishy.

As far as i can see, this include can be removed safely. If it is not safe for other systems, we can include it conditionally

**Step To Reproduce**
1. Basic building

**Expected behaviour**
preCICE should compile without a problem.

**Comment by fsimonis** [comment]
Closed by #1017
