### ISSUE TITLE
Rename MasterSlave to something more appropriate

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1026]
**Please describe the problem you are trying to solve.**
In preCICE we use the terms master and slave to distinguish  between multiple ranks running in parallel.
These terms are archaic and have some baggage.
Alternatives have been discussed at about every other project meeting and it is finally time to come to a conclusion and move on.

Moving away from these wide-spread terms will break a widespread convention, but if one always follows conventions, one can never improve.

There are 3 main execution paths in preCICE:
* a Participant runs on a single process (size = 1)
* a Participant runs on multiple parallel processes (size > 1) and
  * the current rank is the "main rank" (aka master) who sometimes takes the leading role in coordination (rank = 0)
  * the current ranks is a rank who sometimes needs to be coordinated (aka slave) the aforementioned rank (rank > 0)

The direct interface to this information is the [`MasterSlave`](https://precice.org/doxygen/develop/classprecice_1_1utils_1_1MasterSlave.html) utility class, which provides this information based on its configured `size` and `rank`.

This terminology is also used for the communication between participants.
preCICE first connects master ranks of participants and then establishes a connection between slaves. 

**Alternative name for the class `MasterSlave`**

We use communication in 2 cases:
* inside a participant (MasterSlave) and
* between participants (M2N).

I propose to use another very common terminology from networking:
* use intra-communication (as in IntraNet) for the communication between ranks of a single participant
* use inter-communication  (as in InterNet) for the communication between participants

This allows us to rename `utils::MasterSlave` to `utils::IntraComm` or `utils::IntraCommunication`.

**Alternative names for the states master and slave**

The following is a table of alternatives I came across while researching this and that I picked up in discussions.
I numbered them to simplify the discussion.

Nr | master | slave | Opinion
--- | --- | --- | ---
1 | master | follower | :-1: :-1: :-1:
2 | leader | follower | :-1: :-1: :-1:
3 | primary | secondary | :+1: :+1: :+1: 
4 | main | secondary | :+1: :-1:
5 | agency | agent | :-1: :-1:
6 | coordinator | coordinated | :-1: :-1: 
7 | coordinator | node | :-1:
8 | controller | worker | :+1: :-1: :-1: 
9 | supervisor | worker | :+1: :-1: :-1:
10 | parent | child | :+1: :-1: :-1:

My current favourite is (3) as it does not impose additional relations.
However, it still isn't really fitting as for a non-parallel case, `isPimary() = false`.

**Comment by DavidSCN** [comment]
>     a Participant runs on a single process (size = 1)
>     a Participant runs on multiple parallel processes (size > 1) and
>          the current rank is the "main rank" (aka master) who sometimes takes the leading role in coordination (rank = 0)
>          the current ranks is a rank who sometimes needs to be coordinated (aka slave) the aforementioned rank (rank > 0)

Wouldn't it be possible to handle the first two cases as the same case? In the end, the serial participant is our supervisor rank?!

**Comment by BenjaminRodenberg** [comment]
My opinion (I don't have a strong opinion here and I am not too much into the master-slave communication and what it actually does) on this topic:

* From the list above I like
    * (4), because `main` is also used by github, but the `secondary` is not perfect in my opinion.
    * (8) & (9)
* I don't like
    * (1) Let's not use the term `master` or `slave` in any of the replacements, since then we might end up with 50% of the problem.
    * (5) & (6) terms are too similar and easy to mix up

I think wikipedia gives some more ideas here: https://en.wikipedia.org/wiki/Master/slave_(technology)#Replacements. I think parent/child is a good term and missing in the list above.

**Comment by fsimonis** [comment]
> Wouldn't it be possible to handle the first two cases as the same case? In the end, the serial participant is our supervisor rank?!

Sadly this is not the case.
A simple example is `map` of the Eigen RBF:
* non-parallel: Build matrix of data entries, map data, done
* rank 0: Gather data, build total data matrix, map data, partition, send partition data
* rank >0: Send data, receive data

**Comment by uekerman** [comment]
> Wouldn't it be possible to handle the first two cases as the same case? In the end, the serial participant is our supervisor rank?!

That's a different issue in my opinion (a complicated one). Let's do here "only" a simple renaming.

I like `utils::IntraComm`. Would this then also mean that we should rename `m2n`? That would be a different story then.

I think (8) and (9) is not a good idea as "worker" also has some baggage already (I guess particularly if combined with "master"). That would then only be a half-baked solution in my opinion.

I like (3) and (4).

**Comment by fsimonis** [comment]
> I like utils::IntraComm. Would this then also mean that we should rename m2n? That would be a different story then.

Let's only rename the MasterSlave here. Touching m2n is tricky as it would require to change every XML file as everyone uses at least one `m2n` tag.

**Comment by BenjaminRodenberg** [comment]
> > I think wikipedia gives some more ideas here: https://en.wikipedia.org/wiki/Master/slave_(technology)#Replacements. I think parent/child is a good term and missing in the list above.
> 
> I left parent/child out as it really doesn't fit our problem. Added it to the list.

If it does not fit our problem, then let's keep it out. You probably can judge on this much better than I can. Just though this wording slipped your attention and therefore commented on it.

**Comment by MakisH** [comment]
I like "pimary / secondary", I just hope there will be no confusion with the existing "first / second" participants.

The "main / secondary" is okeish, I just feel that they are not exactly opposites / complementary.

Would also something in the direction "steering / following" work? I don't like it, but maybe it sparks ideas. The "leader / follower" conflicts with the "first / second", I think, and does not convey the same message.

**Comment by KyleDavisSA** [comment]
My opinion, "primary / secondary" could work. I also like "master / puppet" as perhaps `secondary` might mean something else, whereas `puppet` is hardly used to describe something. But feel it is not a very popular option and I do not have strong feelings to push for it. I would be happy with 3,4, or 9.

**Comment by oguzziya** [comment]
Primary-secondary sounds good compared to other options. If we can still make suggestions, i might suggest alpha-beta, it might reduce the misunderstanding that can bear from primary/secondary.

**Comment by MakisH** [comment]
Maybe we could also get something from team sports. Any ideas from sports fans? (not me :grimacing: )

**Comment by uekerman** [comment]
like "pointguard / roleplayer" or "captain / runner"? :grin: 
or "pilot / rower" :see_no_evil:

**Comment by fsimonis** [comment]
I am not so keep about sport-inspired names. I would prefer to use something neutral.

Currently, the favourite option is `primary/secondary`.

If we select that version, we would end up with this:

```cpp
// Control flow
if (!utils::IntraComm::isParallel()) { }

if (utils::IntraComm::isPrimary()) { }

if (utils::IntraComm::isSecondary()) { }

// Iteration over secondary ranks
for ( int rank : utils::IntraComm::secondaryRanks()) { }
```

Further potential changes in Log messages
Old | New
--- | ---
Initialize master-slave communication | Initialize Intra-communication
Started event configure/com.initializeMasterSlaveCom | Started event configure/com.initializeIntraComm
Connecting Slave #0 to Master | Connecting Secondary Rank #0 to Primary
Setting up master communication to coupling partner/s | Setting up primary communication to coupling partner/s
Awaiting master connection from SolverTwo | Awaiting primary connection from SolverTwo
Masters are connected | Primary ranks are connected
Setting up preliminary slaves communication to coupling partner/s | Setting up preliminary secondary communication to coupling partner/s
Established  slaves connection to SolverOne | Established secondary connections to SolverOne

**Comment by fsimonis** [comment]
Have we converged to using `primary/secondary`?
Please "react" to this issue with :+1: or :-1: .

**Comment by DavidSCN** [comment]
I like the `primary` and `secondary` idea, but do all agree on the `inter` and `intra`? The formulation is accurate, but very similar. What about a more verbose version like `InterSolver` and `IntraParticipant`?!

**Comment by fsimonis** [comment]
Yes, they are short and similar. But this should not be a problem.

Inter-communication will only be used in log output with enough context not to confuse the user. It will only ever appear in the actual code once we refactor the communication handling. #618 #541

Intra-communication will be used in quite some places in the code and will most likely persist even after the refactor. It could be visible in the XML configuration at some point as we will need to rename the `<master/>` tag to something like `<intracom/> or `<com/>`.

Note that an intra-communication describes the one an only communication between local ranks.
The inter-communication in contrast is always bound to a Participant as it describes one of the possibly many inter-communication to other participants.

So also in code, there always needs to be some extra context.
```cpp
communication.intra().size()
// vs
communication.inter("Participant").size()
```  

> What about a more verbose version like InterSolver and IntraParticipant?!

The main problem here is that `Participant` and `Solver` are not the same. `Solver` is _generally_ used for the software, `Participant` _generally_ for the logical entity in the simulation. In preCICE we _generally_ use `Participant`.
So using Solver vs Participant will lead to confusion without having a real benefit.

**Comment by fsimonis** [comment]
Moved to 2.4.0 as this is not as straight-forward as it may seem.
Especially the logs often need complete rewording.

**Comment by IshaanDesai** [comment]
We did not really converge on whether we want to rename `utils::MasterSlave` to `utils::IntraComm` or `utils::IntraCommunication`. Opinions?

**Comment by DavidSCN** [comment]
I would vote for `IntraComm`. We use `comm` as an abbreviation for communication very frequently in preCICE and I think it is quite unique and saves some space.

**Comment by uekerman** [comment]
The folder and namespace in preCICE is called `com`. The classes typically have the full name, e.g. `MPICommunication`.
