### ISSUE TITLE
`make install` clears linked libraries not in the system search path

### ISSUE THREAD

**Issue by DavidSCN** [precice/precice#1046]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _CentOS Linux 8_
preCICE Version: 2.2.1

**Describe the problem**
I can compile preCICE successfully using `cmake` and defining all dependencies (in particular, PETSc) manually via `-DPETSC_DIR ...`. However, after calling `make install`,  the installed library `libprecice.so` does not find `libpetsc.so` any more, whereas the compiled library in the build directory links successfully against the specified PETSc version. PETSc is installed in a local directory which is not searched by the system automatically. 

**Step To Reproduce**
1. `make` 
2. `make install`

**Expected behaviour**
The link should not be deleted so that the installation works just as good as the compiled library in the build directory.

**Additional context**
Related discussion can be found here: https://stackoverflow.com/questions/42695839/cmake-make-install-does-not-link-against-libraries-in-ubuntu

**Comment by fsimonis** [comment]
This is the default behaviour of CMake.

While building, CMake uses `rpath` to inject search paths into shared libraries and executables. These are used by the dynamic linker when looking for shared libraries.
Doing this allows to build a library link it to an executable and run that executable without adding the build directory to `LD_LIBRARY_PATH` .
When installing libraries and executables, CMake removes these `rpath` entries as it hands over the responsibility of managing dependencies to the system.

To resolve this, you
* need to install PETSc in the system, or
* use a framework that makes packages available in another way (e.g. spack), or
* keep using precice from the build directory.

**Comment by DavidSCN** [comment]
The question form my side was more if we want to change the default behavior or not. In my opinion, it looks desirable to change this behavior, but there might be good reasons I am not aware of not to do this.

**Comment by fsimonis** [comment]
The default behaviour is perfectly fine and I wouldn't change it.
Using rpath in the build directory is a [convenience feature](https://cmake.org/cmake/help/latest/prop_tgt/SKIP_BUILD_RPATH.html) after all. 

> In my opinion, it looks desirable to change this behavior, but there might be good reasons I am not aware of not to do this.

What are the reasons to change it?

Installing the software in the system directories requires the dependencies to be installed and discoverable as well.
Installing the software in some custom prefix requires to manage this yourself. This can be done either by specifying the install rpath yourself [`CMAKE_INSTALL_RPATH`](https://cmake.org/cmake/help/v3.10/variable/CMAKE_INSTALL_RPATH.html), patching it separately (like spack does) or by expanding the ENV (like spack and modules do).

**Comment by DavidSCN** [comment]
Ok, then let me close this.
