### ISSUE TITLE
SCons: platform independent python include path

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#105]
To support different python platforms (e.g. python2/python3, also standard python, anaconda, windows?) it would be nice to have a platform independent SConstruct file. Changes introduced in https://github.com/precice/precice/commit/fad2e1a00bfe5b9468fcad7a10b880757334d2e9 led to a build fail, since the previously hard coded include paths are not available to the Travis system anymore. The dynamically created paths are fine for anaconda and python3, but they are wrong for python2 that is used by the Travis system (see also https://stackoverflow.com/questions/48826123/why-do-include-paths-in-python2-and-python3-differ).

Until we have a better solution https://github.com/precice/precice/commit/08dac1adf5ff3e4334babdd51e9f422a2e495b00 (hopefully?) fixes this issue. But this is not a nice solution. How can we improve this situation? Since this problem depends on the system in use (e.g. anaconda python), fixes should be pushed to the branch https://github.com/precice/precice/tree/fixingPythonIncludePaths to not unnecessarily break the develop branch (again).

**Comment by BenjaminRueth** [comment]
https://github.com/precice/precice/commit/ca32e53ea679e6b73af4cf3bbaefe7d8da68a10b fixes building problems on Travis, but still no final solution found

**Comment by uekerman** [comment]
if by `master`, you mean `develop`, then +1

**Comment by BenjaminRueth** [comment]
6f886ed9a3ba15b9fad50e01e1b8a455cf9bbc36 closes this issue
