### ISSUE TITLE
Implement tests that read and write multiple times

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1055]
As mentioned in https://github.com/precice/tutorials/issues/231 reading and writing multiple times within one timestep is allowed usage of the preCICE API. We should therefore implement corresponding tests (I believe we don't have any test going into this direction yet?).

### Example

Textbook API usage

```
initialize
while(ongoing){
  read
  solve
  write
  advance
}
```

[elastictube-1d](https://github.com/precice/tutorials/blob/6d90ae3eb179113beb400e472c8832e29a48db9b/elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp#L84-L144) triggering https://github.com/precice/tutorials/issues/231:

```
initialize
read  // unnecessary, but allowed
while(ongoing){
  read
  solve
  write
  advance
}
```

Also allowed

```
initialize
read
while(ongoing){
  solve
  write
  write
  write  // this write data will be used in the end.
  advance
  read
  read
  read
}
```

**Comment by BenjaminRodenberg** [comment]
From my point of view this API usage is not very important yet since there is no real use-case. But testing this will become more important when waveform relaxation is implemented (#133).

**Comment by BenjaminRodenberg** [comment]
Since this was marked as a "good first issue": If somebody would like to start working on this. [This test](https://github.com/BenjaminRodenberg/precice/blob/f19b118e449dfb012cad6aefbfd469c4822d0fa8/src/precice/tests/SerialTests.cpp#L527-L529) might be used as a template: Reading already happens multiple times.

```
precice.readScalarData(readDataID, vertexIDs[i], currentDt, readData[i]);
BOOST_TEST(readData[i] == readFunction(readTime, i));
precice.readScalarData(readDataID, vertexIDs[i], currentDt / 4, readData[i]);
```

At the current state the `currentDt` should be removed, since `readScalarData` does not support sampling data at a specific time:

```
precice.readScalarData(readDataID, vertexIDs[i], readData[i]);
precice.readScalarData(readDataID, vertexIDs[i], readData[i]);
```

I guess we should check that

1. reading multiple times returns the same data for every call
2. writing multiple times will overwrite the data and only the latest data will be exchanged

**Comment by mhmdkanj** [comment]
Hi, I'd like to implement this.

I'm thinking it could follow the structure [Data Initialization Test](https://github.com/BenjaminRodenberg/precice/blob/f19b118e449dfb012cad6aefbfd469c4822d0fa8/src/precice/tests/SerialTests.cpp#L802), however with one set of scalar data communicated from one solver to the other.

Roughly it would look something like this (with appropriate checks for the values):
```
Solver1:
  initialize
  read
  change read value
  read
  while(ongoing) {
      advance
      read
      change read value
      read
  }
  finalize
Solver2:
  initialize
  write
  write
  while(ongoing) {
      write
      write
      advance
  }
  finalize
```
 
which tackles the suggested points in the comment above as well as having this multiple read/write initially and during ongoing coupling.

**Comment by BenjaminRodenberg** [comment]
General outline looks good to me. Just a few questions to make sure there is no misunderstanding:

* `change read value` means that after `read` (let's say we read `read data = 5`) we change `read data` on the receiver side (`Solver1`) to something else (let's say `read data = 6`). Then we `read` again and make sure that this is still `5` (since there was no `advance` or anything else which could change the received data).

* Will the `write` statements provide the same data? I would suggest to always write different data. Then you can also make sure that only the last written data actually arrives on the other side.
 
Additionally, I think you should also call `initializeData` somewhere.

I'll try to extend your example below:

```
Solver1:
  initialize
  initializeData
  read (-> readData = 5)
  change read value (-> readData = 6)
  read (-> readData = 5)
  while(ongoing) {
      advance
      read (-> readData = 7)
      change read value (-> readData = 8)
      read (-> readData = 7)
  }
  finalize
Solver2:
  initialize
  write (123, will be ignored)
  write (5)
  initializeData (sends 5 to Solver1)
  while(ongoing) {
      write (456, will be ignored)
      write (7)
      advance (sends 7 to Solver1)
  }
  finalize
```
