### ISSUE TITLE
Seg fault in CommmunicateMesh.cpp

### ISSUE THREAD

**Issue by floli** [precice/precice#106]
```
Core was generated by `../../readMesh -a -c ../precice.xml ../outMesh.txt A'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007efe4c391967 in precice::com::CommunicateMesh::sendMesh (this=0x7fff3f211860, mesh=..., rankReceiver=0) at src/com/CommunicateMesh.cpp:38
38              coords[i * dim + d] = mesh.vertices()[i].getCoords()[d];
[Current thread is 1 (Thread 0x7efe4d238740 (LWP 6539))]
(gdb) bt
#0  0x00007efe4c391967 in precice::com::CommunicateMesh::sendMesh (this=0x7fff3f211860, mesh=..., rankReceiver=0) at src/com/CommunicateMesh.cpp:38
#1  0x00007efe4c8b52f4 in precice::partition::ProvidedPartition::communicate (this=0x25cfec0) at src/partition/ProvidedPartition.cpp:44
#2  0x00007efe4c948b17 in precice::impl::SolverInterfaceImpl::computePartitions (this=0x2582ab0) at src/precice/impl/SolverInterfaceImpl.cpp:1527
#3  0x00007efe4c90d44c in precice::impl::SolverInterfaceImpl::initialize (this=0x2582ab0) at src/precice/impl/SolverInterfaceImpl.cpp:235
#4  0x00007efe4c8d0b40 in precice::SolverInterface::initialize (this=0x7fff3f212ba0) at src/precice/SolverInterface.cpp:27
#5  0x0000000000438761 in main (argc=6, argv=0x7fff3f213488) at readMesh.cpp:124
```
mesh was generated by aste's ```make_mesh 1000 1000```, producing a 1000x1000 mesh on [0,1]x[0,1]
precice.xml: [precice.txt](https://github.com/precice/precice/files/1747439/precice.txt)

2 ranks on participant A, 4 ranks on participant B.
Happens in debug and release builds.

Mapping:
```
      <mapping:petrbf-gaussian shape-parameter="758.7136" preallocation="tree"
                               solver-rtol="1e-9" constraint="consistent"
                               direction="read" from="MeshA" to="MeshB"
                               x-dead="true" y-dead="false" z-dead="false" polynomial="separate"/>
```

I was able to reproduce it with a mesh size of 900x900 and 1100x1100 however not with 500x500.

Version of aste at https://github.com/floli/aste/commit/9fda1e75460ed685812d60872dde5c63a0fb07ef (see RBF_Timings/timings.py for settings)

**Comment by floli** [comment]
A mesh size of 546 works well, but with 547 it crashes.

I was able to reproduce that behavior on two very diffent machines (Ubuntu 16.04 / Arch), 8 cores / 4 cores (logical) but the numbers above are the same, 546 works, 547 crashes.

**Comment by uekerman** [comment]
After a quick view, I cannot see how we would get a problem here. We'll need to have a closer look.

**Comment by fsimonis** [comment]
We could try to compile with [memory sanitizers](https://clang.llvm.org/docs/MemorySanitizer.html#origin-tracking) and see if it helps to track down the origin.
