### ISSUE TITLE
Memory issue with IMVJ acceleration

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1064]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 20.04_
preCICE Version: 2.2.1 (latest `master`)

**Describe the problem**
Running heaptrack on my simulation case shows the following:

![](https://user-images.githubusercontent.com/33414590/128688677-3bae27cf-87bc-4d40-b663-fc483b36377b.png)

With the huge data allocation originating from:

```bash
Eigen::internal::aligned_malloc(unsigned long) in Memory.h:159 (libprecice.so.2)
void* Eigen::internal::conditional_aligned_malloc<true>(unsigned long) in Memory.h:214 (libprecice.so.2)
double* Eigen::internal::conditional_aligned_new_auto<double, true>(unsigned long) in Memory.h:374 (libprecice.so.2)
Eigen::DenseStorage<double, -1, -1, -1, 0>::resize(long, long, long) in DenseStorage.h:408 (libprecice.so.2)
Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::resize(long, long) in PlainObjectBase.h:293 (libprecice.so.2)
void Eigen::internal::resize_if_allowed<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >, double, double>(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, Eigen::internal::assign_op<double, double> const&) in AssignEvaluator.h:720 (libprecice.so.2)
void Eigen::internal::call_dense_assignment_loop<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::internal::assign_op<double, double> >(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, Eigen::internal::assign_op<double, double> const&) in AssignEvaluator.h:734 (libprecice.so.2)
Eigen::internal::Assignment<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::internal::assign_op<double, double>, Eigen::internal::Dense2Dense, void>::run(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, Eigen::internal::assign_op<double, double> const&) in AssignEvaluator.h:879 (libprecice.so.2)
void Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::internal::assign_op<double, double> >(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, Eigen::internal::assign_op<double, double> const&) in AssignEvaluator.h:836 (libprecice.so.2)
void Eigen::internal::call_assignment<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::internal::assign_op<double, double> >(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&, Eigen::internal::assign_op<double, double> const&, Eigen::internal::enable_if<!Eigen::internal::evaluator_assume_aliasing<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::internal::evaluator_traits<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > >::Shape>::value, void*>::type) in AssignEvaluator.h:804 (libprecice.so.2)
void Eigen::internal::call_assignment<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > >(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&) in AssignEvaluator.h:782 (libprecice.so.2)
Eigen::Matrix<double, -1, -1, 0, -1, -1>& Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::_set<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > >(Eigen::DenseBase<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > > const&) in PlainObjectBase.h:714 (libprecice.so.2)
Eigen::Matrix<double, -1, -1, 0, -1, -1>& Eigen::Matrix<double, -1, -1, 0, -1, -1>::operator=<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > >(Eigen::DenseBase<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, -1, 0, -1, -1> > > const&) in Matrix.h:225 (libprecice.so.2)
precice::acceleration::MVQNAcceleration::initialize(std::map<int, std::shared_ptr<precice::cplscheme::CouplingData>, std::less<int>, std::allocator<std::pair<int const, std::shared_ptr<precice::cplscheme::CouplingData> > > >&) in MVQNAcceleration.cpp:101 (libprecice.so.2)
std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() in shared_ptr_base.h:729 (libprecice.so.2)
std::__shared_ptr<precice::acceleration::Acceleration, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() in shared_ptr_base.h:1.169 (libprecice.so.2)
std::shared_ptr<precice::acceleration::Acceleration>::~shared_ptr() in shared_ptr.h:103 (libprecice.so.2)
precice::cplscheme::BaseCouplingScheme::initialize(double, int) in BaseCouplingScheme.cpp:144 (libprecice.so.2)
std::__shared_ptr_access<precice::cplscheme::CouplingScheme, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get() const in shared_ptr_base.h:1.021 (libprecice.so.2)
std::__shared_ptr_access<precice::cplscheme::CouplingScheme, (__gnu_cxx::_Lock_policy)2, false, false>::operator->() const in shared_ptr_base.h:1.015 (libprecice.so.2)
precice::impl::SolverInterfaceImpl::initialize() in SolverInterfaceImpl.cpp:309 (libprecice.so.2)
Adapter::Adapter<3, 3, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::VectorizedArray<double, 4ul> >::initialize(dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) in precice_adapter.h:300 (solid)
FSI::Solid<3, double>::run(std::shared_ptr<TestCases::TestCaseBase<3> >) in mf_elasticity.h:575 (solid)
main in solid.cc:56 (solid)
```

In order to classify the data sizes: the mesh `Solid-read` and `Solid-write` have a size of 4864 interface nodes respectively (vector data), the fluid meshes are even smaller. You may want to see the full configuration file [precice-config.xml](https://github.com/precice/precice/files/6953481/precice-config.log).

Also, compare the heaptrack results when using the same configuration where I just change the `IMVJ` acceleration to `ILS` (note
 the different axis scaling, preCICE (Eigen) still take the largest portion of memory AFAIU):

![](https://user-images.githubusercontent.com/33414590/128689530-6b51abc5-9b3e-4194-b7de-b2af4e63e281.png)

Full heaptrack analysis results for ILS and IMVJ can be found here: [heaptrack.zip](https://github.com/precice/precice/files/6953537/heaptrack.zip)

**Step To Reproduce**
The behavior can be reproduced by using the uploaded configuration file and running the [bending_flap test case](https://github.com/DavidSCN/matrix-free-dealii-precice/tree/master/examples/bending_flap).

**Expected behaviour**
The memory consumption should be reasonable.

**Comment by DavidSCN** [comment]
I can track down the issue on the following LOCs:

https://github.com/precice/precice/blob/3ea47c25ba972e89f5f23b4e4d1707daf578a2a2/src/acceleration/MVQNAcceleration.cpp#L98-L102

In my case, `global_n = entries = 18.222`, i.e., we allocate a full matrix of `18.222 x 18.222 = 332.041.284` doubles -> `332.041.284 doubles x (64 bit/double) / (8 bit/byte) ~= 2.66 GiB` for each matrix, which is also the output from heaptrack.

I guess the matrix allocation has simply the wrong initialization arguments.

**Comment by uekerman** [comment]
Which configuration do you use for IMVJ? (your config file above uses ILS).
The original variant of IMVJ needs indeed quadratic memory. Only the restart variant has a linear memory requirement.
See also the [config ref](https://precice.org/configuration-xml-reference.html#imvj-restart-mode-1) and the [optimized IMVJ paper](https://www2.informatik.uni-stuttgart.de/bibliothek/ftp/ncstrl.ustuttgart_fi/ART-2017-11/ART-2017-11.pdf).

**Comment by DavidSCN** [comment]
> Which configuration do you use for IMVJ? (your config file above uses ILS).

I guess I just experimented too much, but you can straightforwardly exchange `ILS` by `IMVJ`.

> The original variant of IMVJ needs indeed quadratic memory. Only the restart variant has a linear memory requirement.
See also the config ref and the optimized IMVJ paper.

And the original variant is also implemented? Considering that a restart is useless without an actual start: the IMVJ acceleration is not really applicable for large cases and we should document this somewhere, right?

**Comment by uekerman** [comment]
Restart is not referring to a _simulation restart_, but to a periodic restart of the approximation of the Jacobian. 

You need this tag to get to linear complexity.

```xml
<imvj-restart-mode truncation-threshold="0.0001" chunk-size="8" reused-time-windows-at-restart="8" type="RS-SVD"/>
```

Just replacing `ILS` by `IMVJ` will give quadratic complexity.

In our documentation, we nudge users towards using or at least starting with `ILS`. The linear-complexity `IMVJ` is really complicated. Only sth for expert users.

One thing we could do is to make `imvj-restart-mode` a mandatory subtag. Or print a warning if `IMVJ` is used without the tag (and the mesh size is large?).
