### ISSUE TITLE
Rationale of formula for quadratic extrapolation is unclear

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1089]
Does anybody have an idea where this formula comes from?

https://github.com/precice/precice/blob/43f23c79bd7b91fcd3939b34edcaa8279c9220d1/src/time/Waveform.cpp#L71

From my understanding it should rather be the following formula:

`3*x^t - 3*x^(t-1) + x^(t-2)`

My line of thought is the following: For quadratic extrapolation I'm creating a parabola based on the three samples `x^t`, `x^(t-1)` and `x^(t-2)`. The extrapolated value lies at `(t+1)`. I'll provide my derivation below.

### Why do I think this looks wrong?

There is a test that look wrong to me:

https://github.com/precice/precice/blob/43f23c79bd7b91fcd3939b34edcaa8279c9220d1/src/time/tests/WaveformTest.cpp#L45-L75

I think the `8` should be a `9` here, because we use `0`, `1`, `4` for extrapolation. The next value on a parabola is `3^2 = 9`, not `8`

https://github.com/precice/precice/blob/43f23c79bd7b91fcd3939b34edcaa8279c9220d1/src/time/tests/WaveformTest.cpp#L73

### Derivation

`y` is a general quadratic function.
`y_0`, `y_1`, `y_2` are the known values at `x = {0,1,2}`
`y_3` is the unknown value at `x=3`

```
y = a*x^2 + b*x + c

y_0 = c
y_1 = a + b + c
y_2 = 4a + 2b + c
y_3 = 9a + 3b + c

-> c = y_0
y_1 = a + b + y_0
y_2 = 4a + 2b + y_0

a = y_1 - b - y_0
b = y_2/2 - 2a - y_0/2

-> a = y_1 - y_2/2 + 2a + y_0/2 - y_0
a = - y_1 + y_2/2 + y_0/2
2a = y_0 - 2y_1 + y_2

b = y_2/2 - y_0 + 2y_1 - y_2 - y_0/2
b = -y_2/2 + 2y_1 - 3y_0/2 

9a = 9y_2/2 - 9y_1 + 9y_0/2 
3b = -3y_2/2 + 6y_1 - 9y_0/2
c = y_0

-> y_3 = 3y_2 - 3y_1 + y_0   
```

**Comment by BenjaminRodenberg** [comment]
For completeness, I will provide the derivation for linear extrapolation here:

```
y = a x + b

y_0 = b
y_1 = a + b
y_2 = 2a + b

b = y_0
a = y_1 - b
a = y_1 - y_0

y_2 = 2y_1 - 2y_0 + y_0
y_2 = 2y_1 - y_0                    
```

Everything looks good:
https://github.com/precice/precice/blob/43f23c79bd7b91fcd3939b34edcaa8279c9220d1/src/time/Waveform.cpp#L65

**Comment by uekerman** [comment]
The formula is used in the original IQN publication: https://doi.org/10.1016/j.compstruc.2008.11.013

**Comment by BenjaminRodenberg** [comment]
> The formula is used in the original IQN publication: https://doi.org/10.1016/j.compstruc.2008.11.013

Thanks for the reference. The formula is given in the paper (p.796, line 1 of the algorithm). But I could not find a comment on the order or derivation of this formula in the paper. So I think that we are "selling" this kind of extrapolation as second order is misleading. If the formula is in the paper, we should probably keep it.

My suggestion:

* Let's implement the formula suggested above for second order. This is the more natural choice from my perspective.
* Let's use a different name for the formula from the IQN publication.

However, this would make this issue a breaking change, if I understand correctly.

**Comment by BenjaminRodenberg** [comment]
I added a comment in the code:
https://github.com/precice/precice/blob/2c314f3bb939ab4aeb676aad5e01268e7b5bd3dd/src/time/Waveform.cpp#L67

**Comment by ajaust** [comment]
I support this change. I stumbled on this weird extrapolation when formula starting with preCICE and having some issues using extrapolation. It seems I never reported any issue though (shame on me). Just for completeness I would like to mention the Lagrange polynomial which can also be used for the derivation of the new (and correct) extrapolation formula.

**Comment by BenjaminRodenberg** [comment]
Are we actually planning to remove/replace this extrapolation formula? Should be simple to do, but needs some updates in tests.

**Comment by uekerman** [comment]
Yes, let's replace it.

**Comment by BenjaminRodenberg** [comment]
Removed extrapolation in #1503. Closing this issue.
