### ISSUE TITLE
Performance-related compilation flags

### ISSUE THREAD

**Issue by MakisH** [precice/precice#109]
I noticed that we don't use the GCC flag `-march=native` to support architecture-specific instructions, which could help the computations performance.

1. Is this correct?
2. Do you think it would make sense to include it? preCICE's bottleneck is not really in computations at the moment.
3. Is there any reason to _not_ include it?

More information on the [GCC man pages](https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html) (for example, from an older version).

**Comment by floli** [comment]
I just talked about that with a collegue, he deemed it a bad idea:
* You might be cross-compiling unknowingly, e.g. compiling on login nodes, running on compute nodes. In that case it would optimise using wrong instructions
* If someone distributes binaries (to collegues internally) it would not run on a different machine, unless really identical hardware.

**Comment by MakisH** [comment]
I see. Then let's not complicate the building, unless it can offer a big performance improvement (which I don't think so, but I could test at some point).
