### ISSUE TITLE
Missing `vtu` data pieces on exported meshes 

### ISSUE THREAD

**Issue by DavidSCN** [precice/precice#1102]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _CentOS 8_
preCICE Version: 2.2.1 as well as 2.3.0

**Describe the problem**
For our parallel exports, every rank exports `vtu` files and the master rank exports the `master.pvtu` file containing a list of relevant rank files. However, in case a `provided` mesh is not send to other participants and exported, the `master.pvtu` file does not contain the relevant files`

```xml
...
    <PPointData Scalars="Rank " Vectors="Displacement ">
         <PDataArray type="Int32" Name="Rank" NumberOfComponents="1"/>
         <PDataArray type="Float64" Name="Displacement" NumberOfComponents="3"/>
      </PPointData>
   </PUnstructuredGrid>
```
The export of the `provided` *and* sent (to another participant) mesh looks as it should:

```xml
...
      <PPointData Scalars="Rank " Vectors="Stress ">
         <PDataArray type="Int32" Name="Rank" NumberOfComponents="1"/>
         <PDataArray type="Float64" Name="Stress" NumberOfComponents="3"/>
      </PPointData>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r1.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r5.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r9.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r17.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r21.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r25.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r33.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r37.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r41.vtu"/>
   </PUnstructuredGrid>
``` 
Opening the defect file in paraView results just in an empty file.

**Step To Reproduce**
1. Run a parallel coupled simulation with vtk exports on a mesh you don't send to other participants
2. look at the resulting vtks

**Expected behaviour**
The defect file should contain the list of relevant files

**Comment by fsimonis** [comment]
I stumbled across this issue lately too.
Reason is that the exporter does not write subfiles for meshes, whose vertex distributions are empty.

This is buggy with the current implementation and I am not even sure if this works with the two-level initialisation at all.

I suggest to always export every mesh. This will result in empty files for participants that filter out the complete mesh, but that shouldn't be that much of a problem.

**Comment by DavidSCN** [comment]
May I ask you to point out the relevant code snippets and/or files here? 

> I suggest to always export every mesh. This will result in empty files for participants that filter out the complete mesh, but that shouldn't be that much of a problem.

You mean every mesh used by this participant, right? In the end, the issue here would only require changes of the master files, the rank files are just fine. Maybe this was not clear from the description above.

**Comment by fsimonis** [comment]
https://github.com/precice/precice/blob/534499840c32663b5bb656c3d0aa247809e4259d/src/io/ExportVTKXML.cpp#L42-L44

https://github.com/precice/precice/blob/534499840c32663b5bb656c3d0aa247809e4259d/src/io/ExportVTKXML.cpp#L113-L117

**Comment by fsimonis** [comment]
We discussed this issue during today's Telco.

* This will not work with the two-level initialization
* The primary rank has this information, so we should take advantage of this and export non-empty meshes only.
* We need a unified way to access this information for both single and two-level init.
