### ISSUE TITLE
Increase in iteration numbers with extrapolation

### ISSUE THREAD

**Issue by KyleDavisSA** [precice/precice#1103]
This issue is related to PR https://github.com/precice/precice/pull/1096 . When testing the 3D Tube test case, a difference in the number of iterations (total number of iterations over the simulation run time) was found when using the new develop branch and the master branch. While testing the issue, it was found that adding `extrapolation-order > 0` was the source of the increase in the number of iterations in the develop branch.

**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 20.04_
preCICE Version: develop (at dcad530) and master (at https://github.com/precice/precice/releases/tag/v2.2.1)

Add the versions/commit hashes of further adapter and/or bindings.

**Describe the problem**

**Step To Reproduce**
1. Run the 3D Tube test case (https://github.com/precice/tutorials/tree/master/elastic-tube-3d) with `extrapolation-order = 2` for develop and master branch.
2. Run the 3D Tube test case (https://github.com/precice/tutorials/tree/master/elastic-tube-3d) with `extrapolation-order = 0` for develop and master branch.

**Expected behaviour**
The number of iterations per timestep is the same when using the master branch with `extrapolation-order=0` and `extrapolation-order=2`.
The number of iterations per timestep is larger for the develop branch when increasing `extrapolation-order=0` to `extrapolation-order=2`

**Comment by BenjaminRodenberg** [comment]
This issue was observed while preparing release v2.3.0 (#1095). So it should be observable for dcad530. Our reference version of preCICE, where no regression occurs is v2.2.1 (https://github.com/precice/precice/releases/tag/v2.2.1). But we should also ensure that this behavior is stable for older releases.
