### ISSUE TITLE
Apply extrapolation to all data?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1104]
While working on #1098 and #1103 I realized that extrapolation is only applied to the accelerated data. This makes the implementation from my point of view more complicated and is an unnecessary restriction. I would propose to apply extrapolation to all data  - especially, since interpolation will soon be available all data (#1029) and therefore also extrapolation should be available for all data for consistency reasons.

Note that in certain situations extrapolated data will be computed and directly overwritten without any possibility to be used, but I think this is not really harmful and a price worth paying, if this simplifies the code and how preCICE is executed.

I'm putting the `breaking change` label here, because certainly some tests have to be updated. However, we might also be able to treat this in a non-breaking fashion.

**Comment by uekerman** [comment]
> I realized that extrapolation is only applied to the accelerated data

Do you mean the academic "I"? :laughing: 

More seriously, I am not yet completely convinced by your reasoning. Currently, extrapolation should have no effect on data sent from first to second participant. In my opinion, extrapolating and then overwriting will make the code harder to understand. Somebody new to the code, who just wants to learn how serial coupling is implemented, might get unnecessarily confused by this.

**Comment by uekerman** [comment]
Anyway, no breaking change to me. This is pure refactoring and will not change the user perspective.

**Comment by BenjaminRodenberg** [comment]
To make the "more complicated" a bit more concrete. I would like to avoid the `not doesFirstStep()` branch here

https://github.com/precice/precice/blob/c4f51693e5d0ec7646deae06a3b508a36bafe86e/src/cplscheme/BaseCouplingScheme.cpp#L176-L181

and use `_allData` here:

https://github.com/precice/precice/blob/c4f51693e5d0ec7646deae06a3b508a36bafe86e/src/cplscheme/BaseCouplingScheme.cpp#L258-L262

**Comment by fsimonis** [comment]
> Currently, extrapolation should have no effect on data sent from first to second participant. In my opinion, extrapolating and then overwriting will make the code harder to understand. Somebody new to the code, who just wants to learn how serial coupling is implemented, might get unnecessarily confused by this.

@BenjaminRodenberg agrees. Closing
