### ISSUE TITLE
No reference for two subroutines"precicef_action_read(or write)_sim_checkp()"

### ISSUE THREAD

**Issue by lawyer0818** [precice/precice#111]
Dear all, hi, I compiled the fortran SolverProxy.f, but it remianded me that there is no reference for two subroutines"precicef_action_read(or write)_sim_checkp()". But after I annotated them the compilation is successful. And I cannot find their definition in SolverInterfaceFortran.hpp(cpp) either. Many thanks

**Comment by lawyer0818** [comment]
CALL precicef_action_read_sim_checkp(readSimCheckp)
CALL precicef_action_write_sim_checkp(writeSimCheckp)

**Comment by lawyer0818** [comment]
`CALL precicef_action_read_sim_checkp(readSimCheckp)
CALL precicef_action_write_sim_checkp(writeSimCheckp)`

**Comment by uekerman** [comment]
I just had a look. The Fortran Solverproxy is completely outdated. I will try to re-enable it.

**Comment by lawyer0818** [comment]
Cool! We are looking forward to it!

Sent from my iPhone

On Apr 15, 2018, at 18:59, Benjamin Uekermann <notifications@github.com<mailto:notifications@github.com>> wrote:


I just had a look. The Fortran Solverproxy is completely outdated. I will try to re-enable it.
