### ISSUE TITLE
Nightly build of dockerimage precice/precice:develop

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1115]
**Please describe the problem you are trying to solve.**

The python bindings use the docker image `precice/precice` provided via (https://github.com/precice/precice/blob/v2.3.0/.github/workflows/release-docker.yml) in their CI pipeline to create and push a docker image with the python bindings `precice/python-bindings` (https://github.com/precice/python-bindings/blob/develop/.github/workflows/build-docker.yml).

Currently `precice/precice` is only updated, when there is a release. See https://github.com/precice/precice/blob/v2.3.0/.github/workflows/release-docker.yml. But for being able to run tests on the latest version of preCICE, we actually need `precice/precice:develop`. This will also help us downstream to detect early.

**Describe the solution you propose.**

Change the action https://github.com/precice/precice/blob/v2.3.0/.github/workflows/release-docker.yml to create and push `precice/precice:develop` nightly.

**Describe alternatives you've considered**

We will use `precice/precice:latest` in the python bindings until this issue is solved. However, this is not optimal, because this does not allow us to detect compatibility issues with the develop version of preCICE early. We will only see compatibility issues as soon as preCICE is released and will, therefore, only be able to fix them after a release of preCICE and before a release of the bindings.

**Additional context**

As far as I understand we want to support the path marked as "nigthly" from the preCICE paper (https://arxiv.org/pdf/2109.14470.pdf). Solving this issue helps to support this path.

![Screenshot from 2021-10-15 11-12-44](https://user-images.githubusercontent.com/5740604/137464763-bd1e328a-1ca1-40b6-9184-4ba3510bbaf3.png)

**Comment by BenjaminRodenberg** [comment]
Related to this issue: my comments in https://github.com/precice/python-bindings/pull/149

**Comment by BenjaminRodenberg** [comment]
I'm still see a need for using my own docker image `benjaminrodenberg/precice:develop` for testing etc. because none of the approaches that we currently have is really working for the testing setup that I use in the python bindings. See https://github.com/precice/python-bindings/pull/169.

For future reference and because others might find it useful I'm adding the manual steps here:

* I use the following docker file as a basis: https://github.com/BenjaminRodenberg/ci-images/blob/master/ci-precice-2204.dockerfile
* I then build it via `docker build -t benjaminrodenberg/precice:develop -f ci-precice-2204.dockerfile .
`
* Then I push it via `docker push benjaminrodenberg/precice:develop`

**Comment by BenjaminRodenberg** [comment]
Closed by #1598 ?

**Comment by IshaanDesai** [comment]
> Closed by #1598 ?

Yes.
