### ISSUE TITLE
Installation with PythonActions fails (PyUnicode_AsWideCharString, PyUnicode_DecodeFSDefault)

### ISSUE THREAD

**Issue by valentinaschueller** [precice/precice#1116]
**System Setup**

Operating system: macOS 11.6 (Apple M1 Chip)
preCICE Version: 2.3.0

Dependencies installed using 
`brew install cmake eigen libxml2 boost petsc openmpi python3 numpy`

Version numbers:
* cmake: 3.21.3_1
* eigen: 3.4.0_1
* libxml2: 2.9.12
* boost: 1.76.0 
* petsc: 3.16.0 
* open-mpi: 4.1.1_2 
* python@3.9: 3.9.7_1 
* numpy: 1.21.2

`cmake` ran without problems but running `make` inside of the build folder produced the following error:

```make
[ 11%] Building CXX object CMakeFiles/precice.dir/src/action/ScaleByDtAction.cpp.o
/Users/valentina/Downloads/precice-2.3.0/src/action/PythonAction.cpp:43:25: error: use of undeclared identifier 'PyUnicode_AsWideCharString'
    wchar_t *wmessage = PyUnicode_AsWideCharString(pvalue, nullptr);
                        ^
/Users/valentina/Downloads/precice-2.3.0/src/action/PythonAction.cpp:59:45: error: use of undeclared identifier 'PyUnicode_DecodeFSDefault'
  PyObject *const inspect_module_name     = PyUnicode_DecodeFSDefault("inspect");
                                            ^
[ 11%] Building CXX object CMakeFiles/precice.dir/src/action/SummationAction.cpp.o
2 errors generated.
make[2]: *** [CMakeFiles/precice.dir/src/action/PythonAction.cpp.o] Error 1
```

**Steps To Reproduce**

```
wget https://github.com/precice/precice/archive/v2.3.0.tar.gz
tar -xzvf v2.3.0.tar.gz
cd precice-2.3.0
mkdir build
cd build
cmake ..
make
```

**Expected behaviour**

Error-free compilation of preCICE.

**Additional context**

Running `cmake -DPRECICE_PythonActions=OFF ..` leads to no further problems in the installation.

**Comment by fsimonis** [comment]
The release 2.4.0 fully relies on FindPython3, which resolves this issue.
