### ISSUE TITLE
RFC: Change build type names to mixed case

### ISSUE THREAD

**Issue by floli** [precice/precice#112]
I want to change our build types (```release```, ```debug```) to mixed case, i.e. ```Release```, ```Debug```

Two reasons:
* Make it closer to cmakes BUILD_TYPE, see https://cmake.org/cmake/help/v3.11/variable/CMAKE_BUILD_TYPE.html, which is growing to be the de-facto standard for modern build systems. Furthermore it aligns with xSDK community policy M.1 (Support xSDK community GNU Autoconf or CMake options)

* In the course of that, I want to add another build options, also borrowed from CMake: ```RebWithDebInfo``` which means release with debug info, s.t. you have release optimized software, but get more meaningful backtraces on crashes.

This change can be done in a backward compatible manner.

Opinions?

**Comment by MakisH** [comment]
What problems would we encounter in that case? 

I don't see any reason to be strongly against or for this idea. I am up for it as long as it does not break any existing compatibility!

(by the way, are we considering moving to CMake?)

**Comment by uekerman** [comment]
First reaction: why not. However, can you detail a little bit more where this would introduce changes? Maybe, if this is not too much effort, can you do this already in a feature branch such that we can look at the commit?

**Comment by uekerman** [comment]
CMake is a topic for the coding days

**Comment by floli** [comment]
> First reaction: why not. However, can you detail a little bit more where this would introduce changes? Maybe, if this is not too much effort, can you do this already in a feature branch such that we can look at the commit?

Just some lines in SConstruct.

> What problems would we encounter in that case?

You mean, if we do the change? I don't anticipate no problems. If we do in a backward incompatible manner, compile commands have to be adapted.

**Comment by uekerman** [comment]
OK. For the command line arguments, we could support both options (or maybe we even do this already), `build=debug` and `build=Debug`, right?

**Comment by floli** [comment]
Yeah, I would just add the mixed case version and alias the lowercase version to them. Also I print a warning about the old versions being deprecated.
