### ISSUE TITLE
pkg_ressources not available on default Ubuntu install

### ISSUE THREAD

**Issue by floli** [precice/precice#113]
The python package ```pkg_ressources``` is not installed in a default Ubuntu installation, therefore its inclusion has broken builds on a number of machines.

@BenjaminRueth IIRC you proposed a fix in Gitter that uses no additional packages. I think we should change it so no new dependencies are introduced.

**Comment by BenjaminRueth** [comment]
I will merge https://github.com/precice/precice/tree/alternativeNumpyPathCalculation in a moment. This should resolve the issue.

**Comment by BenjaminRueth** [comment]
Merged into develop.
