### ISSUE TITLE
No package available for Ubuntu 21.10 "Impish Idrish"

### ISSUE THREAD

**Issue by MakisH** [precice/precice#1131]
Since a few weeks, there is a new Ubuntu 21.10 version (non-LTS). We need a `.deb` package in our release: https://github.com/precice/precice/releases/tag/v2.3.0

We can remove the 21.04 (Hirsute) ones at the end of 2021.

**Comment by fsimonis** [comment]
Done in https://github.com/precice/precice/actions/runs/2344896510
