### ISSUE TITLE
minor build issue (openSUSE 15.3)

### ISSUE THREAD

**Issue by olesenm** [precice/precice#1151]
working from develop
- mkdir build ; cd build; cmake ..

```
CMake Error at cmake/modules/FindEigen3.cmake:50 (file):
  file failed to open for reading (No such file or directory):

    /usr//usr/include/eigen3/Eigen/src/Core/util/Macros.h
Call Stack (most recent call first):
  cmake/modules/FindEigen3.cmake:101 (_eigen3_check_version)
  CMakeLists.txt:161 (find_package)


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK).
```

It rightly complaints about no `/usr//usr/include/eigen3/Eigen` 

Can use `cmake .. -DEIGEN3_INCLUDE_DIR=/usr/include/eigen3` as workaround, but something odd is going on.

**Comment by olesenm** [comment]
Tacking this on to the same issue:
```
CMake Error at CMakeLists.txt:264 (add_library):
  Target "precice" links to target "Boost::regex" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```
The corresponding package _is_ installed: libboost_headers1_66_0-devel-1.66.0-10.1.x86_64
which provides /usr/include/boost/regex.hpp, /usr/include/boost/regex/   etc.

**Comment by fsimonis** [comment]
@olesenm Thanks for the report!

I was able to reproduce this in a docker container.
We use the "official" `FindEigen3.cmake` in our repository, which tries to load the `Eigen3Config.cmake` installed by the project itself.

The `Eigen3Config.cmake` provided by the openSUSE leap 15.3 eigen3 package is broken. You currently need to use the manual override of the include dir. Let me see if I can report this upstream.

```
/usr/share/eigen3/cmake/Eigen3Config.cmake
---
...
 9: get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
...
28: set (EIGEN3_INCLUDE_DIR  "${PACKAGE_PREFIX_DIR}/${PACKAGE_PREFIX_DIR}/include/eigen3")
...
```

The easiest way to reliably choose the correct MPI version, is to pass the compiler wrapper as compiler.
CMake uses it to deduce the used MPI version.
```
CXX=mpic++ cmake .
```
It is important to note that changes by the mpi-selector affect future shells, not the current one. (According to the man page)
