### ISSUE TITLE
Define primitives in terms of vertices

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1153]
**Please describe the problem you are trying to solve.**
Currently, triangles are defined in terms of edges an edges are defined in terms of vertices.
This makes defining triangles in adapter codes and integration tests tedious:
```
meshID = getMeshID();
setMeshVertices(...);
for e in edges:
  setMeshEdge(...);
for t in trianges
  setMeshTriangle(...);
```
This will become extremely tedious once we support tetrahedral elements.
For consistency, they would need to be defined using triangles.

As the `mesh::Triangle` is implemented this way as well, we need to still create `mesh::Edge`s for each triangle.
Meaning `setMeshTrianglesWithEdges`, needs to check existing edges in order to avoid duplications, which is the reason why the API call is so slow.
```
meshID = getMeshID();
setMeshVertices(...);
for t in trianges
  setMeshTriangleWithEdges(...);
```

**Describe the solution you propose.**

Implement the following approach for connectivity:
* Elements are defined by vertices only.
* Sub-elements such as the edges of a triangle are implicitly defined via the triangle.
* Update the API implementation to still allow constructing triangles from edgeIDs.

Example Triangle Strip of 6 vertices and 4 triangles:

Scenario | #Triangles | #Edges
--- | --- | ---
All edges |  4 | 12
Unique edges | 4 | 9
Implicit edges | 4 | 0

## Pros:
* Easier to use API with faster calls for setting connectivity information.
* No handling of edge IDs in adapters.
* Faster internals as we don't need to handle edges
* Lower memory consumption as meshes won't contain implicit primitives.
  This will be very noticeable once we implement voluminous primitives such as tetrahedra.
* Lower memory consumption as we don't need special maps to access unique vertices of triangles via the edges any more.
* Lower initialization times as the meshes will be smaller, so there will be less to communicate.
* This would make all tests that require meshes with connectivity as well as integration tests way cleaner.

## Cons:
* The repartitioning will filter out complete primitives including all implicit ones. We could implement an algorithm that generates leftover edges, but this will need some thought.
* This will make primitive ownership #963 more difficult to implement as primitives may not exist in every participant (1Triangle vs 1 Edge due to filtered vertex). This will impact scaled-consistent mappings as well as the watch-integral for parallel participants.
* The nearest-projection needs to be redesigned. Problem is that an _implied_ edge of a triangle would be the better choice, but the current implementation would choose the best _explicitly_ defined edge instead. All implied edges need to be indexed for a correct implementation.

**Example:**
Defined primitives are triangle ABC and edge AD.
Point E will project outside of the triangle ABC and find a suitable projection to AD.
So, E will be projected to AD, even though the implicit edge AB would be the more suitable choice. 
![bitmap](https://user-images.githubusercontent.com/13552216/146365428-e9cda696-c0fb-48f1-81aa-a7cf2f249129.png)

**Describe alternatives you've considered**

Leave it as it is.

**Additional context**

* Volume coupling requiring tetrahedra #468 
* Primitive ownership #963 
* Parallel support for scaled-consistent mappings #962 
* Overweight mesh primitives #483

**Comment by oguzziya** [comment]
Not having to define edges for triangles is a wonderful thing IMHO. Most of the time it is even redundant.  I do not want to imagine writing tests for tetrahedral elements... However, I have some concerns regarding the implications and cons:

* In my opinion, there should not be any case where there is a triangle and an independent edge exist together. Same for an edge and a vertex. The edge represents a 1D interface while a triangle represents a 3D interface. Their coexistence is contradicting and is not very common among simulation software. For NN mapping, connectivity is irrelevant therefore it is not critical. However, for NP, it is important as you pointed out. Therefore, even though filtering destroys this connectivity, it is better to re-create it. https://github.com/precice/precice/pull/986 tries to achieve this partially. I think that most of the issue relies on repartitioning. 
* Memory consumption is critical and it seems like the biggest pro. What about having a different direction and implementing edge/implicit edge-related calculations using lazy evaluation. We might benefit from not redesigning whole NP mapping and not compromising from the memory. I am not sure whether this is achievable or not but it might be worth a shot.

**Comment by uekerman** [comment]
I see the appeal of this suggestion in general. I am a bit afraid however that this could lead to mixed-up states, where we always have to distinguish different cases.

My gut feeling tells me it would be easier to get rid of edges for 3D scenarios all together. This follows @oguzziya concerns:

> there should not be any case where there is a triangle and an independent edge exist together

Of course, this would be a really breaking change then. And we would need to rethink how the NP mapping works. But I guess this is possible.

If we change things here, we should only change things once and find a solution that could potentially solve our domain decomposition problems as well (duplicated "halo" elements).

**Comment by fsimonis** [comment]
> I see the appeal of this suggestion in general. I am a bit afraid however that this could lead to mixed-up states, where we always have to distinguish different cases

Do you mean the different cases {2d, 3d} x {interface, volume}?

**Comment by uekerman** [comment]
> Do you mean the different cases {2d, 3d} x {interface, volume}?

That, but also that there could be combinations of the old and the new way: explicit and implicit edges mixed etc.

**Comment by fsimonis** [comment]
After the first prototypes, it became apparent that the current way of implementation is rather arse-backward.

Instead of generating all implicit primitives in the `setMeshX` calls, it is way easier and more efficient to generate all implicit primitives in initialize.

The new workflow will be:
* User defines vertices
* User defines desired connectivity
* preCICE removes duplicates of all explicit primitives.
* preCICE then adds all missing implicit primitives

Direct consequences are:
* singular and bulk functions are similar in terms of runtime.
* bulk functions can validate vertex ids in one go, avoiding duplicate checks.
* initialize will become more expensive
* This mesh pre-processing can be measured using the internal profiling.

So, I'll close #1313 and restart based on that.
