### ISSUE TITLE
SplitParticipantsFixture does not work as intended

### ISSUE THREAD

**Issue by floli** [precice/precice#116]
Modified test from ```ExampleTests.cpp```. The test never failes, obviously the else branch is never entered:

```
BOOST_AUTO_TEST_CASE(IntegrationTestsWithTwoParticipants,
                     * testing::OnSize(4)
                     * boost::unit_test::fixture<testing::SplitParticipantsFixture>())
{
  if(utils::Parallel::getProcessRank()<=1){
    // Put here your preCICE API code for the first participant
    // Don't copy over that line, it's for testing the example
    BOOST_TEST(utils::Parallel::getCommunicatorSize() == 2);

  }
  else {
    assertion(utils::Parallel::getProcessRank() > 1 && utils::Parallel::getProcessRank() < 4);
    // Put here your preCICE API code for the second participant
    // Don't copy over that line, it's for testing the example
    BOOST_TEST(utils::Parallel::getCommunicatorSize() == 2);
    BOOST_TEST(false);
  }
}
```
Executed by
```./tools/compileAndTest.py -t --run_test="*/*/IntegrationTestsWithTwoParticipants"```

I understand the tests, that it splits a communicator {0,1,2,3} in {0,1} and {2,3} (doc on ```SplitParticipantsFixture``` could also be improved).
getProcessRank() likely returns local rank numbers, thus is never larger than 1.

Not sure though....

**Comment by uekerman** [comment]
You're completely right. That's the best solution I found. Currently, the fixture is actually never used for a real test, as most integration tests use a 3-1 distribution (3 ranks for one participant, 1 rank for the other). Maybe, we should update the fixture accordingly. Comments?
