### ISSUE TITLE
Data count can become negative

### ISSUE THREAD

**Issue by uekerman** [precice/precice#1161]
The `Data` class uses a static counter to assign IDs to new instances.

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/mesh/Data.hpp#L93

The counter is increased when a new instance is created:

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/mesh/Data.cpp#L21-L32

There are, however, two ways to decrease the counter, which contradict each other:

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/mesh/Data.cpp#L34-L37

and 

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/mesh/Data.cpp#L76-L79

The latter is called when configuring the `SolverInterfaceImpl` class:

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/precice/impl/SolverInterfaceImpl.cpp#L181-L189

This gives problems when one uses two `SolverInterface` instances after another:

```cpp
SolverInterface interface(...);

interface.initialize();
interface.finalize();

SolverInterface interface2(...);
...
```

As one gets negative data IDs then and ultimately runs into this check:

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/precice/impl/Participant.cpp#L444-L447

(Side remark: maybe it is bad idea that `_dataContexts` is a vector and not a map)

The easiest way to reproduce this is by modifying a solver dummy. I am not sure if we can reproduce this with an integration test as there the ID handling is different.

@fsimonis Any idea how to solve this problem? Do you need the reset for the re-initialization? Ideally, we should remove one of both "decreasing" methods above.

**Comment by fsimonis** [comment]
The solution of this problem is to decouple the id management from the Mesh, similar to what we did with the Mesh IDs.
The configuration will again be the place to assign these IDs.

To implement this, we need to pass the data id directly to the mesh:   
```cpp
// current version
PtrData &Mesh::createData(const std::string &name, int dimension);

// proposed version
PtrData &Mesh::createData(const std::string &name, int dimension, DataID id);
```

This will be easy to implement for preCICE itself, but it will be difficult to migrate the integration tests calling `createData`.
There are currently ~170 calls to this function, which need to be updated.

**Comment by fsimonis** [comment]
Closed via 1190

**Comment by fsimonis** [comment]
This was part of #385
