### ISSUE TITLE
Wrong polynomial configuration for Eigen QR-based RBF mapping

### ISSUE THREAD

**Issue by DavidSCN** [precice/precice#1162]
**Describe the problem**
For all RBF mappings, we have in preCICE the configuration option of the `polynomial` which can be `on`, `off` and `separate`. It is known, that the separate treatment of the polynomial delivers by far the best results (have a look at Florian's thesis or the reference paper). The integrated polynomial could even run into convergence issues in situations where the separated polynomial can easily handle the system. However, our pseudo-parallel eigen3 based QR-RBF implementation only implements the integrated polynomial version (`polynomial=on`). Therefore, setting the `polynomial=separate` (or relying on the default) has no effect and does not give an RBF mapping with a separate polynomial treatment.

There are two situations where one might run into this problem

1. preCICE was build without PETSc leading to the QR-RBF fallback
2. `use-qr-decomposition="true"` was configured

**Expected behaviour**
We should either throw an error if one of the described scenarios occurs or implement the separated polynomial for the QR-RBF. The simple solution of throwing an error comes with the problem of the default configuration being `polynomial=separate`, i.e., if PETSc is not installed the user needs to change the polynomial configuration in any RBF mapping (and needs to change it back if PETSc is installed later on).

**Comment by uekerman** [comment]
I would say, let's implement the missing variants. Should not be too complicated.
