### ISSUE TITLE
Replace utils::ptr_vector<T> with smart pointers

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1164]
`utils::ptr_vector<T>` serves a similar purpose like smart pointers from `std`. We should remove this implementation in favor of smart pointers from `std`.

I already took care of replacing `utils::ptr_vector<T>` with `std::unique_ptr` in https://github.com/precice/precice/pull/1159, but there are many more places, where `utils::ptr_vector<T>` is used.

**Comment by fsimonis** [comment]
We should critically analyse the use cases of the `ptr_vector` in preCICE.
Most uses can be changed to a simple vector as pointers are often unnecessary.
We may have to alter some of the contained types, but I am positive that this can be done.

**Comment by Timo-Schrader** [comment]
I've got a question: `utils::ptr_vector<T>` is a class that stores an underlying `std::vector` which itself stores raw C pointers (e.g., `precice::impl::MappingContext *`). Now I've got two questions:
1. Should we remove  `utils::ptr_vector<T>`  in favor of  `std::vector` storing **non-pointer** objects?
2. Should we refactor raw C-style pointers into `std::*_ptr` objects?
