### ISSUE TITLE
preCICE version/build information in the output

### ISSUE THREAD

**Issue by MakisH** [precice/precice#117]
I think it would be very convenient to have information about the version or the commit number of preCICE in the output. This is particularly important when a user sends log files asking for help.

I will do some research on this and try to implement it. Any ideas are welcome.

**Comment by floli** [comment]
You mean as a kind of startup message at the very top of a log file?

My first shoot at this would be that scons figures out the commit including the latest tag (e.g. from git describe), use that to ```-DPRECICE_VERSION``` which is to be put into the log file.

**Comment by MakisH** [comment]
Yes, thank you for the feedback!

My first approach would also be that, but thenI would need to make this work also without the repository (i.e. for releases). An approach there could be to include this information in an additional file in every release.

**Comment by floli** [comment]
`git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'` gives a nice string including the version and commit id.
