### ISSUE TITLE
Write data, when subcycling is used

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1171]
**Please describe the problem you are trying to solve.**

Currently only data at the end of the coupling window is exchanged. This means that all calls of `write...data(...)` are ignored except the last one before `advance()` is called and the end of the window is reached. We could improve the accuracy by using more / all data that is created and written by the individual participants.

**Describe the solution you propose.**

Currently, I see the following steps:

1. Do a linear interpolation on the window from the data at the beginning and at the end of the window. Ignore data inside of the window. This does not require any updates w.r.t `write...data(...)` and data communication. See #1029 
2. Do a linear interpolation between all substeps, if subcycling is used. This requires additional communication and will change the behavior of the API, because every `write...data()` before calling `advance()` will be used by preCICE. This is especially important for subcycling. We will still ignore multiple `write...data()` calls within one time **step**. This will not require an update of the API, because we can implicitly assume that calling `write...data(...)` will provide data associated with the end of the current time step. Note: The way how we want to perform interpolation is still an open question. I can also imagine using higher order interpolation with subcycling instead of piecewise linear interpolation.
3. Support higher-order interpolation, even if no subcycling is used. If we change the API to something like `write...data(..., dt)` a user can provide time stamped samples and therefore, we could provide multiple samples per step. This is, however, a far range goal and currently out-of-scope.

**Additional context**

In https://onlinelibrary.wiley.com/doi/10.1002/nme.6443, the approach described in (2) is implemented by using a wrapper around preCICE. Main goal of this issue is to bring this feature natively into preCICE.

**Comment by uekerman** [comment]
This does not necessarily have to be a breaking change, leaving option 3 aside. Only the behavior of `isWriteDataRequired` would change, which we could enable in the configuration. I currently don't see how option 2 changes the behavior of the API. preCICE just does sth different with the same data. Just like using a different data mapping does not change the behavior of the API, no?

**Comment by BenjaminRodenberg** [comment]
One important question that we will have to answer: Is a piecewise interpolation (zeroth order?) always used when subcycling is used? There are two possibilities:

1) User has to explicitly activate using piecewise interpolation inside of the window. If zeroth order waveform relaxation is used with subcycling, this is identical to preCICE v2 behavior. This is tested in [this test](https://github.com/BenjaminRodenberg/precice/blob/e314f6827b5a0a42a899965c52071f272ebf4c9f/tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingZero.cpp). Only if piecewise interpolation is explicitly activated, the "write direction" would become active.

2) Always use piecewise interpolation, if subcycling is detected by preCICE. This eliminates some options (we cannot use subcyling with a single non-piecewise interpolant on the window) and requires us to modify, for example, [this test](https://github.com/BenjaminRodenberg/precice/blob/e314f6827b5a0a42a899965c52071f272ebf4c9f/tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingZero.cpp). This would be a breaking change (which is allowed in v3).

From the implementation point of view there is no big difference (I assume). We need the non-piecewise interpolation in any case, if there is no subcycling. It is more about configuration and what options the user gets.

**Comment by uekerman** [comment]
I find option 1 more natural. In the end, piecewise constant interpolation is really an academic option without much practical relevance. Our current subcycling could still have some practical relevance (fewest data to communicate).

**Comment by BenjaminRodenberg** [comment]
Closing this PR, since #1671 was merged.
