### ISSUE TITLE
Remove CONDA_PREFIX from scons

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#119]
the way we are realizing experimental conda support in SConstruct is quite invasive. Meaning, this has a big effect on the whole SConstruct (CONDA_PREFIX everywhere). 1cc992c6de68960887720fa3309f7aa4b1e04fbc already proposes a solution via an additional flag ```libprefix```. We should merge this into develop.

**Comment by floli** [comment]
I am not really sure why it's assigned to me. @BenjaminRueth are you acting on that?

**Comment by MakisH** [comment]
I can also have a look. I resumed looking on Conda on Friday, I plan to finish this week.

**Comment by BenjaminRueth** [comment]
@floli I think assigning you was due to the fact that you came up with the ```libprefix``` idea.

Our current state is that we still have to merge https://github.com/precice/precice/commit/1cc992c6de68960887720fa3309f7aa4b1e04fbc into develop.

**Comment by floli** [comment]
Ok, I see. Since I do not have any means of testing conda, I will not work on this, however, I am happy to give you input when required.

**Comment by floli** [comment]
We (BR and me) have merged scons_prefix with #ac1568cab9c44b93cf89ddbfd2db26b5c3fbbe4c into develop. `scons_prefix` is deleted. Can this issue be closed? @MakisH

**Comment by MakisH** [comment]
I think the issue could be closed. I am still working on this branch, however.

**Comment by BenjaminRueth** [comment]
@MakisH please open another branch, if the original issue of the branch is closed.

**Comment by MakisH** [comment]
I will merge and push to another branch, I know I diverged from the original issue.
