### ISSUE TITLE
Make calling initializeData mandatory?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1196]
**Please describe the problem you are trying to solve.**

Simplifying the implementation of coupling schemes and have a stricter control flow with less optional branches.

**Describe the solution you propose.**

I suggest to make the call to `initializeData()` mandatory for every preCICE program. This is clearly breaking and will affect the users. I see the following advantages:

* Data exchange of initial data becomes more explicit for the user. If no data is written before calling `initializeData()`, initial data will be zero. There is an exception for the second participant of serial coupling schemes, because they receive data from the first iteration of the first iteration.
* We know that we don't have to exchange data in `initialize()`. Currently, we don't know whether `initializeData()` will be called after `initialize()`. Therefore the following statements necessary: 
    * receive data in `initialize` of serial coupling scheme, if `initializeData` is not called: [see here](https://github.com/precice/precice/blob/703fbe46165676bc16a4e7cfbad077b1ff8609b4/src/cplscheme/SerialCouplingScheme.cpp#L66-L73)
    * receive data in `initializeData` of serial coupling scheme, if `initializeData` is called: [see here](https://github.com/precice/precice/blob/703fbe46165676bc16a4e7cfbad077b1ff8609b4/src/cplscheme/SerialCouplingScheme.cpp#L90-L93)

**Describe alternatives you've considered**

Leave it as it is. This would be:

* non-breaking
* simpler for users that don't want to initialize data

**Additional context**

* I stumbled across this point when working on https://github.com/precice/precice/projects/7. Here, everything becomes even more complicated when you don't know at the point in time when `initialize()` is called what will happen next.
* If we conclude on this issue, we could require calling `initializeData`, if `experimental=true`. This would simplify the implementation of waveform relaxation and make code of our users future-proof.

**Comment by BenjaminRodenberg** [comment]
This would also simplify the following lines of code:

https://github.com/precice/precice/blob/703fbe46165676bc16a4e7cfbad077b1ff8609b4/src/precice/impl/SolverInterfaceImpl.hpp#L532-L540

**Comment by uekerman** [comment]
Sth to think about: when we make it mandatory, couldn't we fully integrate the functionality into `initialize`?

**Comment by fsimonis** [comment]
If we merge `initialize` and `initializeData`, then we have two options:
1. figure out the need to write initial data in the SolverInterface Ctor and set the action as required. This should be doable.
2. always assume that the user sets the mesh and initializes the data in one go, which is very natural.  
   We could still set a flag if a user writes to a mesh and use that to enforce this.

**Comment by BenjaminRodenberg** [comment]
Discussed this issue with @uekerman today. We concluded that making `initializeData` mandatory would simplify the implementation serial coupling schemes. `initialize` or `initializeData` of the second participant have duplicate code, because we have to take care of receiving the result of the `advance` call of the first participant in one of the two functions. This mainly refers to this part of the code: https://github.com/precice/precice/blob/b526dc9ba5a84665af0980ce527d74e429b7e1b3/src/cplscheme/SerialCouplingScheme.cpp#L66-L73

Additionally, time interpolation with serial coupling schemes becomes simpler. I'm currently preparing an implementation of this part. @fsimonis Nice synergy effect: This is also related to #1303, because the receive part in `initializeData` of the second participant of an serial coupling scheme is exactly the same like the receive part of `advance`.

**Comment by fsimonis** [comment]
Have you discussed the alternative of merging initialize and initializeData?

**Comment by uekerman** [comment]
Yes, we also discussed that. I guess it should be possible. 

* I agree on your observation about "the need to write initial data in the SolverInterface Ctor" above.
* We could already create all necessary data structure in `setMeshVertices`.

We would get
```cpp
setMeshVertices();
if (actionRequired(WID)) {
  writeData();
  actionFulfilled(WID);
}
initialize();
```

> Do you have an idea for a better name than initializeDataPost?

I guess we don't need a better name here for the moment as we will eventually replace the function with an advance call following #1303.

**Comment by BenjaminRodenberg** [comment]
I'll prepare a draft PR where `initializeData` is mandatory today. I will then probably also use this as a basis for my further work on #1029 (which will also make this PR breaking).

**Comment by fsimonis** [comment]
> We could already create all necessary data structure in setMeshVertices.

I checked and we actually do allocate data after each call to `setMeshVert(ex|ices)`.

The following is currently supported:
```
for v in coords:
  vid = setMeshVertex(m, v)
  writeScalarData(m, vid, norm(v));
end
initialize()
```

**Comment by fsimonis** [comment]
To merge both `initialize` and `initializeData`, we would have to allow `isActionRequired` before calling `initialize` and set the action in the couplingscheme as soon as it is created.
