### ISSUE TITLE
Investigate upgrade to C++17

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1201]
**Please describe the problem you are trying to solve.**
Once we move our baseline versions from Ubuntu 18.04 LTS to 20.04 LTS, we should investigate moving from C++14 to C++17.

This would currently only impact cray.

https://en.cppreference.com/w/cpp/compiler_support

**Comment by MakisH** [comment]
In that case, we can use/improve:
- `[[maybe_uninitialized]]`: https://github.com/precice/precice/pull/1285
- https://github.com/precice/precice/blob/6d27ad5db42997bbc06ff97b39eb4999196295b7/src/utils/traits.hpp#L8
- https://github.com/precice/precice/blob/6d91dc8a221d7e9faf713d8fc8cc494f74d9d263/src/utils/algorithm.hpp#L69

**Comment by fsimonis** [comment]
Available on Ubuntu 20.04 LTS:

* g++ / libstdc++ version 10
* clang 12

So, C++17 isn't an issue from the compiler/STL side of things.

The Intel compiler version shipped with the oneAPI toolkits is 2022.1, so the newest.

**Comment by fsimonis** [comment]
Also, we will be able to make good use of `std::variant` to clean-up #982

**Comment by MakisH** [comment]
> Available on Ubuntu 20.04 LTS:
> 
>     * g++ / libstdc++ version 10

Note that the default is 9.3, though. Still with full C++17 support, but to look at the right lists.
