### ISSUE TITLE
Naming of Nearest Projection in a Volume coupling context

### ISSUE THREAD

**Issue by boris-martin** [precice/precice#1206]
**Please describe the problem you are trying to solve.**
Currently, NP mapping only supports surface (i.e. boundary) coupling and is not suited to volumetric coupling. Extending it raises the question of naming: volumetric interpolation is not actually a *projection*.

-  How do we name the new method? Do we rename the surface version?
-  Should it be one mapping with a surface/volume choice as option, or two completely different mappings? In terms of code, both are doable in a +/- clean way (have a base abstract class and 2 subclasses, or one class with an option)

**Describe the solution you propose.**
On my local prototype, I named "Barycentric mapping" the volumetric version and left the current NP untouched. In terms of config, they are completely different mappings: one use either `mapping:nearest-projection` or `mapping:barycentric` in the preCICE config.
However, the name is misleading, as the surface NP is also barycentric.

**Describe alternatives you've considered**

- Same as above, but name it "volume mapping" instead. Removes the barycentric dilemma, but is weird since NN and RBF can be used in a volumetric context, so defining it as *the* volumetric mapping seems inappropriate.
- Have one unique mapping called "barycentric" (or something like "linear interpolation"?) and a volume/surface flag. Annoying since it "hides" the projection part in the surface version, and it breaks continuity ("nearest projection" has been written many times in a lot of places)
- Keep calling it NP and have a unique class, and keeping the misleading "projection" name even in the volume case.

**Additional context**

As of now, all interpolation is done / planned using edges, triangles and tetrahedras, hence the barycentric name. If we extend to quads, hexaedrons, higher order triangles, etc. the name will become inappropriate. Similarly with "linear interpolation".
=> Maybe think about a name like "local interpolation" to make it more generic?

**Comment by boris-martin** [comment]
Poke @fsimonis @uekerman

**Comment by uekerman** [comment]
I would go for two separate mappings and leave the nearest-projection as it is (backwards compatibility is indeed a strong argument here). The name for the new mapping could `mapping:cell-interpolation` or `mapping:volume-cell-interpolation`? Not sure yet here.
All this is for the user perspective, how to implement and name this internally, is a different question in my opinion.

So far my quick response, I did not yet think about this carefully.
