### ISSUE TITLE
Dead code in Edge.hpp?

### ISSUE THREAD

**Issue by boris-martin** [precice/precice#1211]
In `mesh/Edge.hpp`, some types are forward declared, but I found no reference nor implementation to these.
They seem to be designed for iterating over an edge, but there is actually no iterator implementation.

https://github.com/precice/precice/blob/00e12ff66dc2b5337167761c0741aa718f441c63/src/mesh/Edge.hpp#L15-L18

For Triangle, the `IndexRangeIterator` class is used to implement iterators over vertices. It would be consistent to implement the same for an edge and remove the types declared above.

https://github.com/precice/precice/blob/00e12ff66dc2b5337167761c0741aa718f441c63/src/mesh/Triangle.hpp#L34

**Comment by fsimonis** [comment]
Good catch! These are still leftovers from my initial boost.geometry implementation and should be removed.

We model triangles as rings, which require ranged access over the points, hence the iterator.
Edges can be implemented as segments, which don't require iterator access.

Would you like to do the honors?
