### ISSUE TITLE
Debian package succeds to install but fails to run

### ISSUE THREAD

**Issue by SoilRos** [precice/precice#1225]
**Describe your setup**

Operating system: Debian 10/11
preCICE Version: 2.3.0
Python Bindings for preCICE version: 2.3.0

**Describe the problem**
While aiming to install precice, I tried to install the Ubuntu package on a Debian 11/10 system. Yes, this is a bad idea to start with, but still worth the try since the systems use the same package manager. Now, Debian 11/10 does not complain and installs everything with no problem. However, when it comes to using it, the runtime system is not able to find the correct shared libraries and throws at import time.

**Step To Reproduce**
I created the following minimal docker file that reproduces the issue:

```dockerfile
# does works
# FROM ubuntu:focal

# doesn't work
# FROM debian:10

# doesn't work
FROM debian:11

RUN rm -f /etc/apt/apt.conf.d/docker-gzip-indexes \
  && rm -rf /var/lib/apt/lists/*

RUN export DEBIAN_FRONTEND=noninteractive; \
  apt-get update && apt-get dist-upgrade --no-install-recommends --yes \
  && apt-get install --no-install-recommends --yes wget ca-certificates python3 python3-pip build-essential

RUN wget https://github.com/precice/precice/releases/download/v2.3.0/libprecice2_2.3.0_focal.deb

RUN export DEBIAN_FRONTEND=noninteractive; \
  apt-get install --no-install-recommends --yes ./libprecice2_2.3.0_focal.deb \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --user pyprecice
RUN python3 -c 'import precice as pc; print(pc.__version__)'
```

The error message on Debian 11 is:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/lib/python3.9/site-packages/precice/__init__.py", line 4, in <module>
    from cyprecice import Interface, action_read_iteration_checkpoint, action_write_iteration_checkpoint, action_write_initial_data, get_version_information
ImportError: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory
```

**Expected behaviour**
An error at the installation time telling me that the correct version of boost is not available on my system. 

**Additional context**
Also, the docker container reveals an undocumented requirement for the python bindings: without a c/c++ compiler, the python bindings fail to be installed. So perhaps it makes sense to document this requirement

**Comment by uekerman** [comment]
Connected issue in the Python bindings: https://github.com/precice/python-bindings/pull/140

**Comment by fsimonis** [comment]
I had a look at creating Debian packages and the workflow is basically identical to Ubuntu. I'll give this a go soon, stay tuned.

**Comment by SoilRos** [comment]
@fsimonis Thanks a lot. I confirm that it works on my local machine :)
