### ISSUE TITLE
Remove VRML IO and SimulationState IO

### ISSUE THREAD

**Issue by uekerman** [precice/precice#123]
VRML import and export has always only been functional for serial (or server-based) computations. Recently, we have observed that it accounts for a significant part of the compilation time. We decided to remove it therefore.

While looking into this, it have also realized that `SimulationStateIO` is currently dead code. I will also remove this class, because then, both removals together should render the dependency on SPIRIT2 redundant.

**Comment by uekerman** [comment]
https://github.com/precice/precice/commit/fb52f1c8738c6672367f0559c89412fff61f8378
https://github.com/precice/precice/commit/6166dc21c7a1845bc5fc091526944682ae810976

**Comment by uekerman** [comment]
@floli , @BenjaminRueth Please also remove the spririt2 dependency from the cmake and the conda instructions

**Comment by MakisH** [comment]
Nothing is required for Conda, but I am working on Conda at the moment.
