### ISSUE TITLE
Redesign the XML configuration to avoid attributes

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1236]
_This is supposed to be primarily a place to discuss this_

**Please describe the problem you are trying to solve.**

The preCICE configuration uses an attribute-heavy XML style, while XML is generally used in a tag-heavy style.
The tag-heavy style as some benefits, such as [extensive library support](https://www.boost.org/doc/libs/1_78_0/doc/html/property_tree/tutorial.html) as well as the ability to transform between formats such as json and yaml. Using `boost.property_tree` would allow us to drop the libxml2 dependency and remove part of our custom XML parsing logic.

```xml
<!-- Attribute-heavy -->
<mesh name="MeshA">
  <use-data name="DataA"/>
</mesh>
<mesh name="MeshB">
  <use-data name="DataA"/>
</mesh>

<!-- Tag-heavy -->
<meshes>
  <mesh>
    <name>MeshA</name>
    <use-datas>
      <use-data>Data></use-data>
    </use-datas>
  </mesh>
  <mesh>
    <name>MeshB</name>
    <use-datas>
      <use-data>Data></use-data>
    </use-datas>
  </mesh>
</meshes>
```

**YAML and JSON equivalents**

```yml
meshes:
  - name: MeshA
    use-data:
    - name: Data 
  - name: MeshB
    use-data:
    - name: Data 
```

```json
"meshes": [
  {
    "name": "MeshA",
    "use-data": [ "Data" ]
  },
  {
    "name": "MeshB",
    "use-data": [ "Data" ]
  }
]

```

**Describe the solution you propose.**

Rethink the configuration to be fully tag-based, allowing us to painlessly process various formats and replace our XML processing. This is especially useful in tooling.

**Describe alternatives you've considered**

* Agree to do nothing
* Change to a completely different configuration format (prototypes needed)
* Use tag nesting for all grouping logical units, such as data, meshes, m2ns etc.

**Additional context**

#1235 #928

**Comment by MakisH** [comment]
I think this is a medium-value/high-effort feature.

On the one hand, preCICE is weird nowadays to use an XML-based configuration file. It is very unusual and we don't even define the format properly (see #127).

On the other hand, this is already established and we now even have tools (such as the config-visualizer) around it. I can imagine that people also have their own tools around it by now (e.g., DHCAE).  If we change, we should definitely consider making a conversion tool from the old to the new format, to help people upgrade.

We have also discussed alternatives in the past (see, e.g., LUA #168 or JSON #529). I think the discussion always concluded in "the format does not matter, as we want to make our own preprocessor at some point (https://github.com/precice/controller)".

The currently most favorable languages for configuration seem to me to be YAML/TOML, as they are very easy to write. I think going to JSON for a human-editable format would not be a good idea -- I would only use JSON as a human-readable configuration generated by a preprocessor (e.g., the controller).

I guess the main question is if YAML would be able to cover all features we need and if it could lead to disambiguities.

How would the new dry-run configuration checking be affected if we replaced the configuration format?

**Comment by uekerman** [comment]
I agree with all points @MakisH raised.

Just for completeness: the controller tries to use a high-level YAML description to generate our current XML.
* [example input in YAML](https://github.com/precice/controller/blob/master/examples/2/topology.yaml)
* [example output in XML](https://github.com/precice/controller/blob/master/examples/2/precice-config.xml)

**Comment by MakisH** [comment]
So, we could essentially use the controller (or something like it) to define a new configuration format, without having to break the XML format already. We could let the controller generate XML files and eventually completely replace XML by YAML, or make the controller a first-class component.

**Comment by fsimonis** [comment]
The long-term goal of preCICE is to make the generation of the configuration easier instead of revamping the configuration as such. Closing
