### ISSUE TITLE
Duplication of documentation in SolverIntefaceImpl unclear.

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1244]
Currently, there is a lot of duplicate and outdated documentation in `SolverInterfaceImpl` and `SolverInterface`. I would suggest to delete most of the documentation of `SolverInterfaceImpl`, because it takes a lot of effort to keep both files consistent and I do not see the purpose of duplication here. Documentation in `SolverInterface` is obviously useful for our users. 

Am I missing something here?

To give an example for inconsistent, duplicate and outdated documentation:

https://github.com/precice/precice/blob/d770c53ff59a7023c9e4933949d9e8a0797d5739/src/precice/impl/SolverInterfaceImpl.hpp#L423-L439

https://github.com/precice/precice/blob/d770c53ff59a7023c9e4933949d9e8a0797d5739/src/precice/SolverInterface.hpp#L696-L723

**Comment by uekerman** [comment]
Yes, that's an issue. The one in `SolverInterface.hpp` is the better one. @fsimonis and me reworked this one some while ago.
We could delete all documentation in `SolverInterfaceImpl` (where reasonable) and replace with `@copydoc`.
