### ISSUE TITLE
Add waveform API methods to C and Fortran bindings

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1245]
The new API functions that will be introduced via https://github.com/precice/precice/pull/1187 still need to be added to the bindings.

**Comment by BenjaminRodenberg** [comment]
The following looks to me quite "wavy"

https://github.com/precice/precice/blob/3bfc9d9015c15e4ef8967269ccc67e92a9884086/extras/bindings/c/src/preciceC.cpp#L273-L279

https://github.com/precice/precice/blob/3bfc9d9015c15e4ef8967269ccc67e92a9884086/extras/bindings/fortran/src/preciceFortran.cpp#L329-L337

@fsimonis can we close this issue?

**Comment by fsimonis** [comment]
Right, this was implemented with #1636
