### ISSUE TITLE
Deprecate getMeshVertexIDsFromPositions and getMeshVertices?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1248]
Is the function `SolverInterface::getMeshVertexIDsFromPositions` needed? I have never used it and it would be a candidate for deletion for v3.0.0 from my perspective.

There was some discussion about this API function in https://github.com/precice/precice/issues/374, but besides this it looks mostly unused. As far as I see it there are also no tests for this function.

**Comment by BenjaminRodenberg** [comment]
I realized that the same is true for `getMeshVertices` :see_no_evil:

**Comment by fsimonis** [comment]
We decided to remove it.

**Comment by uekerman** [comment]
IMO `getMeshVertices` could be removed as well. I don't see a use case.

**Comment by fsimonis** [comment]
FYI we are extending [the docs](https://precice.org/couple-your-code-defining-mesh-connectivity.html) to clarify what to do.

**Comment by mardom1** [comment]
I am interested in working on this. Did I understand correctly that they should be directly removed not deprecated?

**Comment by IshaanDesai** [comment]
> I am interested in working on this. Did I understand correctly that they should be directly removed not deprecated?

Decision is to remove the functions and not just deprecate them.
