### ISSUE TITLE
Remove `hasMesh` and `hasData`

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1251]
Same reasoning as described in #1248: Untested and to my knowledge unused.

**Comment by fsimonis** [comment]
Couldn't this be useful for an adapter to check if expected meshes are present. An adapter may have its own configuration file, so it could emit warnings tailored to it.

**Comment by BenjaminRodenberg** [comment]
> Couldn't this be useful for an adapter to check if expected meshes are present. An adapter may have its own configuration file, so it could emit warnings tailored to it.

Sure! I totally see the use-case. But we can only remove this feature now and adding it again when there is a concrete need is no problem, because these functions are simple getters. Currently, it's just unused an untested code I would like to remove to reduce our code-base (it's large enough already with the features that we use).

**Comment by fsimonis** [comment]
Sounds like a lot of work to remove and reintroduce very simple functions.
Testing this should also be trivial.

**Comment by BenjaminRodenberg** [comment]
Any updates here? If we don't want to delete the functions, we can just make it a `v3.x.x` issue.
