### ISSUE TITLE
Compilation Error (‘put_time’ is not a member of ‘std’)

### ISSUE THREAD

**Issue by smartmenia1** [precice/precice#126]
I dowloaded the new precice release and run scons. 

I have now the following error: 
```
mpicxx -o build/debug-nopetsc/utils/Helpers.os -c -Wall -std=c++11 -fPIC -g3 -O0 -fPIC -DPRECICE_NO_PETSC -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_ALL_DYN_LINK -DBOOST_ASIO_ENABLE_OLD_SERVICES -DMPICH_SKIP_MPICXX -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Isrc -I/usr/include/python2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/libxml2 src/utils/Helpers.cpp
src/utils/EventTimings.cpp: In member function ‘void precice::utils::EventData::writeCSV(std::ostream&)’:
src/utils/EventTimings.cpp:196:10: error: ‘put_time’ is not a member of ‘std’
   out << std::put_time(std::localtime(&ts), "%F %T") << ","
 ```
Has anyone an idea?

best regards

**Comment by MakisH** [comment]
Hi @smartmenia1,

which compiler do you use? If you use GCC, [you need at least version 5.0](https://github.com/precice/precice/wiki/Dependencies#c-compiler), as previous versions do not fully support C++11 (such as the `std::put_time()`. You can find your compiler version with `mpicxx --version`.

If you have any other problems related to building, the best way is to ask on our [Gitter chat room](https://gitter.im/precice/Lobby).

**Comment by smartmenia1** [comment]
Thank you. 
best regards
