### ISSUE TITLE
SolverInterface constructor accepts communicator = nullptr

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1260]
**Describe your setup**

preCICE Version: 20c4f71

**Describe the problem**

There are two constructors for `SolverInterface`. One constructor accepts an additional `communicator` argument to allow for custom MPI communicators. Currently it is possible to pass `nullptr` here, which basically maps to the behavior of the `SolverInterface` constructor without the `communicator` argument. This should not be possible from my perspective. If I don't want to use a custom MPI communicator, I should use the right constructor.

**Step To Reproduce**

1. Modify `solverdummy.cpp`:
```
-  SolverInterface interface(solverName, configFileName, commRank, commSize);
+  SolverInterface interface(solverName, configFileName, commRank, commSize, nullptr);
```
2. Running solver dummy is possible without any error.

**Expected behaviour**

If the `SolverInterface` constructor is called with `communicator=nullptr` and error should be given to the user.

**Additional context**

Stumbled across this issue while working on #1249. I expect that working on this issue will also make the documentation more clear.

**Comment by fsimonis** [comment]
Let's push this to the next release as this can/could/should be considered breaking.
