### ISSUE TITLE
precice-config.xml not properly formatted?

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#127]
I just had the problem that I was not able to parse ```precice-config.xml``` using a standard python xml parsing library. 
 
    import xml.etree.ElementTree as ET
    tree = ET.parse("precice-config.xml")

This returns the following error:

    xml.etree.ElementTree.ParseError: unbound prefix: line 12, column 4

As far as I have understood it this means that the namespace ```data``` in my xml is not defined. Here is the corresponding line 12 of the xml:

    <precice-configuration>
    ...
        <data:scalar name="Pressure"/>
    ...
    </precice-configuration>
    

a possible solution is adding the namespaces to the root of ```precice-config.xml```:

    <precice-configuration xmlns:data="data" xmlns:coupling-scheme="coupling scheme" xmlns:mapping="mapping" xmlns:m2n="m2n" xmlns:post-processing="post-processing">
    ...
    </precice-configuration>

With this, I can parse the file without error. But of course, it makes our xml even more verbose. 

----
Here some starting points for discussion:

* Should we add the namespaces to all ```precice-config.xml```?
* Is there a possibility to create an xsd to valiate our xml and, at the same time, provide the missing namespaces? Especially the xml validation part would be a nice addon.
* (a bit offtopic:) Is there a way to ignore missing xml namespaces in python or it this bad style?

**Comment by MakisH** [comment]
Maybe we can auto-generate a specification file in the same way we auto-generate an XML reference?

We should then put it somewhere in the preCICE directories and distribute it.

(maybe the namespace should be something like `org.precice`?)

**Comment by BenjaminRueth** [comment]
With my limited knowledge about xml I come to the following conclusion: 

We should define namespaces in all our configuration files (option 1) or not use namespaces at all (option 2), if we want to have a properly formatted xml document. I have the impression that the namespaces in our configuration files are actually decoration only. Therefore, option 2 would be preferable. However, both options include a lot of work (we will have to update change all configuration files) and the benefit is low (at least from my current point of view). This makes this issue a `wontfix`.

**Comment by uekerman** [comment]
Also keep backward compatibility in mind ... I completely agree
