### ISSUE TITLE
MPI was already finalized (serial)

### ISSUE THREAD

**Issue by MakisH** [precice/precice#128]
While testing the OpenFOAM adapter with different variants of OpenFOAM, I stumbled upon this bug, which probably originates from preCICE itself.

The following warning is shown when running the tutorial case **in serial** (both solvers, either with or without `mpiexec`), with OpenFOAM v1712/v1806:

```
---[preciceAdapter] [DEBUG] Destroying the preCICE solver interface...
---[preciceAdapter] [DEBUG] Deleting the interfaces...
---[preciceAdapter] [DEBUG] Deleting the checkpoints... 
---[preciceAdapter] [DEBUG] Destroying the CHT module...
---[preciceAdapter] The simulation was ended by preCICE. Calling the end() methods of any functionObject explicitly.
End

--> FOAM Warning : 
    From function static void Foam::UPstream::exit(int)
    in file UPstream.C at line 219
    MPI was already finalized (perhaps by a connected program)
```

Both solvers complain. Apart from this, the simulation runs normally.

This error does not occur when running the simulation in parallel. It also does not appear in OpenFOAM 5.x.

**Comment by olesenm** [comment]
This is a warning only. In Pstream we have added extra checking in initialize and finalize. We only initialize if not already initialized. And only finalize if not already finalized. The protects against cases where a separate process has already finalized MPI before OpenFOAM does (finalizing an already finalized is a bad thing).

As an additional bit of logic (good or bad), we always try to finalized MPI with the OpenFOAM application exits, even in serial. If MPI hasn't been used anywhere, then it has no effect. If OpenFOAM is running in serial, but some other process has used MPI (but not finalized it), then this extra bit should help prevent MPI processes from hanging around indefinitely.

The `Pstream::initNull()` provides a convenient way of initializing for adapters.
Somewhere in the functionObject initialization, or before it gets used the first time:
```
   UPstream::initNull();   // My "something" adapter requires mpi to be initialized
```
This is a no-op if MPI has already been initialized (ie, by OpenFOAM) or else it does an initialization without any  argc,argv values.

The destructor does *not* need to do anything special to finalize. If the destructor does an extra MPI_Finalize(), the Pstream::exit() will warn you that someone had already finalized before. In some cases this could be a really useful warning.

**Comment by msuaeronautics13** [comment]
I also have this issue, with a custom adapter I am writing for an in-house Fortran CFD code. It occurs before the first timestep and after a call to `precicef_read_sdata`, which serves to initialize my CFD boundary condition with FEM values. For me, it is not a warning - rather, breaks execution.

**Comment by uekerman** [comment]
@msuaeronautics13 
I am bit puzzled by your problem. Why should MPI be finalized before the first timestep. I am not sure if your problem is related to this issue. Can you provide us with more information? (mailing list or gitter). 
What we definitely require is that you only call `MPI_Finalize` in your code after you have finalized preCICE.

**Comment by MakisH** [comment]
@msuaeronautics13 your issue must be something different, let's discuss it in the mailing list. Until then, you may also have a look at our new wiki page [Initializing preCICE in an existing MPI environment](https://github.com/precice/precice/wiki/Initializing-preCICE-in-an-existing-MPI-environment). 

This issue [has been closed in the OpenFOAM adapter](https://github.com/precice/openfoam-adapter/issues/27), applying the aforementioned patch, as this does not seem to originate from preCICE. Therefore, also closing this.
