### ISSUE TITLE
cmake missing install stage

### ISSUE THREAD

**Issue by olesenm** [precice/precice#129]
As we discussed yesterday, shifting to cmake will certainly help with building. The currently experimental cmake support looks like it does most of the basics, but it only has a build stage and no installation stage.

If we can fix that, spack integration should be no problem. Here is the corresponding spack issue number 
https://github.com/spack/spack/issues/8643 and current state https://github.com/olesenm/spack/tree/precice

**Comment by floli** [comment]
We will be looking into it, but need to get up to speed with regard to cmake installation stuff. 

We are also open to pull requests! :-)

**Comment by olesenm** [comment]
Sure, here's the first bit, but no idea of which top-level includes need to be installed. I figure that someone directly involved with the project will be quicker there.

**Comment by olesenm** [comment]
Also have an `of-precice` package on the same tree: https://github.com/olesenm/spack/tree/precice
Ready to go as soon as the cmake changes are merged.

**Comment by olesenm** [comment]
Closing out with the anticipated merge
