### ISSUE TITLE
clean up parallel initialization

### ISSUE THREAD

**Issue by uekerman** [precice/precice#13]
the position of MPI_Initialize and similar things is a mess at the moment and results in more and more problems. this an attempt to clean all that up.

**Comment by uekerman** [comment]
i changed a couple of things in the new branch initialization_i13 including a cleaner way of initializing PETSc.
@Haroogan can you please check if MPI still works under Windows?
@floli can you please check if all your PETSc applications still work?

@floli i had to change the epsilon in testNumericalEquals from 1e-10 to 1e-9 to make the PETSc unit tests work. any idea why this only happened to me?

the integration tests still produce problems when they finish. i could not figure out why. i guess this could have sth to do with the events, but i am a bit puzzled, maybe @floli you have an idea?

thanks!

**Comment by floli** [comment]
Unit Tests with PETSc work. Integration tests segfault at the end.

Regarding epsilon, I have no idea, quite a few tests are already done with ```validateNumericalEqualsWithEps(x, y, tolerance)``` with ```tolerance=1e-7``` due to the iterative solvers PETsc uses.

**Comment by uekerman** [comment]
yes, the segfault is what i experienced as for the integration tests as well. any idea what could cause this problem?

**Comment by uekerman** [comment]
i gave it some more tests.
when i comment the 3 signal_handlers in ```SolverInterfaceImpl```, i get a deadlock. with them, i get the segfault, sometimes also a deadlock. both happens in ```main.cpp``` after ```precice::utils::Parallel::finalizeMPI()```, so there is not much behind that point. 
anyway, i merged the changes already to develop, since it is definitely better than before. (the MPI error from before already happened earlier and covered this problem)

@Alexander-Shukaev  (now, the correct name) can you please check if MPI still works under Windows?

**Comment by Alexander-Shukaev** [comment]
For me both, unit and integration tests, hang.

**Comment by uekerman** [comment]
for which unit test do they hang exactly. this is really weird. 
could it be that ```MPI_Initialized``` is simply not yet implemented on windows MPI ?
at least this one [https://msdn.microsoft.com/en-us/library/dn473420%28v=vs.85%29.aspx here] seems not very ready

**Comment by Alexander-Shukaev** [comment]
I'm using Intel MPI on Windows.

**Comment by Alexander-Shukaev** [comment]
In any case, when function is not implemented, you either get a corresponding linkage error or a relevant exception at run time.

**Comment by uekerman** [comment]
"relevant exception at run time" ... that's the optimistic way of thinking :)
anyway, can you point me towards the first test that hangs? is it an MPIPorts or an MPIDirect test?

**Comment by floli** [comment]
Using the code https://github.com/floli/prempi/tree/3d5ac879635c3cc1de337016abc5eb41ec9b0224 mpi=on petsc=on I get:
```
PetscInitialize() must be called before PetscFinalize()
*** The MPI_Finalize() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[(null):10646] Local abort after MPI_FINALIZE completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```
at the end of program execution.

**Comment by uekerman** [comment]
there were issues wit the MasterSlave communication. now, both, unit and integration tests work without any error messages, as well as alya. please let me know if you still encounter any problems
