### ISSUE TITLE
Dangling reference in Communication

### ISSUE THREAD

**Issue by floli** [precice/precice#130]
https://github.com/precice/precice/blob/dac0bbc375f37c3424605e693f7198bafec73e11/src/com/MPICommunication.cpp#L145

This line takes a `double` and gives it using a reference to `aSend`. When the `itemToSend` goes out of scope, before `Isend` finishes, the reference becomes dangling.

**Comment by floli** [comment]
We already have something like that in place.

For a generalized version (using boost/variant and threads), see https://github.com/floli/MPI_Ports/blob/master/buffer_manager.hpp

For the version we actually have in precice (no threads and works only for doubles), see https://github.com/precice/precice/blob/5aa57aa21eab832a056327c2828ddfee03089a0b/src/m2n/PointToPointCommunication.cpp#L670

Problem is that the non-threaded version needs to be explicitly invoked. We call it from `PointToPointCommunication::send`, which is also the only place that fills the buffer.

If we use that kind of buffer manager for all asynchronous send operations, we need more places to check for completed requests.

Right now, I think it's the easiest way to go for 2 and give the caller the responsibility of managing the ownership.

**Comment by fsimonis** [comment]
As the Buffer Manager is a complex work package, I'll implement version two. Thus, the ownership remains the responibility of the caller.

**Comment by fsimonis** [comment]
This issue was actually resolved with #184. There is no ownership issue anymore.
