### ISSUE TITLE
Split CouplingScheme processing into sub-steps

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1303]
**Please describe the problem you are trying to solve.**

For the adaptive-dynamic meshes, I need to introduce inter-participant handshakes to propagate the request to reinitialize the internals in case of mesh changes. The reinitialization procedure needs to be called from the SolverInterface, which proves problematic. Furthermore, the reinitialization needs to occur both before the data exchange and the read/write mappings. 

* parallel coupling-schemes have a single synchronization point after calling SI::advance() and before mapWriteData, even before the cplscheme is even called (which exchanges the data).
* serial coupling-schemes have two synchronization points: before mapWriteData (same as the parallel cplscheme), but also before receiving  data.
* multi coupling-schemes have multiple synchronization points depending on the location.
 The controller has one synchronization point per coupling partner, which all occur while receiving coupling information. Each of these calls may lead to a mesh change, which may invalidate writeMappings between the controller and the current coupling partner. So these calls must perform writeMappings on a per-coupling-partner basis.
* compositional coupling-schemes must chain the above synchronization points. 

This leads to the following observations:
* the couplingscheme must be able to reinitialize before the second exchange (serial cplscheme)
* the writeMapping must be called from inside the coupling scheme (compositional cpl-scheme)
* the writeMapping must be repeatedly executed from inside the coupling scheme on a per-coupling-partner basis (multi cplscheme)

The cplscheme needs to hand back to the SolverInterface at each of the above points, which means that the multi and compositional cplschemes cannot precompute and run cplschemes in bulk as it is now the case.

**Describe the solution you propose.**

We change `cplscheme::advance()` from a do-it-all function to an iterator style.
Calling advance() simply advances to the next sub-step and returns the "location" in the cplscheme as a state.
If all sub-steps have been completed, `cplscheme.advance()` returns `done`, which this signals to the SolverInterface to continue `SolverInterface::advance()` and return to the solver.
If an implicit solver needs to iterate, it returns "iterate".

Each intermediate step needs to return the following information to SolverInterface:
* The current coupling-partner (for the inter-participant handshake)
* The need to execute the writeMapping

Coupling schemes then need to keep track of their current sub-step and advance it accordingly.
Implicit coupling schemes may request to iterate.
A compositional coupling-scheme should be simple to implement as it need to call advance() on a coupling scheme and returns until the cplscheme returns a done. Then it continues directly with the next cplscheme until it receives a done form the last cplscheme in the list.

The SolverInterface hands back to the solver if it receives a "done" or a request to "iterate".

This solution could be implemented now as a pure refactoring and then extended to allow re-meshing.

**Describe alternatives you've considered**

A callback-based system, which may be even trickier to implement

**Examples**

### Parallel-explicit

```mermaid
sequenceDiagram
participant SI as SolverInterfaceImpl
participant PE as parallel-explicit CS

SI ->>+ PE : advance()
PE ->>- SI : at pre-exchange
SI ->>+ PE : advance()
note over PE: exhange data
PE ->>- SI: done
```

### Serial-explicit

```mermaid
sequenceDiagram
participant SI as SolverInterfaceImpl
participant SE as serial-explicit CS

SI ->>+ SE : advance()
SE ->>- SI : at pre-send
SI ->>+ SE : advance()
note over SE: send data
SE ->>- SI : at pre-receive
SI ->>+ SE : advance()
note over SE: receive data
SE ->>- SI: done
```

### Parallel-implicit

```mermaid
sequenceDiagram
participant Solver
participant SI as SolverInterfaceImpl
participant PE as parallel-explicit CS


Solver ->>+ SI: adance()
SI ->>+ PE : advance()
PE ->>- SI : at pre-exchange
SI ->>+ PE : advance()
note over PE: exhange data, not convergenced
PE ->>- SI: at iteration
SI ->>- Solver: read checkpoint

Solver ->>+ SI: advance()
SI ->>+ PE : advance()
PE ->>- SI : at pre-exchange
SI ->>+ PE : advance()
note over PE: exhange data, convergenced
PE ->>- SI: done
SI ->>- Solver: write checkpoint
```

### Multi (Controller + partners A and B)

```mermaid
sequenceDiagram
participant SI as SolverInterfaceImpl
participant M as Multi CPL Controller

SI ->>+ M: advance()
note over M: Move to first cpl partner A
M ->>- SI: at pre-exchange A
note over SI: Check and handle reset of A.
note over SI: Map written data for A.
SI ->>+ M: advance
note over M: Receive from A
note over M: Move to second cpl partner B
M ->>- SI: at pre-exchange B
note over SI: Check and handle reset of B.
note over SI: Map written data for B.
SI ->>+ M: advance

note over M:  All received
note over M:  DataCheck convergence
note over M:  Send data to all
alt converged
M ->> SI: done
else not converged
M ->> SI: at iterate
end
deactivate M
```

### Compositional of 2 parallel-explicit

```mermaid
sequenceDiagram
    participant SI as SolverInterfaceImpl
    participant Comp as Compositional CS
    participant PE1 as parallel-explicit CS 1 
    participant PE2 as parallel-explicit CS 2

    SI ->>+ Comp : advance
    Comp ->>+ PE1 : advance
    PE1 ->>- Comp: at pre-exchange
    Comp ->>- SI: at pre-exchange
    SI ->>+ Comp: advance
    Comp ->>+ PE1: advance
    PE1 ->>- Comp: done
    Comp ->>+ PE2: advance
    PE2 ->>- Comp: at pre-exchange
    Comp ->>- SI : at pre-exchange
    SI ->>+ Comp: advance
    Comp ->>+ PE2: advance
    PE2 ->>- Comp: done
    Comp ->>- SI: done
```

### Compositional of parallel-explicit and parallel-implicit

```mermaid
sequenceDiagram
    participant Solver
    participant SI as SolverInterfaceImpl
    participant Comp as Compositional CS
    participant PE as parallel-explicit CS
    participant PI as parallel-implicit CS

    Solver ->>+ SI : advance
    SI ->>+ Comp : advance
    Comp ->>+ PE : advance
    PE ->>- Comp: at pre-exchange
    Comp ->>- SI: at pre-exchange
    SI ->>+ Comp: advance
    Comp ->>+ PE: advance
    PE ->>- Comp: done
    Note over Comp: Moves to next CS
    Comp ->>+ PI: advance
    PI ->>- Comp: at pre-exchange
    Comp ->>- SI : at pre-exchange
    SI ->>+ Comp: advance
    Comp ->>+ PI: advance
    Note over PI: Not converged
    PI ->>- Comp: at iteration
    Comp ->>- SI: at iteration
    SI ->>- Solver: 

    Note over Solver: read solve write

    Solver->>+ SI: advance
    SI ->>+ Comp: advance
    Comp ->>+ PI: advance
    Note over PI: Converged
    PI ->>- Comp: done
    Note over Comp: Moves to first CS
    Comp ->>- SI: done
    SI ->>- Solver: 
```

**Comment by uekerman** [comment]
Thanks for the heads-up summary :+1:
* I agree on the necessary additional synchronization points during a current `cplscheme.advance()`. I can't oversee the compositional scheme yet, but for simple serial and parallel coupling, this should be doable. Multi coupling should also not be too different from parallel coupling (easier than serial coupling in my opinion).
* I am not sure I already understand your plans for the write mappings. In my opinion we should avoid calling them from inside the coupling scheme. Wouldn't it be sufficient to just mark a mesh as invalid and then let the mapping decide whether it wants to recompute or not?
* I don't think we need any special requirement for implicit coupling. `SolverInterface` does not know and should not need to know whether a coupling is explicit or implicit (other than the flags read / write iteration checkpoint). To keep things manageable, we could also restrict the functionality in a first step: resetting a mesh in an implicit coupling is only allowed after convergence.

**Comment by fsimonis** [comment]
Closed by https://github.com/precice/precice/pull/1462
