### ISSUE TITLE
Incorrect projections in the fallback of cell interpolation

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1304]
**Describe your setup**

preCICE Version: 2.4.0 + #1297 

**Describe the problem**

When using linear cell interpolation, there may be edge cases where a point is numerically outside a cell. In that case the mapping find the nearest projection to determine the best projection possible.

Currently, this leads to unexpected results.
In 2D, all edges are checked for a match before the vertices.
This leads to the logic picking edges that are further away instead of picking vertices that are closer.

The following image displays the behaviour of the using cell-interpolation in 2D with a defined triangle ABC.
The coloured areas define which primitive a location is mapped to.

![WrongProjection](https://user-images.githubusercontent.com/13552216/170236216-0274cad8-9968-4217-aedf-48607aee2931.svg)

A concrete example is the right red AB section, where the correct projection is to map to the closest point C. Instead, the projection picks the edge AB, as it results in an interpolation.

**Expected behaviour**
The correct behaviour would be to pick the closest primitive as such:

![CorrectProjection](https://user-images.githubusercontent.com/13552216/170236215-38b2b90d-4509-4a2e-9e90-4e7673150c91.svg)

**Possible solution**

Currently, the projection implementation uses a lazy evaluation approach. The closes edge resulting in a valid projection (interpolation) will be picked completely skipping the evaluation of the nearest vertex.

The correct implementation would be to fetch the closest interpolations of all primitive classes, then pick the most suitable one.
The downside is that this completely disables the lazy evaluation of index trees as all primitives of the entire Mesh always need to be indexed.

**Additional context**

@boris-martin stumbled across this in #1297

**Comment by boris-martin** [comment]
Same problem occurs in NP mapping in 3D by the way. Same configuration with everything in the same plane would yield similar results.

**Comment by boris-martin** [comment]
> The downside is that this completely disables the lazy evaluation of index trees as all primitives of the entire Mesh always need to be indexed.

I don't really see how big is the problem. Overall, wouldn't it roughly multiply the complexity by only 2 ? (Index all edges and vertices instead of just all edges)

**Comment by fsimonis** [comment]
> I don't really see how big is the problem. Overall, wouldn't it roughly multiply the complexity by only 2 ? (Index all edges and vertices instead of just all edges)

This changes the best-case to the worst-case of the projection logic, which also impacts the nearest-projection mapping.

This doesn't matter too much in 2D, but imagine the amount of edges in a tetrahedral mesh of a volume. Now go one step further and imagine a naive implementation of the adapter which defines triangles and edges per tetrahedron. Then things get really out of hand.

This may also be related to #1153

**Comment by fsimonis** [comment]
An inexpensive tradeoff would be to test if the nearest vertex is a better match than the best higher-order primitive.
Finding the nearest vertex always returns a match and the vertices are most likely indexed anyhow.

This won't cover all case, but definitely quite a few.
