### ISSUE TITLE
Fix and enable first-participant timestepping combined with communication of initial data

### ISSUE THREAD

**Issue by uekerman** [precice/precice#1347]
Currently, we get a problem if we use "first-participant" as timestepping method and, at the same time, initialize any data.
Sadly, we cannot fix this in a non-breaking way. Most promising solution IMO is to merge `initialize` and `initializeData`, see also #1196 .  

An integration test that reproduces the problem is available in a draft PR: #1349 

For a detailed description of the problem and the potential fix, see the discussion in #1307, as a partial fix especially https://github.com/precice/precice/pull/1307/commits/62e34179ec0d852f5eba8249724dd6bb4d95b5db.

**Comment by davidscn** [comment]
@uekerman was this fixed in the course of the current development?

**Comment by uekerman** [comment]
yes
