### ISSUE TITLE
Simplify signature of actions

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1358]
While working on #1350 I realized that using `dt` for actions during initialization is risky, because it is not really clear what `dt` means at thsi point in time. Under certain circumstances `dt` is not even known (if second participant performs a write actions during initialize and it has not yet received the `dt` from the first participant).

I'm labelling this as a bug, because I think this is currently a generally design issue.

I see two options:

* don't perform any actions during `initialize`
* remove actions that rely on `dt`

Sightly related: https://github.com/precice/precice/pull/1352. This might fix the issue that for the second participant in serial coupling initialize is actually a merge of initialization and receiving results from the first window of the first participant. I've split these two steps up here. So we can also perform no action in the first half and perform all the usual actions in the second half.

**Comment by uekerman** [comment]
https://github.com/precice/precice/blob/e00e332f67269db474b94858af76223be89e7b90/src/action/Action.hpp#L58-L62

I am not aware of any (real) use case of `timeStepSize` or `computedTimeWindowPart` or `timeWindowSize` here (but `time` yes). In principle, one could use this to compute velocity values from displacement values or similar, but normally it is easier to do this in the adapter. We could even use the waveforms to better do this at some point.

I would vote for removing these arguments completely with v3.0.

**Comment by BenjaminRodenberg** [comment]
This means that the new signature will be `preformAction(double time)` and that's it, right? We will also delete some actions then, but I'm fine with this. We could already deprecate some of the affected actions on develop and remove them in v3.0.0.
