### ISSUE TITLE
Uninformative assertion hit while using dynamic Aitken acceleration

### ISSUE THREAD

**Issue by IshaanDesai** [precice/precice#1360]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 20.04_
preCICE Version: 2.4.0 commit: https://github.com/precice/precice/commit/67b0e6d9c9629b69d923cc540056bfd63a258a56

**Describe the problem**

While using dynamic Aitken acceleration scheme in running a case from the repository [coupled-heat-conduction](https://github.com/IshaanDesai/coupled-heat-conduction), the following assertion was hit:

```bash
[ipvs-epyc1:878755] [ 2] ASSERTION FAILED
Location:   virtual void precice::acceleration::AitkenAcceleration::initialize(const DataMap&)
File:       /home/desaiin/precice/src/acceleration/AitkenAcceleration.cpp:42
Expression: _dataIDs.size() == 2
Rank:       16
Arguments:  none
Stacktrace:
 0# getStacktrace[abi:cxx11]() in /home/desaiin/precice/build/lib/libprecice.so.2
 1# precice::acceleration::AitkenAcceleration::initialize(std::map<int, std::shared_ptr<precice::cplscheme::CouplingData>, std::less<int>, std::allocator<std::pair<int const, std::shared_ptr<precice::cplscheme::CouplingData> > > > const&) in /home/desaiin/precice/build/lib/libprecice.so.2
 2# precice::cplscheme::BaseCouplingScheme::initializeStorages() in /home/desaiin/precice/build/lib/libprecice.so.2
 3# precice::cplscheme::BaseCouplingScheme::initialize(double, int) in /home/desaiin/precice/build/lib/libprecice.so.2
 4# precice::impl::SolverInterfaceImpl::initialize() in /home/desaiin/precice/build/lib/libprecice.so.2
 5# precice::SolverInterface::initialize() in /home/desaiin/precice/build/lib/libprecice.so.2
 6# 0x00007F143A139A7D in /home/desaiin/.local/lib/python3.8/site-packages/cyprecice.cpython-38-x86_64-linux-gnu.so
```

The corresponding dynamic Aitken acceleration configuration part from the [config file](https://github.com/IshaanDesai/coupled-heat-conduction/blob/36ca2f53e6c75e499f03bd648c22163ef27d1593/precice-config.xml) is:

```xml
       <acceleration:aitken>
          <data name="porosity" mesh="macro-mesh"/>
          <data name="k_00" mesh="macro-mesh"/>
          <data name="k_11" mesh="macro-mesh"/>
          <initial-relaxation value="0.5"/>
       </acceleration:aitken>
```

**Step To Reproduce**

The assertion is hit while using dynamic Aitken acceleration scheme in the [macro-micro coupled case example](https://github.com/IshaanDesai/coupled-heat-conduction/tree/36ca2f53e6c75e499f03bd648c22163ef27d1593) from the repository [coupled-heat-conduction](https://github.com/IshaanDesai/coupled-heat-conduction). To run this example, one needs to install pyprecice and the micro-manager.

**Expected behaviour**

It is not clear to me why the dynamic Aitken acceleration would fail, hence the expected behavior would be that the case runs as usual and the implicit coupling is computed.

**Additional context**
[log_micro_simulations.log](https://github.com/precice/precice/files/9055615/log_micro_simulations.log)

**Comment by DavidSCN** [comment]
In principle, this is bug of our configuration, as the data tag can not occur arbitrarily often

https://github.com/precice/precice/blob/d83d3c789172acca414233bd65524297c4ce3438/src/acceleration/config/AccelerationConfiguration.cpp#L393

which does not match the implementation.

I guess it was implemented for a single data set for a serial and parallel coupling scheme and therefore we have only one or two data sets handled in the Aitken acceleration.
The question is a bit what to expect from the user perspective when configuring the acceleration this way:
- all data sets are accelerated with the same Aitken factor computed through one of the data sets (data are dependent on each other)
- each data set receives its own Aitken factor

We handle such a situation already in the QN schemes. I think we should add the same strategy for Aitken and make more transparent what happens for the user.

**Comment by uekerman** [comment]
> each data set receives its own Aitken factor

This will numerically not work as the data values then become inconsistent with respect to each other.
We should stack the data vectors on top of each other (just as we do for QN) and implement this missing variant.

**Comment by uekerman** [comment]
> I guess stacking data would require some kind of rescaling, right?

Yes, could / should use the same rescaling as for the QN methods.
