### ISSUE TITLE
R-Tree weird behavior with respect to the Z-axis (Boost bug ?)

### ISSUE THREAD

**Issue by boris-martin** [precice/precice#1388]
**Describe your setup**

preCICE Version: 2.4.0 develop branch a bit before 2.5.0 release. Followup of https://github.com/precice/precice/pull/1363, found in https://github.com/precice/precice/pull/1361.

**Describe the problem**

This unit test  (insert in RTreeTests.cpp) fails. A point with z=0.3 has a zero distance to a triangle in the plane z=0 (or any other constant), according to Boost. It works when switching axes (e.g. x=0 plane):
```cpp

BOOST_AUTO_TEST_CASE(CorrectTriangleDistance)
{

  // Document the issue
  PRECICE_TEST(1_rank);
  PtrMesh mesh(new Mesh("MyMesh", 3, testing::nextMeshID()));
  Index   indexTree(mesh);

  mesh::Vertex &v1 = mesh->createVertex(Eigen::Vector3d(0.0, 0.0, 0.0));
  mesh::Vertex &v2 = mesh->createVertex(Eigen::Vector3d(1.0, 0.0, 0.0));
  mesh::Vertex &v3 = mesh->createVertex(Eigen::Vector3d(0.0, 1.0, 0.0));
  mesh->createTriangle(v1, v2, v3);

  auto matches = indexTree.getClosestTriangles(Eigen::Vector3d{0.1, 0.2, 0.3}, 4);
  BOOST_REQUIRE(matches.size() == 1);
  BOOST_TEST(matches[0].distance > 0.25);
}

```

**Expected behaviour**
Non-zero distance

**Comment by fsimonis** [comment]
We can remove the Index from the test here.

```cpp
BOOST_AUTO_TEST_CASE(CorrectTriangleDistance)
{
  PRECICE_TEST(1_rank);
  precice::mesh::Mesh mesh("MyMesh", 3, testing::nextMeshID());

  mesh::Vertex &v1 = mesh.createVertex(Eigen::Vector3d(0.0, 0.0, 0.0));
  mesh::Vertex &v2 = mesh.createVertex(Eigen::Vector3d(1.0, 0.0, 0.0));
  mesh::Vertex &v3 = mesh.createVertex(Eigen::Vector3d(0.0, 1.0, 0.0));
  auto& t = mesh.createTriangle(v1, v2, v3);

  // Using the Vector3d directly doesn't compile for some reason
  // Eigen::Vector3d p{0.1, 0.2, 0.3};
  
  // Using a vertex compiles, but fails with a 0 distance. The point is "above" the triangle.
  // mesh::Vertex &p = mesh.createVertex(Eigen::Vector3d(0.1, 0.2, 0.3));
  
  // Shifting the point outside of the triangle (y=1.2) results in a succeeding test.
  mesh::Vertex &p = mesh.createVertex(Eigen::Vector3d(0.1, 1.2, 0.3));

  auto ptot = bg::distance(p, t);
  BOOST_TEST(ptot > 0.);

  auto ttop = bg::distance(t, p);
  BOOST_TEST(ttop > 0.);
}
```

My best guess is that the boost geometry ring concept requires a clockwise order, which we don't guarantee.

**Comment by fsimonis** [comment]
A simple version using point and ring models from boost geometry works.

https://godbolt.org/z/7Y8bn343e

**Comment by fsimonis** [comment]
A possible solution is to compute the location of the projection using the `Polation`.
This requires some internal interface changes.

**Comment by boris-martin** [comment]
In that case, I'd suggest replacing the use of `getClosestTriangles(point, n)` by something similar to the approach used with tetrahedra, where boost distances aren't used at all and we get all triangles whose AABB contains the point. Then we'd have to use the polation distance and sort the matches by distance.

Side advantage would be that we'd get rid of the arbitrary value of the number `n` of closest elements.
