### ISSUE TITLE
Keep function isGradientDataRequired?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1389]
While rebasing `develop` into `develop-v3.0.0` I realized that this function exists:

https://github.com/precice/precice/blob/133dd11bb9648f95d48c442f6c1cd933ca4c3370/src/precice/SolverInterface.hpp#L1111

It looks a bit strange to me to remove `isWriteDataRequired` in #1362 and at the same time have a function that is called `isGradientDataRequired`. I don't have a lot of knowledge about the gradient based mapping, so there might be a totally valid use-case. I just was a bit surprised seeing this function.

**Comment by uekerman** [comment]
This function tells the user whether to additionally write gradient data or not. It basically gets triggered when a gradient-based mapping is configured. Valid use case IMO. And different from `isWriteDataRequired` which basically signaled whether a participant sub-cycles or not.
