### ISSUE TITLE
Getting the preCICE revision from Git while in a third-party repository

### ISSUE THREAD

**Issue by MakisH** [precice/precice#1397]
## Context

When we build preCICE from source, we print the preCICE version information as, e.g.:

```
---[precice]  This is preCICE version 2.4.0
---[precice]  Revision info: v2.4.0-67-gb8beae6e
```
in CMake and in the beginning of the simulation. This essentially means:

> This is preCICE v2.4.0 (hard-coded in a file). More specifically, it is preCICE v2.4.0 (via a tag) + 94 commits, with the latest one being b8beae6e.

## Issue

While looking at some logs (@carme-hp), I got a very confusing output, which looked essentially like this:

```
---[precice]  This is preCICE version 2.4.0
---[precice]  Revision info: v1.3.0-<number>-g<hash>
```

I was very puzzled, thinking that this may be some version mix-up. After some time, I realized that preCICE was included as a dependency in the repository of the respective adapter, which was itself at its own v1.3.0.

This is probably a corner case (tiny benefit), but maybe it is also very easy to fix (tiny effort). Still, I can imagine that there are projects that are organized like this for reproducibility reasons.

### Solution A

One idea would be to extend the message to explain how the revision info is computed. For example:

```
---[precice]  This is preCICE version 2.4.0
---[precice]  Revision info (<latest git tag>-<commits since>-g<commit hash>): v2.4.0-67-gb8beae6e
```
This does not really fix it, but at least gives a hint that could help the user understand such cases.

### Solution B

Another idea would be to extend the check to only run when this is really the preCICE repository. Not sure how exactly to determine that, though.

https://github.com/precice/precice/blob/6d27ad5db42997bbc06ff97b39eb4999196295b7/cmake/cmake_refresh_git_revision.cmake#L15

**Comment by fsimonis** [comment]
We could query git for the root of the repo using `git rev-parse --show-toplevel` and then compare it to the CMake source directory. If both differ, then we know that preCICE isn't a git checkout.
