### ISSUE TITLE
Replace tarch testing by Boost Test

### ISSUE THREAD

**Issue by floli** [precice/precice#14]

**Comment by uekerman** [comment]
with boost test it will be possible to test a single test at run time, right? this would be a really important feature

**Comment by floli** [comment]
Yes, see http://www.boost.org/doc/libs/1_58_0/libs/test/doc/html/utf/user-guide/runtime-config/run-by-name.html

**Comment by floli** [comment]
A HiWi of mine is now working on that issue.

**Comment by uekerman** [comment]
In the meanwhile, boost tests are up and running, but not all tests have yet been ported to boost. This should be our goal and until then we leave this issue open. Please comment here if you have ported some tests to increase the peer pressure :)
New tests have to be implemented in the boost frame.

**Comment by uekerman** [comment]
All tests finally ported. We can do the clean-up now, i.e. remove the tarch testing framework from the sources, from binprecice, and from travis.
