### ISSUE TITLE
Deprecate: Actions with old signature

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1401]
I know: This is definitely a "too late to the party addition".

In #1358 we decided to simplify the interface of all actions. At the end of the Issue there is a comment suggesting that we should deprecate the old interfaces, when the `v2.5` vs. `v3.0` is resolved. This means: We should/could actually deprecate the old signature, because `v2.5` is coming.

However, for practical reasons: We can also directly close this issue and skip the deprecation step, if this brings too much trouble for the release. I think the deprecation is not extremely critical here.

**Comment by DavidSCN** [comment]
We could still incorporate the deprecation as it would only require modifying a few lines. However, I'm not sure if it makes sense as the actions are called from the python interface (right?) and the user would not 'see' the deprecation warning here. Any opinions?

**Comment by BenjaminRodenberg** [comment]
I'm preparing the actual removal in #1403. @uekerman and I briefly discussed the deprecation and it's probably a lot of work and also an overkill. So I would actually tend to just skip the deprecation step. Main question: What do we want to tell our users with the deprecation? I imagine we should also offer the correct alternative, if we ask the users to touch their code. But providing both version (old and new one) at the same time is complicated and not really worth the effort.

**Comment by uekerman** [comment]
Not worth the hassle and unclear use case. Closing this one. Please protest if you disagree.
