### ISSUE TITLE
Rename `use-qr-decomposition` to something more appropriate

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1417]
**Please describe the problem you are trying to solve.**
In general, preCICE has two flavors of data mappings: one using PETSc, which is the default (assuming it was compiled with PETSc) and one using Eigen, which can be queried enabling the option `use-qr-decopmosition=true`. In #1372 we replaced the QR decomposition partially by a Cholesky decomposition and the name of the option doesn't fit any more. In addition, `use-qr-decomposition` might be a bit confusing for users, because they are probably not familiar with the data mapping and the details. 

**Describe the solution you propose.**
We should rename the option to something more appropriate, such that the option a) reflects what's going on under the hood and b) the user gets an intuitive guess when to enable the option (probably for all non-massively parallel cases). @uekerman proposed `use-direct-solver`, which might be a valid option. However, if we decide to also try a (sparse) direct solver in our PETSc implementation, this name will again lead to conflicts in the decision tree. 
As alternatives, I would consider something like `use-distributed-mapping` or `gather-scatter-mapping`, which would reflect the real difference in the implementation. Disadvantage might be that `distributed-mapping` sounds a bit more sophisticated and users simply might not enable it (which I would always recommend in serial runs).

**Comment by fsimonis** [comment]
What would be the user perspective here?
The user selects an rbf and adjusts some shape parameter.
Additionally, they may set some axis as dead.

The implementation/backend really should only need configuration if there are performance issues.
preCICE should select what's most appropriate by default.

Based on this, couldn't we add a "backend" or "method" or "implementation" attribute? This would allow to select gather-scatter-qr or petsc-gmres.
Default should be inferred from the system, so some sort of "guess" value could make that easier to read.

**Comment by BenjaminRodenberg** [comment]
Another line of thought: What would a user search for when looking for this option? How can a user find this option in our documentation? Is there maybe already a fitting name out there?

In our documentation we write

> For small/medium size problems, the QR decomposition is enough and you don’t need to install anything else. However, this follows a gather-scatter approach, which limits the scalability. For large problems, the GMRES solver performs better than the QR decomposition. For this, you need to [build preCICE with PETSc](https://github.com/precice/precice/wiki/Dependencies#petsc-optional). If you built with PETSc, the default is always GMRES. If you still want to use the QR decomposition, you can use the option use-qr-decomposition.

What I understand here is: "I've built preCICE with PETSc, but I want to use the no PETSc option anyway. How can I do this?"

Since I'm not so much into the mapping business I might qualify as a rubber duck: Why would I actually want to use this option, if I also have the (always superior?) PETSc option? Is it mainly a reproducibility thing? Why do I want to use the fallback, if I have PETSc? We could also make this not configurable at all and always use the PETSc option, if it is available. I assume you had a good reason for still making this configurable. Is this maybe a hint to the right name?

**Comment by davidscn** [comment]
> The implementation/backend really should only need configuration if there are performance issues.
preCICE should select what's most appropriate by default.

I also thought about this, but for our research interest we need the option in order to clearly decide for something. Also, this might lead to unexpected behavior. Example: A user sets up a case on his laptop and we decide to go for the eigen variant. For the in-production run, the user decides to run everything on a cluster in parallel and we switch from the eigen backend to the PETSc backend, where the iterative solver fails to converge or something similar. From the user perspective, there is no way to understand what's going on under the hood and why the case fails all of a sudden.

> Why would I actually want to use this option, if I also have the (always superior?) PETSc option? Is it mainly a reproducibility thing? Why do I want to use the fallback, if I have PETSc?

The eigen backend is usually faster and more accurate, especially for everything you do on a laptop. However, I can see that our documentation does not reflect this.

**Comment by fsimonis** [comment]
> From the user perspective, there is no way to understand what's going on under the hood and why the case fails all of a sudden.

True. Maybe an info statement could be helpful here.

Using your scenario:
```xml
<mapping:rbf-thin-plate-splines direction="read" from="MyMesh2" to="MyMesh1" constraint="consistent" />
```

On laptop:
```
INFO: The RBF-mapping of type "thin-plate-splines" from MyMesh2 to MyMesh1 auto-selected the back-end "EigenQRDecomposition" for the current run, as the participant runs on less than 4 ranks. To make this selection permanent add the attribute`backend="EigenQRDecomposition"` to the mapping definition.
```

On a workstation/cluster:
```
INFO: The RBF-mapping of type "thin-plate-splines" from MyMesh2 to MyMesh1 auto-selected the back-end "PETSc" for the current run, as the participant runs on more than 4 ranks. To make this selection permanent add the attribute`backend="PETSc"` to the mapping definition.
```

**Comment by fsimonis** [comment]
An alternative naming scheme for RBFs in general could be the following:
* Keep the `rbf-` prefix
* Use the method as suffix
* Move the actual basis-function to an attribute

```xml
<mapping:rbf-qr basis-function="thin-plate-splines"
  direction="read" from="MyMesh2" to="MyMesh1" constraint="consistent" />
<mapping:rbf-gmres basis-function="thin-plate-splines"
  direction="read" from="MyMesh2" to="MyMesh1" constraint="consistent" />
<mapping:rbf-partition-of-unity basis-function="thin-plate-splines"
  direction="read" from="MyMesh2" to="MyMesh1" constraint="consistent" />
```

This has some benefits:
* we keep the number of possible tags low [We currently have 1 per rbf](https://precice.org/configuration-xml-reference.html#mappingrbf-thin-plate-splines) and the number of choices is growing.
* we can improve error messages, as currently, a typo in the rbf name leads to an `unknown XML tag` error. It would be desirable to be faced with an error like this: `X is not a known basis function. Available options are Y,Z,U... Please open an issue if you need another basis-function`.
* we can expose and document solver-specific parameters in the configuration in a less confusing way.
* we can easily add new back-ends: #1273 and GPU

**Comment by uekerman** [comment]
> Move the actual basis-function to an attribute

I like, but why not also making the backend an attribute? Then, we could define a default in the long run (probably partition-of-unity).

**Comment by davidscn** [comment]
> I like, but why not also making the backend an attribute? Then, we could define a default in the long run (probably partition-of-unity).

I'm not sure whether we want to mix the POU and the global RBFs. Mathematically speaking, Eigen and PETSc are the same, but numerically and implementation-wise very much different. POU is mathematically and implementation-wise different again.

**Comment by fsimonis** [comment]
> I like, but why not also making the backend an attribute?

This will be difficult to document as the one tag represents all backends.
What does `max-iterations` mean for QR for example?

Subtags are also possible.

**Comment by davidscn** [comment]
> max-iterations

There is no such a tag in the mapping, so that's a good question. However, solver tolerance and similar attributes will only be required for one type. POU will again have parameters such as partition size, which don't really fit to the other RBF types.

**Comment by uekerman** [comment]
Yes, makes sense.

**Comment by davidscn** [comment]
To summarize once more what we have so far: use tags for each implementation in order to prevent useless attributes belonging only to one of the implementations and an attribute for the basis function.
The difficult part is then still the naming of the tag itself, because there are multiple information I would like to encode into the tag: the solver itself as well as the parallel execution.

Using `mapping:rbf-qr` would simply be wrong, as we mostly use `Cholesky` for the Eigen implementation right now and only sometimes the QR decomposition. In principle, an accurate description would be `dense-matrix-decomposition`.

Using `mapping:rbf-gmres` would be correct for the PETSc solver.
 
However, using the solver only for the tag will be insufficient once we want to offer different backends using the same solver. A recent example would be the GPU mapping, which will most likely use an iterative solver as well, maybe a GMRES solver in the end. Also, if we decide to support dense matrix decompositions in parallel at some point, the naming above won't be expressive enough.

Possible solutions: 

1. Use the convention `<mapping:solver backend="distributed/gather-scatter/gpu" ...>`, i.e. encode the solver in a tag and introduce an additional attribute for the execution policy. The additional attribute would be useless right now and we would need to safeguard quite a few combinations. Example:  `<mapping:rbf-dense-matrix-decomposition backend="gather-scatter-" ...>`

2. Encode everything in the tag, i.e. `<mapping:solver-backend ...>`, which would have the advantage that there we have only the combinations we support and need right now. Example `<mapping:rbf-gather-scatter-dense-matrix-decomposition .../>`.

**Comment by uekerman** [comment]
Option 2 sounds too cumbersome to me. Option 1 could be good. How would you then encode PoU?

We could make the solver options shorter: `direct` vs. `iterative`

```xml
<rbf:direct backend=gpu ...>
```

`backend` options could also be the implementations: `petsc`, `ginko`, `Eigen`, ...

**Comment by fsimonis** [comment]
> Using mapping:rbf-qr would simply be wrong

Good point. I wasn't aware of this. :+1: 

> In principle, an accurate description would be dense-matrix-decomposition.

This is yet again tricky, as we should really use [sparse linear algebra](https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html) to handle compact RBFs as they usually result in sparse linear systems. _I just noticed that we don't have an open issue for this._

> Encode everything in the tag

This works, but generates even more entries in the documentation and makes the generation of good error messages tricky.
Currently, the configparser traverses the tags and handles this, so a solution requires some kind of callback in the XML tag listener to allow the parser handing off the error message generation to the configuration.

We are dealing with a matrix of:

* dense, sparse systems
* direct, iterative solvers (still misses the actual name of the solver)
* distributed, serial(gather-scatter) processing
* execution on host or device/GPU
* the implementation PETSc, Eigen, ginko
* various configurable RBFs

The question remains what goes in the tag and what goes in the attribute.

We could also go a completely different direction and use the tag only to distinguish the partition of unity from our existing (monolithic?) version. Then we move everything else into the attributes
* `mapping:rbf-partition`
* `mapping:rbf-monolithic`

**Comment by uekerman** [comment]
We still the `mapping` in the tag:

- `mapping:rbf-pou-direct` etc ... but still looks too complicated to me

**Comment by uekerman** [comment]
What about merging `pou` and `non-pou`? Meaning that we could reconstruct `non-pou` via `pou` via specific settings (1 subdomain or similar).

In the long run we want that `mapping:rbf` gives the best method.

**Comment by fsimonis** [comment]
> Rather dislike. This would require the user to know the libraries. Having something like 'serial/gather-scatter' or 'distributed' is more universal.

Strongly agree on this on.

> This is yet again tricky, as we should really use [sparse linear algebra](https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html) to handle compact RBFs as they usually result in sparse linear systems. I just noticed that we don't have an open issue for this.
> 
> > I don't get how this is related to the issue here. Using direct will eliminate this problem anyway.

My comment was more towards the bigger picture that solver type (direct/iterative) and storage layout (dense/sparse) are independent.
`<mapping:rbf use-qr-decomposition="true" ...>` can be `dense-matrix-decomposition` as well as `sparse-matrix-decomposition` depending on the storage layout. We currently use a dense layout, but that doesn't need to stay that way.

> 
> mapping:rbf-partition
> mapping:rbf-monolithic
>  
> > This will lead to useless tags such as tolerance and max-iterations, as discussed further above. I would vote for dedicated tags.

True, so we would need to add direct/iterative to the mix: _(monolithic still used for the lack of a better word)_

* mapping:rbf-partition-direct
* mapping:rbf-partition-iterative
* mapping:rbf-monolithic-direct
* mapping:rbf-monolithic-iterative

> In the long run we want that mapping:rbf gives the best method.

@uekerman If we aim to advertise the alias `mapping:rbf` as a default, then more complicated names like `mapping:rbf-pou-direct` won't be an issue.
Actually, it may be easier to detect and read non-default configurations in the XML file.

@davidscn IIRC, you plan to make the RBF used by PoU configurable. Would it make sense to add support for iterative solvers as well?
If the answer is yes, then it looks like we converged to `mapping:rbf-<pou|the other>-<direct|iterative>` + alias `mapping:rbf`.

Whatever the result of this discussion is, updating the mapping configuration will be fun :see_no_evil:

**Comment by uekerman** [comment]
Discussed in person with @davidscn 

All mappings have the standard attributes: `from`, `to`, `constraint`.
All explicit RBF mappings have the following additional attributes: `basis-function`, `support-radius`, `shape-parameter`. 

Then, we distinguish:

```xml
<!-- partition of unity -->
<mapping:rbf-pou-direct acceleration="off/..." vertices-per-cluster="..." relative-overlap="..."    />
<mapping:rbf-pou-iterative acceleration="off/..." tolerance="..." max-iterations="..."  
                                                   preconditioner="..." vertices-per-cluster="..." 
                                                   relative-overlap="..."  />  <!-- not yet planned -->

<!-- the classical global rbf mapping -->
<mapping:rbf-global-direct acceleration="off/..."  /> 
<mapping:rbf-global-iterative acceleration="off/..." parallelism="gather-scatter/distributed" 
                                                      tolerance="..." max-iterations="..." preconditioner="..."  />  
```

`acceleration` can be sth we extend as we go: 
- off
- gpu
- gpu-petsc
- openmp-eigen 
- openmp-ginkgo
- ...

And on top, we define a user-friendly alias:

```xml
<mapping:rbf ... /> <!-- alias for best mapping method (we could change what is best when necessary) -->
```

This one could be pretty powerful. Some decision tree that automatically chooses the best option for a certain scenario (mesh size, number of MPI ranks, ...).

@fsimonis Sounds reasonable?

**Comment by davidscn** [comment]
>  Is it wise to reuse "acceleration" here? Could this potentially lead to confusion when searching the docs?

Good point. Alternatives that come to my mind: executor, back-end, processing, implementation, aid, enhancement, boost

**Comment by fsimonis** [comment]
Don't we also need to add an attribute for selecting a GPU to run the mapping on? This could be necessary in multi-GPU systems.

Maybe it is a good idea to ignore accelerator-related attributes until we have a concrete implementation.

**Comment by davidscn** [comment]
Probably yes (we need to set a device id). The same holds for OpenMP usage (`OMP_NUM_THREADS`) or similar. 

> Maybe it is a good idea to ignore accelerator-related attributes until we have a concrete implementation.

No strong opinion here. We cannot incorporate the ID or number of threads into the same attribute, so we would have to add one later on anyway. However, adding the accelerator or whatever tag later on will be easy and straight forward.

**Comment by davidscn** [comment]
Let me remark here that https://github.com/precice/precice/issues/1417#issuecomment-1380375728 comes at the cost of default values for the support-radius and the shape-parameter. Right now, we have these attributes only selective depending on the basis function. Also, the user won't be able to see at a first glance, whether the shape-parameter or the support-radius will be required as an input parameter.

**Comment by uekerman** [comment]
> Let me remark here that https://github.com/precice/precice/issues/1417#issuecomment-1380375728 comes at the cost of default values for the support-radius and the shape-parameter. Right now, we have these attributes only selective depending on the basis function. Also, the user won't be able to see at a first glance, whether the shape-parameter or the support-radius will be required as an input parameter.

Not a big problem IMO. 99% of users will not change basis functions, but only copy whatever we say they should use.

**Comment by uekerman** [comment]
> Maybe it is a good idea to ignore accelerator-related attributes until we have a concrete implementation.

:+1:

**Comment by fsimonis** [comment]
The solution to this is actually rather simple from an implementation point of view:
We create a subtag

```xml
<mapping:rbf-pou-direct vertices-per-cluster="..." relative-overlap="...">
  <basis-function:gaussian shape-parameter="..." />
</mapping>
```

This requires a slightly modified configuration.

Question is whether we want to open that can of worms…

**Comment by uekerman** [comment]
I like the subtag idea :+1: Makes things also easier to read, no?

**Comment by davidscn** [comment]
What happened with

> Not a big problem IMO. 99% of users will not change basis functions, but only copy whatever we say they should use.

Using a subtag is better in terms of permitted configs, but will make configuration writing more intricate.

**Comment by davidscn** [comment]
After discussing this during the TelCo, we decided to go for the additional subtag.
