### ISSUE TITLE
Parallelize the existing initialization of preCICE by a two-level approach

### ISSUE THREAD

**Issue by uekerman** [precice/precice#142]
This issue should be an overview on the complete story and link to respective smaller work packages.

This is a draft and should be extended and formatted. 

The following steps need to happen during initialization (in this order):

### 1. [Communicate Bounding Boxes and Generate Connection Information](https://github.com/precice/precice/pull/169)
* package: `partition`
* new function `communicateBoundingBox`: 
  * gather and send bounding boxes at `ProvidedBoundingBox` (finally will be merged to `ProvidedPartition`) 
  * receive set of bounding boxes at `ReceiveBoundingBox` (finally will be merged to `ProvidedBoundingBox`) 
* new function `computeBoundingBox`: 
  * generate a feedback for each rank which includes connected ranks on the orther side
  * gather these feedbacks at Master of `ReceivedPartition` and send it to the other master.
  * Master of `ProvidedPartition` bradcasts the set of feedbacks to its slaves  
  * each rank creates a `CommunicationMap` (member variable of `Mesh`), a map _rank |-> set of vertices. At this level list of vertices has only one dummy member (-1). This list will be udated later.

- [x] Implemented
- [x] Unit tests
- [x] Reviewed 
- [ ] Merged to `develop`

### 2. [Create Communications](https://github.com/precice/precice/pull/180)
* package: `m2n`
* new functions `acceptPreCommunication`, `requestPreCommunication` 
* we get initialConnectionMap from Mesh 
* generate `mappings` by calling accept/requestPreConnection -> without vertex list

- [x] Implemented
- [x] Unit tests
- [ ] Reviewed 
- [ ] Merged to `develop`

### 3. [Broadcast Local Mesh Partitions](https://github.com/precice/precice/pull/181)   
* package: `partition` , `m2n` 
* partition: new function `communicate`  
* each rank on `ProvidedBoundingBox` broadcasts mesh partition to all connected ranks on `ReceivedboundingBox`
* `M2N` needs new methods `accept/requestSlavesPreConnection` to call `accept/requestPreConnection` in `PonitToPointCommunication` 
* two new method in `PonitToPointCommunication` class: broadcastSend/ReceiveMesh 
* `M2N` needs new method `broadcastSendLocalMesh` and `broadcastReceiveLocalMesh`  that in turn calls a new method `broadcastSendMesh` and `broadcastReceiveMesh`  in the respective `PointToPointCommunication`
* each rank iterates over the simlified `mappings` and use `com::CommunicateMesh` to send the mesh partitions point to point. 

- [x] Implemented
- [x] Unit tests
- [ ] Reviewed 
- [ ] Merged to `develop`

### 4. Compare Local Meshes
* package: `partition`
* modify existing function `compute`
* No longer compute a `VertexDistribution`, but a `LocalCommunicationMap` (again member variable of `Mesh`), a map _rank |-> set of indices_ (to whom do I communicate which global IDs

- [x] Implemented
- [x] Unit tests
- [ ] Reviewed 
- [ ] Merged to `develop`

### 5. Create Final Mappings
* package: `m2n`
* use `localCommunicationMap` as input and not `VertexDistribution`
* update mapping according to `localCommunicationMap`, we should use `updateAccepterCommunicationMap` and `updateRequestreCommunicationMap` to fill in the vertex list!
* same communicators can be used! we just update the list of verices!  

- [x] Implemented
- [x] Unit tests
- [ ] Reviewed 
- [ ] Merged to `develop`

### 6. Refactoring

* we want to use same classes in the partition package at the end
* the implementation should be configurable for testing and using both approaches
* we should refactor all changes in that direction and delete unused lines 

### General

- [x] Integrated in `SolverInterfaceImpl` (configurable)
- [x] Integration tested
- [ ] Reviewed 
- [ ] Performance tested
- [ ] Merged to `develop`

### List of sprint issues:
* TODO

**Comment by atotoun** [comment]
WP1: we will call the resulting data structure `connectionMap`

**Comment by BenjaminRueth** [comment]
This part should be fixed in the refactoring:

https://github.com/precice/precice/blob/b6d13378bfd99a231c8f9a37d0f8448d0b16eeeb/src/m2n/GatherScatterCommunication.cpp#L165-L187

**Comment by uekerman** [comment]
Finally solved in #533
