### ISSUE TITLE
Make using pre-Commit hooks the default (and only) way for code formatting

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1423]
For https://github.com/precice/precice/pull/1422/commits/76c3d7e01cfa308307ab95729def72605f96c767 running `make format` does not perform any necessary changes, but the formatting tests are still failing. See https://github.com/precice/precice/runs/7981872112?check_suite_focus=true. I guess that the reason is that the pre-commit hooks are now used for formatting checks.

**Expected behaviour**

Since the checkboxes in the PR suggest running `make format` (and I'm used to it), I would expect that running `make format` (even without the pre-commit hooks being setup) results in passing formatting tests.

**Comment by BenjaminRodenberg** [comment]
Any updates here? Can anybody else verify this?

**Comment by fsimonis** [comment]
We have to update the PR template.
The pre commit hook is the way to go as it replaces a manual step by an automatic one. It also uses a consistent version, which always was a pain to handle.

I recommend you to install the pre-commit hook and forget about formatting :smile:

**Comment by BenjaminRodenberg** [comment]
I already feared that I have to update my old habits :see_no_evil: Then let's rephrase this issue: If we make the pre-commit hooks the default for formatting, we should update the PR template (like you already mentioned) and remove `make format` (for v3?). Is this a reasonable step? I'll also quickly update the title of this issue.

**Comment by BenjaminRodenberg** [comment]
If we update the PR: I think providing a link to [the documentation](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) helps to lower the entry barrier. It's really simple to install and use the hooks (old habits updated :heavy_check_mark:).
