### ISSUE TITLE
Resetting sent data in coupling scheme to zero after sending affects downstream calculations. Why?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1424]
**Describe your setup**

https://github.com/precice/precice/commit/b7b5739b62cbab3948c98b97911f211090d6dea2

**Describe the problem**

To clean up things and to make sure there are no strange, I changed the source code to reset data after sending and before receiving in the coupling scheme (see link to commit above). However, I observed that some tests are failing after this change. 

**Step To Reproduce**

1. Check out branch
2. Run tests

**Expected behaviour**

As far as I know the data should not be used anymore after sending. I also think that this would be the most intuitive behavior. Any idea why this is happening?

**Additional context**

This is a pure software engineering issue. But it might also be a bug. I'm not sure here.

**Comment by BenjaminRodenberg** [comment]
@uekerman: I assigned you hoping that you have an idea where this is coming from.

I added it to the `2.x.x` milestone, because it seems to be acceleration related. If we want to change something here to make things more friendly on the side of the code, it might be good to do this before 3.0.0.

**Comment by uekerman** [comment]
I guess many things could still be done with data after sending:

- It could be sent to another participant
- It could be used in an action
- It could be exported

**Comment by uekerman** [comment]
I don't think this is a bug, closing. Please re-open if anyone doesn't agree.
