### ISSUE TITLE
Quantitative Validation: FSI3 Benchmark

### ISSUE THREAD

**Issue by DURAI04** [precice/precice#143]
Now I am working in the filed of SU2- PreCICE-Calculix Coupling. I did all software installations in ubuntu 16.04. After that i test the flap case https://github.com/precice/precice/wiki/FSI-tutorial which is working fine. Now i need to validate the one problem.For that regard i used for the following reference case. It is not working properly. Can you please help me?
![selection_021](https://user-images.githubusercontent.com/17636077/43988823-374ec6f8-9d5b-11e8-9e68-81d6e4507311.png)
[su2_calcu.tar.gz](https://github.com/precice/precice/files/2279968/su2_calcu.tar.gz)

**Comment by MakisH** [comment]
We are closing this as it is not an issue in preCICE, but rather something for the tutorials or the adapters. See, for example, this contribution to the tutorials: https://github.com/precice/tutorials/pull/64

Other than that, you can now use our [preCICE forum](https://precice.discourse.group/) to discuss specific cases.
