### ISSUE TITLE
Which data actions are really needed?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1438]
While working on waveform relaxation I had a lot of trouble with providing the right data at the right time to the data actions. We might be able to simplify this part of preCICE by removing some features here. The following function is called at several places in `SolverInterfaceImpl`:

https://github.com/precice/precice/blob/b81e53f5bd5d63b18b45692756d894211050f381/src/precice/impl/SolverInterfaceImpl.cpp#L2028-L2041

There are the following timings that are used with this function:

* `action::Action::READ_MAPPING_PRIOR`
* `action::Action::READ_MAPPING_POST`
* `action::Action::WRITE_MAPPING_PRIOR`
* `action::Action::WRITE_MAPPING_POST`
* `action::Action::ON_TIME_WINDOW_COMPLETE_POST`

Ideally, I would like to remove all data actions that are used with these timings and only keep `action::Action::ON_TIME_WINDOW_COMPLETE_POST`. We could potentially also introduce a new timing at the end of the window, if the iteration has not converged. The purpose of this is to move all actions after the waveform relaxation and mapping is done to have less interference of actions, mapping and waveform relaxation.

**Comment by BenjaminRodenberg** [comment]
@uekerman can we close this issue? I think #1614 pretty much resolves this.

**Comment by uekerman** [comment]
yes
