### ISSUE TITLE
Make building of PySolverInterface safe and clean

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#144]
https://github.com/precice/precice/commit/f5fa4ed01f30696df37d41523bac1e56daceb6bb makes sure that `setup.py` only deletes `precice/src/precice/bindings/python/build`. Before, it was possible to accidentally delete any folder names `build`, if `setup.py` is not run from `precice/src/precice/bindings/python`. This is especially annoying, if `setup.py` is run from `precice` just after compiling preCICE.

With https://github.com/precice/precice/commit/f5fa4ed01f30696df37d41523bac1e56daceb6bb, `setup.py` can be run from arbitrary folders and only `precice/src/precice/bindings/python/build` is deleted - if it exists. 

However, the new `build` and `PySolverInterface.so` are created in the folder, where `setup.py` is run. `PySolverInterface.cpp` is created in `precice/src/precice/bindings/python`. **This is messy.** 

What do we actually want to have the binaries? I see the following possibilities:

1. do not allow to run `setup.py` outside of `precice/src/precice/bindings/python`.
2. no matter, where `setup.py` is run, put all resulting files into the root folder. (here I do not see any possibility to realize a good cleanup process of temporary files)
3. no matter, where `setup.py` is run, put all resulting files into `precice/src/precice/bindings/python`.

# Progress

- [x] where do we want to have the binaries?
    - [x] temporary in `precice/src/precice/bindings/python`
    - [x] python module at default location (i.e. `site-packages` or `dist-packages`)
- [x] update code influenced by binaries at python default locations
    - [x] elastictube [StructureSolver.py](https://github.com/precice/elastictube1d/blob/master/PythonTube/StructureSolver.py#L10)
    - [x] elastictube [FluidSolver.py](https://github.com/precice/elastictube1d/blob/master/PythonTube/FluidSolver.py#L21)
    - [x] [solverdummy.py](https://github.com/precice/precice/blob/develop/tools/solverdummies/python/solverdummy.py#L13)
- [x] compatibility
    - [x] python 2 (2.7.12)
    - [x] python 3 (3.5.2)
- [x] include building python bindings in preCICE build? yes! --> offloaded issue to https://github.com/precice/precice/issues/182
    - [x] update SCons build process (optional, we want to move towards cmake)
    - [x] update cmake build process
- [x] add relevant changes to [changelog](https://github.com/precice/precice/blob/develop/CHANGELOG.md)

**Comment by BenjaminRueth** [comment]
One thing that just came to my mind: we could also add the building of the python languages to the main preCICE build process. I would suggest making this optional, since otherwise we get cython as an additional dependency for building preCICE.

**Comment by MakisH** [comment]
Without having a good view of the problem, I would recommend putting all the bindings in the same build path as preCICE, in a dedicated directory, if needed.

This means:
1. if we have everything built in `precice/build/`, then put the Python bindings in `precice/build/bindings/python`.
2. if we install headers in e.g. `usr/local/lib/precice/` and `usr/local/include/precice`, then put the bindings also in `usr/local/lib/precice/bindings/python` and `usr/local/include/precice/bindings/python`.

I would prefer to avoid having binaries under `precice/src/` (as we do now, for the bindings).

In all these, keep in mind that we want to push towards CMake, so don't invest much on SCons anymore.

**Comment by MakisH** [comment]
Integrating the building of any bindings to the main preCICE build process is a good idea (assuming that they are always shipped together), but of course it should be off by default.

**Comment by floli** [comment]
> if we install headers in e.g. usr/local/lib/precice/ and usr/local/include/precice, then put the bindings also in usr/local/lib/precice/bindings/python and usr/local/include/precice/bindings/python.

Shouldn't this be put under `/usr/lib/python3.7/site-packages` or alike?

Also, please have a look at #68, when you're working at the python adapter. ;-)

**Comment by BenjaminRueth** [comment]
I created a branch for this issue https://github.com/precice/precice/commit/4a37deb0830ce7437bdfb640024d03d63d4d575b.

Building is now done via `python setup.py build` and `(sudo) python setup.py install`. To my understanding using this way we do not have to worry about where to put the binaries. 

`build` is created in the folder, from where you are running `setup.py build`. However, the `PySolverInterface.cpp` is created in `precice/src/precice/bindings/python`. It is possible to run `setup.py` from arbitrary locations, but I think it is most reasonable to run `setup.py build` from inside `precice/src/precice/bindings/python`. Otherwise the `build` folder and `PySolverInterface.cpp`, that are both temporary, are at different places.

As a second step you run `setup.py install`. To my understanding, this puts `PySolverInterface.so` to a default location (such as `site-packages` or `dist-packages`). You can also specify a prefix, if you cannot access `site-packages`.

Another benefit of this approach is, that we do not have to manually search for `PySolverInterfacce` anymore, since it is on `PYTHONPATH` already. This saves some lines of code in codes using the Python API. I can take care of updating this.

**Does this new build process have any other effects?** E.g. Testing? Travis?

**Comment by MakisH** [comment]
I am definitely not the right person to talk about Python, but, if this `distutils.core.setup()` is a standard way to install python packages, then definitely do it like this!

I only noticed this in the `setup.py`:

https://github.com/precice/precice/blob/4a37deb0830ce7437bdfb640024d03d63d4d575b/src/precice/bindings/python/setup.py#L9

Shouldn't this be set externally? Unless I am missing something here.

**Comment by BenjaminRueth** [comment]
The reason for setting `precice_root` this way is that you sometimes have to run `sudo setup.py install`. `sudo` does not know `PRECICE_ROOT`. I'm also not 100% happy with this solution, but on the other hand it, this way we can build the python bindings without the necessity of any additional environment variables being set (and `setup.py` should not be moved around anyway).

**Comment by BenjaminRueth** [comment]
Created branch [updatedPythonBindingsBuildProcess](https://github.com/precice/elastictube1d/tree/updatedPythonBindingsBuildProcess) on elastictube1d repository. See https://github.com/precice/elastictube1d/commit/6e9d2ce23453d8d33372102a10c0b12cfc223c16
