### ISSUE TITLE
Improve solverdummy argument parsing

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1447]
Our solverdummies are part of the test infrastructure. In case something goes wrong with the argument parsing, users (might) face issues like this one

https://stackoverflow.com/questions/62570882/what-basic-string-m-construct-null-not-valid

which is very cryptic and due to inappropriate handling of the parsed arguments (see the discussion in the link and our current implementation).

https://github.com/precice/precice/blob/e6da8d5d9432f0872ff0e1ecf652477fbbcf6c68/examples/solverdummies/cpp/solverdummy.cpp#L13-L17

**Comment by kursatyurt** [comment]
How about using `GNU getopt` for parsing or using something like [this solution](https://www.codeproject.com/Tips/5261900/Cplusplus-lightweight-parsing-command-line-argumen)?

**Comment by davidscn** [comment]
Thanks for the suggestions, I think a simple abort is sufficient right now, see #1448
