### ISSUE TITLE
Refactor CompositionalCouplingSchemeTest.cpp

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#145]
This issue originates from resolving #90.

In `CompositionalCouplingSchemeTest` (https://github.com/precice/precice/blob/develop/src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp) there are basically two classes of tests:

* `testDummySchemeComposition...`, which are rather simple
* tests with 3 participants calling `setupAndRunThreeSolverCoupling` with different configuration files.

**Does it make sense to split these two classes of tests into two independent `.cpp`-Files?** Currently `CompositionalCouplingSchemeTest.cpp` is with nearly 1000 lines quite long, so it would reduce the complexity of the script to split it. Additionally the `testDummySchemeComposition...` tests do not rely on xml-configs or on setting up communication via `connect`, while for the tests with 3 participants `connect` is called multiple times and I am also not sure whether we could replace calling connect with the M2NFixture (see #90). **Is it possible to use the M2NFixture also for the three solver case?**

# Progress

- [x] split up tests into two test suites
- [x] use M2Nfixture, M2Nfixture only works for 2 participants

**Comment by uekerman** [comment]
Concerning the two files sub-task. Here, we have a convention: Every class has exactly one test class with the same name + `Tests`. I would only break this convention if there is a real necessity, which I don't see here. Yes, the class is long, but still easy to overview ... and long test classes are normally a good sign ;)

**Comment by uekerman** [comment]
Concerning the `M2NFixture`. 

You cannot use the existing `M2NFixture` as this one works with two participants. One could do an additional fixture or one could extend the current implementation. Both do not improve anything, in my opinion, as having three participants is really something very specific to this class (maybe also `MultiCouplingScheme`, but there are currently no unit tests). 

So a local fixture defined in the class is the proper way to go ... and what we have already. 

The only copy&paste code is the function `connect`, which is very short. One could move this into another fixture, but this is maybe overkill.  

In my opinion, nothing to do here, except the splitting up into two suites.
