### ISSUE TITLE
Rework CompositionalCouplingScheme

### ISSUE THREAD

**Issue by uekerman** [precice/precice#1453]
## Problems of current implementation

- The current implementation is nicely explained in [Bernhard's thesis](https://www5.in.tum.de/pub/Gatzhammer2014_preCICE.pdf), section 4.1.5 (be careful, Bernhard calls these scheme "multi coupling", while "multi coupling" is now sth different in preCICE; let's stick with the term "compositional coupling").
- The current implementation is heavily based on the defined order of the coupling schemes in the xml configuration. This is not good as it is hard to understand and easy to mess up, see also #982 .
- There are meaningful, yet simple case that the current implementation cannot handle, #593  .
- On the other hand, the implementation supports cases that are numerically unstable: multiple implicit schemes for one participant, see also https://doi.org/10.1007/s00466-014-1113-2 .
- Parallel coupling schemes were not yet carefully considered for the current design.

## Suggestions

- The split of `CouplingScheme::advance` into `firstExchange` and `secondExchange` (suggested in #1451) could already solve #593 if `CompositionalCouplingScheme` does separate loops over the participants for both functions.
- Let's allow only one implicit scheme **per participant** and refer the user to "multi coupling" otherwise.
- Let's execute parallel-explicit schemes before serial-explicit schemes to allow setups where explicit schemes should be computed right away in every timestep (parallel-explicit) and cases where explicit schemes should be computed after the implicit scheme converged (serial-explicit).
- Let's make the implementation independent of the order in the configuration by defining a unique overall sorting. This is also important to avoid deadlocks in case sending becomes blocking (needs testing).

Suggested sorting:
- Parallel-explicit schemes come first
- Then, the one implicit scheme
- Finally, serial-explicit schemes

```cpp
_firstTime = true;

CompositionalCouplingScheme::firstExchange(){
if (_firstTime){
  for (scheme : parallelExplicitSchemes())
    scheme.firstExchange();
  _firstTime = false;
  }

theOneImplicitScheme.firstExchange();

if (theOneImplicitScheme.isConverged())
  {
  for (scheme : serialExplicitSchemes())
    scheme.firstExchange();
  }
```

and exactly the same for `secondExchange`.

## Problems with these suggestions

After `theOneImplicitScheme.firstExchange()` we cannot yet get information on `theOneImplicitScheme.isConverged()` :confused: 

## More

- Let's create a `coupling-scheme:multi-explicit` scheme and rename the current one to `coupling-scheme:multi-implicit`. 
- Unclear yet whether we should allow using a multi-coupling scheme withing a compositional coupling scheme. If yes, we have to treat it as the one implicit scheme, but could be simpler to forbid this.

**Comment by uekerman** [comment]
> After theOneImplicitScheme.firstExchange() we cannot yet get information on theOneImplicitScheme.isConverged() confused

A "solution" could be to handle all explicit schemes first and then the one implicit one. Would we lose meaningful use cases then?

**Comment by fsimonis** [comment]
> A "solution" could be to handle all explicit schemes first and then the one implicit one.

I'll work on a prototype for this version based on #1451 (without the synchronizations).

**Comment by uekerman** [comment]
@carme-hp Could be interesting for you as you also wanted to combine explicit and implicit scheme IIRC
