### ISSUE TITLE
Rename attributes in `m2n` tag

### ISSUE THREAD

**Issue by uekerman** [precice/precice#1460]
## Problem

We currently have:

```xml
<m2n:sockets from="Fluid" to="Solid" exchange-directory="../" />
```

The `from` and `to` are kind of hard to understand. I often have to look up again which was which. And sometimes users misunderstand these and think that for a bi-directional coupling one would need two:

```xml
<m2n:sockets from="Fluid" to="Solid" exchange-directory="../" />
<m2n:sockets from="Solid" to="Fluid" exchange-directory="../" />
```

## Suggested solution

Rename to:

```xml
<m2n:sockets acceptor="Fluid" requestor="Solid" exchange-directory="../" />
```

## Alternatives

?

**Comment by fsimonis** [comment]
Universal alternative that should be straight forward:

```xml
<m2n:sockets server="Fluid" client="Solid" />
```

The server awaits a connection and the client connect to it.

_I omitted the exchange directory due to #1429_

**Comment by fsimonis** [comment]
> Technically true, but it could confuse many users, since "client" and "server" usually have a specific meaning in the coupling tools community.

A user will only touch this tag when they need to set up communication between participants and there is no ambiguity in this context. There a few terms that clear in computer science.

**Comment by fsimonis** [comment]
_My last message somehow disappeared._

Client and server still aren't the correct terms though, as there are multiple clients and multiple servers in case of P2P.

So, ideas are welcome.

**Comment by uekerman** [comment]
Any of these suggestions is better than what we have right now :blush: 

I like `host` and `join`, but no strong opinion. `server` and `client` is indeed not ideal as explained by @MakisH 

`acceptor` and `requestor` has the advantage that we use the same terminology under the hood. So, for devs it is easier to understand.

**Comment by fsimonis** [comment]
> acceptor and requestor has the advantage that we use the same terminology under the hood. So, for devs it is easier to understand.

Shouldn't we pick names that are easier to understand for the user? :wink:

I am increasingly tending towards host-client. Easy to understand, research and close to what is actually going on. Googling for connection problems with a host will be more helpful than connection problem with an acceptor.

**Comment by MakisH** [comment]
My first reaction encountering these terms:
- `acceptor` / `connector`: I like that MPI uses them as well (no experience), this could make them uniform with MPI ports. But they don't sound very self-explanatory to me.
- `accept` / `connect`: Somehow this feels a bit better, but I am not sure if we want verbs.
- `publisher` / `lookup`: Sounds closer to my mental model. I like the `publisher`, not sure about `lookup`.
- `publish` / `lookup`: Same verbs issue.
- `host` / `join`: Goes to the right direction.
- `acceptor` / `requestor`: The one I like the most so far. But still does not directly clarify who publishes the socket address. (the acceptor, but that is the follow-up step)
- `server` / `client`: I already expressed my feelings :grimacing: 

Than you for trying to find better terms! I am sure we will converge to something very good.

**Comment by davidscn** [comment]
Discussing in person:

We still want to rename it to something more appropriate and in order to stick to 'known' communication terminology we will go with

```xml
<m2n:sockets acceptor="Fluid" connector="Solid" exchange-directory="../" />
<m2n:mpi acceptor="Fluid"   connector="Solid" ... />
```
