### ISSUE TITLE
Use names instead of IDs in API

### ISSUE THREAD

**Issue by uekerman** [precice/precice#1461]
## Motivation

When explaining the API of preCICE, there is always this weird moment arguing what these mesh and data IDs are for.

```python
mesh_id = interface.get_mesh_id("Fluid-Mesh")
vertex_ids = interface.set_mesh_vertices(mesh_id, positions)
```

We could merge these two calls into:

```python
vertex_ids = interface.set_mesh_vertices("Fluid-Mesh", positions)
```

and similarly for all other calls. Tricky is the data access as we would now need both names, data and mesh (as the data ID depends on the mesh ID):

```python
write_block_scalar_data("Force", "Fluid-Mesh", vertex_ids, u)
```

## Technical level

In principle one could implement this, for example, directly in the Python bindings without changing preCICE itself. But we could also directly modify the C++ API. 

Opinions?

**Comment by fsimonis** [comment]
We could encapsulate the internal mesh ids in a proxy object:

```py
vertexids = interface.mesh("Fluid-Mesh").set_vertices(positions)
interface.mesh("Fluid-Mesh").write_scalar_data("Force", vertexids, u)
```

If we pin vertex ids directly to a mesh, then we could even do:

```py
fluid_vertices = interface.mesh("Fluid-Mesh").set_vertices(positions)
fluid_vertices.write_scalar_data("Force", u)
```

It is worth noting, that moving away from the IDs will result in more complex C bindings.
The big question is what is more important to us: Consistency or comfort

Related to #717

**Comment by BenjaminRodenberg** [comment]
> It is worth noting, that moving away from the IDs will result in more complex C bindings. The big question is what is more important to us: Consistency or comfort

I thought the same about the python bindings (and probably it applies generally): If we move away from low level types we probably have to think for every language about an individual solution that fits. This might improve usability, but also makes the bindings less consistent (think about the numpy arrays vs. raw double arrays in the python bindings, required some discussions and thinking work).

**Comment by fsimonis** [comment]
Disucssion result:
* We like this a lot
* Does this impact performance if called in a hot loop (setMeshVertex per vertex of a mesh, or read write per vertex)

**Comment by davidscn** [comment]
I benchmarkd  the write data functions we have in preCICE using Googlebench. In the table below, I tested 1e6 data sites using our bulk version (`*Block*`) and our singular versions within a loop. The `*String` version of each function has additionally the `getMeshID` and `geDataID` call in front of the write data function such that these calls appear in the hot loop for our singular data write versions:  

```bash
Run on (16 X 2010.85 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x8)
  L1 Instruction 32 KiB (x8)
  L2 Unified 512 KiB (x8)
  L3 Unified 4096 KiB (x2)
Load Average: 1.11, 0.79, 0.65
--------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
BM_writeBlockVector          3885738 ns      3885167 ns          180
BM_writeBlockVectorString    3653688 ns      3653705 ns          193
BM_writeVectorData          38512469 ns     38511761 ns           18
BM_writeVectorDataString   131978414 ns    131978440 ns            5
BM_writeBlockScalar          1309731 ns      1309685 ns          539
BM_writeBlockScalarString    1330140 ns      1330109 ns          522
BM_writeScalarData          38251144 ns     38249104 ns           18
BM_writeScalarDataString   133618678 ns    133616930 ns            5
```

Interestingly, merging the `getMeshID` and `getDataID` calls into the singular `writeScalarData` (just an example here) function and removing the kind of duplicated sanitization with `PRECICE_CHECK` (in principle, they would be required only once), results in the following timings:

```bash
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
BM_writeScalarData                 36570796 ns     36567614 ns           19
BM_writeScalarDataString          138022666 ns    138000109 ns            5
BM_writeScalarDataSingleFunction   78007861 ns     78006106 ns            9
```

i.e., the redundant checks take a considerable portion of the additional computational cost.

**Comment by fsimonis** [comment]
Discussion result:
* We accept trading performance for usability.
* Impact on block versions are negligible.
* Impact on singular versions, especially in a loop are significant (factor of 2), but the absolute time is still minor.

**Comment by fsimonis** [comment]
I created a microbenchmark to study the impact of a deep refactoring by porting the string interface to string_view. I tried to add a compilation firewall using a pimpl as well as an extra internal layer which should mimic the lookups we perform during input sanitization.

Scenario is setting the data of vertices one by one, which is the absolute worst-case for the name-based method.

Setup:
```
Benchmark
 calls accross compilation units
Outer
  calls 
Outer::Impl
  calls
Inner
  calls (based on transparent comparator)
std::map<string,bool>::count()
```

Each call type is supported along the entire chain. So there won't be conversions:
`const string&` aka SR
`string_view` aka SV
`const string_view&` aka SVR

Each benchmark repeats a call 1e6 times to stay somewhat consistent with the tesz from @davidscn.
Each method is called with a `std::string` (STR) or a hardcoded c-string (CSTR). These are short as long names are rarely used in practise. There is always some conversion going on except for the SR_STR case, which directly passes by reference to const.


Built and run on 5900X in Release without LTO and using DoNotOptimize on the results.

### clang++ 14.0.6
```
2022-11-17T11:04:11+01:00
Running ./bench
Run on (24 X 3700 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x12)
  L1 Instruction 32 KiB (x12)
  L2 Unified 512 KiB (x12)
  L3 Unified 32768 KiB (x2)
Load Average: 0.20, 0.23, 0.23
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
BM_SR_CSTR    19792124 ns     19787192 ns           44
BM_SR_STR     12235664 ns     12232554 ns           57
BM_SV_CSTR    12480597 ns     12477698 ns           56
BM_SV_STR     12482134 ns     12479207 ns           56
BM_SVR_CSTR   12256804 ns     12253709 ns           57
BM_SVR_STR    12461790 ns     12458597 ns           56
```
### g++ 12.2.0 
```
2022-11-17T11:03:05+01:00
Running ./bench
Run on (24 X 3700 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x12)
  L1 Instruction 32 KiB (x12)
  L2 Unified 512 KiB (x12)
  L3 Unified 32768 KiB (x2)
Load Average: 0.14, 0.24, 0.23
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
BM_SR_CSTR    11346242 ns     11343703 ns           62
BM_SR_STR     10606518 ns     10603994 ns           66
BM_SV_CSTR    10807686 ns     10804908 ns           65
BM_SV_STR     11057826 ns     11045993 ns           63
BM_SVR_CSTR   10864274 ns     10807980 ns           64
BM_SVR_STR    10833544 ns     10806084 ns           65
```

* The string_view variants are slightly faster than the string ref variants.
* Calling `const std::string&` with a c-string requires the construction of a `std::string`, which makes the biggest difference of about 60% for clang, but only 6% for g++

This means that the results in https://github.com/precice/precice/issues/1461#issuecomment-1315603435 seem too extreme as the conversion alone should not result in such a stark difference.

**Comment by fsimonis** [comment]
As a conclusion:
* We decided the go forward with this change.
* Usability is more important than performance. Performance impact is negligible for bulk variants.
* We expect users to hardcode names using c-strings, so `std::string_view` is the way to go.

**Comment by fsimonis** [comment]
Another idea to prevent having to pass two arguments to data-related functions could be to introduce a syntax for referring to data on a mesh:

```py
setMeshVertex("MeshA")
writeMeshScalarData("MeshA:DataA")
```

Pros:
* One argument instead of two
* Readable
* Easy to use for cases with hard-coded names
* Having to pass multiple strings in Fortran is rather verbose (see constructor)

Cons:
* Handling and generating strings are tricky in C and Fortran
* Forbids names to include `:`
* It is not apparent that the expected string is such a data designator

**Comment by uekerman** [comment]
I see the pro arguments, but this could be unnecessary invasive for adapter configurations.
