### ISSUE TITLE
Write preCICE configuration into Debug log

### ISSUE THREAD

**Issue by uekerman** [precice/precice#1465]
**Please describe the problem you are trying to solve.**

When trying to understand setups of others (why did it crash?), one of the first questions is always: "Please also provide your preCICE config".

**Describe the solution you propose.**

We could write the complete configuration file as one txt stream into the Debug log. Sounds a bit hacky, but could be useful.

The purpose is not to make the config accessible through the API or similar, but solely for dumping information helpful for debugging. 

Opinions? Too hacky? (Did we discuss this before?)

**Comment by fsimonis** [comment]
Packages and release builds don't include Debug logs. So we always have to tell the user to build a debug version first.
This saves the user a single upload. I am not sure if this makes a noticeable difference.

A usable implementation should be relatively simple. We could compress the XML by replacing newlines with spaces and only print it on the primary rank.
From the developer perspective, it is easier to read a formatted XML file though.

**Comment by fsimonis** [comment]
Discussion result:
* The usual Debug not being in release builds problem makes this an incomplete idea
