### ISSUE TITLE
Location of dimensions option in the configuration format

### ISSUE THREAD

**Issue by MakisH** [precice/precice#1466]
Split from https://github.com/precice/precice/issues/1416.

**Please describe the problem you are trying to solve.**

preCICE configuration files currently start with:

```xml
<solver-interface dimensions="..." />
```

In the context of the Geometric Multiscale feature, we want to be able to define different dimensions for each participant. Even further, we may want to define different dimensions for each coupling scheme. Defining a global dimensions size for all participants would lead to some duplication or additional input checks.

**Describe the solution you propose.**

I am not sure about a concrete solution yet.

Specifically about the dimensions, I think we could move it to each participant:

```xml
<participant name="{string}" dimensions={integer}">
```

If needed, we could then derive the largest number of dimensions automatically.

**Comment by MakisH** [comment]
> > Even further, we may want to define different dimensions for each coupling scheme.
> 
> This part, I don't understand yet. Could you elaborate, why coupling schemes may need a dimension?

Imagine that we are coupling 1D flow with a 2D solid, and the 2D solid with a 3D flow. In principle, we could use a 2D interface for the first one and a 3D interface for the latter one.

But the "coupling scheme" term was probably a bit unfortunate here.

**Comment by carme-hp** [comment]
I think would rather have the dimensionality specific to the mesh than to the participant, since for my muscle case, a participant should be able to send meshes of different dimensionality to different participants.

My (simplified) case  is the following:
I have a solid mechanics muscle solver, a solid mechanics tendon solver and a neuronal-feedback muscle solver. 
The solid mechanics solvers exchange 3D meshes between each other. However between the solid mechanics muscle solver and the neuronal-feedback muscle solver a 1D mesh is exchanged.

**Comment by MakisH** [comment]
@carme-hp could you please sketch roughly how you would imagine an ideal configuration for your case? Documenting your setup drawing here would be helpful.

Is the mesh you exchange with the neuronal-feedback participant 1D (one or more scalars) or 0D (one scalar, assuming it is an ODE solver)? Of course, the terminology here is a bit broken.

I understand it is not enough to have it in the participant level, because one of your participants is used in couplings with both a 3D and a 1D other participants. But it still remains a 3D participant that could directly benefit from the geometric multiscale mapping, having preCICE automatically convert from the 3D world to the 1D world, right?

**Comment by carme-hp** [comment]
Hi, sorry for my extremely late reply.

Here is my case setup:

![5participants(3)](https://user-images.githubusercontent.com/71499004/220345589-b4f09870-94eb-46b7-8fe9-6ea4ca1cbc80.png)

In the `precice-config.xml` that could look like a combination of the following:
- one multi-coupling scheme 
```
<coupling-scheme:multi>
  <participant name="TendonMechanics" control="yes"/>
  <participant name="Muscle1Mechanics" />
  <participant name="Muscle2Mechanics" />
  ...
</coupling-scheme:multi>
```
- two uni-coupling schemes
```
<coupling-scheme:serial-explicit>
  <participants first="Muscle1Mechanics" second="Muscle2Activation"/>
```
and 
```
<coupling-scheme:serial-explicit>
  <participants first="Muscle2Mechanics" second="Muscle1Activation"/>
```

- two bi-coupling schemes
```
<coupling-scheme:serial-explicit>
  <participants first="Muscle1Activation" second="Muscle1Mechanics"/>
```
and 
```
<coupling-scheme:serial-explicit>
  <participants first="Muscle2Activation" second="Muscle2Mechanics"/>
```

The time execution (given that explicit schemes go first in v3) should be:

![preciceworkshop23-Page-8 drawio](https://user-images.githubusercontent.com/71499004/220356055-c7a50bd0-9e24-4149-8718-b0232417a098.png)


Note that the neuronal-feedback participant mentioned in the discussion is what here I called *activation*. 

Regarding the dimensions of the participants, I agree with @MakisH  that we can say it's a 3D participant. As you see in the picture, we would have three 3D participants and two 1D participants.  To decide which dimension to assign to each participant from the picture I looked at the openDiHu components of each participant  and selected the component with more dimensions as the deciding factor:

![3participants(1)](https://user-images.githubusercontent.com/71499004/220346630-fb36085d-c413-4515-9dbe-b577924bd0e5.png)

Some points regarding the transfer of data in this setup:
- the *continuum mechanics* solvers exchange 3D data (displacement, velocity, traction) between each other. 
- each *continuum mechanics* solver sends stretch data to both *activation* solvers.
- stretch data is one or several scalars. The current biophysical models assume it to be a single scalar, yet using more than one scalar would be more realistic. For now, it can be assumed to be a single scalar, meaning 0D data. 

Finally, about
> having preCICE automatically convert from the 3D world to the 1D world, right?

I'm not sure what you meant by that, but I imagine that the conversion of data would be made inside openDiHu, as this is already done when we simulate a whole muscle with a single participant and as far as I know is already working well.

**Comment by MakisH** [comment]
Thanks a lot for the detailed description!

> * two uni-coupling schemes
> ...
> * two bi-coupling schemes

I am not sure I understand this distinction. Given that the mechanics solver and the activation solver are distinct participants, both are bi-coupling schemes, right? I am not sure I am familiar with which code solves what.

I understand that OpenDiHu solves everything in different modules. Does every module act as a stand-alone executable? Are all five boxes in your figure coupled with preCICE, or is there also any internal coupling at the moment? I am sure you explained that to me already, but I am not sure I remember anymore.

In any case, the multi-coupling scheme should be the gold standard, and it is a good argument for keeping the dimensions on the mesh level.

> Finally, about
> 
> > having preCICE automatically convert from the 3D world to the 1D world, right?
> 
> I'm not sure what you meant by that, but I imagine that the conversion of data would be made inside openDiHu, as this is already done when we simulate a whole muscle with a single participant and as far as I know is already working well.

We currently have adapters convert from 1D to 3D, but this breaks the black-box assumption of preCICE: the 1D solver needs to know that it is coupled to a 3D solver. We are trying to automatically handle this via the mapping.

**Comment by carme-hp** [comment]
> I am not sure I understand this distinction. Given that the mechanics solver and the activation solver are distinct participants, both are bi-coupling schemes, right? I am not sure I am familiar with which code solves what.

Sorry, I think the correct terms here are uni-directional coupling vs bi-directional coupling.

> I understand that OpenDiHu solves everything in different modules. Does every module act as a stand-alone executable? Are all five boxes in your figure coupled with preCICE, or is there also any internal coupling at the moment? I am sure you explained that to me already, but I am not sure I remember anymore.

Yes, that's a bit confusing. In the figure you see many OpenDiHu module, which are grouped together by color. Each color  is an executable that calls one or more OpenDiHu modules. So the 5 colors in the diagram represent the 5 participants in precice. Black arrows are handled by precice, while grey arrows correspond to OpenDiHu's internal coupling.

**Comment by MakisH** [comment]
>     * To avoid misunderstandings: When we talk about "dimension of a mesh", we do not mean the dimension of the manifold that the mesh meshes, but the dimension of the space in which the mesh is embedded. Meaning: how many coordinates do we define in `setMeshVertex`.

I understand it as "1D velocity vs 3D velocity", which can be specified on points in any of the 1D, 2D, or 3D spaces.

> ```
> <mesh name="MyMesh1" dimensions="2"> 
>   <use-data name="Temperature"/> 
> </mesh> 
> ```

This could even be added in a backwards-compatible fashion. If there is a global `dimensions` attribute (as currently), then we can inherit it in all meshes (as currently).
 
> > How do you handle direct-access? (How do I know what dimension the remote mesh has?)
> 
> I think it is not that complicated. We already have `getDimensions()`. If "by mesh", we simply add the mesh name as an argument.

This would also be backwards-compatible.

> In a first step, we could simply add checks for every mapping in the configuration that dimensions need to be identical for both meshes ("geometric multi-scale not supported for nearest-projection mapping").
> 
> Of course, this will touch many places and every integration test, but all changes should be rather simple.

This sounds like a nice opportunity for test-driven development!

cc @ezonta

**Comment by davidscn** [comment]
Discussing in person.

- since we concluded in #1559 that we need getter functions for the number of data components associated to a specific data set, we want to preserve consistency with the existing getter functions associated to the mesh. Hence, we need to adjust the current `getDimensions(...)` to

```cpp
int getMeshDimensions( precice::string_view meshName );
```

- as mentioned above, the data tag will then move into the mesh definition

```xml
<mesh name="MyMesh1" dimensions="2"> 
  <use-data name="Temperature"/> 
</mesh> 
``` 

this will enable participants to provide meshes of different dimensions.

**Comment by MakisH** [comment]
The configuration file is now built as the following tree:

- Level 1: `<precice-configuration dimension="3">`
   - Level 2: `<data>`
   - Level 2: `<mesh>`
   - Level 2: `<participant>`
   - ...

With the dimensions we get from `<precice-configuration>`, we initialize the dimension of the Level 2 elements:

https://github.com/precice/precice/blob/d3485cd614f29f82e54269028be8a737f9325954/src/precice/config/Configuration.cpp#L76-L79

where:

https://github.com/precice/precice/blob/d3485cd614f29f82e54269028be8a737f9325954/src/precice/config/Configuration.hpp#L128-L134

Assuming we now move the dimensions to the mesh, what should we do with the rest of the Level 2 objects, assuming we don't read any other dimensions?

## data

We currently have data used by meshes, but not meshes associated to data. We could create all `DataConfiguration` without setting dimensions, and then let the `MeshConfiguration` call `setDimensions` on the data it uses.

Since we can have meshes of different dimensions, the `DataConfiguration::setDimensions` would then be called once by each `MeshConfiguration`, right? In any case, it would set the maximum number of dimensions observed in a mesh.

The constructor of `Configuration` is first creating the data configuration and then passing it to the mesh configuration:

https://github.com/precice/precice/blob/d3485cd614f29f82e54269028be8a737f9325954/src/precice/config/Configuration.cpp#L54-L57


## participant

A participant can only use meshes of the same dimension.

Since it has a pointer to a mesh configuration, it should just be able to ask the first mesh about its dimension.

**Comment by MakisH** [comment]
I quickly discussed this with @uekerman, and we agreed that we need more such pen-and-paper examples before changing the code too much, also to realize how everything is connected in terms of dimensions.

In some cases where it will be complicated to access dimensions (e.g., in data or participant), this may be a good hint to remove the dimensions from that component altogether.

In the end, we want a config like this:

```xml
<precice-configuration>
  <data:vector name="Data-One" />
  <data:vector name="Data-Two" />

  <mesh name="SolverOne-Mesh" dimensions="3">
    <use-data name="Data-One" />
    <use-data name="Data-Two" />
  </mesh>

  <mesh name="SolverTwo-Mesh" dimensions="1">
    <use-data name="Data-One" />
    <use-data name="Data-Two" />
  </mesh>

  <participant name="SolverOne">
    <provide-mesh name="SolverOne-Mesh" />
    <write-data name="Data-One" mesh="SolverOne-Mesh" />
    <read-data name="Data-Two" mesh="SolverOne-Mesh" />
    <!-- geometric multiscale mapping -->
  </participant>

  ...
```

Note that the two `<use-data name="Data-One" />` lead to different objects, which could have different dimensions.

**Comment by fsimonis** [comment]
An additional possibility could be to make the data dimensions explicit and independent of the spacial dimensionality.

Currently, we restrict the user to `scalar` data and `vector`ial data. The latter follows the dimensionality of the mesh.
By making the dimensions explicit, we no longer have to infer dimensions, which simplifies the data configuration.

This also opens up the possibility for providing tensor data, which in turn could make global data more useful #202.
This would also allow things like encoding complex numbers as 2D data on a 3D mesh.

The dimensionality of the data is no longer baked into the API (`writeVectorData` is now `writeData`), so this extension would be completely transparent to the user.

Example of this:
```xml
<precice-configuration>
  <data name="Data-One" dimensions="3" /> <!-- 3d vectorial data -->
  <data name="Data-Two" dimensions="1" /> <!-- 1d scalar data -->

  <mesh name="SolverOne-Mesh" dimensions="3">
    <use-data name="Data-One" /> <!-- 3d data on a 3d mesh -->
    <use-data name="Data-Two" /> <!-- 1d data on a 3d mesh -->
  </mesh>

  <mesh name="SolverTwo-Mesh" dimensions="1">
    <use-data name="Data-One" /> <!-- 3d data on a 1d mesh -->
    <use-data name="Data-Two" /> <!-- 1d data on a 1d mesh -->
  </mesh>

  <participant name="SolverOne">
    <provide-mesh name="SolverOne-Mesh" />
    <write-data name="Data-One" mesh="SolverOne-Mesh" />
    <read-data name="Data-Two" mesh="SolverOne-Mesh" />
    <!-- geometric multiscale mapping -->
  </participant>
```

This change could result in an API change though as `getDataDimensions` doesn't need the meshname anymore:
```diff
-  int getDataDimensions(::precice::string_view meshName, ::precice::string_view dataName) const;
+  int getDataDimensions(::precice::string_view dataName) const;
```

**Comment by ezonta** [comment]
As mentioned in #1552, this would be problematic for the geometric multiscale mappings, we need to map `Data-One` between the 1D and 3D participant and the 1D participant will not return 3D data, but a "1D vector", if that makes sense. So we would need to be able to define vectorial data that is 1D for one mesh, but 3D for another.

**Comment by fsimonis** [comment]
> As mentioned in https://github.com/precice/precice/pull/1552, this would be problematic for the geometric multiscale mappings,

Not necessarily for the mapping itself. #1660 simplifies the mappings to `void map(Sample input, VectorXd output)`. The data dimensions of the input and the output would be different in your case.

Hence, this becomes a configuration issue as you would need a way to specify which data to map.

Example based on the suggestion https://github.com/precice/precice/issues/1466#issuecomment-1560882071
```xml
<precice-configuration>
  <data name="Data-One" dimensions="3" />
  <data name="Data-Two" dimensions="1" />

  <mesh name="SolverOne-Mesh" dimensions="3">
    <use-data name="Data-One" />
  </mesh>

  <mesh name="SolverTwo-Mesh" dimensions="1">
    <use-data name="Data-Two" />
  </mesh>

  <participant name="SolverOne">
    <provide-mesh name="SolverOne-Mesh" />
    <write-data name="Data-One" mesh="SolverOne-Mesh" />
    <read-data name="Data-Two" mesh="SolverOne-Mesh" />

    <receive-mesh name="SolverTwo-Mesh" from="SolverTwo" />

    <mapping:placeholder
        from="SolverTwo-Mesh" to="SolverOne-Mesh"
        from-data="Data-Two"  to-data="Data-One" />
  </participant>
```

**Comment by ezonta** [comment]
> Not necessarily for the mapping itself. #1660 simplifies the mappings to `void map(Sample input, VectorXd output)`. The data dimensions of the input and the output would be different in your case.

Ah that makes sense! That would work.

> Could we actually offload this decision to the user? We should essentially never have a "1D (scalar) pressure" and a "1D (vector) velocity" on the same coupling mesh.

I am not sure I understand what you mean by "offload this decision to the user". 🤔

**Comment by uekerman** [comment]
Quick remark:

```xml
<mapping:placeholder
        from="SolverTwo-Mesh" to="SolverOne-Mesh"
        from-data="Data-Two"  to-data="Data-One" />
```

This could lead to more compute effort as we would now have a mapping per **data pair**. Currently, we only need to compute one `computeMapping` (e.g. matrix decomposition) per **mesh pair**. A participant could have, for instance, many write data tags but only one write mapping.

**Comment by fsimonis** [comment]
@uekerman we could introduce subtags for the various data pairs to solve this. 

```xml
<mapping:placeholder
    from="SolverTwo-Mesh" to="SolverOne-Mesh">
    <map-data from="Data-Two" to="DataOne" />
</mapping:placeholder>
```

This would solve the computing issue, correct?

**Comment by uekerman** [comment]
> This would solve the computing issue, correct?

Yes, could solve the issue, but better expect a major refactoring then :see_no_evil: 

I think the whole discussion should be steered from what we want feature-wise: Which geometric multi-scale mappings do we want to tackle now, which ones in the future? Which vectorial dimension do we need then?

**Comment by MakisH** [comment]
I would not introduce mappings per data pair at the moment.
I would also prefer to keep the scalar and vector categorization for now.

If we want to open the quite big box of changing mapping between mesh pairs to mapping between data pairs (with quite some implications also in tutorials and documentation), then it would make sense to also drop the scalar/vector.

**Comment by fsimonis** [comment]
Let me summarize this.

## Data dimensionality based on mesh

* Dimensionality of vectorial data only known in the context of a mesh.
* User defines data for geometric multiscale mappings as always.
* No API-change, no configuration change.
* Geometric multiscale mappings map between data of same name (consistent behaviours to other mappings)

## Explicit data dimensionality (independent of mesh)

* Dimensionality is well-known throughout the configuration.
* User needs to define twice as many data entries for geometric multiscale mappings.
* API change `getDataDimension(meshName, dataName)` to `getDataDimension(dataName)`, simplifying tests and adapters.
* Configuration change `<data name="3D-Data" dimensions="3"/>`
* Geometric multiscale mappings map between data of different names, requiring additional `from-data` and `to-data` designations somewhere.


## Long-term considerations

* Explicit dimensionality takes considerably more effort to implement.
* Explicit dimensionality allows additional use-cases such as 2D data on 1D/3D meshes or data of higher dimensionality. The latter would also make #202 more useful.
Could be added non-breaking using an additional data config such as `<data:explicit name="4D" dimensions="4" />`. This will still require a mesh name when getting the dimensionality via the API though.
* Being able to configure and `from-data` and `to-data` opens the door for using different mappings for various data between the same mesh.

**Comment by fsimonis** [comment]
> No API-change, **but** configuration change Right?

Ah right, the dimensionality moves to the mesh. I'll change it in the summary.
