### ISSUE TITLE
Give warning when buffered requests grows too large or limit size

### ISSUE THREAD

**Issue by floli** [precice/precice#147]
Thorsten has the idea to either limit the number of buffered send request (and go into blocking send if it is too large) or put a warning if size is above a certain threshold.

**Comment by fsimonis** [comment]
We could keep track of the total memory occupied by buffered objects and use that as a limiting factor too.

I like the idea of using blocking send as a fallback. :+1:

**Comment by fsimonis** [comment]
Related to #130

**Comment by floli** [comment]
Closed, since buffered requests are disabled for the time being.
