### ISSUE TITLE
Port API from `const string` to `string_view`

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1471]
**Please describe the problem you are trying to solve.**

As we upgraded to C++17, we can now use `std::string_view` in the interface instead of `const std::string&`.
This should reduce unnecessary copies for `"hardcoded"` strings in user-code and the bindings.

**Describe the solution you propose.**
Port these functions to taking [`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view)

**Comment by fsimonis** [comment]
We decided to port the API from using mesh and data IDs to using names instead.
Meaning that the scope of this will strongly change after we implemented #1461.

**Comment by tanaytekin** [comment]
Hello,
I want to work on this issue. 
What parts of the project do you mean by interface/API? Only [this](https://github.com/precice/precice/blob/main/src/precice/SolverInterface.hpp) header?

**Comment by fsimonis** [comment]
@tanaytekin Hi there, as mentioned in the previous comment, #1461 will blow this up hugely in scope. So, this isn't a good first issue any more.
I hope you will find something else though.

**Comment by tanaytekin** [comment]
> @tanaytekin Hi there, as mentioned in the previous comment, #1461 will blow this up hugely in scope. So, this isn't a good first issue any more. I hope you will find something else though.

Ok thanks :pray:
