### ISSUE TITLE
Consistent log files naming

### ISSUE THREAD

**Issue by floli** [precice/precice#148]
Some log files we write end with txt, some with log: https://github.com/precice/precice/wiki/Output-Files
Also the naming scheme is inconsistent, we also write `A.watchpoint.txt`.

* Files should end with `.log`. That implies plain text.
* Files should contain the participant's name, here: `A`
* Should files start with a capital or lowercase letter?

Naming schemes.

* Scheme: `convergence-A.log`
* Scheme: `A-convergence.log`. So that all log files of one participant are into one place, if sorted alphabetically.
* Scheme: `pre-A-convergence.log`. An additional, static prefix, so that all files written by precice are into one place.

We are not discussing the inner file format here.

**Comment by uekerman** [comment]
`A-convergence.log` might be a bad idea as also the solver's log files might start this way. At least, this could lead to confusion. 

Before closing this issue, we need to update all tutorials, documentation, scripts, etc.

**Comment by floli** [comment]
Will rename the log files to `precice-A-convergence.log` if no objections.

**Comment by floli** [comment]
For VTK export don't we set a export directory in the config? So, I think we should leave it as it is. It's also more complex do the change for VTK exports, the code is somewhat convoluted.

**Comment by floli** [comment]
Sample output:
```
precice-FLUID-eventTimings.log
precice-FLUID-events.log
precice-FLUID-iterations.log
precice-STRUCTURE-convergence.log
precice-STRUCTURE-eventTimings.log
precice-STRUCTURE-events.log
precice-STRUCTURE-iterations.log
```
We now need to scan through the wiki can fix it.

**Comment by uekerman** [comment]
Looks good! Do you have `postProcessingInfo.txt` as well?
I can change the wiki entries, should not be too many.

**Comment by floli** [comment]
I can only find mention of `postProcessingInfo.txt` in `BaseQNPostProcesing:82`, commented out. But my search may not have find all occurrences. Are you sure it's actually written still?

**Comment by uekerman** [comment]
I updated the [wiki page](https://github.com/precice/precice/wiki/Output-Files).
Should we already update the visualization scripts? Or only after v1.3.0 it out?

**Comment by floli** [comment]
Your commit https://github.com/precice/precice/commit/3dd2a92e9c4f112756f2dcae1d81a173c3db6cc4 lacks to solver name as part of the file name.

Visualization scripts (as far as the ones I wrote) all take a `--file` argument, so no update necessary.

**Comment by uekerman** [comment]
Yes, it is not easily accessible here and I guess not that important for the `postProcessingInfo` as either way only the `second` participant would write the file.
Ready to close in my opinion.
