### ISSUE TITLE
parallelize IQN-IMVJ PP method

### ISSUE THREAD

**Issue by scheufks** [precice/precice#15]
Parallelization of the IQN-IMVJ quasi-Newton update to make the multi-vector method available to the master-slave mode. Drawback of the method: The Jacobian matrix has to be stored explicitly and the update involves a couple of very time consuming and expensive matrix-matrix multiplications. All attempts to prevent us from storing the explicit representation of the jacobian matrix failed so far or, at least do have some remarkably drawbacks concerning storage and/or computational complexity. Hence, we try to parallelize the explicit version as a first attempt. 

---
To that end, we have to parallelize the Jacobian update J_inv = J_inv_n + (W - J_inv_n*V)Z, where Z = (V^TV)^-1V^T is computed from updated QR-decomposition (already parallelized). Working branch is updatedQR branch.

###### Steps:
* divide and decompose J_inv in a suitable way (block column-wise in blocks of size n_global * n_local)
*  implement parallel version of multiplication J_inv_n*V
* implement parallel version of multiplication W_til * Z, where W_til = (W-J_inv_n*V)
  * includes: implement send/receive operation for matrix blocks
  * later: for further enhancement implement a all-reduce operation instead of looping over all slaves
* implement parallel version of matrix-vector product J_inv *R 

A .pdf  [document](https://github.com/precice/precice/files/674/Freudenstadt.pdf) is attached, containing some ideas and concepts for this issue.

**Comment by uekerman** [comment]
i had a brief look. i would try again to keep all master_slave related things out of the pp class. for the moment, as a first test this is ok, but later, all necessary decomposition information should be stored at the mesh (which can accessed via ```cplData```). 
in initialize, we can generate the ```_dimOffsets``` from that information. 
the matrix multiplication then would also go into another class (similar to updateQR).
i will prepare the necessary functions in mesh.

**Comment by uekerman** [comment]
2 further comments:
* the send/receive cycle could be done easier (and more efficient) with the async com methods. or there is there a specific thing that i don't see?
* send/receive of matrices, i don't like too much, since the matrices themselves are stored as a one-dimensional arrays. better serialize first and communicate as a double*  (or some similar operation for Eigen).
