### ISSUE TITLE
signals library vs. signals2 header / SConstruct vs. cmake

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#150]
There are some inconsistencies regarding the boost library signals, signals2 respectively.

# cmake

If we build preCICE using cmake, the library signals is required:
See [CMakeLists.txt lines 61-63](https://github.com/precice/precice/blob/7a0c8f201a0405ea516638e68003c17d312caa26/CMakeLists.txt#L61)
```
find_package(Boost 1.60.0 REQUIRED
  COMPONENTS filesystem log log_setup program_options signals system thread unit_test_framework)
add_definitions(-DBOOST_ALL_DYN_LINK -DBOOST_ASIO_ENABLE_OLD_SERVICES)
```
If we build boost from source following the [instructions from the wiki](https://github.com/precice/precice/wiki/Dependencies#boost), signals is not installed. Therefore, cmake cannot complete.

# scons

SConstruct only looks for the header `signals2.hpp`. See [SConstruct line 217](https://github.com/precice/precice/blob/7a0c8f201a0405ea516638e68003c17d312caa26/SConstruct#L217).
```
checkAdd(header = 'boost/signals2.hpp', usage = 'Boost Signals2')
```
Here, no additional library has to be installed and also, if boost was built from source following the [instructions from the wiki](https://github.com/precice/precice/wiki/Dependencies#boost), everything works.

# Progress

- [x] use signals or signals2? use new signals2
- [ ] make cmake and SConstruct consistent
- [ ] (if we use signals2) update [instructions from the wiki](https://github.com/precice/precice/wiki/Dependencies#boost)

**Comment by floli** [comment]
We use signals2, which is header only. No update to wiki necessary, searching for old signals lib will be removed from cmake.
