### ISSUE TITLE
Naming convention for CMake variables

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1516]
**Please describe the problem you are trying to solve.**
The current naming convention of our CMake variables has no clear pattern: we have underscore separated all capital variables such as `PRECICE_ENABLE_C` and `PRECICE_RELEASE_WITH_ASSERTION`, we have a mixture of underscore and CamelCase variables such as in `PRECICE_MPICommunication` and `PRECICE_PETScMapping` and no clear guideline what the variable is supposed to express: the dependency and configuration of (external) software or the purpose of the configuration in the library.  

**Describe the solution you propose.**
CMake itself uses exclusively all caps and underscore naming conventions (e.g. `CMAKE_PREFIX_PATH`). I would propose to stick to the convention as it comes with certain benefits

1. you don't need to think about capitalization (PETSc and preCICE) and the random mixture we use `PRECICE_PETSc...`
2. underscore separation is better readable
3. we stick to the CMake style and convention. Other projects I looked at (e.g. gismo, deal.II or ginkgo) stick to the same naming convention.

Open question is then still what to encode into the variable name. What I have seen quite often is just to use the external package (without any semantics, e.g. `PRECICE_WITH_MPI` or `PRECICE_WITH_PETSC`), but maybe there are other ideas. See also additional context below. 

**Describe alternatives you've considered**
Invent a new naming convention people have to lookup every time it is being used and try to convince others that this new naming convention is better.

**Additional context**
In the context of recent GPU data mapping investigations, it becomes somewhat difficult to encode the purpose of the dependency into the CMake variable name. Using a similar style as the PETSc variable name we would maybe use `PRECICE_GinkgoMapping` (assuming we decided for Ginkgo as a GPU support). However, from the user perspective it is not clear that this method comes with a certain type of parallelization concept and hardware requirements (OpenMP or GPU). Looking at the variables it might be a user question, whether preCICE can perform data mapping without these dependencies or whether these dependencies are mandatory. The actual benefit of using Ginkgo would be the (shared memory) parallelization, so wouldn't `PRECICE_GinkgoMappingParallelization` be a better name? Using the dependency only for the CMake variables might be the most straightforward solution.

**Remotely related**
Looking at the CMake-GUI, it seems a bit arbitrary, which variables we expose by default (in the non-detailed view) to the user. Example: The GUI shows all boost component paths as well as a (private?) PETSc variable called `_petsc_lib_petsc_real`, the MPI paths are not shown. In my opinion, only the user-relevant variables should be given in the default gui view.

**Comment by uekerman** [comment]
Let's also document the convention we use (or end up using) in the dev docs.

**Comment by fsimonis** [comment]
Conclusions:
* Use uppercase with underscores for everything.
* Stick to using features with prefixes `PRECICE_FEATURE` such as `PRECICE_GINKGO_MAPPING`.
* Rename C and Fortran options to `PRECICE_C_BINDINGS` and `PRECICE_FORTRAN_BINDINGS`.
