### ISSUE TITLE
Can we assume readData is also receiveData?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1527]
In #1526 I stumbled over a [configuration file](https://github.com/precice/precice/blob/2552a91041bd93aec0b2eb9d5da62287367ef7a0/tests/serial/watch-integral/WatchIntegralScaleAndNoScale.xml) for one of tests. The following part about the configuration looks odd: `DataTwo` is defined as `read-data` for `SolverTwo`, but there is no mapping or exchange defined for `DataTwo`. This looks to me like an invalid configuration that preCICE should be able to detect. From my perspective every `read-data` of a participant should appear in a corresponding `exchange` and therefore be part of the coupling scheme's receive data.

Main questions:

* Is the situation descibed above a valid use-case? I cannot imagine one.
* If we decide that the configuration above is invalid, how can we check it? What's the corrected version of the test in #1526 

Additional context:

* Assuming that every readData is part of receiveData makes the implementation simpler and removes some edge cases in #1523.

**Comment by uekerman** [comment]
There are use cases, where we want to read data that is not communicated:

- Data is communicated over a different mesh and then mapped
- Data is the result of an action, e.g. a summation action

Probably even more, but let's stop here.

**Comment by davidscn** [comment]
Not completely sure about the details here, in both cases, there needs to be a corresponding `write-data` tag somewhere, which is also somewhat the issue in the linked issue, right?

**Comment by BenjaminRodenberg** [comment]
> Not completely sure about the details here, in both cases, there needs to be a corresponding `write-data` tag somewhere, which is also somewhat the issue in the linked issue, right?

Not necessarily: See [summation action](https://github.com/precice/precice/blob/develop/tests/serial/SummationActionTwoSources.xml). But I agree: In the example above I'm missing the source where the `read-data` comes from. This source should be either a [mapping](https://github.com/precice/precice/blob/10167dd1bc613466db289581cabaebe333b2736d/tests/serial/multiple-mappings/MultipleReadToMappings.xml#L40), an [exchange tag](https://github.com/precice/precice/blob/10167dd1bc613466db289581cabaebe333b2736d/tests/serial/AitkenAcceleration.xml#L39) or an [the `target-data` of an action](https://github.com/precice/precice/blob/10167dd1bc613466db289581cabaebe333b2736d/tests/serial/SummationActionTwoSources.xml#L28).

Not sure how to check whether a source exists. Considering the different configuration files above it looks complicated.

**Comment by uekerman** [comment]
> Not sure how to check whether a source exists. Considering the different configuration files above it looks complicated.

Yes, such a global check of the config file, we currently don't do.
