### ISSUE TITLE
Link to style guide broken in CONTRIUBUTING.md

### ISSUE THREAD

**Issue by kanishkbh** [precice/precice#1533]
**Describe the problem**
In the [contributing guidelines](https://github.com/precice/precice/blob/8f09ec2db8065a93ab4f9323c4cb2e721a429089/docs/CONTRIBUTING.md),  the link to style guide (https://ipvs.informatik.uni-stuttgart.de/sgs/precice/docs/develop/conventions.html) gives a 404.

**Comment by MakisH** [comment]
It should probably point to https://precice.org/dev-docs-dev-conventions.html

**Comment by kanishkbh** [comment]
#1546

**Comment by uekerman** [comment]
closed in #1546
