### ISSUE TITLE
Raw assertion for illegal configuration of compositional coupling scheme

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1534]
**Describe your setup**

latest state of develop: 8f09ec2 (+ some unrelated changes on my own fork)

**Describe the problem**

I just tried to run `Integration/Serial/threeSolvers/ThreeSolversImplicitExplicit` with a modified configuration using two implicit coupling schemes:

```
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
  <solver-interface dimensions="2">
    ...
    <coupling-scheme:serial-implicit>
      <participants first="SolverOne" second="SolverTwo" />
      <max-time-windows value="10" />
      <time-window-size value="1.0" />
      <max-iterations value="10" />
      <min-iteration-convergence-measure min-iterations="3" data="Data1" mesh="MeshA" />
      <exchange data="Data0" mesh="MeshA" from="SolverOne" to="SolverTwo" />
      <exchange data="Data1" mesh="MeshA" from="SolverTwo" to="SolverOne" />
    </coupling-scheme:serial-implicit>

    <coupling-scheme:serial-implicit>
      <participants first="SolverOne" second="SolverThree" />
      <max-time-windows value="10" />
      <time-window-size value="1.0" />
      <max-iterations value="10" />
      <min-iteration-convergence-measure min-iterations="3" data="Data0" mesh="MeshB" />
      <exchange data="Data0" mesh="MeshB" from="SolverOne" to="SolverThree" />
      <exchange data="Data2" mesh="MeshB" from="SolverThree" to="SolverOne" />
    </coupling-scheme:serial-implicit>
  </solver-interface>
</precice-configuration>
```

Since #1462 this is illegal:

> allow at most one implicit scheme

As expected this configuration does not work, but I run into a raw assertion that is hard to understand for users. A proper preCICE check would be better here.

**Step To Reproduce**
1. Modify `tests/serial/three-solvers/ThreeSolversImplicitExplicit.xml` as suggested above
2. Run `precice/build$ mpirun -np 4 ./testprecice -t Integration/Serial/ThreeSolvers/ThreeSolversImplicitExplicit --log_level=all`

We observe that the following assertion is triggered:

```
ASSERTION FAILED
Location:   void precice::cplscheme::CompositionalCouplingScheme::addCouplingScheme(const PtrCouplingScheme&)
File:      precice/src/cplscheme/CompositionalCouplingScheme.cpp:38
Expression: _implicitScheme == nullptr
Rank:       0
Arguments:  none
```

**Expected behaviour**

A error message that is more understandable for a user.

**Comment by fsimonis** [comment]
This should be covered by this check:

https://github.com/precice/precice/blob/8f09ec2db8065a93ab4f9323c4cb2e721a429089/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L382-L386

Old implicit | New implicit | OK?
--- | --- | ---
Y | Y | N
Y | N | Y
N | N | Y
N | Y | Y

`Bad = !(old.implicit and new.implicit) = !old.implicit or !new.implicit `

**Comment by BenjaminRodenberg** [comment]
What about this branch:

https://github.com/precice/precice/blob/8f09ec2db8065a93ab4f9323c4cb2e721a429089/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L388-L395

Looks to me like we also might need to check here?
