### ISSUE TITLE
Configuration: check for multiple coupling scheme between same participants

### ISSUE THREAD

**Issue by MakisH** [precice/precice#155]
I noticed that, when (accidentally) having both an explicit and an implicit coupling scheme node, this will lead to weird problems during `advance()`. Moreover, there is no relevant output during `advance()` in the default log level, giving the impression that the solver itself hanged.

It would be nice to either:
1. have a check and don't continue if multiple coupling scheme nodes are available,
2. allow for multiple coupling scheme nodes and provide an additional "switch" node to choose among them. Since this would be needed only for more than two nodes, this would be backwards-compatible. This way, we could also distribute files with all the parameters ready-to-use, without having to use comments.

**Comment by MakisH** [comment]
Oh, indeed, this is the way we do multi-coupling.

As for the second suggestion, I have something like this in mind:

```xml
<coupling-scheme type="serial-implicit" />

<coupling-scheme:serial-explicit>
   ...
</coupling-scheme:serial-explicit>

<coupling-scheme:serial-implicit>
   ...
</coupling-scheme:serial-implicit>

<coupling-scheme:parallel-explicit>
   ...
</coupling-scheme:parallel-explicit>

<coupling-scheme:parallel-implicit>
   ...
</coupling-scheme:parallel-implicit>
```

Combining it with merging the configurations of the serial (non-MPI) and parallel (MPI), we could then have one configuarion file, where we could just change 1-2 "switches" to experiment with different options.

This would just be a usability improvement, but probably a small one. It offers nothing new that cannot be done with the current approach with comments.

But indeed, the issue here is just some error message missing.

**Comment by floli** [comment]
> Concerning your second suggestion, I am not too sure. Sounds a bit over-engineered to me (only useful for rare cases) and not too easy to understand. Do you disagree?

I agree. We use a declarative configuration language and we should omit putting too much logic into the configuration file.

**Comment by MakisH** [comment]
After discussion, we conclude to simply implement an error message when multiple coupling schemes are defined for the same participants.

**Comment by MakisH** [comment]
We need to try a minimal working example and then we will try to fix it if it is easy to fix. Otherwise, we will close it.

**Comment by BenjaminRueth** [comment]
> We need to try a minimal working example and then we will try to fix it if it is easy to fix. Otherwise, we will close it.

First proposal for a test: Take a solverdummy, in `precice-config.xml` duplicate coupling scheme and modify it a bit. We will see what happens then.

**Comment by MakisH** [comment]
In https://github.com/precice/precice/pull/345, @fsimonis found that this is actually quite complex, without offering much benefit.
