### ISSUE TITLE
Refactor controller in multi coupling-scheme config

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1560]
**Please describe the problem you are trying to solve.**

When configuring a multi coupling-scheme, there must be exactly one participant marked as the controller.
```xml
    <coupling-scheme:multi>
      <participant name="SolverA" control="yes" />
      <participant name="SolverB" />
      <participant name="SolverC" />
```

**Describe the solution you propose.**

Move the controller to a separate tag and remove the `control` attribute from the participant tag.
This simplifies the participant tags and clarifies who the controller is.

```xml
    <coupling-scheme:multi>
      <controller name="SolverA" />
      <participant name="SolverB" />
      <participant name="SolverC" />
```

**Describe alternatives you've considered**

None

**Additional context**

This could clarify the documentation further. It is now clear that there is one controller and further participants.

**Comment by BenjaminRodenberg** [comment]
Similar box we may or may not want to open:

https://github.com/precice/precice/blob/accb6aed5ada36ff718915e21819327cb2a04c8b/tests/serial/SummationActionTwoSources.xml#L65

For `BiCouplingSchemes` the second participant has basically the same role like the controller. Additionally: For parallel coupling schemes we are also talking about first and second. Does this even make sense? I think we could resolve many of these inconsistencies by using the approach followed by the multi-coupling-scheme. (btw: with https://github.com/precice/precice/pull/1432 I once went a bit too far in this direction, less thinking about the user perspective and more about the implementation)

**Comment by fsimonis** [comment]
Conclusion:
- no benefit
