### ISSUE TITLE
The initial and final exports contain 0 data

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1563]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 18.04_
preCICE Version: 2.5.0 + develop

**Describe the problem**

When using exports, the `inital` and `final` exports do contain 0 data.

For the `initial` export, this is the case even if data is initialized by the solver. This will was partially solved by #1350 as now the data is written first. Written data is still reset.

For the `final` export, written data is reset and thus it will contain 0 data.

**Expected behaviour**
Export data before it is reset.

**Additional context**

#1157 closes this issue.

**Comment by uekerman** [comment]
Let's also consider whether removing the final vtk export completely. I don't see a real use case and it often confuses more than it helps.
