### ISSUE TITLE
Silent crash for mismatching opening and endig tags

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1564]
Operating system (e.g. Linux distribution and version): _Ubuntu 18.04_
preCICE Version: 1965ceb

**Describe the problem**
In our RBF mappings, we have now closing and ending tags due to the basis-function being a subtag (related to #1417). However, this leads to the situation that  we have multiple 'legal' opening tags (e.g. `rbf-global-iterative` ...) and multiple 'legal' closing tags. 
Mixing the opening and the closing tag leads to a silent crash of preCICE without any useful information (even with trace log enabled).

**Step To Reproduce**
Use a config with mismatching ending and closing tags for the mapping. Example:
```xml
      <mapping:rbf
        direction="write"
        from="Fluid-Mesh"
        to="Solid-Mesh"
        constraint="conservative" >
         <basis-function:compact-polynomial-c0 support-radius="1" />
      </mapping:rbf-global-direct>
```

**Expected behaviour**
A clear error message.

**Comment by uekerman** [comment]
In principle, this is rather independent of preCICE, right? Could we just do sweep over the complete xml file before the actual configuration to check whether opening and closing tags match? Maybe `libxml2` has such a functionality already?

**Comment by fsimonis** [comment]
We used to forward an error in such a case. Not sure why this isn't the case anymore.
I'll investigate, given that I am currently working on the config parser anyhow.
