### ISSUE TITLE
Request to improve error message if method = "first-participant" is used for with parallel coupling schemes

### ISSUE THREAD

**Issue by kandekac** [precice/precice#1569]
**Please describe the problem you are trying to solve.**
This is the config file I used with first-participant method and it gives following error
```xml
<coupling-scheme:parallel-implicit>
      <participants first="Plasticity" second="Corrosion"/>
      <time-window-size method="first-participant"/>
      <max-time value="1"/>
      <max-iterations value="30" />
      <exchange data="K_m" mesh="Plasticity-Mesh" from="Plasticity" to="Corrosion" />
      <relative-convergence-measure limit="1.0e-3" data="K_m" mesh="Plasticity-Mesh" />
</coupling-scheme:parallel-implicit>
```
Error from preCICE
`---[precice] ERROR:  Invalid value "first-participant" of attribute "method": value must be "fixed"
`
**Describe the solution you propose.**
This would be very helpful If this limitation is clearly mentioned  in the error
`---[precice] ERROR:  Invalid value "first-participant" of attribute "method": value must be "fixed or use a serial coupling scheme if you want to use method="first-participant"`

**Comment by fsimonis** [comment]
It's rather silly that we have an attribute with a single valid option here. I'll remove that while working on the config parser.

**Comment by BenjaminRodenberg** [comment]
> It's rather silly that we have an attribute with a single valid option here. I'll remove that while working on the config parser.

Not sure that I understand what you mean. We have `method="fixed"` (default) and `method="first-participant"`. There are certainly a few questionable design decisions here, but is this really related to this issue?

**Comment by BenjaminRodenberg** [comment]
> Parallel coupling-schemes only allow `method="fixed" `.

Ah ok. So you would suggest to completely remove the `method` attribute from parallel coupling schemes? Would make things less messy, true.

Not sure how it would look on the user side, if a user tries to use `method="first-participant"` with a parallel coupling scheme anyways. I guess we should still catch this case for parallel coupling schemes and raise a special error, if the attribute `method` is provided to a parallel coupling scheme? I think something that points the user to the fact that the `method` attribute is only available for serial coupling schemes is more helpful than `preCICE:ERROR:  Tag <time-window-size> contains an unknown attribute named "method".`

**Comment by fsimonis** [comment]
@BenjaminRodenberg Do you think this is good enough?

```
ERROR: The tag <time-window-size> in the configuration contains the attribute "method". This feature is only available for serial coupling schemes.
```
