### ISSUE TITLE
Extract serial/parallel from the coupling-scheme tag

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1571]
**Please describe the problem you are trying to solve.**

@BenjaminRodenberg and I lately discussed that parallel and serial coupling schemes have identical configuration (apart from `<time-window-size method="first-participant"/>`) and are fundamentally very similar, yet separate tags represent them.
For performance reasons, a parallel coupling scheme is generally preferred, yet the word `parallel` seems to trigger a permissive amount of unease in many users. Serial coupling schemes are often the default and remain unchanged.

**Describe the solution you propose.**
Remove `serial` and `parallel` from the coupling scheme configuration.
Add an attribute (or subtag) to control this part and default to the parallel version.
This could enable use the term `staggered`, which according to @BenjaminRodenberg is more common in the field.

| configuration | coupling | current | proposed |
--- | --- | --- | --- 
parallel | explicit | `<coupling-scheme:parallel-explicit>` | `<coupling-scheme:explicit>`
parallel | implicit | `<coupling-scheme:parallel-implicit>` | `<coupling-scheme:implicit>`
serial | explicit | `<coupling-scheme:serial-explicit>` | `<coupling-scheme:explicit staggered="true">`
serial | implicit | `<coupling-scheme:serial-implicit>` | `<coupling-scheme:implicit staggered="true">`

**Describe alternatives you've considered**

An alternative could be to move the attribute to a separate tag.
```xml
<coupling-scheme:explicit>
  <configuration staggered="true" />
  <participants first="A" second="B"/>
</coupling-scheme:explicit>
```

**Additional context**
Triggered by #1560

**Comment by uekerman** [comment]
Sorry to be the bad cop here, but I don't really see the problem yet :grin:  

> For performance reasons, a parallel coupling scheme is generally preferred

I would advice against such general conclusions. Highly problem dependent.

> This could enable use the term staggered, which according to @BenjaminRodenberg is more common in the field.

Very dangerous. "staggered" was originally used as a synonym for "partitioned". I always try to avoid this term completely as everybody understands it differently. IMO "serial" and "parallel" are much clearer terms.

**Comment by fsimonis** [comment]
Good to know. In the meantime, I found some additional differences between them.
