### ISSUE TITLE
Implement comparision operators for Mesh, Edge, Vertex, ...

### ISSUE THREAD

**Issue by floli** [precice/precice#158]
It would be nice to be able to directly compare objects, e.g. `mesh1 == mesh2` or `edge1 == edge2` if all coordinates are identical.

**Comment by S0mmerD** [comment]
> Isn't comparing the identifier sufficient to deduce equality?
Vertex has two identifiers. The first one is the mesh-local `_id`. For one mesh two vertices should not have the same `_id`, but for multiple meshes this does not suffice. There is actually not really any gain from using `_id` for comparison:
- Different Mesh: `id` is meaningless
- Same Mesh `id` *can* prove inequality but first one has to make sure the two vertices belong to the same mesh. Note that this can be done with `PropertyContainer` but involves a map lookup, at which point comparing two `Eigen::Vector3d`s would be faster. 

I think that one would very often like to compare Vertices from different meshes, so i would say that:
`
Vertex v1(Eigen::Vector3d::Constant(1.0), 0);
Vertex v2(Eigen::Vector3d::Constant(1.0), 1);
Vertex v3(Eigen::Vector3d::Zero(), 0);
BOOST_TEST(v1 == v2);
BOOST_TEST(v2 != v3);
BOOST_TEST(v1 != v3);
`
And that `mesh1 == mesh2` if and only if all vertices are equal with respect to the upper relation. Meshes are noncopyable so a first check would compare adresses of them, thus making references to the same mesh cheaply comparable, but for distinct meshes there is no shortcut as far as i can see (unless one finds a way to use boost.geometry in some way, but so far a mesh is just a mere `vector<PropertyContainer*>`).

**Comment by uekerman** [comment]
* You only want to use this in tests, right? Or is there any other situation? Then, looking at the IDs makes no sense, I think. 
* `_id` can be the same for different meshes, but also for different ranks. `_globalIndex` can be the same for different meshes, but is unique among ranks.

**Comment by floli** [comment]
Right now I see the application only in tests, let's see where else it would become useful.

I would go with
* Vertices are equal, if their coordinates are equal (s.t. they describe the same point)
* Edges are equal, if both vertices are equal.
* Triangles are equal, if all three edges are equal.
* and so forth...

@fsimonis You suggested to also overload the comparison operator? How should that be defined?

**Comment by fsimonis** [comment]
@SOmmerD

> Meshes are noncopyable so a first check would compare adresses of them, thus making references to the same mesh cheaply comparable, [...]

At the moment, every "implementation" of `PropertyContainer` is `noncopyable`.
So, if we model `operator==` to check for identity, then comparing addresses is sufficient.

> I think that one would very often like to compare Vertices from different meshes, so i would say that: [...]

So you think that we should compare based on coordinates by default.

---

@uekerman

> _id can be the same for different meshes, but also for different ranks. _globalIndex can be the same for different meshes, but is unique among ranks.

The `_gobalIndex` is set externally, so it provide something like an _optional extended identification_. As @S0mmerD wrote, in the end we would still have to identify the owning mesh in order to be absolutely sure.
Checking for identity using identifiers seems a bit clumsy.

---


@floli
> Right now I see the application only in tests, [...]

@uekerman
> You only want to use this in tests, right? 

We should be careful with defining the default equality operator as it should be available library-wide. So shall we:
* define default equality based on the value (i.e. following the rule: _in doubt: do as the ints do_), or
* define default equality based on the identity (address/meshid/globalid/id), or
* provide no default equality, making clear that there is no obvious implementation.

In the end we can (and IMHO should) define various equality predicates and use them when necessary. Abstract example compiled from the previous comments:
```cpp
// the address method
struct memAddrEquals { bool operator()(A, B); };

// the method from floli's comment
struct geometricEquals { bool operator()(A, B); };

// precondition: A, B are elements of the same mesh and on the same rank
struct localIDEquals { bool operator()(A, B); };

// precondition: A, B are elements of the same mesh
struct globalIDEquals { bool operator()(A, B); };

// precondition: A, B are elements of possibly different meshes
// Additionally looks up the meshid, expensive
struct globalMeshawareIDEquals { bool operator()(A, B); };
```
We can then simply implement `operator==` in terms of one of these explicit predicates.

---

@floli After writing the above, I think that defining `operator<` for the primitives is nuts.
My motivation was the possibility to use `std::map`. A sane option is provide a `std::hash` specialization, which would allow us to use `std::unordered_map`.

**Comment by sommerd** [comment]
Please remove me from this thread

**Comment by floli** [comment]
I had the chance to talk about that with @uekerman and @atotoun in person.

Let's use the geometric equality. It's just what we need right now. Also, don't rely on `_id` being the same means that the vertices are equal, just use `math::equals` on `v.getCoords()`. Vertices are at most 3-dimensional, so that comparison shouldn't be too costly.

What is your take on `operator==` as a member- or free-function?

**Comment by S0mmerD** [comment]
> What is your take on operator== as a member- or free-function?

Defining some operator as a (possibly friend) free-function is usually done when one of the operants is non-class type. Another use case would be if they are rather unrelated classes and you don't want to clutter the class definitions with the other class. Neither of these is the case here. 
Defining some operator as a member function has the advantage of benefiting from virtual function dispatch (C++ does not support multiple dispatch though), but this is not important here either. 

**I would prefer member functions simply for the sake of readability**

> Vertices are at most 3-dimensional, so that comparison shouldn't be too costly.

Comparing vertices is very cheap indeed. Probably one vectorized instruction.

> just use math::equals on v.getCoords()

`Eigen::DenseBase<Derived>::isApprox(const DenseBase<OtherDerived>& other, const RealScalar& precision)`

**Comment by floli** [comment]
>     just use math::equals on v.getCoords()
> 
> Eigen::DenseBase<Derived>::isApprox(const DenseBase<OtherDerived>& other, const RealScalar& precision)

Yes, that's what `math::equals` use. Please use it, not the Eigen function directly. Unless you have a reason to do otherwise.

> Are Edges directed? Does the order of vertices in a Quad/Triangle play a role?

That's a good question. The normal direction on Edges and Triangles is simply set, not computed from the coordinates. `Mesh:: computeState` however computes the normal if `computeNormal` is set.

Should the normal be part of the comparison?

**Comment by uekerman** [comment]
Edges are not directed. The order of vertices in a Triangle plays no role. Not sure about Quads though. The normal does not depend on the order of the vertices, but is explicitly set. We should also compare the normal if it is set.

**Comment by fsimonis** [comment]
> Let's use the geometric equality. It's just what we need right now. Also, don't rely on _id being the same means that the vertices are equal, just use math::equals on v.getCoords(). Vertices are at most 3-dimensional, so that comparison shouldn't be too costly.

@floli Fine with me; this choice needs to be clearly documented though (e.g. Doxygen @ warning/note).

> What is your take on operator== as a member- or free-function?

@floli @S0mmerD 
Clear case for me and [many other seasoned programmers](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c4-make-a-function-a-member-only-if-it-needs-direct-access-to-the-representation-of-a-class) incl. Meyers (Effective C++ Item 23):
_Only make a function a member if it needs access to the internals._
These functions can be implemented using the public interface only. Allowing implicit conversions is not a concern here, so there is no reason to put them into the class.

> Defining some operator as a (possibly friend) free-function is usually done when one of the operants is non-class type.

@S0mmerD What you mean is the case where you want to allow implicit conversions for one of the operands, common e.g. in DSLs.

> Edges are not directed. The order of vertices in a Triangle plays no role. Not sure about Quads though.

@S0mmerD 
So you can check the permutation of the vertex coordinates. I'll finish PR #161, then you can use the direct access for Triangle and Quad. Quads are still unimplemented, but you could copy-paste the operator from Triangle to have at least some functionality in place.

**Comment by S0mmerD** [comment]
> These functions can be implemented using the public interface only. Allowing implicit conversions is not a concern here, so there is no reason to put them into the class.

True. I will update PR #165 to reflect this.
> @S0mmerD What you mean is the case where you want to allow implicit conversions for one of the operands, common e.g. in DSLs.

Yes, this is another reason, but neither important in our case.
> So you can check the permutation of the vertex coordinates. I'll finish PR #161, then you can use the direct access for Triangle and Quad. Quads are still unimplemented, but you could copy-paste the operator from Triangle to have at least some functionality in place.

This is exactly what i have done. Once you finished PR #161 i will update my pull request to use the triangle iterator. Right now it's done by comparing edges, as these are what defines a Triangle. I experimented with comparing Triangles/Quads by vertices but the code became rather ugly. (You have to do something like
```
array<Vertex*, 3> vertices1;
generate(vertices1.begin(), vertices1.end(), [triangle1, n=0]()mutable{return &triangle1.vertex(i++);}
array<Vertex*, 3> vertices2;
//...
return std::is_permutation(vertices1.begin(), vertices1.end(), vertices2.begin(), 
    [](Vertex* a, Vertex* b){return *a == *b;});
```

**Comment by S0mmerD** [comment]
@fsimonis 
> These functions can be implemented using the public interface only.

Actually i just noticed that it is not that easy to implement these functions using the public interface only. For instance consider `Edge`: Two edges are the same if their vertices are the same, `std::is_permutation` would be a perfect fit. However this function needs pointers (like all standard library algorithms), which none of the geometric primitives specifies. Of course i could just go `&edge.vertex(0)` but that would be really brittle and dangerous, relying on the undocumented guarantee that the vertices are stored contigously. Another way would be to copy all the vertices into an array beforehand, but this would again be overly complex.
