### ISSUE TITLE
Reading from a mesh via direct access does not work

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1582]
**Describe the problem**

The following setup does not work:

```
<participant name="SolverTwo">
  <receive-mesh name="MeshOne" from="SolverOne" safety-factor="0" direct-access="true" />
  <read-data name="Velocities" mesh="MeshOne" />
  <write-data name="Forces" mesh="MeshOne" />
</participant>
```

I always read `0` for `Velocity` with `SolverTwo`.

I guess this is currently a blind spot, because all tests in `tests/parallel/direct-mesh-access` only use direct access for writing data to a mesh.

**Step To Reproduce**

I added a test in https://github.com/BenjaminRodenberg/precice/commit/16614c52064221fafd7d49d8b4e08ca22582a53b

**Expected behaviour**

From my understanding direct mesh access should support reading and writing data from / to the mesh that provided direct access.

**Comment by davidscn** [comment]
Just tested this thoroughly: using the direct access and reading data works perfectly fine. There is a bug in the linked commit:

```diff
-interface.writeBlockScalarData(writeDataID, providedMeshID, ids.data(), writeData.data());
+interface.writeBlockScalarData(writeDataID, ids.size(), ids.data(), writeData.data());
```

causing the behavior you observe. Also the merge in #1584 contains this bug. Initializing data works fine as well, using this feature.
