### ISSUE TITLE
Non-zero initial data not possible with direct access

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1583]
**Describe the problem**

To provide initial data, we have to call a write data function before calling `initialize()`. If we use direct access, we can only write to a mesh that we access via direct access *after* `initialize`. Therefore, initializing data via direct access is not possible. 

**Step To Reproduce**

I added a test to illustrate the problem via https://github.com/BenjaminRodenberg/precice/commit/1a50d473454d7796ae52b267c4dc1387529353db

**Expected behaviour**

See test mentioned above.

**Additional context**

This is basically a consequence of #1350.

**Comment by davidscn** [comment]
Yes, that's not possible anymore by the way we establish the communication and write data. I would add a `won't fix` label as I don't see any chance to fox this issue in the current setting. Also, I would assume that this is rather a corner case for users (how to generate the 'write data' without the topology information, which we can only query after we called 'initialize()'.

**Comment by BenjaminRodenberg** [comment]
Is this documented somewhere? I totally support making this a `wontfix`, but we should also make sure our users know about this restriction.
