### ISSUE TITLE
Assertion shown to user terminal output

### ISSUE THREAD

**Issue by saumiJ** [precice/precice#16]
@uekerman 

Running elastic1dtube example with PostProc: `IQN-ILS` fails. Assertion shown to user's output as:

`too many iterations in orthogonalize, termination failed
assertion in file src/cplscheme/impl/QRFactorization.cpp, line 228 failed: u(_cols-1) == rho
parameter u.tail(1): 0.00000000000000000000e+00
parameter rho: 9.98982626785207548416e-06
StructureSolver: src/cplscheme/impl/QRFactorization.cpp:228: void precice::cplscheme::impl::QRFactorization::insertColumn(int, precice::cplscheme::impl::QRFactorization::EigenVector&): Assertion 'false' failed.`

**Comment by floli** [comment]
Welcome Saumitra!

@scheufks may also be interested in that.

**Comment by SaumitraVinayJoshi** [comment]
Hi @floli!

Yes, Benjamin suggested I only tag him for now as I'm new here and Klaudius would be a bit confused seeing an issue from me.

**Comment by uekerman** [comment]
i already talked with klaudius. it's definitely a bug in the way that we need a meaningful error message here, but more probably there is still sth wrong with the adapter.
@SaumitraVinayJoshi did you already ask for a merge request for the 1D example? then, i could have a look again

**Comment by uekerman** [comment]
that's the same that @floli had already a fight with last week. 
in the 1D elastic tube example, we only define a 1D mesh, we should however use  2D mesh. preCICE cannot handle 1D meshes. also, in the precice-config the dimension is set to 2.
@SaumitraVinayJoshi can you just please adjust the 2 adapters by setting the y coordinate always to 0. (if you have doubts just have a brief look at the src code of setMeshVertices)
