### ISSUE TITLE
Warning message for non-matching interface geometries 

### ISSUE THREAD

**Issue by uekerman** [precice/precice#160]
As pointed out by @msuaeronautics13, it would be helpful to get a warning if two interface meshes describe obviously different geometries, such as a wrong z-plane, etc. 

Currently, with the right decomposition, we have the check:
https://github.com/precice/precice/blob/017e2f3c93bd62280f8031bd9c2ca4c147e57861/src/partition/ReceivedPartition.cpp#L90-L95

But this only fails with the right decomposition. Would be good to have a more general solution.

**Comment by MakisH** [comment]
After discussion in the coding days:
* In the long run, we need something good here.
* Let's find a neat, maintainable way to do this (it should also work in parallel etc).
* If we need a dependency, let's prefer boost.geometry over vtk.

**Comment by fsimonis** [comment]
For the record:
We could add a `max-distance` threshold to NN and NP mappings. The mapping could throw an error if the distance between the associated elements of two meshes surpass it.
The distance to the projected element is available, so this should be easy to implement.

**Comment by uekerman** [comment]
I like the `max-distance` threshold idea! We should make it a warning, however, as it is quite impossible to define a good and robust value. My gut feeling suggests sth like 0.01.
@KyleDavisSA What do you think?

**Comment by KyleDavisSA** [comment]
Is the 0.01 value a relative threshold for a mesh? I think for large meshes, an absolute threshold might give a warning even if the geometries do match up. How could this distinguish between cases where the mesh density differs drastically or where the geometries are actually different?

**Comment by uekerman** [comment]
It's an absolute threshold, a relative one would again be complicated to compute. 

> How could this distinguish between cases where the mesh density differs drastically or where the geometries are actually different?

Is does not. That's the main problem. So, we should choose the value in a very conservative way.

**Comment by fsimonis** [comment]
My idea is to provide a configuration option to the user as we simply
cannot make assumptions on the mesh. Just imagine how meshes could look
like in astrophysics.

Alternative to this, we could log the max distance for an entire mesh to
give the user a hint.

**Comment by uekerman** [comment]
I am not sure whether making this value configurable is a good option. In the end, we want to make it easier for the user. It would just be another parameter that is hard to explain. 

I think it is possible to choose a good and robust value. Currently, we don't have users from astrophysics and I also guess that they would use a different unit system :)

In the worst case, the user gets a warning he should ignore. We need to choose a proper warning message and give more information about this in the wiki. And explain how to switch off warnings in the logging configuration. 

To make it a relative measure, we could actually use the size of the bounding box around the complete mesh. And we also know the number of vertices, so we could do an approximate mesh width.

**Comment by fsimonis** [comment]
> I am not sure whether making this value configurable is a good option. In the end, we want to make it easier for the user. It would just be another parameter that is hard to explain.
>
> I think it is possible to choose a good and robust value. Currently, we don't have users from astrophysics and I also guess that they would use a different unit system :)

Our coordinate system is unit-less and the application unknown, thus we cannot make any assumptions here. We thrive for a general and sustainable solution and hard-coding a threshold will lead to necessary bug reports and confused users in the long run.
Astrophysics is an extreme example and a potential use-case.
 
> In the worst case, the user gets a warning he should ignore. We need to choose a proper warning message and give more information about this in the wiki. And explain how to switch off warnings in the logging configuration.
> 
> To make it a relative measure, we could actually use the size of the bounding box around the complete mesh. And we also know the number of vertices, so we could do an approximate mesh width.

Instead of throwing a potentially meaningless warning at the user, it might be sufficient to log some statistical analysis on the distances to the projections. `min, max` are trivial to compute. `median, arithmetic average, variance` would be interesting but requires storing all distances, which should be fine.
Maybe this is sufficient from user perspective?

Given the above stats, we could also generate a `Your mapping is all over the place and probably shouldn't be`-warning.

**Comment by uekerman** [comment]
I think logging is definitely a good idea. Could even be part of the INFO output. We already do:

https://github.com/precice/precice/blob/develop/src/precice/impl/SolverInterfaceImpl.cpp#L1590-L1594

Extending this by minimal logging information could do the job. 

"The max/avg/min distance is 0.01, 0.005, 0.0" or sth similar.

We don't need more complicated output. Then, we could still do a WARNING instead of an INFO for very suspicious values.
