### ISSUE TITLE
Configurable wait in finalize

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1600]
**Please describe the problem you are trying to solve.**

The participants wait for each other in `finalize`.
This was introduced to prevent job systems such as SLURM from killing all participants as soon as the first one exits.
This is unnecessary in many cases and delays progress of the solver (such as cleanup or exports) that happen after preCICE is finalized.

**Describe the solution you propose.**
Add a configuration option to enable/disable this behaviour.

Example:
```xml
<precice-configuration sync-mode="0" wait-in-finalize="1">
</precice-configuration>
``` 

**Describe alternatives you've considered**
_leave as is_

**Additional context**

**Comment by uekerman** [comment]
Sounds good. What would be the default setting then? "1" or "0".
"1" would be more backwards compatible, but maybe not what most users need.

**Comment by fsimonis** [comment]
We could try to disable this by default and see if anything breaks. We can easily change this before we release.
