### ISSUE TITLE
preCICE C++ API requires C++ 17 in user codes

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1605]
**Describe the problem**

Due to our changes in #1471, we use now a `std::string_view` in order to pass string arguments to preCICE. However, now that we use `C++17` features explicitly in the API, we essentially force all adapter compiler to use and be compatible with a `-std=c++17`.

**Expected behaviour**
Either document this change or provide a backwards compatible version of `string_view`. Expecting C++17 support from the compiler is probably not overly problematic, but expecting all adapter/user-code to be compiled with C++17 might be too restrictive.

**Additional context**
I discovered this during the OpenFOAM-adapter porting: OpenFOAM (precompiled binary) was built with C++14. Calling the OpenFOAM own `wmake` compiler wrapper will automatically invoke `-std=c++14`, which leads to errors in the `SolverInterface`

```bash
precice/SolverInterface.hpp:55:23: error: expected ‘)’ before ‘participantName’
   55 |       std::string_view participantName,
      |                       ^~~~~~~~~~~~~~~~
      |                       )
```

**Comment by IshaanDesai** [comment]
Not only adapters, but also some of the [bindings](https://github.com/precice/python-bindings/blob/develop/setup.py#L67).

**Comment by fsimonis** [comment]
A danger of `using string_view = precice::span` for compatibility reasons is, that we will never make the shift to STL `std::string_view` and `std::span`.

With the release of Ubuntu 24.04 LTS, our baseline shifts to Ubuntu 22.04 LTS, which already ships with a C++20 `span` implementation.
So, it is realistic that we could require C++20 internally and by user-code (due to `std::span`) in April 2024.

**Comment by davidscn** [comment]
> So, it is realistic that we could require C++20 internally and by user-code (due to std::span) in April 2024.

The main question here remains: Do we want to enforce constraints on the user build-system or not? Although _our_ baseline supports all these STL features, it doesn't imply that our user codes go with the same strategy. Example: OpenFOAM build its packages as of now using c++14, which is -speaking in our dependency structure- deprecated.

**Comment by MakisH** [comment]
>     * In the worst case, we can simply backport the API from `std::string_view` to `const std::string&`, which will come with a performance / convenience impact. An alternative to `std::string_view` is to use the span `using string_view = precice::span<const char>` after [Using spans instead of raw pointers in the API #1577](https://github.com/precice/precice/issues/1577) (in case we conclude on using this).

Can't we have two versions? I would not make quick conclusions on the performance and the convenience. A few strings (even in every API call now) sound tiny compared to everything else going on in a coupled simulation. With `const std::string&`, this would mean 

What is the inconvenience with `const std::string&`?

While of course `std::string_view` would be great in a codebase we fully control, I see the compatibility issues as too complicated to just make C++17 obligatory.

**Comment by MakisH** [comment]
> But this was for std::string vs ids, right? Not for std::string vs std::string_view (which would probably be somewhere in between, probably closer to the ids).
> 
> Referenced the wrong comment (but it was close) [#1461 (comment)](https://github.com/precice/precice/issues/1461#issuecomment-1318414711)

I understand that still, the performance argument is not very strong. I do understand that `std::string_view` is better for string literals and it does seem as a better type for the API. 

Independently of our decision on the specific API detail, the main issue remains: what C++ standards is preCICE compatible with in user codes, and how to support older standards? Given that C++ has a strong tradition in backwards compatibility, and user codes are often years behind in standard versions, I think we need to stick with compatibility.

Maybe we could even have "legacy C++ bindings". But defining (and updating the definition of) "legacy" would be an issue.


> > This check would happen at compile-time of preCICE. How could it solve the OpenFOAM issue?
> 
> We would need to put it into the `SolverInterface.hpp`. Then the check happens at adapter-compile time. We would need to think about a proper way to support both in the library, of course, but this could be easily doable by always building both versions, for example.

Good point with the `.hpp`, but we would indeed need to ensure that both versions are anyway available. I think overloading would already do the trick.

**Comment by davidscn** [comment]
> Good point with the .hpp, but we would indeed need to ensure that both versions are anyway available. I think overloading would already do the trick.

I could imagine that overloading will either lead to ambiguity issues or will always boil down to the `std::string` version, as that's the data type passed most of the time to these kind of functions.

**Comment by fsimonis** [comment]
**Some comments on the discussion**

> I understand that still, the performance argument is not very strong. I do understand that std::string_view is better for string literals and it does seem as a better type for the API.

The performance argument is extremely weak for block versions.
The point of using string_views is to clearly encode the indent of the argument into the API. So: "I need to read some character sequence". The direct consequence is that we don't require the caller to (possibly implicitly) create a `std::string` before calling the API.

If the user calls singular versions of read/write data for numerous vertices, then this could become expensive.

>
>We could in principle declare something like a precice::string and then differentiate according to the applied standard library:
>
>```cpp
>#if __cplusplus >= 201703L
>   using precice::string = std::string_view
>#else
>   using precice::string = std::string
>#endif
>```

This is fundamentally a switch on the calling adapter-side of the API. As both versions need to be present, this requires us to implement both versions in the SolverInterface.cpp.

Also, `__cplusplus` is not consistently implemented in the Visual Studio Compiler. We could need to use `_MSVC_LANG` for the right value, making this a bit cumbersome.

> I was just thinking of function overloading, with the const std::string& version calling the std::string_view version.

Function overloading has 3 major downsides:
1. this would close to double the size of our API as most functions either take a mesh or data name as input
2. we need to implement/document/maintain all overloads in the API
3. the API then still needs both versions to be available. The `string_view` implementation could be dynamically disabled though.



**My take-away at this point of the discussion**
* It is a nuisance for users to move to `C++17` in the calling code (for `std::string_view`).
* The same will happen again when we try to move the API to `C++20` (for `std::span`).

My proposition to move on (falls back on what @davidscn initially suggested):
* We move our currently used `utils/span.hpp` to the interface and update it to the latest version
* We add a constructor for the `const char*` case to support C-strings and string literals.
* We use `using string_view = ::precice::span<const char>` to emulate string views.
* We use `::precice::span` in the rest of the interface #1577 

This way:
* we get all the conversions, flexibility, and safety we require in the API
* we can still internally use `std::string_view` and eventually `std::span` in the `SolverInterfaceImpl` and any other internals.

@IshaanDesai this should be compatible with

**Comment by davidscn** [comment]
Discussing in person.

- we want to remain C++11 compliant in our C++ API
- we need to distinguish between our C++ requirement in the preCICE library itself, i.e., which C++ is required to compile preCICE (currently C++17) and the C++ requirement of our API (C++11 as of now)
- since we converged in #1577 to introduce a `precice::span`, we can easily support a C++11 compliant `string_view` with the alias define `using precice::string_view = precice::span< const char >`
