### ISSUE TITLE
QN acceleration throws error for the tutorial `partitioned-heat-conduction`

### ISSUE THREAD

**Issue by IshaanDesai** [precice/precice#1610]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 22.04_
preCICE Version: develop https://github.com/precice/precice/commit/b7454159cc51fc418e8de9ac1ab0d6e68c0dc9d2

python-bindings develop https://github.com/precice/python-bindings/commit/81c5f0ce06a777782494e8233293ec7520c10235
FEniCS adapter with compatibility changes: https://github.com/precice/fenics-adapter/commit/cfec85d977bda690478b8b1b4fea9c9c384fa2c1
Tutorials repository with compatibility changes for all FEniCS participants: https://github.com/precice/tutorials/commit/433635eed18190b81215430d7274b89e0fbcd325

**Describe the problem**

After implementing changes to the adapter and the tutorial to make the FEniCS cases work with the latest `precice:develop`, running the [partitioned-heat-conduction](https://github.com/precice/tutorials/tree/fenics-tutorials-v3/partitioned-heat-conduction) tutorial with FEniCS results in the error:

```bash
---[precice]  iteration: 3 of 100, time-window: 3, time: 0.2 of 1, time-window-size: 0.1, max-timestep-length: 0.1, ongoing: yes, time-window-complete: no, read-iteration-checkpoint 
Solving linear variational problem.
---[precice]  relative convergence measure: relative two-norm diff of data "Heat-Flux" = 2.05e-14, limit = 1.00e-05, normalization = 6.32e+00, conv = true
---[precice]  relative convergence measure: relative two-norm diff of data "Temperature" = 4.36e-16, limit = 1.00e-05, normalization = 1.13e+01, conv = true
---[precice]  All converged
---[precice] WARNING:  The coupling residual equals almost zero. There is maybe something wrong in your adapter. Maybe you always write the same data or you call advance without providing new data first or you do not use available read data. Or you just converge much further than actually necessary.
---[precice] WARNING:  The number of columns in the least squares system exceeded half the number of unknowns at the interface. The system will probably become bad or ill-conditioned and the quasi-Newton acceleration may not converge. Maybe the number of allowed columns ("max-used-iterations") should be limited.
---[precice] ERROR:  Attempting to add a zero vector to the quasi-Newton V matrix. This means that the residuals in two consecutive iterations are identical. If a relative convergence limit was selected, consider increasing the convergence threshold.
---[precice] ERROR:  Receiving data from another participant (using sockets) failed with a system error: read: End of file. This often means that the other participant exited with an error (look there).
```

It appears that the quasi-newton acceleration is somehow more *strict* than what it was before.

**Step To Reproduce**

Run the tutorial with the above mentioned adapter and tutorial branch.

**Expected behavior**

The tutorial worked without any issues before.

**Additional context**

In its original state, there are [`9` vertices](https://github.com/precice/tutorials/blob/0482e5b4d3e1604dd031d2b113a2aaa63733c9a8/partitioned-heat-conduction/fenics/problem_setup.py#L36). Increasing to `11` vertices results in the tutorial running successfully with warnings. Increasing further to `30` vertices results in even the warnings disappearing.

If the same tutorial is run with preCICE `v2.5.0`, python bindings `v2.5.0.2`, fenics-adapter `v1.4.0`, and  tutorials `v202202.0`, it runs fine with `9` vertices but fails in a similar fashion for `7` vertices.

**Comment by Fujikawas** [comment]
This would be solved by https://github.com/precice/precice/pull/1863.
