### ISSUE TITLE
Wrong CMake variable, when preCICE used as submodule

### ISSUE THREAD

**Issue by anastazja-bro** [precice/precice#1613]
When using preCICE as a submodule, there are errors in configuration - source files are not written in the correct place because CMAKE_BINARY_DIR is used in sources.cmake file. Changing it to PROJECT_BINARY_DIR solves the issue.

**Comment by fsimonis** [comment]
I knew this would hound us one day :wink: 

Thanks for opening the issue and letting us know that there is a demand for the use as CMake subproject.

**Comment by anastazja-bro** [comment]
Thanks :)
