### ISSUE TITLE
Dead link in wiki: How to couple codes with preCICE

### ISSUE THREAD

**Issue by KanakRaj2** [precice/precice#1629]
Sir, I am a new user of Precice Coupling. As I am trying to learn precice, while we seen some tutorial where it is showing the we may see the coupling documents at https://precice.org/couple-your-code-prerequisites.html but when we open that link, it is showing error that page not found.
Con you please help me to share those documents so that I may learn the coupling of solver in openfoam.

**Comment by fsimonis** [comment]
Hi,

You can find the documentation here https://precice.org/couple-your-code-overview.html

Where exactly did you find the broken link?

**Comment by KanakRaj2** [comment]
Sir, it is there on https://github.com/precice/precice/wiki
Also, sir can you please share some link to learn precice for coupling CHT and multiphase in OpenFoam.
