### ISSUE TITLE
Extend cmake building to handle last and different build settings

### ISSUE THREAD

**Issue by uekerman** [precice/precice#163]
For scons, we have the neat feature that every different build option (e.g. `python=no`) goes into a different subfolder (e.g. `debug-nopython`) and that there is always a symbolic link `last` pointing to the last build. 

Would be good to also have this for cmake.

**Comment by floli** [comment]
There may be a chance to add a symlink from build/last to **the last build folder**, but creating build folders like you proposed is detrimental how cmake works.
