### ISSUE TITLE
Remove deprecated mpi single ports tag

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1650]
https://github.com/precice/precice/blob/f62ab3bb779f1817bd9e960dd91937fb3951de5f/src/m2n/config/M2NConfiguration.cpp#L87-L100

This issue is mainly a reminder. If somebody has more information on this issue or wants to start working on this, feel free to edit etc.

**Comment by fsimonis** [comment]
This is one of many tags we kept for backwards compatibility
