### ISSUE TITLE
Specify how exports and waveforms interact

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1655]
**Please describe the problem you are trying to solve.**

1. There is no association between exported file name and time / time window / iteration. Iterations are counted globally and subcycling breaks the remaining names.
2. Time interpolation breaks the assumption that there is one set of data per export. Each data will now be samples, which amount can vary between time windows
3. Received data from various participants may have incompatible time discretization. 
4. We cannot export read data, because they might live on a different time discretization. A possible solution here is resampling over the waveforms, but we still cannot export data that is not `_providedData`. This eliminates the possibility to analyze read mappings, if subcycling is used.

**Describe the solution you propose.**

* Every solver exports written data, as time discretization is identical for every write data. This covers both meshes of write mappings.
* Optionally: Resample read data at the same time scale as the written data (expensive)
* To analyse the mapping, we could use some kind of "debug mode", where only the data at the end of the window is exported. There we know that all data lives on the same time mesh. Analysing subcycling and mapping at the same time is not possible in this setting.
* Another possibility is to add a mapping exporter, which exports mesh and data before and after the execution of a mapping. Time scales are identical in this case.

**Describe alternatives you've considered**

* Only export at end of window (basically the "debug mode") mentioned above.

**Additional context**

**Comment by fsimonis** [comment]
I moved this to version 3.0.0 as we need to come up with a clear solution for this.

Otherwise, ASTE cannot be ported to v3.

**Comment by uekerman** [comment]
Closing as included in #1306
