### ISSUE TITLE
Geometry Format - WKT

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#166]
There exists a format for textual description of geometries called _Well-Known Text_ [ref](https://en.wikipedia.org/wiki/Well-known_text). It is supported by [boost.geometry](https://www.boost.org/doc/libs/1_68_0/libs/geometry/doc/html/geometry/reference/io.html) alongside the SVG format.

The WKT format is readable, short, parsable and not too verbose (in contrast to SVG):
```
POINT (30 10)
LINESTRING (30 10, 10 30)
POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))
```

A downside of the format is that Triangle and Quad look very similar as they map to the same description:
```
POLYGON ((30 10, 40 40, 20 40, 10 20))
POLYGON ((30 10, 40 40, 20 40))
```

For the mesh description we could output the following:
```
MULTIPOINT ((10 40), (40 30), (20 20), (30 10))
MULTILINESTRING ((10 10, 20 20),(40 40, 30 30))
MULTIPOLYGON (((30 20, 45 40, 10 40)),((15 5, 40 10, 10 20)))
MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20)),((15 5, 40 10, 10 20, 5 10)))
```

Shall we use this format to print our `mesh::*` classes? (Related to #165)

**Comment by S0mmerD** [comment]
Looks interesting. I would like to hear some more opinions on this, but i'd like to implement it that way. The syntax looks clean and concise.

**Comment by uekerman** [comment]
The obvious mean question: We already have vtk output for meshes, what would be the use case for this additional output format?  

Always important: It needs to work for distributed meshes as well. That's the reason why we killed many previous geometry/mesh io options in preCICE.

**Comment by floli** [comment]
I think it's not going to be an format for export, but for `operator<<`, isn't it? So it's rather a debug functionality, than a user feature.

**Comment by fsimonis** [comment]
@uekerman @floli My idea was to use this format to make our logging (`operator<<`) readable and consistent. The bonus of using a standard is that it opens up the usage of existent tooling.
Users can simply copy the output into an [online visualizer](http://www.samuelbosch.com/p/geometry-visualizer.html) to help them with debugging.
Example for the link above:
```
GEOMETRYCOLLECTION(
MULTIPOINT((0 0), (0 1), (1 0), (1 1)),
MULTILINESTRING((-1 -1, 2 -1),(-1 2, 2 2)),
MULTIPOLYGON(((-1 3, 0.5 5, 2 3)),((-1 -2, 0.5 -4, 2 -2))),
MULTIPOLYGON(((-1 0, -2 0, -2 1, -1 1)),((2 0, 3 0, 3 1, 2 1)))
)
```

**Comment by uekerman** [comment]
OK, then, this was a misunderstanding. Looks good to me!
