### ISSUE TITLE
LUA Configuration

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#168]
At the moment preCICE uses a rather extensive [XML configuration](https://github.com/precice/precice/wiki/XML-Reference). As we all know, XML is a bit tedious to work with.

We could migrate the configuration to LUA in order to allow a more flexible, and programmatic way to configure the library.

### References
* [Binding Code To Lua](http://lua-users.org/wiki/BindingCodeToLua)
* [Using LUA and C++ in practice](https://eliasdaler.wordpress.com/2015/08/10/using-lua-and-cpp-in-practice/)
* [Sol2 Docs](https://sol2.readthedocs.io/en/latest/)
* [Talk about Sol2 (C++Now 2018)](https://www.youtube.com/watch?v=0Lwy4_sKeJM)

**Comment by uekerman** [comment]
I am a bit reluctant concerning this change. I don't yet see the benefit for users. They normally don't need a programmable configuration. Often, they don't even change the configuration very often. I only see a benefit for us developers when we want to test methods over a range of parameters etc. 

An important downside is that our standard user is somehow familiar with XML, but probably has never heard of LUA. Also keep in mind that such a huge change caries a lot of work load beyond a potential student project: user documentation, user requests, backward compatibility, ...

**Comment by MakisH** [comment]
Conclusion from discussion in the coding days:
* Unclear added value.
* LUA could be better to have started with (it would open up a whole new world for us), but we would need to validate so many things, that it would not worth the effort.
* The usability problem could be solved by adding a config-generating tool (see https://github.com/precice/controller ).
* Closing this as "wontfix" for now.
