### ISSUE TITLE
Mapping that may result in `nan` values

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1686]
The following line might introduce a scaling factor `nan`, if `integralOutput.array()` is equal to zero. 

https://github.com/precice/precice/blob/c1f6cb902452c429e4a84c8bd34a61680cd7db0c/src/mapping/Mapping.cpp#L166

This can happen easily, if data has not been initialized (defaults to zero). I ran into this problem while working on #1684. Here the tests from `Integration/Serial/MappingScaledConsistent` do not initialize data. This results in `nan` values, that are propagated to the user, if `waveform-order = "1"` is used.

**Comment by fsimonis** [comment]
We can fix this with a custom binary op in eigen. I'll fix this soon
