### ISSUE TITLE
Use `waveform-degree="1"` or `waveform-degree="3"` as default?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1690]
With https://github.com/precice/precice/pull/1684 using waveforms became non-experimental and the default. First degree interpolation is at the moment the default we agreed on. However, there is also the possibility to use a higher degree as default as soon as #1671 is merged. We should conclude on this point until the release of version 3, because changing the default would be breaking.

I will provide some information on the two candidates below:

### Use `waveform-degree="1"` as default

1st degree interpolation is generally always possible, because we only need two samples to construct a 1st degree interpolant. Using data from the beginning and the end of the window is always available. If additional data is available due to subcycling, a piecewise linear interpolation would be used instead.

Note that a piecewise linear interpolation produces the same results like a linear interpolation as long as we work on the same time grid.

From the user perspective this would lead to a behavior of preCICE that is easy to understand: No matter how many samples I provide in window, there is always a linear interpolation between two samples.

### Use `waveform-degree="3"` as default

3rd degree interpolation is only possible, if 4 or more samples are available in a time window. Meaning, we need subcycling to actually perform 3rd degree interpolation. If less than 4 samples exist, our interpolation routine will automatically pick a lower-degree interpolation; if no subcycling is used this leads to 1st degree interpolation.

If we compare results from runs with and without subcycling there might be a difference -- even if time grids agree -- due to the different interpolation routines and smoothness of the interpolant.

From the user perspective the behavior of preCICE becomes a bit harder to understand: The user has to understand that subcycling and higher-order interpolation go hand in hand. However, if a user uses subcycling, this would automatically lead to a higher-order interpolation routine (likely to also lead to better results) without the need for any further user interaction.

Note: Looking at other libraries for scientific computing might also help us here: In scipy the function [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) also applies some "magic" for picking the best `method`, if the user does not explicitly ask for a specific method. This corresponds more or less to using 3rd degree interpolation as default, because this would automatically fallback to 1st or 2nd degree (different `method`) in certain situations.

### Explicit coupling schemes

For explicit coupling schemes the situation is complicated: In most cases 1st or even higher-degree interpolation is not available, because the only data that is known when we enter a window is the data at the beginning. We do not have access to any data inside the window or at the end due to the coupling scheme. The second participant in a serial explicit is the only exception here, because it first receives the data produced by the first participant in the current time window before starting any computations. In this case 1st or higher-degree interpolation is available. Also related: https://github.com/precice/precice/issues/1691

**Comment by davidscn** [comment]
Just as a comment. The discussion reminds me a bit on the mapping configuration. We eventually agreed on an alias tag, which is in essence some auto-configuration and also documented as such. Maybe it would be worth to do something similar here: giving configuration options like 'highest-order', 'least-sync' or 'auto' to enforce some default behavior which is not bound to a specific algorithm/method in the background.

**Comment by BenjaminRodenberg** [comment]
Updated terminology following #1699

**Comment by BenjaminRodenberg** [comment]
Closing this issue, since #1732 is merged and defaulting to `waveform-degree="1"` is consistent.
