### ISSUE TITLE
Composition of implicit and explicit scheme triggers assertion, if subcycling

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1692]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 18.04_
preCICE Version: [1180edb](https://github.com/precice/precice/commit/1180edb58bacce28dd066b852edfc2eb6623135a)

Add the versions/commit hashes of further adapter and/or bindings.

**Describe the problem**

A composition of an explicit and implicit coupling scheme runs into the following assertion, if subcycling is used:

```
ASSERTION FAILED
Location:   virtual bool precice::cplscheme::BaseCouplingScheme::addComputedTime(double)
File:       /home/benjamin/Programming/precice_develop/src/cplscheme/BaseCouplingScheme.cpp:338
Expression: isCouplingOngoing()
Rank:       0
Arguments:  
  0: "Invalid call of addComputedTime() after simulation end." == Invalid call of addComputedTime() after simulation end.
```

**Step To Reproduce**

I modified some existing tests in f4695369fdab085142a99f9c1e33f00d55eaaf72.

**Expected behaviour**

The setup should work.

**Additional context**

For a composition of explicit schemes everything works as expected. We actually already have a tests for this case: https://github.com/precice/precice/blob/1180edb58bacce28dd066b852edfc2eb6623135a/tests/serial/time/explicit/compositional/ReadWriteScalarDataWithSubcycling.xml ; For the composition of implicit and explicit schemes we missed adding a test.

**Comment by fsimonis** [comment]
Closed by #1705
