### ISSUE TITLE
Rename `waveform-order` to `waveform-degree`

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1699]
Because `waveform-order="1"` leads to (piecewise) linear interpolation (i.e. polynomial degree = 1, but the interpolation order of the scheme or convergence order of the time stepping scheme can be higher). So let's talk about the `waveform-degree="1"` instead.

Alternatives:

* `interpolating-polynomial-degree="1"`
* `bspline-degree="1"`

**Comment by BenjaminRodenberg** [comment]
Another thing to keep in mind: Sooner or later we might want to use alternative interpolation schemes to B-splines. Example: Create a polynomial fit of degree $p$ that approximates $n$ given substeps.

**Comment by uekerman** [comment]
`waveform-degree` is good :+1:

**Comment by BenjaminRodenberg** [comment]
Closed via #1714
