### ISSUE TITLE
Automatically check CHANGELOG for additions

### ISSUE THREAD

**Issue by MakisH** [precice/precice#170]
Problem: sometimes we (or Pull Request contributors) forget to mention changes in the [CHANGELOG.md](https://github.com/precice/precice/blob/develop/CHANGELOG.md).

Idea: add an automatic check for additions (or no additions).

This should be only a warning or reminder to the contributor. Therefore, we could use a GitHub bot (for example, @precice-bot), which could write a comment in the respective pull request. See, for example, [this PR](https://github.com/shkodm/precice/pull/3#issuecomment-429620483). @shkodm is already working on this.

**Comment by BenjaminRueth** [comment]
similar to https://github.com/precice/precice/issues/170

**Comment by MakisH** [comment]
Related to #621. We will eventually implement this with GitHub Actions.

**Comment by MakisH** [comment]
To simplify things (and especially an unclear decision tree for the automation), let's delegate this to the reviewer. I will add this to a PR template and configure GitHub to use it.
