### ISSUE TITLE
Avoid unnecessary mappings in `DataContext`

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1707]
The [mapping is applied to the complete storage of `Stamples`](https://github.com/precice/precice/pull/1612/files#diff-8d2f34adf551a7a24672179250b2b510723c2cec784a5680ff00d0d7ce41e711R87-R102). This is especially important for follow-up PRs that improve subcycling (#1664, #1671).

The relevant code part is the following:

https://github.com/precice/precice/blob/394d6483effeee43c4d23cff709fafe7106ca566/src/precice/impl/DataContext.cpp#L101-L119

One mapping operation that we don't need to perform is the mapping of data at `WINDOW_START`, because this data does not change anymore. Currently, we perform a mapping for the data at `WINDOW_START` in every iteration even though this is not needed. There is a possibility for improving performance here, because we might be able to save half of the mapping that are performed (no subcycling, only data at `WINDOW_START` and `WINDOW_END`, only mapping at `WINDOW_END` is actually needed).

Note: during initialization we need to map also the data at `WINDOW_START`, which would require a special treatment.

**Comment by BenjaminRodenberg** [comment]
My opinion on this issue: As long as there is no strong evidence that the additional mapping overhead is too costly, I would not touch this part. It was a lot of work refactoring the overall architecture w.r.t management of `Samples` etc. I think everything has become much cleaner and this should help us with features that are currently under development (e.g. Quasi-Newton for Waveforms). By introducing again exceptions for certain cases (here, initialization) I see a high risk for making implementation (again) much more complicated for a gain in performance.

**Comment by davidscn** [comment]
> As long as there is no strong evidence that the additional mapping overhead is too costly, I would not touch this part.

Computing rbf mappings is probably the most compute-intense part we have in preCICE. You can find 'strong' evidence for example in [Timo's thesis](https://elib.uni-stuttgart.de/handle/11682/13046) or the [OpenFOAM adapter paper](https://journal.openfoam.com/index.php/ofj/article/view/88). From my very naive waveform understanding, the 'time zero sample' should just go in front of the mapping loop 

https://github.com/precice/precice/blob/394d6483effeee43c4d23cff709fafe7106ca566/src/precice/impl/DataContext.cpp#L101-L103

rather than inside the loop, such that the additional complexity is rather trivial.

**Comment by uekerman** [comment]
Quick addition: Besides mapping, we should also avoid communicating redundant data.

**Comment by BenjaminRodenberg** [comment]
> From my very naive waveform understanding, the 'time zero sample' should just go in front of the mapping loop rather than inside the loop, such that the additional complexity is rather trivial.

That's clear, but there are many additional things to keep in mind (compositional coupling schemes, data initialization, actions, ...). Feel free to provide a PR and prove me wrong, but currently I don't want to open this box because I've already spent quite some time here.

**Comment by uekerman** [comment]
We will have to open this box eventually. It is a clear performance issue. Independent of this is the question when we do it and who does it :grin: 
Maybe finishing the acceleration implementation first makes sense. Only then we can really say which refactoring we still need.

**Comment by BenjaminRodenberg** [comment]
Note: The `bool` introduced in #1719 can probably help us here to avoid some unnecessary communication of samples at `WINDOW_START`.

**Comment by BenjaminRodenberg** [comment]
https://github.com/precice/precice/pull/1791 goes into a similar direction, because it also introduces an additional mapping. I think we should generally revise the way how we tell `ParticipantImpl` whether a mapping has to be performed or not. Currently, this is mostly done by checking if `_couplingScheme->hasDataBeenReceived()` or `_couplingScheme->willDataBeExchanged(0.0)`. To me this looks like `ParticipantImpl` is looking at an implementation detail of `_couplingScheme`. Something like `_couplingScheme->isMappingRequired()` or maybe even doing this on the level of the `DataContext` feels more natural.

Additionally, I think we will have more situations in the future, where `ParticipantImpl` cannot easily decide whether a mapping has to be performed or not (imagine we only want to use some of the written data in a scenario with largely different time step sizes).

**Comment by BenjaminRodenberg** [comment]
Implementation Idea (might also be a nice thesis topic): Maybe we could solve this whole problem by using some kind of hash / check-sum? If we map `dataOnA` from `MeshA` to `MeshB` the mapping operation `dataOnB = map(dataOnA)` is expensive. We could do the following to avoid unnecessary mappings:

```
newHash = hash(dataOnA);
if (dataOnB.hash != newHash) {
    dataOnB.hash = newHash;
    dataOnB = map(dataOnA);
} else {
    // no mapping necessary, because dataOnB already contains mapped data
}
```
The same approach should also work for communication.

**Comment by davidscn** [comment]
I don't follow the recent changes continuously, but with the current state of develop ([3d13be6](https://github.com/precice/precice/commit/3d13be6d08aa54c40144d3678555fb37fc76f294)) preCICE performs in our standard [aste tutorial](https://github.com/precice/tutorials/blob/master/aste-turbine/precice-config.xml) four instead of one mapping: two in initialize and two in advance. This increase makes the tutorial somewhat unusable.

**Comment by uekerman** [comment]
Even if you use `substeps="false"`?
Currently, `true` is still the default on develop, but this will change to `false` soonish.

**Comment by davidscn** [comment]
> Even if you use `substeps="false"`? Currently, `true` is still the default on develop, but this will change to `false` soonish.

Yes, even `substeps="false"` results in four mapData calls in total.

**Comment by BenjaminRodenberg** [comment]
If #1819 is `v3.0.0`, this one should also go into `v3.0.0` as far as I understand.

**Comment by fsimonis** [comment]
I have some questions regarding this:
* Is it acceptable if we execute write mappings in the last call to advance of a simulation in case the data will not be exchanged? Only first in a serial coupling scheme needs to provide this data.
* Is it acceptable if we map all substeps in the write mapping even though we define `<exchange ... substeps="false" >` for the given data?

**Comment by fsimonis** [comment]
Update on the substeps:

We will add a global toggle that ignores provided data samples for time steps that are definitely subcycling if all exchanges don't use substeps.

Meaning the participant will generate samples for every time window, which includes artificial synchronization points when mixing time windows.

From an adapter perspective, advancing less than `getMaxTimeStepSize()` will not result in samples, nor mappings iff all exchange tags use `substeps=false` aka the current default.
