### ISSUE TITLE
`precice-events analyze` crashes

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1708]
**Describe your setup**

Recent develop snapshot  394d648 and python 3.10

**Describe the problem**
I'm trying to use the profiler. I have a very basic serial run and after running `precice-events merge <dir>` I would like to investigate the result of `precice-events analyze`. However, the latter command fails with the following backtrace:

```bash
Reading events file events.json
Output timing are in us.
Traceback (most recent call last):
  File "~/precice/tools/profiling/precice-events", line 719, in <module>
    sys.exit(dispatcher.get(args.cmd, showHelp)(args))
  File "~/precice/tools/profiling/precice-events", line 710, in <lambda>
    "analyze": lambda ns: analyzeCommand(ns.eventfile, ns.participant, ns.output,  ns.unit),
  File "~/precice/tools/profiling/precice-events", line 472, in analyzeCommand
    joined.reset_index(inplace=True, names="event")
  File "~/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
TypeError: DataFrame.reset_index() got an unexpected keyword argument 'names'

```

**Step To Reproduce**
The behavior can easily be reproduced using our test data (e.g. [`from-common-dir`](https://github.com/precice/precice/tree/develop/tools/profiling/tests/from-common-dir))
1. `precice-events merge`
2. `precice-events analyze B`

**Expected behaviour**
No crash

**Additional context**
This feature seems to be untested, so we cannot expect it to work in the first place-

**Comment by davidscn** [comment]
The trivial change of

https://github.com/precice/precice/blob/394d6483effeee43c4d23cff709fafe7106ca566/tools/profiling/precice-events#L472

```diff
- joined.reset_index(inplace=True, names="event") 
+joined.reset_index(inplace=True) 
```

fixed it for me. Not sure whether this is a proper solution, though.

**Comment by fsimonis** [comment]
Looks like a problem with the pandas version.

We currently don't test this as I didn't want to make pandas a dependency of preCICE for the sole sake of testing.
Of course, we could add an optional switch to run these tests is pandas is found and install pandas in the ci-images.

**Comment by uekerman** [comment]
Having this in the CI would indeed be good moving forward :+1:

**Comment by fsimonis** [comment]
A question here is which baseline we are going to pick for pandas.

The above error is due to a keyword required by pandas 1.5.0.

Ubuntu 22.04 ships with pandas 1.3.5 and Ubuntu 20.04 with 0.25.3.

Can we expect users to install a newer pandas via pip?

**Comment by uekerman** [comment]
> Can we expect users to install a newer pandas via pip?

I would say yes. It is also a dependency of the tool, not of preCICE, right?

**Comment by fsimonis** [comment]
The tool now requires polars instead of pandas for some commands. This should be installed by the user.
