### ISSUE TITLE
Move `waveform-degree` from `read-data` to `exchange` (or somewhere else?)

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1709]
See https://github.com/precice/precice/pull/1696 for some more background. I'm using `waveform-degree`, because we already decided to rename in #1699.

For resampling data (#1658) we need to be able to define `waveform-degree` not only for `read-data`, but generally for `CouplingData`. The following configuration is not sufficient anymore

```xml
<mesh name="MeshOne">
    <use-data name="DataOne" />
    <use-data name="DataTwo" />
</mesh>
...
<participant name="SolverOne">
  <provide-mesh name="MeshOne" />
  <write-data name="DataOne" mesh="MeshOne" />
  <read-data name="DataTwo" mesh="MeshOne" waveform-order="3" />
</participant>
...
<coupling-scheme:parallel-implicit>
  <participants first="SolverOne" second="SolverTwo" />
  ...
  <exchange data="DataOne" mesh="MeshOne" from="SolverOne" to="SolverTwo" initialize="true"/>
  <exchange data="DataTwo" mesh="MeshOne" from="SolverTwo" to="SolverOne" initialize="true"/>
  <acceleration:constant>
    ...
  </acceleration:constant>
</coupling-scheme:parallel-implicit>
```

We arrived in #1699 at the following solution:

```xml
<mesh name="MeshOne">
    <use-data name="DataOne" />
    <use-data name="DataTwo" />
</mesh>
...
<participant name="SolverOne">
  <provide-mesh name="MeshOne" />
  <write-data name="DataOne" mesh="MeshOne" />
  <read-data name="DataTwo" mesh="MeshOne" />
</participant>
...
<coupling-scheme:parallel-implicit>
  <participants first="SolverOne" second="SolverTwo" />
  ...
  <exchange data="DataOne" mesh="MeshOne" from="SolverOne" to="SolverTwo" initialize="true" />
  <exchange data="DataTwo" mesh="MeshOne" from="SolverTwo" to="SolverOne" waveform-order="3" initialize="true" />
  <acceleration:constant>
    ...
  </acceleration:constant>
</coupling-scheme:parallel-implicit>
```

**Comment by BenjaminRodenberg** [comment]
One concern by @uekerman: Compositional Coupling Schemes, e.g.

```
<exchange data="DataOne" mesh="MeshOne" from="SolverOne" to="SolverTwo" waveform-order="3"/>
<exchange data="DataOne" mesh="MeshOne" from="SolverOne" to="SolverThree" waveform-order="1"/>
```

I think this should work. Currently we would solve this via

```
<participant name="SolverTwo">
  ... + mapping and the usual mesh setup
  <read-data name="DataTwo" mesh="MeshTwo" waveform-order="3" />
</participant>
...
<participant name="SolverThree">
  ... + mapping and the usual mesh setup
  <read-data name="DataThree" mesh="MeshThree" waveform-order="1" />
</participant>
```

**Comment by uekerman** [comment]
> I think this should work. Currently we would solve this via

I also have a good feeling that this will be no problem. But better test than sorry :blush:

**Comment by BenjaminRodenberg** [comment]
I'm currently starting with the implementation. One problem that I already saw:

`ReadDataContext` (or `DataContext` generally) has no connection to the `CouplingData`. This means, we have to put the waveform into `mesh::Data` if we want both to be able to access it. From the user perspective we might still be able to use the approach suggested above, but from the implementation perspective we need to go to the `Data` level. Will keep you posted here or open a PR.

**Comment by fsimonis** [comment]
Data sounds like like a logical place to put it. Then the waveform is together with the time storage aka it's source data.

Alternative may be to put it into the time storage itself.

Would it be possible to configure the waveform degree on a data level instead of a participant / coupling-scheme level instead.
A more central approach could reduce many headaches

**Comment by BenjaminRodenberg** [comment]
We might run into trouble with the actions:

The following configuration defines two solvers `SolverSource{One,Two}` that send data to `SolverTarget`. The data `Source{One,Two}` is then summed up to `Target`:

https://github.com/precice/precice/blob/7be06e8083d1432166094baad12d50bfaa9d76c2/tests/serial/SummationActionTwoSources.xml#L21-L29
...
https://github.com/precice/precice/blob/7be06e8083d1432166094baad12d50bfaa9d76c2/tests/serial/SummationActionTwoSources.xml#L56-L68

### Move `waveform-degree` inside `exchange`

`Target` is actually not exchanged. It only exists on `SolverTarget`. Therefore, the following "translation" of the config above is not sufficient:

```
  <coupling-scheme:serial-explicit>
    <participants first="SolverSourceOne" second="SolverTarget" />
    <max-time-windows value="2" />
    <time-window-size value="1.0" />
    <exchange data="SourceOne" mesh="MeshTarget" from="SolverSourceOne" to="SolverTarget" waveform-degree="1" />
  </coupling-scheme:serial-explicit>

  <coupling-scheme:serial-explicit>
    <participants first="SolverSourceTwo" second="SolverTarget" />
    <max-time-windows value="2" />
    <time-window-size value="1.0" />
    <exchange data="SourceTwo" mesh="MeshTarget" from="SolverSourceTwo" to="SolverTarget" waveform-degree="1" />
  </coupling-scheme:serial-explicit>
```

### Move `waveform-degree` inside `data`

If we move the `waveform-degree` inside `SolverTarget`'s data, we can also define the `waveform-degree` for `Target`:

```
  <mesh name="MeshTarget">
    <use-data name="SourceOne" />
    <use-data name="SourceTwo" />
    <use-data name="Target" waveform-degree="1" />
  </mesh>
```

**Comment by fsimonis** [comment]
For the record: we moved `waveform-degree` to `<data:... />` instead of  `<use-data ...>`
