### ISSUE TITLE
Query on serial implicit coupling - acceleration schemes

### ISSUE THREAD

**Issue by megandlima** [precice/precice#1711]
Hello,

I'm solving an FSI problem (serial implicit coupling) using an in-house fluid solver and FEniCS for the solid part. As per what I have understood, Aitken scheme uses only displacement values for convergence whereas QN scheme uses both force and displacement values. Hence, if I want to use Aitken scheme, do I still need to write and read checkpoints for reading force in the fluid solver, as I thought that writing and reading checkpoint for displacements in FEniCS should be enough? 

Also, when I try to use QN scheme, I get this error:
You configured acceleration data "Force" in the serial implicit coupling scheme between participants "Fluid" and "Solid". For serial implicit coupling schemes, only data exchanged from the second to the first participant can be used for acceleration. Here, from "Solid" to "Fluid". However, you configured data "Force" for acceleration, which is exchanged from "Fluid" to "Solid". Please remove this acceleration data tag or switch to a parallel implicit coupling scheme.

Thank you very much!

**Comment by BenjaminRodenberg** [comment]
Hi! Can you share your `precice-config.xml` file? This would help to understand the issue better. Additionally to me this sounds at the moment like a problem with the correct usage of preCICE and not so much like a technical issue. I think re-posting your question in our forum (https://precice.discourse.group/) and closing it here might fit better.
