### ISSUE TITLE
Mixing tolerances for time-windows in compositional coupling schemes

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1712]
**Describe your setup**

preCICE Version: develop @ https://github.com/precice/precice/commit/3bfc9d9015c15e4ef8967269ccc67e92a9884086

**Describe the problem**

```xml
  <coupling-scheme:serial-explicit>
    <participants first="A" second="B" />
    <time-window-size value="1" valid-digits="10" />
  </coupling-scheme:serial-explicit>

  <coupling-scheme:serial-explicit>
    <participants first="B" second="C" />
    <time-window-size value="1" valid-digits="8" />
  </coupling-scheme:serial-explicit>
```

If B calls `advance(1.0-10e-9)`, then the first coupling scheme has completed, but the second hasn't despite equal time-windows and points in time.

The tolerance should be equal for all coupling schemes in a composition.

**Step To Reproduce**
1. Use the configuration above
2. In B, call `advance(1.0-10e-9)`

**Expected behaviour**
This should result in a configuration error.

**Comment by uekerman** [comment]
Alternative "fix": Move the `valid-digits` somewhere global.

**Comment by fsimonis** [comment]
Conclusion:
- checking valid digits doesn't make sense
- use min time step size instead
- make a global setting
