### ISSUE TITLE
Mixed time window sizes in compositional coupling schemes

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1713]
**Please describe the problem you are trying to solve.**

Mixing different time window sizes in a compositional coupling schemes is allowed, but not completely clear.

Example:
```xml
<coupling-scheme:serial-explicit>
  <participants first="A" second="B" />
  <time-window-size value="2" />
</coupling-scheme:serial-explicit>

<coupling-scheme:serial-explicit>
  <participants first="B" second="C" />
  <time-window-size value="3"  />
</coupling-scheme:serial-explicit>
```

## Maximum time step size

The max time step size of 
* A is the time-window-size 2
* C is the time-window-size 3
* B aligns with A and B:
  1. Meet A: 2 (t=2)
  2. Meet B: 1 (t=3)
  3. Meet A: 1 (t=4)
  4. Meet A and B: 2 (t=6)

Is it reasonable for B to expect this fluctuation in time step sizes?

## Data Mapping

A participant performs data mapping and communication at the end of a time window.
The communication is handled by the coupling schemes, which thus supports mixed time windows.
The data mapping is handled by the participant, resulting in unnecessary mapping executions.
Only the participants synchronized with provide/require data which may need to be mapped.
This gets magnified by https://github.com/precice/precice/pull/1664 as we now map two samples per data.

If mappings for exchanged data is defined on B, then this would result in unnecessary mappings on B:

Step | Meeting who | DT | t | useless map in advance 
--- | --- | --- | --- | ---
1 | A | 2 | 2 | 2 calls
2 | B | 1 | 3 | 2 calls
3 | A | 1 | 4 | 2 calls
4 | A & B | 2 | 6 | 0 call

## Implicit coupling

Assuming:
```xml
<coupling-scheme:serial-explicit>
  <participants first="A" second="B" />
  <time-window-size value="1" />
</coupling-scheme:serial-explicit>

<coupling-scheme:serial-implicit>
  <participants first="B" second="C" />
  <time-window-size value="2"  />
</coupling-scheme:serial-explicit>
```

Then we get the following get timestep sizes:
* A is the time-window-size 1
* C is the time-window-size 2
* B aligns with partners
  1. 1 as it meets A (at t=1)
  2. 1 as it meets A and B (at t=2)

If the implicit scheme doesn't converge, then the checkpoints are restored and the schemes revert to t=0.
Now the max step size for B and C are 2 and they both meet at t=2.

What data of A do we expect at this point in time? t=0, t=1, or t=2?
How do we sample from this partial data in time? Do we need to keep all samples?

## Prescribed time window

One or multiple serial coupling schemes may also prescribe the time window. 

As an example A and C could prescribe the time window for B.

**Describe the solution you propose.**

We need to clarify what use-cases we support, test the supported ones and prevent the unsupported ones.

**Additional context**

**Comment by BenjaminRodenberg** [comment]
Why does a (global) `<time-window-size value="6" />` in your very first example not solve the problem? The solvers could just use their individual time step sizes.

The mixture of an explicit scheme with a small time window size and the implicit scheme with a large time window size sounds interesting. But I see two problems:

* wouldn't this also break many assumptions about explicit coupling schemes in a compositional coupling scheme, because we would need to somehow iterate? Even though it is an explicit scheme.
* If I get the example right, we would need to jump back to checkpoints that are several windows in the past. This is not possible without the adapter maintaining something like a stack of checkpoints.

**Comment by fsimonis** [comment]
The current checkpointing behaviour for B looks as follows:

* initialize
* save checkpoint
* advance(1) - meet explicit A
* advance(1) - meet explicit A and meet implicit B which doesn't converge
* load checkpoint
* advance(2) - directly meet B

So, the solver discards state influenced by the steps from A.
In the second iteration of B-C, the data if A from t=2 is available.

**Comment by BenjaminRodenberg** [comment]
> * initialize
> 
> * save checkpoint
> 
> * advance(1) - meet explicit A
> 
> * advance(1) - meet explicit A and meet implicit B which doesn't converge
> 
> * load checkpoint
> 
> * advance(2) - directly meet B

Shouldn't A (according to the current implementation) already save a checkpoint after advance(1)? So

* A,B,C save checkpoint at t=0
* advance(1) - meet explicit A
* A saves checkpoint at t=1
* advance(1) - meet explicit A and meet implicit B which doesn't converge
* A,B,C load checkpoint at t=0, **for A only checkpoint at t=1 available**
* advance(2) - directly meet B

I think an integration test for this feature would really help (I guess none exists?)

**Comment by fsimonis** [comment]
I noticed a major issue in #1729. Mixed time window sizes currently don't work with the way we timestamp samples in the `time::storage`.

**Comment by fsimonis** [comment]
@uekerman suggested enforcing coupling schemes handling the same data to use the same time window size.

If a user hits this issue, then the simple workaround is to duplicate the data and use one per coupling scheme.

**Comment by fsimonis** [comment]
Conclusion:
- We support mixing time window sizes
- One coupling data must have a unique time window size
- We agree to using global time stamps for stamples
