### ISSUE TITLE
Use absolute timestamps for samples

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1729]
**Please describe the problem you are trying to solve.**

Currently, we save user-provided data as samples in a reference time frame from `[0, 1]`, where 0 is the beginning and 1 is the end of the current time window.

When a participant completes a time window, the sample at the end becomes the sample at the beginning `1 -> 0` and all other samples are discarded.

This only works if all coupling schemes use the same time window size, which isn't guaranteed #1713.
Otherwise, a participant may be at different relative locations in the differently sized time windows.

Example:
**todo**

As samples are stored globally in the `time::storage`, there is no unique relative time frame to store them to.

Furthermore, it is not clear which samples to remove after at least one coupling scheme completes a time window. Some coupling schemes may subcycle.  

**Describe the solution you propose.**

Use absolute time stamps for saving samples.

* A participant is always at a known point in time, hence, time-stamping user-provided data becomes clear.
* If a coupling scheme completes a time window, we discard everything before the oldest time window start. For this, we replace `time::storage::move()` and `time::storage::trim()` with `time::storage::discardBefore()`.
* The interpolation functions operate on the global time frame instead of the relative one.

**Describe alternatives you've considered**

* Restrict samples to the compositional time windows, which is the union of all time window ends in time. For time window sizes 2 (0, 4, 6,…) and 3 (0, 3, 6,…), the union would be (0, 2, 3, 4, 6,…). **Problem** we only keep samples of the final compositional time window, breaking interpolation.
* Save samples in the coupling schemes, where the relative time frame is clear. **Problems:** Data duplication and mappings, actions, and exporters still need access to these samples.
* Save samples globally and save references to them from inside coupling schemes with relative time stamps. **Problems** Access and lifetime of samples will become tricky to get right. 

**Additional context**

A further upside of global time stamps is that this simplifies the implementation of data extrapolation in the future.

#1713

This could impact the work of @BenjaminRodenberg and @NiklasKotarsky

**Comment by BenjaminRodenberg** [comment]
Important clarification: This is a pure implementation detail. We do not want to change the user interface, meaning a user would still provide a `relativeReadTime` to `readData`. Internally we want to use a absolute, global time for time stamps due to the reasons mentioned above, but from the user perspective measuring time relative to the beginning of the current time *step* makes sense and fits into the overall design.
