### ISSUE TITLE
Data storage can be moved multiple times per time window to the next time window

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1730]
**Describe your setup**

preCICE Version: develop (> 2.5.0)

**Describe the problem**

At the end of a time window, the data storage is moved.
The end sample becomes the new start sample and the new end sample is extrapolated. Then old samples are discarded.

This is triggered in **each coupling scheme**. If different schemes read the same data, then this is done repeatedly.

Let f be the first and l be the last sample, then 2 coupling schemes using the same data results in the following samples when moving to a new time window:
`[f, … ,l] -> [l, e(f, … ,l)] -> [e(f, … ,l), e(l, e(f, … ,l)]`

This hasn't been noticed, as the extrapolation defaults to 0th order:
`[f, … ,l] -> [l, l] -> [l, l]`

Using 1st order will show this bug.

**Step To Reproduce**
1. Configure a data to be exchanged by 2 coupling schemes
2. Use an implicit coupling scheme with extrapolation order 1

**Expected behaviour**
Each data storage should be moved exactly once.

**Additional context**
#1723 would allow to handle this centrally inside the participant.

**Comment by BenjaminRodenberg** [comment]
Important comment here: The effect of such a "multiple times move" is not visible, if we only use constant extrapolation. Therefore, it is tricky to come up with corresponding test and there is no way to actually observe the problem without extrapolation (related #1731). Not sure whether I would consider this an actual bug or just a bad implementation that might cause trouble in the future, but we should definitely fix it.

**Comment by uekerman** [comment]
Couldn't we introduce a safeguard boolean that we could assert in the move function?
