### ISSUE TITLE
The future of extrapolation

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1731]
**Please describe the problem you are trying to solve.**

With current changes, extrapolation is becoming increasingly problematic to maintain (#1713) at a questionable practical benefit.
The second order extrapolation was very mystical before we dropped it (#1089 #1503), so we currently only support 1st order extrapolation. 

Due to the current refactoring, the configuration location for the extrapolation doesn't make sense any more. It should move to the `<data:...>` tag just like we did with the `waveform-degree` #1709.

A possible extension of the waveform interpolation would be to use extrapolation with explicit coupling. This is uncharted territory though and a possible future research topic for our waveform experts @BenjaminRodenberg and @NiklasKotarsky.

**Describe the solution you propose.**

* Remove the support for extrapolation
* Only reintroduce it as `<data:scalar name="d" extrapolation-order="n" />` once we conducted enough research on it.

**Comment by BenjaminRodenberg** [comment]
I can prepare a draft PR where I remove everything related to extrapolation.
