### ISSUE TITLE
Refactor B-Spline interpolation into a separate file

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1747]
**Please describe the problem you are trying to solve.**

We are currently using B-Spline interpolation in waveforms provided by Eigen.
This is implemented as part of the `time::Storage`.

The interface is clear though: `(timestamps, samples, timeToSample) -> sample`

We should extract this into a separate file, and test it.

**Additional context**

#1746

**Comment by BenjaminRodenberg** [comment]
Was already closed via https://github.com/precice/precice/pull/1771.
