### ISSUE TITLE
Implement error message for old serial RBF mapping when using a parallel participant

### ISSUE THREAD

**Issue by threimann** [precice/precice#175]
FSI with FASTEST/FEAP, error:

'Failed to set TLS value: Invalid argument'

See logs.

[fastest.out.txt](https://github.com/precice/precice/files/2519477/fastest.out.txt)
[feap.out.txt](https://github.com/precice/precice/files/2519479/feap.out.txt)
[precice_config.xml.txt](https://github.com/precice/precice/files/2519481/precice_config.xml.txt)

**Comment by uekerman** [comment]
Please use `petrbf` instead:
```
 <mapping:petrbf-thin-plate-splines  direction="read"  from="Structure_Nodes" to="Fluid_Nodes"     constraint="consistent"   timing="initial"/>
```
or with a function with local support, see in the [wiki](https://github.com/precice/precice/wiki/Mapping-Configuration#radial-basis-function-mapping)


It's actually an assertion:
```
fhp.gnu64.precice.mpi: src/mapping/RadialBasisFctMapping.hpp:329: void precice::mapping::RadialBasisFctMapping<RADIAL_BASIS_FUNCTION_T>::tagMeshFirstRound() [with RADIAL_BASIS_FUNCTION_T = precice::mapping::ThinPlateSplines]: Assertion `false' failed.
```
This is bad. Normally an error should appear. We should fix this.
