### ISSUE TITLE
Adaptive solver time steps emit preCICE assertions

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1751]
**Describe your setup**

I'm using a fixed time-window size and adaptive time-steps within one of the solvers. I'm pretty sure that the origin of the assertion is within the adapter (rounding issues), but it emits one of the following assertions:

I'm using a recent develop snapshot of preCICE: ef76221a3ea9d5b4ba52e4ca524905ba275cb23c

**Describe the problem**

The scenatio triggers certain (developer) assertions in preCICE. I think both of the following assertions are related and should be actual preCICE errors:

```bash
ASSERTION FAILED
Location:   void precice::cplscheme::BaseCouplingScheme::sendData(const PtrM2N&, const DataMap&, bool)
File:       /home/schneidd/precice/src/cplscheme/BaseCouplingScheme.cpp:130
Expression: math::equals(timesAscending(nTimeSteps - 1), time::Storage::WINDOW_END)
Rank:       0
Arguments:  
  0: timesAscending(nTimeSteps - 1) == 0.9999999999999898
  1: nTimeSteps == 3
```

or

```bash
ASSERTION FAILED
Location:   void precice::time::Storage::setSampleAtTime(double, precice::time::Sample)
File:       ~/precice/src/time/Storage.cpp:33
Expression: math::smaller(maxStoredNormalizedDt(), time)
Rank:       0
Arguments:  
  0: maxStoredNormalizedDt() == 1
  1: time == 0.5000000000000001
  2: "Trying to write sample with a time that is too small. Please use clear(), if you want to write new samples to the storage." == Trying to write sample with a time that is too small. Please use clear(), if you want to write new samples to the storage.
```

**Step To Reproduce**
Was created with the flow-over-heated-plate tutorial and the two OpenFOAM participants. Adapter version: tba

**Expected behaviour**
Hit a preCICE error instead of the exception.

**Comment by BenjaminRodenberg** [comment]
Yes. This should raise an error. I think this is again a good case where we would need a test for the "unhappy" execution path that leads to an error. Related to #280

**Comment by BenjaminRodenberg** [comment]
@NiklasKotarsky fyi: Assigned you here and linked to #1788 for a better overview.
