### ISSUE TITLE
Unable to write initial data to preCICE for macro-micro coupled scenarios

### ISSUE THREAD

**Issue by IshaanDesai** [precice/precice#1767]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 22.04_
preCICE STATE: https://github.com/precice/precice/commit/8393841e62a78e87db1067543e2da4cc265e55d5

Add the versions/commit hashes of further adapter and/or bindings.

Micro Manager: https://github.com/precice/micro-manager/commit/6dcbf68dcd83d3094d008af5d68d687ea3352de1

**Describe the problem**

Although the Micro Manager uses the Python API, the problem is not related to it and is hence described below in terms of the original C++ API.

The Micro Manager does not need a coupling mesh of its own, but just needs the vertex information of the macro-scale participant. Using `getMeshVertexIDsAndCoordinates()`, it gets the vertex IDs and coordinates of the macro-scale participant mesh. It then defines one micro simulation per vertex of this mesh. Then it checks if the micro simulation objects have a function called `initialize()` and if they do, then it calls this function to get the initial state. Then it attempts to write the initial state to preCICE by checking `requiresInitialData()` and then `initialize()`.

The problem is that the function `getMeshVertexIDsAndCoordinates()` cannot be run before `initialize()`. But without running it, the Micro Manager does not know how many micro simulations to create, and hence it cannot get their initial states.

This problem was not encountered before because the functions `initialize()` and `initializeData()` were separate. Back then the order of calling functions was:

1. `initialize()`
2. `getMeshVertexIDsAndCoordinates()`
3. `isWriteDataRequired()`
4. `writeData...`
5. `initializeData()`

**Step To Reproduce**

https://github.com/precice/micro-manager/actions/runs/5825484943/job/15797159769?pr=51

**Expected behaviour**

Currently I do not see a way that the Micro Manager can get the mesh information from the macro-scale participant and also give initial data of the micro simulations to preCICE. One solution is that we do not allow micro simulations to write initial data to preCICE, but I have to study how this would affect macro-micro simulations.

Opening the issue to discuss if I am looking over something rather obvious.

**Comment by davidscn** [comment]
From the preCICE side, this is essentially #1583

**Comment by IshaanDesai** [comment]
> From the preCICE side, this is essentially #1583

Did not see this issue, it is indeed exactly the same. I will add a wont fix label here and also close this. I think it is still good to have this as a closed issue for documentation on macro-micro coupled scenarios.

**Comment by davidscn** [comment]
>  I think it is still good to have this as a closed issue for documentation on macro-micro coupled scenarios.

You could also transfer the issue to the micro-manager repository, if you want.
