### ISSUE TITLE
Docs/XML reference for residual-relative-convergence-measure incorrect

### ISSUE THREAD

**Issue by valentinaschueller** [precice/precice#1768]
The [XML reference for `residual-relative-convergence-measure`](https://precice.org/configuration-xml-reference.html#residual-relative-convergence-measure-1) states that the residual of the current iteration is compared to the residual of the previous iteration. However, checking [the implementation of this convergence measure](https://github.com/precice/precice/blob/develop/src/cplscheme/impl/ResidualRelativeConvergenceMeasure.hpp#L58) reveals that the residual of the current iteration is compared to `_normFirstDiff`, which is only computed in the first iteration of a time window[^1].

I have not managed to find out where the documentation for this XML tag is located, but the formula should be updated to reflect what is actually implemented: i.e., we divide by `\| H(x^0) - x^0 \|`, not `\| H(x^{k-1}) - x^{k-1} \|`.

[^1]: a new measurement series is created every time window, I checked this in a different part of the code

**Comment by davidscn** [comment]
> I have not managed to find out where the documentation for this XML tag is located

https://github.com/precice/precice/blob/develop/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L542-L547
