### ISSUE TITLE
Export mapping to file for re-runs

### ISSUE THREAD

**Issue by msuaeronautics13** [precice/precice#177]
Right now, initialization of nearest-projection mapping is slow - see #132 . It might be useful to give users the option to write out the mapping matrices to a file, and allow preCICE to reload such mapping for subsequent runs on the same mesh. This would be a stopgap for while the issues with nearest-projection are being worked out, but could still be useful otherwise.

**Comment by floli** [comment]
A possible remedy for that is also in #99, which is active right now. Let's see, if this caching mechanism is still needed then. #99 / #132 will definitely be implemented quicker than this issue. See also PR #156 for the curious ones.

**Comment by fsimonis** [comment]
@floli @msuaeronautics13 I hope the new implementation is fast enough so that we can close this issue!

**Comment by floli** [comment]
I close it, please comment if there are still performance problems with the **initialization of NP mapping**.
