### ISSUE TITLE
Remove deprecated configuration features

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1772]
**Please describe the problem you are trying to solve.**

It's time to remove deprecated configuration features from:

* exporters (legacy `vtk` in parallel) and the `normals` attribute
* m2n / intra-communication (old `master` tag and some `mpi`-related aliases #1650)
* there may be more scattered around the code base

**Comment by Durganshu** [comment]
Deprecated `normal` attributes seem to be already removed from the existing code base.

**Comment by fsimonis** [comment]
@Durganshu also found old filter attributes, which still use the master & slave terminology.
