### ISSUE TITLE
End of time window assertion fails when a large number of substeps are used

### ISSUE THREAD

**Issue by NiklasKotarsky** [precice/precice#1776]
**Describe your setup**

Operating system (e.g. Linux distribution and version): Ubuntu Ubuntu 22.10
preCICE Version: develop f7289a6

**Describe the problem**
If one uses more than 500 equally spaced substeps in the time window then the assertion `PRECICE_ASSERT(math::equals(timesAscending(nTimeSteps - 1), time::Storage::WINDOW_END))` and `PRECICE_ASSERT(math::equals(data->stamples().back().timestamp, time::Storage::WINDOW_END))` are triggered by the numerical accuracy inside BaseCouplingScheme.cpp and SerializedStamples.cpp. 

**Step To Reproduce**
1.The code to reproduce the error is in the repository
 https://github.com/NiklasKotarsky/precice/tree/Err-assertion-end-of-timeWindow
2. The failing test: Integration/Serial/Time/Implicit/SerialCoupling/ManySubstepsReadMapping

**Expected behaviour**
The assertion should not be triggered from only using more than 500 substeps.

**Additional context**
Attach relevant logs and files to this issue.
Format your text (and especially any output/error messages) (see the [GitHub Markdown guide](https://guides.github.com/features/mastering-markdown/)

**Comment by NiklasKotarsky** [comment]
Yes, it seems to me that it is the same root cause. I solved it on the solver side side by adding `currentDt = std::abs(dt-maxDt)<1e-12 ? maxDt : dt;`. Ideally I should be able to use a tolerance of about 1e-14 here or numerical accuracy. The root cause of the issue might be mismatched tolerances in PreCICE. As I understand it in baseCouplingScheme.cpp the end of a time window is calculated with an accuracy of about 1e-10 in line 436 with `const bool isAtWindowEnd = math::equals(getNormalizedWindowTime(), time::Storage::WINDOW_END, _eps);`. The end of the time window is later checked to an accuracy of 1e-14 in both storage.cpp and data.cpp with `PRECICE_ASSERT(math::equals(timesAscending(nTimeSteps - 1), time::Storage::WINDOW_END))`.

**Comment by uekerman** [comment]
also connected to #1712

**Comment by BenjaminRodenberg** [comment]
@NiklasKotarsky fyi: I assigned you here and linked this issue to #1788. I hope that's correct and ok for you.
