### ISSUE TITLE
PoU RBF mapping writes exports without being configured to do so

### ISSUE THREAD

**Issue by MakisH** [precice/precice#1778]
Running the perpendicular-flap tutorial with the latest develop, I get this stray file:

```
perpendicular-flap/fluid-openfoam/exports/pou-centers-Solid-Mesh.vtu
```

I have the feeling this was not intended to be here, as no participant defines an `<export: >` tag:

```xml
  <participant name="Fluid">
    <provide-mesh name="Fluid-Mesh" />
    <receive-mesh name="Solid-Mesh" from="Solid" />
    <write-data name="Force" mesh="Fluid-Mesh" />
    <read-data name="Displacement" mesh="Fluid-Mesh" />
    <mapping:rbf direction="write" from="Fluid-Mesh" to="Solid-Mesh" constraint="conservative">
      <basis-function:compact-polynomial-c6 support-radius="1." />
    </mapping:rbf>
    <mapping:rbf direction="read" from="Solid-Mesh" to="Fluid-Mesh" constraint="consistent">
      <basis-function:compact-polynomial-c6 support-radius="1." />
    </mapping:rbf>
  </participant>

  <participant name="Solid">
    <provide-mesh name="Solid-Mesh" />
    <write-data name="Displacement" mesh="Solid-Mesh" />
    <read-data name="Force" mesh="Solid-Mesh" />
    <watch-point mesh="Solid-Mesh" name="Flap-Tip" coordinate="0.0;1" />
  </participant>
```

**Comment by davidscn** [comment]
This is a current debug feature of the method and kept intentionally. It is only generated in debug mode, i.e., shouldn't affect users.

**Comment by fsimonis** [comment]
> This is a current debug feature of the method and kept intentionally. It is only generated in debug mode, i.e., shouldn't affect users.

Not sure if this is a reasonable expectation. If these exports are useful to debug PoU in the wild, then they should be configurable and usable in release builds. If not, then some `ifdefs` and a CMake option would make sense.

Depending on how #1655 goes, we may need to add mapping-specific exports at some point anyway. So, this could some kind of advanced export.

**Comment by davidscn** [comment]
> If these exports are useful to debug PoU in the wild, then they should be configurable and usable in release builds.

Yes, they are useful, but not for users, mostly for myself. Accessing them in release builds is not really necessary in my opinion and I would not want to expose these exports to the config. In the long run, they should be removed anyway.

We could make it a more hidden CMake option, of course. The debug build (which is anyway only for devs) is right now the CMake option. I can also comment out the code and only use it privately. No strong opinion here. I would agree to almost all options, as long as it won't be and lead to breaking changes now or in the future.

**Comment by uekerman** [comment]
I think we should hide it a little bit better.
We often recommended users to build in Debug mode as long as they develop adapters. I would say "comment out" or use a CMake option. "comment out" is also what we do for the [advanced QN exports](https://precice.org/running-output-files.html#precice-accelerationinfolog).

**Comment by davidscn** [comment]
> I would say "comment out" or use a CMake option. "comment out" is also what we do for the [advanced QN exports](https://precice.org/running-output-files.html#precice-accelerationinfolog).

I went now for this, although there is a high chance that the 'dead code' won't compile in the near future anymore.
