### ISSUE TITLE
precice.hpp is not included to 2.5.0 source code

### ISSUE THREAD

**Issue by TEFEdotCC** [precice/precice#1817]
The header file
src/precice/precice.hpp
is missing in the 2.5.0.tar.gz or zip file.

Building e.g. openfoam-adapter fails.

**Comment by davidscn** [comment]
The header file `precice/precice.hpp` was introduced in the most recent preCICE development targeting version 3.0, i.e., you are probably trying to build the latest state of the OpenFOAM adapter in the `develop` branch with preCICE version 2.5, which is incompatible. 

- If you want to use the latest state of the adapter, you have to use the develop version of preCICE. However, your current precice-config.xml file most likely won't be compatible with the introduced breaking changes.
- If you want to use preCICE version 2.5.0, you have to use [the latest release](https://github.com/precice/openfoam-adapter/releases) archive of the adapter (recommended).
