### ISSUE TITLE
AUR package for Arch Linux and Manjaro fails.

### ISSUE THREAD

**Issue by ng0177** [precice/precice#1827]
The current [AUR package](https://aur.archlinux.org/packages/precice) does not install in Arch Linux due to multiple errors and dependencies.

**Comment by fsimonis** [comment]
Hi, bug reports regarding AUR packages should be discussed with maintainers.

That aside, do you have `petsc-complex` installed? preCICE is only compatible with the normal/real version of PETSc (the normal `petsc` package).

**Comment by ng0177** [comment]
Thank you. Actually reading the comments, other have noted the issue, too. Then, preCICE installs fine!

**Comment by floli** [comment]
I (the maintainer of https://aur.archlinux.org/packages/precice) have just added a conflicts declaration with `petsc-complex`.
