### ISSUE TITLE
Add new mixed convergence measure 

### ISSUE THREAD

**Issue by Fujikawas** [precice/precice#1833]
**Please describe the problem you are trying to solve.**
According to the discussion for https://precice.discourse.group/t/multiple-convergence-criteria/1591, we offer following 
- absolute convergence measure
- relative convergence measure 
- relative iterative convergence measure

for the coupling interface, while there exists the need that a mixed absolute-or-relative-convergence-measure could be employed for each participant.

**Describe the solution you propose.**
We could add this mixed convergence criteria to support more users.

**Describe alternatives you've considered**
Or we could create a free-combined convergence measure, which does not limit the number or types of participants, data sets or Boolean functions. The existing convergence measures could be basic elements for this measure.

**Comment by uekerman** [comment]
Configuration could look like this?

```xml
<absolute-or-relative-convergence-measure atol="{float}" rtol="{float}" 
                                          data="{string}" mesh="{string}" 
                                          strict="0" suffices="0"/>
```

**Comment by Fujikawas** [comment]
Since we would use `absolute-convergence-measure` and other existing ones as components for the mixed convergence measure, the form imo might be
```xml
<absolute-convergence-measure limit="{float}" data="{string}" mesh="{string}" name="A"/>
<relative-convergence-measure limit="{float}" data="{string}" mesh="{string}" name="R1"/>
<relative-convergence-measure limit="{float}" data="{string}" mesh="{string}" name="R2"/>
<combine-convergence-measures relationship="A OR R1 AND R2">
``` 
This differs from the present design a bit though (`name` added and `strict` & `suffices` removed). Reuse large part of the current checking process is still possible :)

**Comment by uekerman** [comment]
The logical operators (`combine`) would be very complex to implement. I would not advise to do that right now.
And I think, with this new addition (`absolute-or-relative-convergence-measure`), we cover all meaningful cases pretty well already.

**Comment by fsimonis** [comment]
> Would like to know from where the difficulty mainly comes :)

I build something similar in my master's thesis using Boost.spirit, so I can jump in here.

Even if you use something like [Boost.spirit](https://www.boost.org/doc/libs/1_83_0/libs/spirit/doc/html/spirit/introduction.html) to handle the parsing for you, there are a lot of additional things that need to be taken care of:
Case sensitivity, operator aliases (`OR`, `|`, `||`), operator precedence, grouping, correctly handling unary operations such as `not`, and name sanitization.
Then after you build your abstract syntax tree, it needs to be combined with the configured convergence measures to account for undefined and unused names, as well as evaluation, and likely visualization.
All of this needs to be tested and one needs to come up with understandable error messages.

It's not super complex, but it's a lot of work.

It may be a good future addition though, so I would recommend you to open a separate issue for that.

Regarding the mixed convergence measure, it's a quick solution to copy and extend an existing convergence measure.
