### ISSUE TITLE
Suggestion: add the ability to use long double instead of double

### ISSUE THREAD

**Issue by davidsblom** [precice/precice#19]
Currently, when I use a long double instead of double values, the solver does not compile. 
Is it possible to compile precice in floating precision, double precision or long double precision?

**Comment by floli** [comment]
This is currently not possible and I'm not very eager to add since. My departements other project has this support (at least compile for float and double, don't know about long double) and it's a hassle to maintain.

What is your rationale for that? Do you need the precision of long double? Do you expect memory or performance gains from using float?

**Comment by davidsblom** [comment]
float is something which I don't need, but I figured that if you would support double and long double, then floating precision makes sense as well.

I'm currently running into the limit of double precision for the higher order time integration schemes. I observe this already for a fifth order method. I guess this is only needed for scientists, but that's also the focus of precice is my understanding.

**Comment by davidsblom** [comment]
I was just wondering whether you know why it's such a hassle to maintain this for your departements other project. Because of dependencies which force you to use doubles or problems similar to this?

**Comment by floli** [comment]
I've asked today what are the issues with maintaining different floating point types and it seems to be that they support all versions to be co-installable, so not related to us.

Still, I think long double will bring us performance issues (the CPUs are designet for handling double FP, SSE can't handle long double afaik), compatiblity issues (we have some python bindings, where the FP type needs to be double) and portability issues.

PETSc will also need recompilation, we maye won't be feasible on the HPC systems.

**Comment by davidsblom** [comment]
I agree that a long double will perform not as good as a double implementation, and cause some problems.
