### ISSUE TITLE
Don't allow calling `getMaxTimeWindowSize` and `readData` after last `advance`

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1904]
**Please describe the problem you are trying to solve.**

Calling `readData` or `getMaxTimeWindowSize` after the last `advance` call (i.e. when `isCouplingOngoing` returns `false`) does not make sense, but is currently allowed.

**Describe the solution you propose.**

Add security checks to disallow calling these API functions in the wrong context.

**Describe alternatives you've considered**

Leave things as they are. But this also requires us to be able to deal with this situation and we cannot make certain assumptions (e.g. `getMaxTimeWindowSize` *always* returns a `dt > 0`)

**Additional context**

Tests in #1867 failed due to `PRECICE_ASSERT(math::greater(nextTimeStepSize, 0.0), nextTimeStepSize)` in `double ParticipantImpl::getMaxTimeStepSize()`. This could be fixed by rearranging the API calls in the tests such that there is no `getMaxTimeStepSize` call after `advance`.

**Comment by uekerman** [comment]
I agree on `getMaxTimeWindowSize`. Not sure about `readData` yet (what happens to second participant in a serial coupling scheme?)

**Comment by BenjaminRodenberg** [comment]
I can take this over. Proposed solution:

* allow to call `readData` and `getMaxTimeWindowSize` after the last `advance`
* if `getMaxTimeWindowSize` is called after the last `advance`, it will always return `preciceDt = 0`
* if `readData` is called after the last `advance`, it will only accept `relativeReadTime = 0` a `relativeReadTime > 0` will trigger an error.
