### ISSUE TITLE
Port ConfigParser to string_view

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1926]
**Please describe the problem you are trying to solve.**

The ConfigParser bridges the call-back-based C-library libxml2 to the C++ XMLTag and XMLAttribute of preCICE.

This requires a lot of non-owning C-string to `std::string` transformations.
Performance aside, this is difficult to read and code analysers complain.

**Describe the solution you propose.**

Using `std::string_view` for everything non-owning would be way easier on the eye.
Less casting, less noise, fewer copies.

**Describe alternatives you've considered**
Ignore the linters

**Comment by Durganshu** [comment]
I'm picking up on this issue.

**Comment by fsimonis** [comment]
@Durganshu be aware that this is not simple replace job. It's about figuring out which components own data and which ones only read it.

This is especially important on the interface between libxml2 and the xml::ConfigParser::CTag generation.

**Comment by Durganshu** [comment]
Thanks for the heads up!

**Comment by fsimonis** [comment]
This has been largely done in #1978
