### ISSUE TITLE
Name in LogConfiguration.cpp

### ISSUE THREAD

**Issue by 3rav** [precice/precice#193]
Hi,

In LogConfiguration.cpp is #include "versions.hpp" but file is named versions.hpp.in (from precice-1.3.0.zip).

**Comment by floli** [comment]
`versions.hpp` will be generated from `versions.hpp.in` by the build system (CMake or scons). Do you experience any related problems?

**Comment by 3rav** [comment]
Hi,
If I used cmake I have this error (with scons everything is OK):

```
C:/msys64/usr/local/precice-1.3.0/src/logging/LogConfiguration.cpp:16:10: fatal error: versions.hpp: No such file or directory
 #include "versions.hpp"
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/precice.dir/build.make:804: CMakeFiles/precice.dir/src/logging/LogConfiguration.cpp.obj] Błąd 1
```

**Comment by floli** [comment]
What directory is your build dir, i.e. where did you execute cmake and make?
Inside the build dir, `versions.hpp` should be generated, is it there?

**Comment by fsimonis** [comment]
@3rav CMake reads the file `version.hpp.in`, configures it, and writes it to `version.hpp` in the project's binary directory,  It then adds the projects binary directory to the include paths, so that the compiler finds it.
The magic happens here:
https://github.com/precice/precice/blob/3a27a4117937d2b979fceacf045d8edab2b580a5/CMakeLists.txt#L91-L92

Coming to your problem:

* If you have white-spaces in your path, you could try to quote the variable by changing the second line to:`include_directories("${PROJECT_BINARY_DIR}")`
* Could you send us the compiler invocation to see if there is the correct flag set? Using make you can execute a dry-run using `make -n`. The rather verbose output contains the invocations in question.

**Comment by 3rav** [comment]
Hi,

My directory is: /usr/local/precice-1.3.0

Form cmake:
```
$ cmake -G "MSYS Makefiles" -DCMAKE_CXX_STANDARD_LIBRARIES=-lws2_32 -DCMAKE_BUILD_TYPE=release
-- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build configuration: release
-- Special platform settings: none
-- MPI support disabled
-- PETSc support disabled
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   filesystem
--   log
--   log_setup
--   program_options
--   signals
--   system
--   thread
--   unit_test_framework
--   date_time
--   regex
--   chrono
--   atomic
-- Found Eigen3: C:/msys64/mingw64/include/eigen3 (Required is at least version "3.2")
-- Found LibXml2: C:/msys64/mingw64/lib/libxml2.dll.a (found version "2.9.8")
-- Python support disabled
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/usr/local/precice-1.3.0
```

From make -n see attachment.
[make -n.txt](https://github.com/precice/precice/files/2599924/make.-n.txt)

**Comment by fsimonis** [comment]
Hi there,

this is quite an interesting case as you are building in-source meaning that `PROJECT_BINARY_DIR` and `PROJECT_SOURCE_DIR` point to the same location.
CMake is supposed to including the paths `.../precice-1.3.0/src` and `.../precice-1.3.0/` but it doesn't include the latter.

We are configuring the version file to the `binary` dir, but we really should configure it to `binary/src` dir. I'll fix that in the develop branch.

So there are three options for you:
### 1) Build out of source
`cd precice-1.3.0; mkdir build; cd build; cmake ..`
### 2) Adjust the CMakeLists.txt
Change the following two lines:
https://github.com/precice/precice/blob/3a27a4117937d2b979fceacf045d8edab2b580a5/CMakeLists.txt#L91-L92 to
```
 configure_file("${PROJECT_SOURCE_DIR}/src/versions.hpp.in" "${PROJECT_BINARY_DIR}/src/versions.hpp" @ONLY) 
 include_directories(${PROJECT_BINARY_DIR}/src) 
```
### 3) Copy the versions header
Copy the configured file from `.../precice-1.3.0/versions.hpp` to `.../precice-1.3.0/src/versions.hpp`

Hope that helps!
