### ISSUE TITLE
`precice-profiling analyze` is not deterministic

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1951]
**Describe the problem**
Using the command `precice-profiling analyze` leads to data frames and also console print outs, which appear to be random with respect to the order of rows. This is particularly a problem when processing the data further and use in version control.

**Step To Reproduce**
1. Pick a profiling.json file
2. run `precice-profiling analyze <arg>` multiple times and observe the arbitrary arrangement of rows

**Expected behaviour**
Deterministic output

**Comment by davidscn** [comment]
Easy fix would be to sort the dataframe here

https://github.com/precice/precice/blob/034f96ba8ee6907afa37b8134290e8373eb56224/tools/profiling/precice-profiling#L574-L580

using `joined.sort("eid")`

I think sorting according to the event ID makes sense, as it also groups events together, which appear in the code together (potentially hierarchically).

**Comment by fsimonis** [comment]
Pushed a fix for this. This is not really a bug though. It's more of an inconvenience :wink:
