### ISSUE TITLE
Fluidx3d adapter for fast Cfd with gpu by openCL 

### ISSUE THREAD

**Issue by stefano2734** [precice/precice#1955]
**Please describe the problem you are trying to solve.**
A clear and concise description of what the problem is.

New extreme fast open source  software fluidx3d with use of OpenCL. 
https://github.com/ProjectPhysX/FluidX3D

Nvidia, Intel,  AMD and many other firms hardware at Linux and windows are here available for accelerated usage.

**Describe the solution you propose.**

adapter for fluidx3d for coupling  with OpenFoam, calculix and others.
developer of fluidx3d is Dr. Moritz Lehmann.

**Describe alternatives you've considered**

**Additional context**
See examples 
https://youtu.be/-MkRBeQkLk8?si=zT034MiBuAYAXiqw

**Comment by fsimonis** [comment]
Issues in the preCICE repository are primarily about the preCICE library itself.

The place to discuss topics regarding the ecosystem, including adapters and projects, is our [Discourse forum](https://precice.discourse.group/). If you are working on an adapter, it also is the right place to advertise it.
