### ISSUE TITLE
Crash when reading data at time window end in serial second

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1981]
**Describe your setup**

Operating system (e.g. Linux distribution and version): -
preCICE Version: (3.0.0)+develop e4298f4d269ba44783d2480754ff52842782f596

**Describe the problem**
In a serial scheme, the participant running as second crashes in time window at t=256.1 of size 0.1.
It attempts to read data at the end of the time window using:

```
readData(..., p.getMaxTimeStepSize(), ...)
```

This fails internally while attempting to interpolate read-data using a bspline as the requested time doesn't match a received stample and is considered out of range.

Reason:

* There are multiple samples received from first participant, who is subcycling with dt=2.5e-5  
* So, the bspline doesnt't use constant extrapolation
* Looking up existing stamples in `Storage::findTimeID()`, there is no match, as the timestamp of the last stample received from the first participant has a time stamp is not approx the requested time due to accumulated error in the time stamps.
* The bspline then attempts to interpolate. The requested time gets normalised to range of stamples `[256.1, 256.2]`, which results in `1.0000000000005684`.
* This is considered outside `[0;1]` respecting our tolerance, leading to a crash.

The assertion looks as follows

```
precice::advance(0.1), maximumPreciceTimestepSize_: 0.1
PreCICE volume coupling, timestep 2561, t=256.1
ASSERTION FAILED
Location:   Eigen::VectorXd precice::math::Bspline::interpolateAt(double) const
File:       /.../src/math/Bspline.cpp:69
Expression: math::smallerEquals(tRelative, 1.0)
Rank:       0
Arguments:
  0: "t is after the last sample!" == t is after the last sample!
  1: tRelative == 1.0000000000005684
  2: 1.0 == 1
  3: _tsMax == 256.2
```

**Expected behaviour**

Return the end sample.

**Additional context**

Related to #1939

**Comment by BenjaminRodenberg** [comment]
A quick summary of our debugging session yesterday:

We can reproduce the issue with the solverdummy. Changing the `precice-config.xml` in the following way is sufficient:

```diff
diff --git a/examples/solverdummies/precice-config.xml b/examples/solverdummies/precice-config.xml
index 4c0dd0c83..e055fb932 100644
--- a/examples/solverdummies/precice-config.xml
+++ b/examples/solverdummies/precice-config.xml
@@ -47,13 +47,11 @@
 
   <m2n:sockets acceptor="SolverOne" connector="SolverTwo" />
 
-  <coupling-scheme:serial-implicit>
+  <coupling-scheme:serial-explicit>
     <participants first="SolverOne" second="SolverTwo" />
-    <max-time-windows value="2" />
-    <time-window-size value="1.0" />
-    <min-iterations value="2" />
-    <max-iterations value="2" />
+    <max-time value="1000" />
+    <time-window-size value="0.1" />
     <exchange data="Data-One" mesh="SolverOne-Mesh" from="SolverOne" to="SolverTwo" />
     <exchange data="Data-Two" mesh="SolverOne-Mesh" from="SolverTwo" to="SolverOne" />
-  </coupling-scheme:serial-implicit>
+  </coupling-scheme:serial-explicit>
 </precice-configuration>
```

This triggers the problem from above:

```
...
preCICE: iteration: 1, time-window: 2562, time: 256.1 of 1000, time-window-size: 0.1, max-time-step-size: 0.1, ongoing: yes, time-window-complete: yes, 
DUMMY: Advancing in time
ASSERTION FAILED
Location:   Eigen::VectorXd precice::math::Bspline::interpolateAt(double, double) const
File:       /home/benjamin/Programming/precice/src/math/Bspline.cpp:70
Expression: math::smallerEquals(tRelative, 1.0)
Rank:       0
Arguments:  
  0: "t is after the last sample!" == t is after the last sample!
  1: tRelative == 1.000000000000341
  2: 1.0 == 1
  3: _tsMax == 256.2
  4: start == 256.1
  5: rel == 0.1

Stacktrace:
 0# 0x00007F5A98E743F3 in /usr/local/lib/libprecice.so.3
 1# 0x00007F5A98DB3611 in /usr/local/lib/libprecice.so.3
...
```

The original reason is that `time + preciceDt` or `256.1 + 0.1` does not result in `256.2`, but in a number slightly bigger leading to problems inside `BSpline.cpp`. If I use the version provided with #1982 everything works in this setup.

**Comment by testmygittt** [comment]
Hi sir, I want to do FSI simulation of a patient specific aorta. I want to
couple OPENFOAM and FENICS.
I have learned and run all the tutorial programs of fenics.
But I am facing some problem in coupling fenics with openfoam. So, Can you
help me??

**Comment by MakisH** [comment]
@testmygittt for user-related questions, please ask in the preCICE forum, adding more details about your case and the errors you are facing. We use GitHub issues to track specific and confirmed code-related bugs.
