### ISSUE TITLE
Different observable behaviour since time refactoring in elastic-tube-1d

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1984]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Arch_
preCICE Version:
* assumed good v3.0.0
* assumed bad 5ec22864011ded681b232e8597b34561be01abdd
* first bad via bisect 4ffc8964421e11c611859fc6947c95b280fed5a5

tutorials: da7a1494f5c36b4ef509daf2a43bfee42fb32d9d (current develop)
pyprecice: 3.0.0.0 from PyPi

**Describe the problem**

The elastic-tube-1d tutorial with solvers `solid-python` and `fluid-cpp` produces different results since the release of v3.0.0.
I added `<export:vtk directory="../precice-exports" />`

As a baseline/good commit I used v3.0.0 and I saved the produced
* iterations.log of fluid
* precice-exports

I then bisected checking the above against the output of runs based on the precice commits, starting at the HEAD of develop.

Result: 4ffc8964421e11c611859fc6947c95b280fed5a5 is the first bad commit.

The change of time handling improves the accuracy of how we deal with time in preCICE and introduced a bunch of time-related tests that haven't been feasible before.
This fixed a desync between Participant and Coupling Schemes and also unveiled the further problem #1981.

**Step To Reproduce**

preCICE
```
cmake --preset=production-audit -DBUILD_TESTING=OFF .
make -j$(nproc) -C build
```
Tutorial:

Add exporters to config (I found that comparing the iteration logs is sufficient for this issue).
```
cd elastic-tube-1d
rm -r fluid-cpp/build
python -m venv solid-python/venv
solid-python/venv/bin/pip install pyprecice
```

To run:
```
# in fluid-cpp
./run.sh
# in solid-python
. venv/bin/activate
./run.sh
```

To test:

```
# in fluid-cpp
diff precice-Fluid-iterations.log precice-Fluid-iterations.log.baseline
# additionally
pipx install "fieldcompare[all]"
fieldcompare dir ../precice-exports ../precice-exports-baseline -rtols 3e-7
```

**Expected behaviour**

The output and iterations should be the same for v3.0.0 up to the current develop.

**Additional context**

Iteration logs:
* [v3.0.0-iterations.log](https://github.com/precice/precice/files/14790811/v3.0.0-iterations.log)
* [bad-iterations.log](https://github.com/precice/precice/files/14790809/bad-iterations.log)

Watchpoint middle:
* [v3.0.0-watchpoint-Middle.log](https://github.com/precice/precice/files/14790810/v3.0.0-watchpoint-Middle.log)
* [bad-watchpoint-Middle.log](https://github.com/precice/precice/files/14790807/bad-watchpoint-Middle.log)

**Comment by fsimonis** [comment]
It is possible that this is due to the inverse of #1981.

In 1981, `getMaxTimeStepSize()` returns a value which overshoots the end of the time window by more than our tolerance, leading to a crash.
What we could observe here is `getMaxTimeStepSize()` undershooting the end of the time window by more than our tolerance.

This results in preCICE not returning the sample at the end of the time window, but interpolating using the BSpline instead.
As substeps are disabled, this would use linear interpolation.

**Comment by BenjaminRodenberg** [comment]
> The elastic-tube-1d tutorial with solvers solid-python and fluid-cpp produces different results since the release of v3.0.0.

Do you also observe this kind of behavior, if you do not mix the programming languages? I think the most simple one would be `fluid-cpp` + `solid-cpp`. If something is wrong with the time stepping, I would assume that all flavors of the case show the same kind of regression.

**Comment by uekerman** [comment]
> I found that comparing the iteration logs is sufficient for this issue

The two log files above are identical. Are they or did anything go wrong when uploading?

**Comment by fsimonis** [comment]
@uekerman reuploaded the iteration logs and added the Watchpoints for good measure.

**Comment by fsimonis** [comment]
I ran v3.0.0/good and the bad commit again with both cpp solvers.
These are the logs of **solid-cpp**:

[good-Solid-iterations.log](https://github.com/precice/precice/files/14791002/good-Solid-iterations.log)
[good-Solid-convergence.log](https://github.com/precice/precice/files/14791003/good-Solid-convergence.log)
[good-Fluid-watchpoint-Middle.log](https://github.com/precice/precice/files/14791004/good-Fluid-watchpoint-Middle.log)
[bad-Solid-iterations.log](https://github.com/precice/precice/files/14791005/bad-Solid-iterations.log)
[bad-Solid-convergence.log](https://github.com/precice/precice/files/14791006/bad-Solid-convergence.log)
[bad-Fluid-watchpoint-Middle.log](https://github.com/precice/precice/files/14791007/bad-Fluid-watchpoint-Middle.log)

Differences remain.

**Comment by uekerman** [comment]
My best guess is that the differences come from different `dt`s returned to the solver and used here:

https://github.com/precice/tutorials/blob/da7a1494f5c36b4ef509daf2a43bfee42fb32d9d/elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp#L97-L110

BUT: I think that we are doing now is better than we what we had before.

**Comment by fsimonis** [comment]
So, the return value of `getTimeStepSize()` is so clean now, that we can see different behaviour in the `elastic-tube-1d` tutorial and even lower iteration numbers.

@MakisH I wouldn't be surprised if this shows up in other tutorials too.

I'll close this issue.

**Comment by BenjaminRodenberg** [comment]
What's a bit surprising: That even the number of iterations change with such a little difference in the `dt`.

Possible explanation: The tiny fluctuations in the `dt` also result in tiny fluctuations in the result as this `dt` is used as the time step size for the solver. This finally influences number of required quasi-Newton iterations (again, only a little bit but it is observable).

**Comment by uekerman** [comment]
and the number of iterations is a very ill-conditioned problem.
