### ISSUE TITLE
Some parallel Quasi-Newton test run in serial

### ISSUE THREAD

**Issue by NiklasKotarsky** [precice/precice#2008]
There are some tests in the folder test/quasi-newton/parallel that run in serial like TestQN1/TestQN3. From what I can understand these tests should be identical their counterpart in the serial quasi-newton tests. Chaining the config file such that they run in parallel results in failing tests see branch https://github.com/NiklasKotarsky/precice/tree/error-chainging-tag-to-parallel.

**Comment by NiklasKotarsky** [comment]
Thanks for the clarification and sorry for the confusion. I think that I got confused by that the only indication of the parallelism is given by number of ranks in the boost Precice test statement. The only reasonable idea I can think of is to add some kind comment in the cpp files clarifying this, which I might add in the future. Since this issue is quite niche and mostly a misunderstanding on my part I will close it.

**Comment by fsimonis** [comment]
No worries :smiley:
