### ISSUE TITLE
Release docker images have only root user

### ISSUE THREAD

**Issue by davidscn** [precice/precice#2031]
**Please describe the problem you are trying to solve.**
I would like to make use of the available docker images provided by preCICE. However, they only contain a user with root privileges. It would be useful to have by default a PRECICE_USER (similar to our CI) images.

This would greatly enhance the user-experience when using MPI within the container.

**Describe the solution you propose.**
Provide a PRECICE_USER

Edit: The predecessor image (develop:latest) had this user.

**Comment by fsimonis** [comment]
This was an intentional decision after the long discussion regarding image inconsistencies https://github.com/precice/precice/issues/1947

The nightly release is a release image of the develop version.
A release image is stock Ubuntu + preCICE Debian package without further modifications.

If you want to run MPI as root, which is highly discouraged even inside docker containers, then you can use `--allow-run-as-root` or set the following ENV:

```bash
export OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
```

[OpenMPI docs](https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man1/mpirun.1.html#running-as-root)

I'll close this as won't fix.

**Comment by davidscn** [comment]
> This was an intentional decision after the long discussion regarding image inconsistencies https://github.com/precice/precice/issues/1947

Doesn't seem to contain any explanation.

> If you want to run MPI as root, which is highly discouraged even inside docker containers, then you can use --allow-run-as-root or set the following ENV:

That's highly discouraged, why doing it then.

>  A release image is stock Ubuntu + preCICE Debian package without further modifications.

It's good practice to add a user. This practice enhances the security of the container by limiting the potential impact of a security breach (Principle of Least Privilege). From the usability perspective, having a non-root user carries an indispensable value. So what's the reason to not have it?

> I'll close this as won't fix.

Why?

**Comment by fsimonis** [comment]
> Doesn't seem to contain any explanation.

The main discussion was very chaotic and happened in https://github.com/precice/python-bindings/issues/191. I created issues based on that and linked them.

> That's highly discouraged, why doing it then.

MPI is not supposed to run as root, yet the default user for every docker image is root.
This is conflict that the user of the needs to solve when trying to run things with mpi in general.

> It's good practice to add a user.

It's good practice, but its' not standard.

The purpose of these images is to provide a consistent Ubuntu system with a preCICE installation to use or test. The expectation should be `Ubuntu with preCICE`. Everything that diverges from the `ubuntu` image can, will, and has lead to surprises.

The problem on how to run solvers is not the concern of these images. Just like it isn't the concern of the `ubuntu` image on how to run packaged programs like gmesh using MPI.

**Comment by davidscn** [comment]
> It's good practice, but its' not standard.

Well then why not following good practices?

> The purpose of these images is to provide a consistent Ubuntu system with a preCICE installation to use or test.

To use or test without a user will most likely require MPI as root. Running MPI as root "can result in catastrophic damage to the OS file system, leaving your system in an unusable state.". 

> Everything that diverges from the ubuntu image can, will, and has lead to surprises.

I don't get it: Having the user doesn't change anything from the image itself, apart from the fact that you can execute commands as non-root user. So by adding this, which surprise do you have in mind?

> The problem on how to run solvers is not the concern of these images.

Maybe it should be, because that's what preCICE is for.

**Comment by fsimonis** [comment]
> Maybe it should be, because that's what preCICE is for.

It's not the concern of the release images to run things.
They are just there to make preCICE easier to use consistently without needing to fetch and install the preCICE Debian package from the github release, or compiling a develop version.

> I don't get it: Having the user doesn't change anything from the image itself, apart from the fact that you can execute commands as non-root user. So by adding this, which surprise do you have in mind?

Creating a user isn't straightforward as it requires making many assumptions:

* What is the user called?
* Does the user need a password?
* Does the user need a home directory?
* What login shell should it use?
* What's the primary and secondary groups it should be in?
* Should sudo be installed, and should it be password-less?
* Should Dockerfile commands run in the login shell of this user? (Requires extra Docker magic)

At the end of the day, this is something a user of the image needs to know. preCICE cannot know the needs of the user.

Surprises arise when these release images get out of sync again, which is easily possible as they are based on different Dockerfiles.

If you need to add a user, you can easily do it when you extend the image for your case / CI [doing so](https://github.com/precice/ci-images/blob/master/ci-ubuntu-2404.dockerfile#L5).

**Comment by davidscn** [comment]
> It's not the concern of the release images to run things.

How does this fit to "The purpose of these images is to provide a consistent Ubuntu system with a preCICE installation to use or test."

> They are just there to make preCICE easier to use consistently without needing to fetch and install the preCICE Debian package from the github release, or compiling a develop version.

Exactly, and after compiling one would want to test it.

> Creating a user isn't straightforward as it requires making many assumptions:

While your list is long, there are obvious answers to these points in my opinion.

> preCICE cannot know the needs of the user.

While it's true that you can't anticipate every need of every user of your image, establishing a secure and useful default  is beneficial. Users with niche cases can alter things at anytime.

> If you need to add a user, you can easily do it when you extend the image for your case

In my case, I don't want to create or add an image in the first place, but just use what's there (otherwise I can directly compile preCICE). GitHub actions allow to just specify 

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container: precice/nightly
```
if there is something comparable (in terms of usability), which allows me to compile and test everything, I am completely fine. However, if I (and everyone else) has to set up their own image for testing, then compiling is easier and I don't understand the benefit of having the image in preCICE.

If it's such a big deal, could we just provide two images, one 'nightly' image which complies to standards and one  `user-nightly' image useful for testing and running things locally/interactive?

**Comment by fsimonis** [comment]
I changed the title of this issue, as the usability problem concerns all release docker images of preCICE.

Let me try to surmise the above.

## User-perspective

I cannot easily run software in the image as I need to create a non-root user myself.
I either need to add the user in the CI and switch to it, which isn't convenient in GitHub actions, or I need to extend the image myself, which requires a lot of extra infrastructure.

What I want to do is to set a user to non-root and be done with it.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container:
       image: precice/nightly
       options: --user=precice
```

## Maintainer perspective

I want to keep the image as simple as possible to keep it as extendable as possible.
Running MPI programs with non-root is a general docker problem, not specific to preCICE or its adapters.
Adding a user requires making many assumptions, which make the image less general and may even prevent it from being reused.

## Potential solutions

### A 

Make the assumption that we need:
* sudo installed
* a non-root user called `precice`
* with non-password sudo

And include the user in the image generation.

If a user of the image wants to run as non-root, they can either use `--user=precice` at container start or selectively use `su precice` for commands.

_This requires regenerating all previous tags to keep things consistent._

### B

Defer the creation of the non-root user to the user of the image by

1. creating the user
2. adjusting user groups
3. adjusting user permissions
4. `su user`
5. run commands

_GitHub doesn't have a way to define a user for a step yet (except from misusing `step.shell`), so this requires to selectively run commands using `su -c precice command`._ 

### C

Automatically create images `precice-noroot` from the release images `precice/precice` containing the user described in A.

`precice/precice:3.1.0` -> `precice/precice-noroot:3.1.0`
`precice/precice:nightly` -> `precice/precice-noroot:nightly`

_Simple to automate and (re)generate such images_

### D

Automatically create tags from the releases containing the user described in A.

`precice/precice:3.1.0` -> `precice/precice:3.1.0-noroot`
`precice/precice:nightly` -> `precice/precice:nightly-noroot`

_Unusual tags and difficult to automate_


---

If we really want to support no-root users directly from preCICE, then I would prefer option C, as it is easy to use and easy to automate without adding extra bulk to the `precice/precice` image.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container:
       image: precice/precice-noroot:nightly
       options: --user=precice
```

**Comment by MakisH** [comment]
I just read the full discussion, and I also support having a regular user in the images. So far, these images seem a bit useless for users. Also, in some cases (e.g., OpenFOAM), solvers assume that there is a user in the system. Having that in the base image makes everything easier.

If we decide that it is better to maintain two images, then let's do the one as an extension of the other and avoid duplication.

For sure, we need to make some assumptions, but as @davidscn wrote, users that want something special typically know how to do it.

**Comment by fsimonis** [comment]
OK, I'll:

1. Copy all tags from `precice/precice` to `precice/precice-bare`
2. Patch release and docker workflows to target `precice/precice-bare`
3. Create a work that builds a user ontop of the bare image.

**Comment by fsimonis** [comment]
Further insight and discussion resulted in the following:

* sudo isn't necessary. The user alone suffices for the majority of use cases.
* Without sudo, the problematic "assumption" are reduced only to the user creation.
* This boils down the extra modifications of the Dockerfile to `RUN useradd -m -s /bin/bash precice`

So, let's keep as simple as possible and:
* Add the user to the `precice/precice` docker releases.
* Regenerate recent releases.
