### ISSUE TITLE
Allow `MAX_WAVEFORM_DEGREE` > 10

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#2038]
**Describe the solution you propose.**
We simply have to modify the following line:
https://github.com/precice/precice/blob/fc3fddf308652abb59799b5a949b91d7f9ec7c8e/src/time/Time.cpp#L9

Should we set an upper bound at all?

**Describe alternatives you've considered**
Keep it as it is and recompile preCICE, if I want to use a higher waveform degree.

**Additional context**
We decided to restrict the waveform degree when introducing the feature. For my experiments I'm regularly manually adjusting this option. So far, I have not seen any strange behavior when picking a very high waveform degree. Therefore, I think we could be less restrictive.

**Comment by uekerman** [comment]
Yes, let's simply remove. Such things should anyway be handled in the configuration.
