### ISSUE TITLE
CMake 3.12 gives policy warning

### ISSUE THREAD

**Issue by floli** [precice/precice#206]
```
CMake Warning (dev) at /usr/share/cmake-3.12/Modules/CheckIncludeFileCXX.cmake:69 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    /home/lindnefn/software/petsc/arch-linux2-c-debug/lib/libpetsc.so;/usr/lib/liblapack.so;/usr/lib/libblas.so;/usr/lib/libX11.so;/usr/lib/openmpi/libmpi_usempif08.so;/usr/lib/openmpi/libmpi_usempi_ignore_tkr.so;/usr/lib/openmpi/libmpi_mpifh.so;/usr/lib/openmpi/libmpi.so;/usr/lib/libgfortran.so;/usr/lib/libm.so;/usr/lib/libgcc_s.so;/usr/lib/libquadmath.so;/usr/lib/libpthread.so;/usr/lib/libstdc++.so;/usr/lib/libdl.so

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  /usr/share/cmake-3.12/Modules/FindThreads.cmake:123 (CHECK_INCLUDE_FILE_CXX)
  CMakeLists.txt:57 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

This warning is given by CMake 3.12.

**Comment by floli** [comment]
See: 
* https://cmake.org/cmake/help/latest/policy/CMP0075.html
* https://cmake.org/cmake/help/latest/command/cmake_policy.html
* https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html

I understand the cmake documentation, that `cmake_minimum_required (VERSION 3.5)` implicitly sets the policy to `old` (because it was introduced with 3.12 > 3.5), but that does not seem to the case.

**Comment by fsimonis** [comment]
I encountered this warning whilst working on #195.
There is another warning  regarding `find_package` introduced with 3.12 which I will fix too: [CMP0074](https://cmake.org/cmake/help/latest/policy/CMP0074.html#policy:CMP0074)

It implicitly sets the policies to old, but cmake still complaints about them as we have not explicitly set them.
