### ISSUE TITLE
Config suggestions are not readable

### ISSUE THREAD

**Issue by davidscn** [precice/precice#2061]
**Describe your setup**

preCICE Version: [03c92b9](https://github.com/precice/precice/commit/03c92b92539d831b1999c47cd2ea5e014f0f1b8c)

**Describe the problem**

preCICE computes string matches to make suggestions in case the user config has typos or similar. 

https://github.com/precice/precice/blob/03c92b92539d831b1999c47cd2ea5e014f0f1b8c/src/xml/XMLTag.cpp#L204-L209

Since recently, these suggestion are not useful anymore and contain mostly garbage:

The configuration contains an unknown tag <basis-function:compact-polynomial-c5>. Did you mean <W��.0[h��u����ompact-polynomial-c8>,<W��.0[h��u����ompact-polynomial-c8>,<W��.0[h��u����ompact-polynomial-c8>,<W��.0[h��u����ompact-polynomial-c8>,<W��.0[

**Step To Reproduce**
1. Pick a tutorial and introduce a config typo
2. run the tutorial
3. observe the suggestions

**Expected behaviour**
I would suggest to remove the feature or fix it and add a corresponding test. In the current shape, it causes more confusion. Of course, it could be related to my OS, but let's see if other can reproduce it or not.

**Comment by fsimonis** [comment]
Found it, but not where you suspected it to be.

It is a lifetime issue in the section of the ConfigParser, which handles incorrect tags.

https://github.com/precice/precice/blob/03c92b92539d831b1999c47cd2ea5e014f0f1b8c/src/xml/ConfigParser.cpp#L236

This should be a vector of strings. Changed here https://github.com/precice/precice/commit/d8a9b60fc756a919d9c71f72ef60f73f88b58a9a

I'll open a PR.
