### ISSUE TITLE
Report synchronize event in profiling if useful

### ISSUE THREAD

**Issue by davidscn** [precice/precice#2077]
**Please describe the problem you are trying to solve.**

Using our profiling, one get to see the recently introduced '`*.sync` events (see https://github.com/precice/precice/pull/2019)
However, if synchronization is disabled or if preCICE is executed in serial, there is no value in having these events and they only report a timing of `0.0`.

**Describe the solution you propose.**
Only profile synchronization in case they become relevant (synchronization=true and parallel execution).

**Comment by fsimonis** [comment]
True. It makes sense to filter these out in serial.
