### ISSUE TITLE
Extend fundamental events to basic components

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#2114]
**Please describe the problem you are trying to solve.**

As discusses with @davidscn, the `fundamental` events don't include enough information to understand where preCICE is spending time, it only informs if the time spend is in preCICE or the solver.

**Describe the solution you propose.**

Add fundamental events for essential sections of preCICE:

* `initialize`
  * `connect` setting up primary communication (indicator for slow file system)
  * `reparatition`
  * `mapInitialData`
  * `export`
* `advance`
  * `debugSync` rank synchronization in debug
  * `mapWriteData`
  * `accelerate`
  * `mapReadData`
  * `export` (which can become a major hit if used carelessly)

**Describe alternatives you've considered**

Communicating data between participants would be amazing to understand serial coupling schemes, but is generally tricky as it is interleaved with acceleration and other parts.

**Comment by davidscn** [comment]
If possible, I would also consider time interpolation as another fundamental factor, such that we map features from our configuration to the fundamentals.

**Comment by fsimonis** [comment]
For the time Interpolation in `readData` we have https://github.com/precice/precice/issues/2013

But there will also be time interpolation in the IQN acceleration.
