### ISSUE TITLE
precice 3.2.1 and mingw

### ISSUE THREAD

**Issue by 3rav** [precice/precice#2119]
When trying to update the precision package (https://packages.msys2.org/base/mingw-w64-precice) I get this error:

```
-- Configuring done (4.5s)
CMake Error: install(EXPORT "preciceTargets" ...) includes target "precice" which requires target "preciceCore" that is not in any export set.
CMake Error in CMakeLists.txt:
  export called with target "precice" which requires target "preciceCore"
  that is not in any export set.


-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by 3rav** [comment]
Strage, version 2.5.0 allowed compiling a static version:

![image](https://github.com/user-attachments/assets/06e62537-dce5-4de8-a7e2-a73382daccaf)

https://packages.msys2.org/packages/mingw-w64-x86_64-precice

**Comment by fsimonis** [comment]
This should do the trick to prevent the CMake target generation from complaining:

https://github.com/precice/precice/blob/ffe0f992db5b28381ecb5f32ebeec3bd0f4afd52/CMakeLists.txt#L628

```diff
-install(TARGETS precice
+install(TARGETS precice preciceCore
```

I still strongly advise against building preCICE as a static library. Using it will be a challenge.

**Comment by BenjaminRodenberg** [comment]
I assume 3.2.1 is a typo and 3.1.2 is meant.
