### ISSUE TITLE
Remove hard-coded build/last in building and testing scripts

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#217]
In our current scons based build process preCICE gets built in the folder `$PRECICE_ROOT/build/last`. In the following scripts this path is hard-coded:

* [`setup.py`](https://github.com/precice/precice/blob/develop/src/precice/bindings/python/setup.py#L58) for building `PySolverInterface`
* [`compileAndTest.py`](https://github.com/precice/precice/blob/develop/tools/compileAndTest.py#L40) for testing

This is problematic, if preCICE is actually built in another folder and we still want to use these scripts. One example where the current solution breaks is if we build preCICE using cmake (see [here](https://github.com/precice/precice/wiki/Building:-Using-Cmake)), where not `build/last`, but `build` contains `libprecice.so`.

One possible solution might be providing an optional parameter to these scripts. I already implemented such a solution for `compileAndTest.py` in https://github.com/precice/precice/commit/56d9385e801679f49bb7ee84b19611a2497090d0. A similar solution for `setup.py` should be possible (see also https://github.com/precice/precice/pull/146), but I already faced some problems when I gave it a first try.

An alternative idea is introducing a new environmental variable (e.g. `PRECICE_BUILD`) as in https://github.com/precice/precice/commit/9447f1dd7ef4bc36c45c1e0595cc42ef846077cf.

Related questions that we should also keep in mind:

* ~~How do we have to modify `setup.py`, if we want to install `PySolverInterface` using `pip`?~~ (see https://github.com/precice/precice/issues/217#issuecomment-447771523)
* What is the best approach, if we directly want to build `PySolverInterface` within our main build process? Related to https://github.com/precice/precice/issues/182

Do you have any opinions on this?

**Comment by uekerman** [comment]
When we run cmake or scons, we know the value of `PRECICE_ROOT` and we know the current directory, so in principle we could find out the relative difference and store this somewhere. Sounds a bit hacky, but could be another solution. Having two environment variables `PRECICE_ROOT` and `PRECICE_BUILD` appears over-engineered to me. Is there a standard way to solve this problem?

**Comment by BenjaminRueth** [comment]
For the build process of the python bindings, #182 is related to this issue. If we build the python bindings along the main build process in cmake/scons, we do not have to worry about how to specify the variables (from a user perspective), since the building process for the python bindings will be hidden within the main build process.

**Comment by BenjaminRueth** [comment]
In our [wiki](https://github.com/precice/precice/wiki/Building:-Using-Cmake) there is now a workaround that should help when using cmake. Short version: create a symbolic link `build/last` that points to the actual building directory. 

For the future: Doing this directly in cmake would be nice. Not creating symbolic links (which is a bit hacky) would be even nicer.

**Comment by BenjaminRueth** [comment]
Regarding: **How do we have to modify `setup.py`, if we want to install `PySolverInterface` using `pip`?**

I do not think that we should worry about this use-case. In the future, we want to build the python bindings along with preCICE (#182). In this case, I do not see any purpose in providing the python bindings via `pip`. 

Installing the python bindings only makes sense for users that have already installed preCICE. But, the python bindings are installed along with preCICE anyway (in the future).

**Comment by floli** [comment]
> Having two environment variables PRECICE_ROOT and PRECICE_BUILD appears over-engineered to me.

I agree.

>  Is there a standard way to solve this problem?

Using `$PATH` is the standard way to find binaries.

Keep in mind, that all these fuzz only applies when building from source. 

> For the future: Doing this directly in cmake would be nice.

We have agreed on not doing this from cmake.

**Comment by fsimonis** [comment]
This seems to be a bit of a spaghetti-issue. This is what I understand of all of this:

What to find | How to find it now | How we could also find it 
--- | --- | ---
Root for tests  | `PRECICE_ROOT` | -
Includes | `PRECICE_ROOT`, `CPLUS_INCLUDE_PATH`,.. | -
Shared Libs | link, `LD_LIBRARY_PATH` | `PRECICE_BUILD`, file
Static Libs | link, `LIBRARY_PATH` | `PRECICE_BUILD`, file
Binaries | link, `Path` | `PRECICE_BUILD`, build-dir option, file

`link` is the current symbolic link approach.
`file` is my "just write the path of the build dir into a file and read it if its available"-proposal.

We can achieve everything we need using standard ENV variables, even the link is really not required.

Complementary to what @floli wrote:  if someone installs preCICE using a package manager, this should all work out of the box. (except maybe the tests)
Also, if someone builds from source and installs it into a custom prefix, it is likely that this person will adjust the ENV variables too.

As @BenjaminRueth said: We _maybe/hopefully_ could add a build-dir-option to the scripts.

Adding the options has absolutely no drawbacks, so lets go with that approach.

**Comment by BenjaminRueth** [comment]
> > For the future: Doing this directly in cmake would be nice.
> 
> We have agreed on not doing this from cmake.

@floli I forgot about this. I assume then we can close #182 (and ignore my conlusions in https://github.com/precice/precice/issues/217#issuecomment-447771523)

**Comment by MakisH** [comment]
Conclusion from discussion in the coding days:
* For a while we want to support both CMake (default) and SCons
* The `compileAndTest.py` is useful, let's keep it SCons-only for now
* If someone wants to keep using `compileAndTest.py`, feel free to open a PR porting it to CMake
* We can still run the tests directly when building with CMake
* We had cases where (e.g. EasyBuild) this link created problems
* Closing as "wontfix" for now.

**Comment by floli** [comment]
> The compileAndTest.py is useful, let's keep it SCons-only for now

The script does not care about the build system, unless you use it to compile.

**Comment by MakisH** [comment]
Well, but it needs the `build/last` to run the tests, right? And this link we only create with SCons.

**Comment by floli** [comment]
There exists the `ln` command which allows you to create these links yourself.
