### ISSUE TITLE
Debug non-working test on riemann (Benjamin's laptop)

### ISSUE THREAD

**Issue by floli** [precice/precice#22]
*Moved from Munich GitLab. Original creator: @uekerman*

File based communication, unit test, integration test, coupling mode, testBug()

**Comment by uekerman** [comment]
missing coupling mode integration tests are working. not sure what the original problem was ...

**Comment by floli** [comment]
Is this still open? I think I remember it has been resolved.

**Comment by uekerman** [comment]
yes, that's done
