### ISSUE TITLE
Avoid using a relative path in setup.py for PySolverInterface

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#220]
The proposed change in https://github.com/precice/precice/pull/219 fixes the bug. However, we could also use `PRECICE_ROOT = os.getenv("PRECICE_ROOT")`, which is defined anyway, and avoid using relative paths `PRECICE_ROOT = os.path.join(PYTHON_BINDINGS_PATH, "../../../..")` ([see setup.py](https://github.com/precice/precice/pull/219/commits/9b0f1d9df865571a47f8375313be16171703d084#diff-9f96816e1cce294ee2c6fa12852a507aR15)). We already use the same mechanism in, for example, [compileAndTest.py](https://github.com/precice/precice/blob/develop/tools/compileAndTest.py#L44).

The reason for originally using relative paths instead of `PRECICE_ROOT` is that one other has to use `sudo` to run `python3 setup.py install`. Using the `-E` option, `sudo` can access `PRECICE_ROOT`

**Comment by MakisH** [comment]
What if we provide `PRECICE_ROOT` as an additional argument to the `setup.py` script?

I would prefer to decouple the two directories, since they are also so far from each other. I could imagine that we keep the python bindings in a separate directory in some package or system.

**Comment by BenjaminRueth** [comment]
I proposed a first implementation in https://github.com/precice/precice/commit/41e97dedebe16272c785277df17ef372a2e9f386.

**Comment by BenjaminRueth** [comment]
> What if we provide `PRECICE_ROOT` as an additional argument to the `setup.py` script?

Adding command line options to `setup.py` is to me still a bit mysterious. Therefore, I would prefer to avoid this if it is not really necessary (see implementation of `--mpicompiler` in https://github.com/precice/precice/pull/146).

**Comment by ajaust** [comment]
I support that change. I had troubles building the Python-interface for `preCICE 1.3` on my system (Ubuntu 18.04). I think, this problems was mainly caused because the `setup.py` script expects the preCICE directory is called `precice` what is not the case for me. I usually add a version number and keep several version on my machine for testing. 

I changed `setup.py` line 15:
```
PRECICE_ROOT = os.path.join(PYTHON_BINDINGS_PATH, "../../../../../precice")
```
to
```
PRECICE_ROOT = os.path.join(PYTHON_BINDINGS_PATH, "../../../../")
``` 

In my opinion there was no need to go 5 levels up and thus out of the preCICE directory I am already in. It might still fail if you run the procedure from the wrong directory as the paths are relative.

**How to reproduce the error**:
Go to
```
$PRECICE_ROOT/src/precice/bindings/python
```
and delete all old build files. Then run
```
python setup.py build
```
The error message I get is:
```
running build
#####
calling my_build
using --mpicompiler=mpic++
adding extension
#####
running build_ext
#####
calling my_build_ext
using --mpicompiler=mpic++
#####
Compiling /home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings/python/PySolverInterface.pyx because it changed.
[1/1] Cythonizing /home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings/python/PySolverInterface.pyx
building 'PySolverInterface' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/home
creating build/temp.linux-x86_64-2.7/home/jaustar
creating build/temp.linux-x86_64-2.7/home/jaustar/projects
creating build/temp.linux-x86_64-2.7/home/jaustar/projects/precice
creating build/temp.linux-x86_64-2.7/home/jaustar/projects/precice/precice-1.3.0
creating build/temp.linux-x86_64-2.7/home/jaustar/projects/precice/precice-1.3.0/src
creating build/temp.linux-x86_64-2.7/home/jaustar/projects/precice/precice-1.3.0/src/precice
creating build/temp.linux-x86_64-2.7/home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings
creating build/temp.linux-x86_64-2.7/home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings/python
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings/python/../../../../../precice -I/usr/include/python2.7 -c /home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings/python/PySolverInterface.cpp -o build/temp.linux-x86_64-2.7/home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings/python/PySolverInterface.o -I/home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings/python/../../../../../precice -Wall -std=c++11 -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -I/usr/lib/x86_64-linux-gnu/openmpi/include -pthread
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/jaustar/projects/precice/precice-1.3.0/src/precice/bindings/python/PySolverInterface.cpp:545:10: fatal error: ./src/precice/Constants.hpp: No such file or directory
 #include "./src/precice/Constants.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by BenjaminRueth** [comment]
#270 closes this issue

**Comment by MakisH** [comment]
I am a bit confused, which part of #270 solved this issue? We get the same in the system tests and I am trying to fix it.

**Comment by fsimonis** [comment]
@MakisH It turns out that the distutils `build_ext` command supports the arguments `--library_dirs` and `--include-dirs`.

For custom prefixes, one can pass the library and include destinations to `source.py build_ext` using the above options. Thus, the relative path as well as PRECICE_ROOT are not necessary in the script itself.
To build, use:
```console
python3 setup.py build_ext --include-dirs=$PRECICE_ROOT/src --library-dirs=$PRECICE_ROOT/build/last
```

For a system install, calling `python3 setup.py build` works fine.
