### ISSUE TITLE
Add comments to and complete the Fortran 2003 bindings

### ISSUE THREAD

**Issue by MakisH** [precice/precice#222]
Alongside creating a dummy solver (see #172), we should also add comments to the [Fortran 2003 bindings](https://github.com/precice/precice/blob/develop/src/precice/bindings/f2003/SolverInterfaceF2003.f90), which currently have none.

**Comment by uekerman** [comment]
Some function are also still missing as pointed out by @msuaeronautics13, e.g. `isTimestepComplete`. In the process of adding comments, we should also complete the bindings.
