### ISSUE TITLE
Assertion failure instead of error message: BaseQNPostProcessing::applyFilter()

### ISSUE THREAD

**Issue by MakisH** [precice/precice#223]
Under some conditions, the user may receive the following assertion failure, without any other error message:

https://github.com/precice/precice/blob/bfb5424e38456ddcc3679583ec48c1b639ac5535/src/cplscheme/impl/BaseQNPostProcessing.cpp#L481

Here is an [example](https://gist.github.com/MakisH/cdf84a9a483db749e0c371f4307ebaa9#file-log1).

**Comment by uekerman** [comment]
I ran into this one as well. I guess it happens when the user gives two times the same values to preCICE. So kind of an invalid usage of preCICE. Then, the difference is zero and might be filtered out. We need a good error message here. I'll think about one.

**Comment by BenjaminRueth** [comment]
related to #383

**Comment by uekerman** [comment]
after all, not related to #383

**Comment by uekerman** [comment]
Should be fixed by #787, but I am not sure how to test this?
