### ISSUE TITLE
Bug: ReceivedPartition already holds non-empty mesh before receiving 

### ISSUE THREAD

**Issue by MakisH** [precice/precice#224]
Under some conditions, the user may receive the following assertion failure, without any other error message:

https://github.com/precice/precice/blob/bfb5424e38456ddcc3679583ec48c1b639ac5535/src/partition/ReceivedPartition.cpp#L38

Here is an [example](https://gist.github.com/MakisH/cdf84a9a483db749e0c371f4307ebaa9#file-log2).

**Comment by uekerman** [comment]
This is an actual bug and should be no error message. The mesh here should simply be empty. 
Can you give more information when this happens? e.g. the config and when and how you call `setMeshVertices`

**Comment by MakisH** [comment]
Unfortunately I don't have the case anymore, but I can certainly say that it was an extreme case, as there was some serious problem in the respective adapter back then, leading to garbage data.

**Comment by uekerman** [comment]
Could be that [setMeshVertices](https://github.com/precice/precice/blob/develop/src/precice/impl/SolverInterfaceImpl.cpp#L650) does also allow to write data to a "received" mesh. We could try to reproduce this with an integration test. If so, we need to place an error mesh there.

**Comment by fsimonis** [comment]
@uekerman @MakisH Is there an update on this issue?

**Comment by MakisH** [comment]
It only affected me once in a case of clear API abuse, I don't have the means to reproduce it anymore. It is ok to be closed from my side.
