### ISSUE TITLE
Exported vtu files are not grouped correctly in ParaView

### ISSUE THREAD

**Issue by MakisH** [precice/precice#226]
Paraview (at least version 5.0) uses the last part of the file names to group files of different times. Therefore, our [exported vtk files](https://github.com/precice/precice/wiki/Exports-Configuration) from serial simulations are nicely grouped together (`mesh_name-participant.dtTIME.vtk`).

This is not the case with the vtu files exported from parallel runs, which have names of the format `mesh_name-participant.dtTIME_rRANK.vtu`).

https://github.com/precice/precice/blob/6baedc6a1c6d4a1f3e11a2745cfc4e24ef166d59/src/io/ExportVTKXML.cpp#L148

Additionally, maybe these files should also have the `precice-` prefix (see #148 ).

**Comment by fsimonis** [comment]
@MakisH Would this naming scheme solve the problem?

`mesh_name-participant-RANK.dtTIME.vtu`

**Comment by MakisH** [comment]
Yes, it would work. I would even go for `precice-participant-mesh_name-rRANK.dtTIMESTEP.vtu`.

![paraview_grouping](https://user-images.githubusercontent.com/4943683/50653916-cf0f3400-0f93-11e9-95b4-097b91223419.png)

**Comment by fsimonis** [comment]
Problem is that the front and back part of the filename get generated in different modules.
```
mesh_name-participant.dtTIME_rRANK.vtu
^^^^^^^^^^^^^^^^^^^^^^^^^^^^.......... [1]
............................^^^^^^^^^^ [2]

[1] from parameter name
    from IO::Export::doExport()
    from SolverInterface::handleExports()

[2] std::to_string(utils::MasterSlave::_rank)
    from ExportVTKXML::writeSubFile()
    from ExportVTKXML::doExport()
```
I can think of two solutions:
1) change the interface of IO::Export to allow passing more information. Some sort of struct containing mesh-name, participant, timestep, rank.
2) using placeholders in the string. Maybe using [fmlib](http://fmtlib.net/latest/) named placeholders.
