### ISSUE TITLE
Deadlock problems for compositional cplschemes

### ISSUE THREAD

**Issue by floli** [precice/precice#23]
_Moved from Munich GitLab. Original creator: @uekerman_

The unit tests give a deadlock for the 4 tests in  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp::run() this happens, however, only on some machines, including Benjamin's laptop, or helium in Stuttgart. On atsccs31 everything works fine.

**Comment by floli** [comment]
*Benjamin Uekermann commented 8 months ago*

Now, those test also fail (deadlock) on atsccs31. since we changed to C++-11, i had to switch to ```compiler=mpicxx```. On Florian's machine, they even produce a run-time error:
```
Fatal error in MPI_Recv: Message truncated, error stack: MPI_Recv(186).......................: MPI_Recv(buf=0x7fff9ed6c268, count=1, MPI_INT, src=0, tag=0, comm=0xc4000000, status=0x7fff9ed6bf10) failed MPIDI_CH3U_Request_unpack_uebuf(599): Message truncated; 15408 bytes received but buffer size is 4
```
We should have a closer look and decide whether this can be fixed easily or is even not of importance. i already tried to switch all communications in multi...-xml to single-mpi, but this did not help.

**Comment by uekerman** [comment]
Seems to have disappeared
