### ISSUE TITLE
Tutorial couplage OpenFoam CalculiX

### ISSUE THREAD

**Issue by augustinhugues** [precice/precice#236]
Hi,
I try to run the tutorial OpenFoam CalculiX with OpenFoam 1812.
CalculiX and CalculiX adapter seem to work ok, but OpenFoam crases, and it looks like it is because of preCICE or the OpenFoam adapter, but I ran the preCICE test after compilation and it was ok, same for the adapter.
I link the Fluid.log below
[Fluid.log](https://github.com/precice/precice/files/2783183/Fluid.log)
Cheers,

Augustin

**Comment by MakisH** [comment]
Hi @augustinhugues,

I will gladly help you, but let's continue the discussion on [Gitter](https://gitter.im/precice/Lobby). Here we only keep concrete issues/bugs/feature requests for preCICE (the core library) and not user support discussions. We also keep all the OpenFOAM adapter related issues in a [separate repository](https://github.com/precice/openfoam-adapter).

I will close this now, but I will leave some ideas here:
* Does the `flap_prep` tutorial work?
* The `cyliderFlap` uses PETSc for the RBF mapping. Have you built preCICE with PETSc? There seems to be a problem in the initialization of PETSc.

Best regards,
Makis
