### ISSUE TITLE
Some issues with C++ solver dummy

### ISSUE THREAD

**Issue by Dominanz** [precice/precice#239]
I encountered a number of minor problems with the [C++ solver dummy](https://github.com/precice/precice/tree/develop/tools/solverdummies/cpp). All these problems could be reproduced by @BenjaminRueth if not specified otherwise.

COMPILING

- The `-o` is missing in the compilation command provided
- Compiling does not seem to work with the command provided: The precice library can't be found, even if `LD_LIBRARY_PATH` is set correctly. It only works when `-L[LIBRARYPATH]` is added before -lprecice

RUNNING

- In the current config file, the default communication should be switched to sockets, since MPI does not work with OpenMPI.
- The command `mpiexec -n 2 ./solverdummy precice-config.xml X` where X=A resp. X=B throws an error complaining that B_Mesh is wrong, probably empty
- The command `mpiexec -n 2 ./solverdummy precice-config.xml X X_Mesh Datax Datay 1 1` where (X,x,y)=(A,1,2) resp. (X,x,y)=(B,2,1) does not throw errors, but for some reason, only the A solver performs proper time stepping, while B gets stuck after the first step. This problem happened to me but could not be reproduced by @BenjaminRueth

**Comment by fsimonis** [comment]
@Dominanz 
> The -o is missing in the compilation command provided

True

> Compiling does not seem to work with the command provided: The precice library can't be found, even if LD_LIBRARY_PATH is set correctly. It only works when -L[LIBRARYPATH] is added before -lprecice

Try setting `LIBRARY_PATH` as well.

**Comment by fsimonis** [comment]
@Dominanz The cpp solverdummy now comes with a `CMakeLists.txt` which should make things easier.

**Comment by BenjaminRueth** [comment]
we can work on (the branch `fixingCPPSolverDummy`)[https://github.com/precice/precice/tree/fixingCPPSolverDummy] on this issue

**Comment by BenjaminRueth** [comment]
I added a dummy [`README.md`](https://github.com/precice/precice/blob/fixingCPPSolverDummy/tools/solverdummies/cpp/README.md), where we can provide instructions for compilation and running. The [`README.md`](https://github.com/precice/precice/blob/fixingCPPSolverDummy/tools/solverdummies/python/README.md) is currently just a copy of the corresponding ready of the python solverdummy

**Comment by IshaanDesai** [comment]
Changed [README.md](https://github.com/precice/precice/blob/fixingCPPSolverDummy/tools/solverdummies/cpp/README.md) on [this branch](https://github.com/precice/precice/tree/fixingCPPSolverDummy) to add new instructions to fix compilation issue
