### ISSUE TITLE
Mesh mapping requirements query by an adapter

### ISSUE THREAD

**Issue by KyleDavisSA** [precice/precice#246]
It would be beneficial to have a functionality within preCICE that an adapter can call to find out what meshing information is required by the adapter. This is helpful in cases where nearest-projection mapping is used and the mesh connectivity is required. Using Calculix as an example, extra mesh surface files are required in the Calculix input file in order to use NP mapping. Whether this is required can be checked automatically with a function like: 

```cpp
bool interface.doesMeshNeedtoDefineNodeConnectivityInformation(meshID)
```

where this function will return whether the node connectivity is required for preCICE to perform the mesh mapping. That way the adapters can know exactly which information preCICE requires. This would also be useful as an adapter sometimes needs the surface connectivity to determine the face centers for heat transfer applications, but not for the mapping process.

**Comment by uekerman** [comment]
We (@KyleDavisSA and me) decided offline that for CalculiX, it is easier to handle this in the adapter config. So, nothing to do here.

**Comment by fsimonis** [comment]
Would this it be a useful feature in the long run?

Keep in mind that configured actions can enforce a more specific mesh requirement requirement.
So this could be a way to query the mesh requirement after full configuration. 

Or shall we postpone any further discussion on this until there is an actual user request regarding this feature?

**Comment by uekerman** [comment]
I would say let's postpone this until needed. Currently our strategy is that only preCICE has the full knowledge here. See line 762 below. It's debatable whether this is the right strategy, though. 

https://github.com/precice/precice/blob/develop/src/precice/impl/SolverInterfaceImpl.cpp#L749-L777
