### ISSUE TITLE
Implementation of manifold mapping as a post processing

### ISSUE THREAD

**Issue by floli** [precice/precice#25]
_Moved from Munich GitLab. Original creator: @uekerman_

We want to implement the manifold mapping that david describes in his WCCM2014 paper. the most complicated aspect hereby is that we need a coupling scheme included in another. coarse or fine solver will be the same participant. over an action we can steer from precice what the participant should do next, also we would use the same communication from both coupling schemes.

On the other, we will need two meshes, each data field twice, and two coupling schemes, defined in the config.xml

On the implementation level, we will need a new pp, that has the coarse coupling scheme as a member. (it will be instanced in the cplScheme configuration) -> how do we mark this in the config.xml -> cplScheme is tag in pp?

To optimize on the coarse level (during the pp of the fine level), we then call advance of the coarse cplScheme till convergence (ImplicitCplScheme.measureConvergence() has to be public then)

To solve the SVD of the manifold mapping scheme, we will us "Eigen", a C++ library, where we could copy the src code directly (similar to boost)

... altogether not that easy, but possible, i guess. at least i don't see a big problem coming.

**Comment by uekerman** [comment]
Klaudius just commented that the feature is basically done and validated, but has not yet been heavily tested.
