### ISSUE TITLE
Get rid of communication factories

### ISSUE THREAD

**Issue by uekerman** [precice/precice#256]
Since we no longer need m communication instances in `PointToPointCommunication`, but only one, we could get rid of the communication factories (`src/com/`) and instead create the one communication in the configuration. 

This does not hold for the m2n factories (`src/m2n`) as we still don't know how many meshes to communication during the m2n configuration.

**Comment by floli** [comment]
I am not sure, if we really can abolish the CommunicationFactory.

For each (participant A, B) one M2N is created. The objects are saved in a list of `M2NTuple` in the configuration. 

In `SolverInterfaceImpl` we call `m2n->createDistributedCommunication(context->mesh)` for each mesh. This creates a communication which is held in `M2N::distComs`. Thus, we still have multiple communications per M2N object. These communications are created in the M2N configuration, where the number of meshes is known yet.

**Comment by floli** [comment]
For the reasons above @uekerman and @floli concluded to not "fix" that but the current architecture provides are saner separation of concerns than potential fixes that close that issue.
