### ISSUE TITLE
Change MasterSlave com to MPIDirectCom

### ISSUE THREAD

**Issue by uekerman** [precice/precice#26]
... without accept/request.
advantage: we can do slave-slave com (e.g. for the cyclic com). also, much nicer
disadvantage: master-slave over sockets no longer possible

**Comment by uekerman** [comment]
Instead of replacing, we should better add this as a further option.

**Comment by uekerman** [comment]
We have 3 options:
 * keep everything as it is (con: potential large initialization time for >1000 ranks, cf. thesis benjamin)
 * drop current implementation and use the participants's MPI communicator instead (con: cannot use sockets any longer, important for commercial solvers, or solver that work without MPI)
 * add MPIDirectCommunication with copy of MPI_COM_WORLD as fourth option?

**Comment by MakisH** [comment]
We are closing this as deprecated after recent changes by @fsimonis.
