### ISSUE TITLE
Scope symbols, sources and macros

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#263]
The xSDK requirement M9 requires a __limited and well-defined symbol, macro, library, and include file name space__.

So we need to:
* [x] prefix __all__ precice-related __macros__ with  
`PRECICE_` #476 , later 7e40c1d3
* [x] move __all__ precice-related __symbols__ in namespaces  
`namespace precice {`  
#473 will extract `prettyprint` and `json`, thus removing the last remaining instances
* [x] ~~scope __all source files__ with an include level and thus additional directory level~~  
_looks like we don't need to scope the sources_
  * `#include "precice/mesh/Mesh.hpp"`
  * move `/src/*`to `/src/precice/`  
  * move the interface files to the canonical `/includes/precice/` (this also simplifies installation)

**Comment by fsimonis** [comment]
Regarding the scope of the source files:

Lets consider moving our interface headers to the canonical `include`. This results in the following structure:
```
.
├── cmake
├── docs
├── include
│   └── precice
│       ├── Constants.hpp
│       ├── MeshHandle.hpp
│       └── SolverInterface.hpp
├── src
└── tools
```

This raises questions about _where_ to put the bindings.
Should we move the bindings out of `src/precice/` into e.g. `bindings` or even `extra/bindings`?
Should we use this opportunity to extract the python bindings and turn them into a separate repository?

**Comment by MakisH** [comment]
How would these options affect how IDEs can discover/navigate the API and the implementations? I also think it makes sense to move the bindings somewhere else.

**Comment by fsimonis** [comment]
We have finally fulfilled all requirements.
