### ISSUE TITLE
Rename PySolverInterface

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#265]
I think the name `PySolverInterface` is a bad name. It is not really specific and we should find a better name. If you have any propositions, feel free to comment below.

# Consequences

We will have to change all references to the `PySolverInterface` module. Here is an incomplete list of tutorials/solvers... using `PySolverInterface`:

* https://github.com/precice/elastictube1d/tree/master/PythonTube
* https://github.com/precice/fenics-adapter
* feel free to add any missing items to this list

**Comment by ajaust** [comment]
I support renaming the interface. It is too generic in my opinion. In the Python-file there might not be any reference to **preCICE** if the programmer does not add any comments. I see also a low risk for conflicting names if the user creates some bindings for their own software.

My suggestions would be something like:
- `PyPreciceInterface`

**Comment by MakisH** [comment]
Conclusion from coding days discussion:
* Names could be better (user perspective)
* It would be nice to have consistent names for all the bindings
* We need names good for both developers and users, and also for installing preCICE in system directories
* Currently we leave it like this
* Eventually (v2.0.0) we could rename these

**Comment by BenjaminRueth** [comment]
If we wrap the new, nicely named bindings (`newShinyName`) into a library with the old name (`PySolverInterface`), we can already introduce this change in `v1.x` (don't break the API!). In this case, we do not have to change the tutorial cases, as they should still work.

**Example:** This should still work in `v1.x`

```
import PySolverInterface
```

This should also work

```
import newShinyName as PySolverInterface
```

**Comment by floli** [comment]
Why should the name have a `Py` in front? Yes, it's a Python lib, but what else do you expect to import when you do `from precice import SolverInterface`?
