### ISSUE TITLE
Rename all API bindings consistently

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#266]
As a pilot we start with #265. However, in order to have a consistent naming scheme, we should apply this change to all the API bindings.

# ToDos

- [x] Delete old `PySolverInterface` in version 2.0.0 #576

**Comment by uekerman** [comment]
I am not sure what we exactly had in mind here. For `C` and `Fortran`, the story is a bit different to `python` as we need different names to distinguish between all variants. In a `C++` code, you could use both bindings as well as directly the `C++` API.
And the naming scheme is already consistent: `precicef_initialize` vs `precicec_initialize`.  
Anybody remembers sth else?

**Comment by MakisH** [comment]
Maybe it would be a good idea to rename the `Fortran` and `f2003`, as they are just using different mechanisms to do the same thing (which is nothing Fortran2003-specific).
