### ISSUE TITLE
Fortran bindings: Unavailable precicef_write_data_required routine due to error in interface declaration

### ISSUE THREAD

**Issue by nico-krais** [precice/precice#276]
Currently, the precicef_write_data_required routine is not available in the Fortran 77 interface. This is due to a wrong declaration of the input variable in SolverInterfaceFortran.cpp, where a _const_ is missing.

The effect of this is simply that the routine is not available in the library, as e.g. seen by a `nm libprecice.so | grep -i precicef` command.

This issue is fixed in https://github.com/precice/precice/pull/275.

I tried this on an Ubuntu 18.04 system using gcc 7.3.0.

**Comment by MakisH** [comment]
Closed via https://github.com/precice/precice/pull/275.
