### ISSUE TITLE
Delete .A-B.address file after unclean exit

### ISSUE THREAD

**Issue by floli** [precice/precice#28]
After an unclean exit of preCICE connection file still linger around. These should be deleted.

**Comment by floli** [comment]
To determine an unclean exit, we need to catch signals. A well-behaving library should not install signal handlers, this should be limited to the host applications. So, that is likely to be a wontfix. Any objections?

**Comment by uekerman** [comment]
If a solution to this problem via signals is not reasonable, we could still investigate to find a solution at start-up. The "reading" participant could, for example, throw a warning and wait if he runs into a suspicious file. Suspicious could be one which has a too old time stamp.
Or we can make an even better check-sum, by using more information, such as the config (both, the reader and the writer need to have the same).
