### ISSUE TITLE
No Exception thrown if solverdummy is configured wrongly

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#282]
You can reproduce the bugs, if you run the [python solverdummy](https://github.com/precice/precice/tree/develop/tools/solverdummies/python) with the following input.

### Bug1: identical solver and mesh name is used

**terminal1:** `python solverdummy.py precice-config.xml SolverOne MeshOne`

**terminal2:** `python solverdummy.py precice-config.xml SolverOne MeshOne`

* what we observe: preCICE hangs
* what we would like to see: preCICE should throw an exception in terminal2, that SolverOne has already been registered in terminal1

### Bug2: wrong combination of SolverTwo and MeshOne

**terminal1:** `python solverdummy.py precice-config.xml SolverTwo MeshOne`

**terminal2:** `python solverdummy.py precice-config.xml SolverOne MeshOne`

* what we observe: preCICE crashes
* what we would like to see: preCICE should already see in terminal1 that the solverdummy is wrongly configured and throw an exception

### Working: wrong combination of SolverOne and MeshTwo

**terminal:** `python solverdummy.py precice-config.xml SolverOne MeshTwo`

* what we observe: preCICE throws an exception `preCICE:ERROR:  Mesh with name "MeshTwo" is not defined!`. Something similar would be nice for **Bug2**

**Comment by uekerman** [comment]
We will not be able to do anything about Bug1. The second `SolverOne` knows nothing about the first one. If both are "acceptors" in the m2n communication they both write the same address file, so one overwrites the other one. If both are "receptors" they both wait for the same address file to be read. If you would start a third solver, now `SolverTwo` probably one of both `SolverOne` would connect while they other one would still wait. 

Bug 2: I agree. There should be an error message if we try to define a vertex on a non-provided mesh.

**Comment by fsimonis** [comment]
#341 solves this problem.

```
$ python3 solverdummy.py ../precice-config.xml SolverTwo MeshOne
preCICE: This is preCICE version 1.4.0
preCICE: Configuring preCICE with configuration: "../precice-config.xml"
preCICE: Run in coupling mode
preCICE:ERROR:  Can only write to provided meshes! 0
Run finished at Mon Mar 25 13:24:15 2019
```
