### ISSUE TITLE
Link is not working in "Tutorial for SSI with CalculiX"

### ISSUE THREAD

**Issue by 3rav** [precice/precice#285]
Link to necessary files for SSI example is not working ([this repository](https://github.com/precice/tutorials/tree/master/SSI/)), error 404.

**Comment by uekerman** [comment]
Thanks for the hint! The tutorial is still in a PR: https://github.com/precice/tutorials/pull/19
Any comment there is very welcome!
The link should work as soon as we merge. We were a bit too quick here in the wiki.

**Comment by uekerman** [comment]
We also added a note in the wiki.
