### ISSUE TITLE
Coexistence of internal with external dependencies

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#290]
__xSDK M12__ requires that dependencies checked-into the repository have to coexist with external dependencies. They propose solutions:
1) Using only external dependencies instead of internal copies.
2) Changing the internal copy so that it can coexist with an external copy.

@floli Does this affect our `json.hpp`? If so, are we allowed to modify it?

**Comment by floli** [comment]
`json.hpp` is header-only, the `#include "json.hpp"` should only find the internal copy. I see no problems here.

Closing, feel free to reopen if this wasn't the only concern.
