### ISSUE TITLE
Library name without embedded version.

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#291]
__xSDK M13__ prohibits to embed the version name into the library name. Only sonames `libprecice.so.1.3.0`, `libprecice.so.1`, etc are allowed. 

This directly conflicts with `lintian` which recommends to embed the version into the library.

**Comment by floli** [comment]
Not sure, if I understand correctly. I think the common way on Linux is to install at `libprecice.so.1.3.0` and to link from `libprecice.so` to it. IMO this should satisfy xSDK and is a sane and standard way to do it.

**Comment by MakisH** [comment]
> This directly conflicts with `lintian` which recommends to embed the version into the library.

Any reference for this? I am not sure this is correct.

**Comment by fsimonis** [comment]
I think that this lintian warning could be about the version of the deb package, not the version of library. I'll look the message up in the following days.

**Comment by fsimonis** [comment]
Ok, I was getting confused. TIL:
1) The soname is about the ABI of the library which has nothing to do with the library version.
2) Lintian says that the package name should reflect the ABI version:  
preCICE 1.4.0 with ABI version 0 -> `libprecice.so.0` -> Package `libprecice0` with Version 1.4.0

So our SONAME is currently non-standard. I'll fix that when I get some free time.

**Comment by fsimonis** [comment]
We added the version to the package in 5df2152b5
