### ISSUE TITLE
Make tagMesh*Round use boost::geometry

### ISSUE THREAD

**Issue by floli** [precice/precice#293]
Right now, `tageMeshFirstRound` and `tagMeshSecondRound` use a bounding box and then iterate through all vertices to check if they are in the bounding book. This is a use case `boost::geometry` is made for.

* Maybe write an adapter to directory use `mesh::BoundingBox`
* Or create a `Box2d` or `Box3d` and enlarge by the support radius. Use the `within` predicate to get all vertices within the box.

**Comment by uekerman** [comment]
@floli probably refers to the methods in `PetRadialBasisFctMapping`. For the other mapping methods, `tagMeshFirst/SecondRound` do different things. 
If there is a neat way to use `boost::geometry` here, there might be many other potential improvements in the `partition` package as well.
