### ISSUE TITLE
Integrate a testing coverage tool

### ISSUE THREAD

**Issue by MakisH** [precice/precice#307]
Since we have quite some tests in preCICE, it would be useful to also have a testing coverage tool to show us where tests are missing etc. It would also be a nice code quality metric which we can track over time.

A common tool that several projects use is [code coverage](https://codecov.io/) (e.g. see [Spack](https://codecov.io/gh/spack/spack)). Any other ideas/suggestions?

**Comment by fsimonis** [comment]
Using https://codecov.io/ should be trivial with CMake and even easier to setup than their example program.

This should suffice:
```console
$ LDFLAGS="--coverage" CXXFLAGS="--coverage" cmake -DBUILD_SHARED_LIBS=ON $PRECICE_ROOT
$ make -j $(nproc) testprecice
$ ctest
```

After that we can use travis to generate and upload the reports as described [here](https://github.com/codecov/example-cpp11-cmake#travis-setup-using-lcov).

**Comment by fsimonis** [comment]
Here an [example for c++ coverage](https://codecov.io/gh/codecov/example-cpp11-cmake/src/master/src/complex.cpp)

**Comment by MakisH** [comment]
> Here an [example for c++ coverage](https://codecov.io/gh/codecov/example-cpp11-cmake/src/master/src/complex.cpp)

The link looks broken
