### ISSUE TITLE
Debian packages: missing logo

### ISSUE THREAD

**Issue by MakisH** [precice/precice#308]
It would be nice to have the preCICE logo as package image, so that it could appear into e.g. the Ubuntu Software Center (screenshot from 18.10).

(the "proprietary" licence status should be an Ubuntu issue)

![precice_deb](https://user-images.githubusercontent.com/4943683/53734456-57bb2b00-3e84-11e9-832e-15502745d27d.png)

**Comment by fsimonis** [comment]
Finally found some information on this:
https://wiki.ubuntu.com/SoftwarePackageOperations#Data_for_packages

**Comment by fsimonis** [comment]
This is thus out-of-scope
