### ISSUE TITLE
Automate package creation

### ISSUE THREAD

**Issue by MakisH** [precice/precice#319]
Now that we have Debian packages, it would be good to automate the process, so that e.g. [Travis could create them](https://travis.debian.net/).

Moreover/alternatively, we could use [Open Build Service](https://openbuildservice.org/help/), or something similar, to produce packages for other distributions as well.

**Comment by MakisH** [comment]
We could actually better do this with GitHub actions, once we have them integrated.

@fsimonis You had some nice scripts to produce packages. Are they already in the repository?

**Comment by mohamad-altaweel** [comment]
@MakisH  Hello Mr. Chourdakis
I would be interested in doing this issue. I am a master student doing a lecture Simulation Software Engineering at the University of Stuttgart and this issue would be a good candidate for my submission of the course. Is this issue still open or it is deprecated ?

**Comment by MakisH** [comment]
Hi @mohamad-altaweel,
it's great that you want to work on this! I think that @fsimonis has done significant progress here over the past couple of years, but the process is not yet fully automated and documented. I think this would be a great opportunity to push towards this direction.

**Comment by fsimonis** [comment]
Hi, this is largely [finished](https://github.com/fsimonis/precice/tree/auto-packages).
GitHub actions are just a pain to test, which is why I haven't opened a PR yet.
