### ISSUE TITLE
log output: add line stating that the RBF interpolation is being computed

### ISSUE THREAD

**Issue by davidsblom** [precice/precice#32]
Since the computation of the interpolation matrix can take quite a long time, sometimes computations get killed due to time constraints. Then it's easier for the user to see that there wasn't actually a crash, but the RBF interpolation matrix was simply not completely computed yet.

**Comment by uekerman** [comment]
i added some statements for computeMapping, that's where the RBF mapping gets initialized. i did not add anything for map, since this would be quite a spam, but i guess the problem lies more in the initialization.
