### ISSUE TITLE
assertion thrown for fluid-structure-acoustics interaction

### ISSUE THREAD

**Issue by davidsblom** [precice/precice#33]
When using the PETSc based RBF interpolation, an assertion is thrown

assertion in file src/utils/PointerVector.hpp, line 90 failed: index < _content.size() 
ateles: src/utils/PointerVector.hpp:90: CONTENT_T& precice::utils::ptr_vector<CONTENT_T>::operator[](std::size_t) [with CONTENT_T = precice::mesh::Vertex; std::size_t = lon 
g unsigned int]: Assertion `false' failed. 
assertion in file src/utils/PointerVector.hpp, line 90 failed: index < _content.size() 
ateles: src/utils/PointerVector.hpp:90: CONTENT_T& precice::utils::ptr_vector<CONTENT_T>::operator[](std::size_t) [with CONTENT_T = precice::mesh::Vertex; std::size_t = lon 
g unsigned int]: Assertion `false' failed

This is the same problem I send an email last week about. Not crucial for the papers, but I guess it needs to be fixed.

**Comment by uekerman** [comment]
you still get this assertion with the last fix I send you last Friday per mail?

**Comment by davidsblom** [comment]
With that patch the problem is fixed. But is the underlying problem fixed as well? Or is there no underlying problem?

**Comment by uekerman** [comment]
that was just a hacky fix, we still need a clean fix for develop. there is no crucial underlying problem, just some mixed up indices.
