### ISSUE TITLE
Implementation of Watch-Integral

### ISSUE THREAD

**Issue by uekerman** [precice/precice#342]
Similar to the `watch-point` feature (see [configuration wiki page](https://github.com/precice/precice/wiki/Watchpoint-Configuration)), for some applications it is interesting to track integral values over a certain mesh. Two examples:
* Total force on a geometry in an FSI simulation
* [Flow rate](https://en.wikipedia.org/wiki/Volumetric_flow_rate) for a fluid-fluid coupling

Currently, one could extract this information by a python action, but I think it would be handy to have sth more automatic. Should also be relatively easy to implement. A good name of this logging could be `watch-integral`. The configuration could be:
```xml
<watch-integral mesh="MyMesh1" name="MyWatchIntegral" /> 
```

**How to compute the integral values?**
* When no mesh connectivity is given: simply sum up all values
* When mesh connectivity is given: sum up and weight with area (e.g. area of all neighboring triangles divided by number of neighboring triangles), also compare the [ScaleByAreaAction](https://github.com/precice/precice/blob/develop/src/action/ScaleByAreaAction.cpp)

**Additionally, we need to track the surface area itself**
... to e.g. compute the flow rate in the end:
* When no mesh connectivity is given: simply the total number of vertices
* When mesh connectivity is given: the total surface area

The latter, I would suggest to simply output as an additional column in the watch-integral log file. Then, the user can decide what he wants to do with it, e.g. scale the sum by the area in a gnuplot script.

**Comment by oguzziya** [comment]
I started to work on this
