### ISSUE TITLE
Prevent integer overflow in configuration

### ISSUE THREAD

**Issue by uekerman** [precice/precice#346]
@g009266 reported that a too high value in `max-timesteps` leads to the cryptic error message:
```
terminate called after throwing an instance of 'char const*
```
Probably due to an integer overflow or sth similar. I was able to reproduce that problem on my laptop.

**Comment by fsimonis** [comment]
@uekerman We are using `int` for the timesteps and iterations, which is [32bit](https://en.cppreference.com/w/cpp/language/types) for architectures of our interest. Meaning, the maximum timestep is `2 147 483 648`, which should be enough for common use cases.

Thus, this sounds more like a bug in the parsing/configuration. Can you please provide the config you used to reproduce this?

**Comment by uekerman** [comment]
@g009266 used indeed 1e10 as number of timesteps

**Comment by uekerman** [comment]
this is beyond anything useful, yes, but the error message is bad

**Comment by fsimonis** [comment]
@uekerman Without the try block, we/the user would get this message:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
```
