### ISSUE TITLE
Unify preCICE configuration for parallel and serial solvers

### ISSUE THREAD

**Issue by uekerman** [precice/precice#347]
When changing a solver from serial to parallel execution, the preCICE configuration has to be adapted at several locations. Some of them are purely technical and hard to understand for our users. We need to improve this situation.

* `master:mpi-single` should be the default if a solver is run in parallel.
* `gather-scatter` should be picked automatically if necessary
* RBF mappings should always be called `rbf` and there should be a clever default depending on whether preCICE was built with PETSc and whether a solver is run in parallel or not. 

*I will add more information to this issue.*

**Comment by Dominanz** [comment]
I agree with this.
A thing that I find particularly annoying is the fact that if the config contains a master tag and the solver is run serially (e.g. launched with mpirun -n 1),  preCICE throws an ``ERROR: You cannot use a master with a serial participant.``. Thus, if the user writes a scalable application and launches one or more processes depending on the number of available nodes, then he has to modify the config in case he has only one node available for some reason.
Is there a good reason for preCICE to throw an error if the master tag exists in a serial participant? If not, I would suggest that preCICE simply ignores the tag (and maybe throws a warning) in a serial execution.

**Comment by uekerman** [comment]
> Is there a good reason for preCICE to throw an error if the master tag exists in a serial participant?

It's purely a technical issue. So, no good reason :)

We should go for a proper solution, though, not ignoring the tag, but simply not requiring it in the first place.
