### ISSUE TITLE
Debian package is missing files for binding (python)

### ISSUE THREAD

**Issue by micheltakken** [precice/precice#352]
I was trying to use the python binding for preCICE with preCICE version 1.4.0, but it seems that if preCICE is installed with the Debian package (libprecice1.4.0-bionic.deb), there are files missing for the python binding.
The only file found in the python bindings folder was `setup.py`, but for example no `precice.pyx` or `constants.pyx`

**Comment by BenjaminRueth** [comment]
If you want to use the python bindings with preCICE being installed using the Debian package follow these instructions:

1. install preCICE using `libprecice1.4.0-bionic.deb`
2. clone [preCICE 1.4.0 from github](https://github.com/precice/precice/releases/tag/v1.4.0)
3. use the sources from the cloned repository to install the python bindings

This is obviously a workaround. The python bindings (or the sources necessary for building them) should be shipped with the debian package and it should not be necessary to clone the repository, if you already have the debian package.

**Comment by uekerman** [comment]
Is the workaround documented in the wiki somewhere?

**Comment by fsimonis** [comment]
Shipping the python bindings with the package was not planned. It looks like the setup script got included as part of installing the necessary files for the tests.

We need to fix this and come up with a proper solution regarding packaging.

**Comment by MakisH** [comment]
Some context, to avoid confusion: We decided for now to fix CMake to not include **any** files related to the python bindings, so that it is not confusing.

A proper solution would probably be to install the Python packages via a separate package (ideally through pip).
