### ISSUE TITLE
OpenFOAM crashes in re-partitioning for empty ranks 

### ISSUE THREAD

**Issue by augustinhugues** [precice/precice#353]
Configuration:
OpenFoam 1812, precice 1.4 (built with cmake), petcs 3.10, CalculiX 2.15
(RAM 126Gb, 32 procs)

When I use `nearest-projection` mapping  with mesh connectivity with C3D10 elements the calculation crashes during the filer mesh by bounding box if I am using more than 12 procs (about 14500 cells per proc). It is working fine for serial and up to 12 procs.

I link the log files and the config files.
[Fluid.log](https://github.com/precice/precice/files/3062949/Fluid.log)

[Solid.log](https://github.com/precice/precice/files/3062950/Solid.log)

[precice-config_parallel.txt](https://github.com/precice/precice/files/3062957/precice-config_parallel.txt)
[config.txt](https://github.com/precice/precice/files/3062958/config.txt)

**Comment by KyleDavisSA** [comment]
In the cases that work, is there a part of the interface on every processor from openFOAM? I have found that there are problems with the bounding box function when running openFOAM and a portion of the coupling interface is not on every processor. I don't have a problem if is split over all processors. This is also specific to nearest-neighbor and nearest-projection mapping that I have checked so far.

**Comment by augustinhugues** [comment]
I split a profile along the Z axis, with a space on each side of the profile. I ve just checked, for the 12 proc case, the first and last proc has a really small part of the profile, I think you are right and if I check for 14 proc (which is not working), at least one of the proc won't contain the coupling interface at all.
I check and keep you updated.

**Comment by MakisH** [comment]
I also wonder if this originates from the OpenFOAM adapter or from preCICE, so I am also very interested in your findings. By the way, how does your geometry look like?

**Comment by KyleDavisSA** [comment]
To the best of my memory, this was not a problem with the heart valves where I know that the interface was not on all processors, but this was with FOAM-FSI. It was also an older preCICE version, so I don't know what exactly is causing it.

In my case, I was using the cylinderFlap tutorial. The NN and NP mapping only works when the interface is on all processors.

**Comment by augustinhugues** [comment]
[wing.zip](https://github.com/precice/precice/files/3085568/wing.zip)

Here is my geometry is a section of airfoil profil the coord is 10m and the length is 5m, but will be 40m for final calculation.

As you expected, as long as every proc has a cell of the interface it is running ok. When I go up to 14 procs, two of them haven't any cell of the coupling interface.
For 12 procs, I have 10 proc with about 1500 to 2000 of coupling interface cells, and only 59 on the first one and last one, but it is still running.

**Comment by MakisH** [comment]
Could you maybe try setting `geometric-filter="no-filter"` in your `precice-config.xml`?

```
<use-mesh name="Calculix_Mesh" from="Calculix" safety-factor="2" geometric-filter="no-filter"/>
```

**Comment by MakisH** [comment]
This disables the geomtery filtering, I found it in the [XML Reference](https://github.com/precice/precice/wiki/XML-Reference).

```xml
<!-- TAG use-mesh
           Makes a mesh (see tag <mesh> available to a participant.
           (can occur 0..* times)
           ATTR safety-factor: If a mesh is received from another partipant (see tag <from>), it needs to bedecomposed at the receiving participant. To speed up this process, a geometric filter (see tag <geometric-filter>), i.e. filtering by bounding boxes around the local mesh, can be used. This safety factor defines by which factor this local information is increased. An example: 0.1 means that the bounding box is 110% of its original size.
           ATTR from: Makes a mesh (see tag <mesh> available to a participant.If a created mesh should be used by another solver, this attribute has to specify the creating participant's name. The creator has to use the attribute "provide" to signal he is providing the mesh geometry.
           ATTR geometric-filter: If a mesh is received from another partipant (see tag <from>), it needs to bedecomposed at the receiving participant. To speed up this process, a geometric filter, i.e. filtering by bounding boxes around the local mesh, can be used. 2 different variants are implemented: a "filter-first" strategy, which is beneficial for a huge mesh and a low number of processors, and a "broadcast/filter" strategy, which performs better for a very high number of processors. Both result in the same distribution (if the safety factor is sufficiently large).For very asymmetric cases, the filter can also be switched off completely ("no-filter").
           ATTR name: Name of the mesh.
           ATTR provide: If a mesh is received from another partipant (see tag <from>), it needs to bedecomposed at the receiving participant. To speed up this process, a geometric filter, i.e. filtering by bounding boxes around the local mesh, can be used. 2 different variants are implemented: a "filter-first" strategy, which is beneficial for a huge mesh and a low number of processors, and a "broadcast/filter" strategy, which performs better for a very high number of processors. Both result in the same distribution (if the safety factor is sufficiently large).For very asymmetric cases, the filter can also be switched off completely ("no-filter").If this attribute is set to "on", the participant has to create the mesh geometry before initializing preCICE. -->
      <use-mesh safety-factor="{float}(default:'0.1')" from="{string}(default:'')" geometric-filter="{string:'filter-first' or 'broadcast-filter' or 'no-filter'}(default:'broadcast-filter')" name="{string}" provide="{boolean}(default:'0')"/>
```

**Comment by uekerman** [comment]
The problem is reproducible with the OpenFOAM-CCX flap_perp tutorial and NN mapping. See PR for potential fix.

**Comment by augustinhugues** [comment]
With the #360 fix on preCICE my case is running on 32 procs

**Comment by uekerman** [comment]
@KyleDavisSA Great! Thanks for reporting back!

**Comment by MakisH** [comment]
#362 indeed works for the flap_perp tutorial, but now I think I found another instance of this, described in https://github.com/precice/openfoam-adapter/pull/46#pullrequestreview-228558264. Does this look related?

**Comment by uekerman** [comment]
No, looks like a different issue. There, it crashes in `Mesh::computeState`.
