### ISSUE TITLE
Implement missing API functions in Python bindings

### ISSUE THREAD

**Issue by uekerman** [precice/precice#363]
The [python bindings](https://github.com/precice/precice/blob/develop/src/precice/bindings/python/precice.pyx) do not yet implement all API functions, compare the [C++ documentation](http://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html).

Still missing is:
* [x] `setMeshVertex`
* [x] `hasToEvaluateSurrogateModel`
* [x] `hasToEvaluateFineModel`
* [x] `getMeshVertices`

As soon as `setMeshVertex` is implemented, it would be good to modify 

https://github.com/precice/precice/blob/develop/tools/solverdummies/python/solverdummy.py#L37

accordingly.

**Comment by BenjaminRueth** [comment]
Other language bindings are missing some functions, as well. See https://github.com/precice/precice/pull/395

**Comment by BenjaminRueth** [comment]
Also missing: `getMeshHandle`

**Comment by BenjaminRueth** [comment]
closed by #402
