### ISSUE TITLE
Python bindings: `read_scalar_data` not working

### ISSUE THREAD

**Issue by uekerman** [precice/precice#364]
The current implementation of `read_scalar_data` does not work as Python does not copy a simple double by reference. 

https://github.com/precice/precice/blob/develop/src/precice/bindings/python/precice.pyx#L393-L394

A possible solution would be to change the value to be read to a return value.

**Comment by fsimonis** [comment]
For the sake of consistency, I would go the extra mile and change the entire bindings to return the resulting `[out]` parameters by value.
I think this is the closest we can get to a pythonic experience.

**Comment by floli** [comment]
I agree with @fsimonis. In Python you don't use output parameters, just return (multiple) values.

**Comment by BenjaminRueth** [comment]
This means we will have to change the following functions:

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/bindings/python/precice.pyx#L328

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/bindings/python/precice.pyx#L352

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/bindings/python/precice.pyx#L369

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/bindings/python/precice.pyx#L393

Additionally, there is the following function, which looks like it should also be changed: 

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/bindings/python/precice.pyx#L214

But I do not really know the use-case of this function, though...

**Comment by uekerman** [comment]
There is also:

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/bindings/python/precice.pyx#L187
  
> https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/bindings/python/precice.pyx#L214
> But I do not really know the use-case of this function, though...

It can be used for dynamic meshes, currently not supported, but on the roadmap of @fsimonis.

**Comment by fsimonis** [comment]
We should also remove the size parameters and use the sizes of passed lists.
For multiple list arguments we can either assert equal list sizes or convert them to a list of tuples. The first option is probably easier to use.

**Comment by BenjaminRueth** [comment]
If we go from return by reference to return by value this will change the API. Therefore, we should have this change in the next major release.

**Comment by floli** [comment]
> If we go from return by reference to return by value this will change the API. Therefore, we should have this change in the next major release.

We are still talking about the python bindings only? Then I would just go forward and change the API. The Python bindings are probably not used so widely, compared to the C++/C interface. A major release of preCICE is probably still some time away and the python bindings are rather new and still fluid.

**Comment by BenjaminRueth** [comment]
I would also not do a major release just for the Python bindings (this is for sure an overkill), but just introduce the changes as soon as we are releasing 2.0.0. But we can also introduce this (python) API breaking change in the next 1.x Release, If nobody objects. Im fine with this.

**Comment by BenjaminRueth** [comment]
All Issues mentioned in https://github.com/precice/precice/issues/381 are related to this question: https://github.com/precice/precice/issues/364#issuecomment-491579978.

**Comment by BenjaminRueth** [comment]
We can already (partially) introduce this change in `v1.x.x`, by providing a wrapper:

```python
def read_block_scalar_data (self, data_id, size, value_indices, values): 
    values_return = self.v2_read_block_scalar_data(data_id, size, value_indices)
    values[:] = values_return[:]

def v2_read_block_scalar_data (self, data_id, size, value_indices): 
    #actual implementation calling 
    self.thisptr.readBlockScalarData (data_id, size, value_indices_, values_)
    ....
    return values
```

in `v2.0.0` we delete `read_block_scalar_data` and rename `v2_read_block_scalar_data` to `read_block_scalar_data`.
