### ISSUE TITLE
Get rid of outdated functions in Constants.*

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#365]
The following functions are not really useful anymore:

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/Constants.hpp#L9-L13

We can get rid of them. Don't forget to also remove them in the bindings.

**Comment by uekerman** [comment]
I would actually go one step further and remove `Contants.hpp` completely.

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/Constants.hpp#L15-L18

... could be moved to `SolverInterface` or we replace them by better solutions

https://github.com/precice/precice/blob/e480aef4e3a74ccd405f03a2770bee18cdb548e9/src/precice/Constants.hpp#L20-L21

... I don't know what this is for

**Comment by uekerman** [comment]
I think nobody uses `actionPlotOutput`

**Comment by BenjaminRueth** [comment]
> I think nobody uses `actionPlotOutput`

I tried to remove it, but then I got into trouble:

```
[ 65%] Linking CXX executable binprecice
libprecice.a(SolverInterfaceImpl.cpp.o): In function `precice::impl::SolverInterfaceImpl::initializeData()':
/home/benjamin/precice/src/precice/impl/SolverInterfaceImpl.cpp:321: undefined reference to `precice::constants::actionPlotOutput[abi:cxx11]()'
libprecice.a(SolverInterfaceImpl.cpp.o): In function `precice::impl::SolverInterfaceImpl::finalize()':
/home/benjamin/precice/src/precice/impl/SolverInterfaceImpl.cpp:442: undefined reference to `precice::constants::actionPlotOutput[abi:cxx11]()'
libprecice.a(SolverInterfaceImpl.cpp.o): In function `precice::impl::SolverInterfaceImpl::handleExports()':
/home/benjamin/precice/src/precice/impl/SolverInterfaceImpl.cpp:1540: undefined reference to `precice::constants::actionPlotOutput[abi:cxx11]()'
collect2: error: ld returned 1 exit status
CMakeFiles/binprecice.dir/build.make:244: recipe for target 'binprecice' failed
make[2]: *** [binprecice] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/binprecice.dir/all' failed
make[1]: *** [CMakeFiles/binprecice.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```
