### ISSUE TITLE
Extend logging by filter %ParticipantName%

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#376]
I think that the possibility to create independent logging files, one for each participant, would be useful.

# Why are logging files useful? Can we not just write the terminal output to a file?

Currently, we have an issue with the Fluent adapter, where Fluent just eats up all command line output that is created by preCICE. We found out, that we can circumvent this problem by using files for logging output. However, here the output of the two participants is mixed up, while the command line output is nicely separated (one terminal prints the output of participant one, another terminal prints the output of participant two).

# How should it look like?

In my opinion it would be good to be able to specify a filename and filter for the participant name. The resulting config should look like this:

```
<precice-configuration>
  <log enabled="true">
    <sink type="file" output="debug_Fluid.log" filter="%ParticipantName% == Fluid" enabled="false" />
    <sink type="file" output="debug_Solid.log" filter="%ParticipantName% == Solid" enabled="false" />
  </log>
  <solver-interface dimensions="3">
```

I am not an expert with boost.looging, therefore I hope that what I am proposing is possible from a technical point of view.

# Possible pitfall

The log files will be created in the folder, where the executable is started. This allows a workaround, if you currently want to create two log files with separated output: Just start the executables from different folders (e.g. start `solid` from the folder `Solid` and `fluid` from `Fluid`). You will get two log files (`Solid/logging.log` containing the log from `solid` and `Fluid/logging.log` containing the log from `fluid`).

If we add the functionality to create log files, where the output is filtered for the participants, this might result in empty log files in the respective folders (empty `Solid/debug_Fluid.log` and empty `Fluid/debug_Solid.log`). Creating empty files is no big problem, but ugly.

**Comment by fsimonis** [comment]
Good idea, but I would vote for the `Participant` to keep the name shorter.

@floli Does the the boost.logging file sink create a file on configuration or on the first write?

**Comment by floli** [comment]
> @floli Does the the boost.logging file sink create a file on configuration or on the first write?

It is created on opening the file.
