### ISSUE TITLE
Unexpected behaviour after using SolverInterface destructor

### ISSUE THREAD

**Issue by Dominanz** [precice/precice#378]
I have experienced a problem when allocating a SolverInterface object dynamically. The following lines of code reproduce my observation (at least on my machine):
```
SolverInterface* interface;
interface = new SolverInterface("SolverOne",0,1);
interface->configure("precice-config.xml");
delete interface;
interface = new SolverInterface("SolverOne",0,1);
interface->configure("precice-config.xml");
```
When doing this together with the config from the solverdummies, preCICE throws the following error:
``Participant "SolverTwo" can read/write data "Velocities" only once!``

I suspect that this behaviour is unintended. I would expect that, after destroying the old SolverInterface and deallocating its memory, I can allocate a new instance of SolverInterface and configure it again.
Searching the code of preCICE, I found that the error is thrown [here](https://github.com/precice/precice/blob/b44813661aa6ec74660c4310d3bad24cd929deea/src/precice/impl/Participant.cpp#L308). My guess would be that the destructor of the SolverInterface class doesn't work properly. It seems that the second SolverInterface created in the example code above encounters remnants of the previous one, causing it to throw the error.

This problem is probably very uncommon, since SolverInterfaces are allocated statically in most examples I have seen, so they are only destructed once the program exits anyway.
However, I encountered this problem while working on MATLAB bindings, where working with pointers is not really evitable. Since exiting MATLAB means ending the session, I encounter the problem whenever I try to run a program coupled with preCICE repeatedly in the same MATLAB session, which is very annoying (especially for testing and debugging). Therefore, I'd really appreciate a fix or a suggestion on how to prevent this error.

Thanks for any help!

**Comment by uekerman** [comment]
This is a known bug due to some static IDs preCICE uses. I have a workaround patch (but no proper solution) on my laptop, which I don't have with me. I can post my patch on Monday.

**Comment by Dominanz** [comment]
This would be welcome! Could you maybe give a few more details on where the problem originates? Maybe I find the time to have a look on that.

**Comment by BenjaminRueth** [comment]
As far as I understand the situation, here is the proposed workaround: https://github.com/precice/precice/commit/873a99f53c4554c21d4570bdfccc353dead4203f

However, this is not a proper solution and therefore, we do not want to merge it into develop and we cannot close this issue. @uekerman is this correct?

**Comment by uekerman** [comment]
All yes.
The proper solution will be #385 
Let's keep this open till we solved it in develop.

**Comment by fsimonis** [comment]
Reconstruction is possible after #1419
