### ISSUE TITLE
Bug in preconditioner after convergence in 1 iteration 

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#383]
I came across the following Segmentation fault:

![image](https://user-images.githubusercontent.com/5740604/57600129-38620d80-7559-11e9-9f38-f7bf42b031cb.png)

Debug output tells me that an assertion in `Preconditioner.hpp` is raised:

![image](https://user-images.githubusercontent.com/5740604/57600747-f8038f00-755a-11e9-8dd8-94b8e8f5ba31.png)

## How to reproduce it

* use precice https://github.com/precice/precice/commit/cd64044136eb74bf695a81fd48919eec7b9b0f23
* use waveform relaxation version of fenics-adapter https://github.com/precice/fenics-adapter/commit/5cc2dadb2e85d5611ab31506e10e4254436d68ab
* use the waveform relaxation example in https://github.com/precice/tutorials/commit/a3b7665e4df4443c55a89557a54f0758368f6940
* from folder `HT/partitioned-heat/fenics-fenics` in `precice/tutorials` run
```
heat.py -d -wr 5 5
heat.py -n -wr 5 5
```

## How to fix it

* use waveform relaxation example in https://github.com/precice/tutorials/commit/bc4eb52dca7d3581c2f038a6fd956ca49d81067a
* everything else as above

## What we already know about this error

If we try to reproduce this error in a setup where no waveform relaxation is used (i.e. remove [this line](https://github.com/precice/tutorials/blob/decda12cddd27e3173c47762998c46a815e0d006/HT/partitioned-heat/fenics-fenics/precice-config.xml#L57) in the config), everything works well.

**Comment by uekerman** [comment]
I was able to reproduce the problem with the setup of @BenjaminRueth. 

The convergence file of the second participants is:
```
Timestep  Iteration  resNorm(0)  resNorm(1)  resNorm(2)  resNorm(3)  resNorm(4)
1  1  0.0000000000000009  0.0000000000000013  0.0000000000000015  0.0000000000000016  0.0000000000000018
2  1  0.0567515926092959  0.0561241042936325  0.0555101368449787  0.0549092644674294  0.0543210787766795
```
which gives some idea where the problem might come from. In particular, I don't think that this is too much related with waveform relaxation. 

I'll try to reproduce the problem with an integration test.
