### ISSUE TITLE
C solver dummy includes preCICE in non-standard way

### ISSUE THREAD

**Issue by MakisH** [precice/precice#392]
The C solverdummy is inconsistent to the C++ and to what we have documented, as it tries to include `SolverInterfaceC.h`, instead of `precice/SolverInterfaceC.h` (and similarly for `Constants.h`):

https://github.com/precice/precice/blob/420e8d7938fa2103a9e933ee5e488bf47c058856/tools/solverdummies/c/solverdummy.c#L1-L2

**Comment by floli** [comment]
Problem: `precice/SolverInterfaceC.h` only works if you have installed preCICE. If you're working on the source tree, there is no root where `precice/SolverInterfaceC.h` resolves to the file in the source tree.

**Comment by BenjaminRueth** [comment]
* there is an inconsistency between source tree and installation
* if we use `make install`, `#include precice/SolverInterfaceC.h` works.)
* python? uses `import precice`, built with cython using `SolverInterface.hpp`
* this is a xSDK requirement: you need a scope for your environment (either `#include precice/SolverInterfaceC.h` or `#include precice_SolverInterfaceC.h`)
* openQuestion: How do users use preCICE? We should support both approaches, if needed (`#include precice/...` and `#include ...`)

**Comment by BenjaminRueth** [comment]
In https://github.com/precice/precice/pull/395 this is solved. Additionally, if we use `#include "SolverInterfaceC.h"` instead of `#include "precice/SolverInterfaceC.h"`, we get compiler warnings. See also https://github.com/precice/precice/pull/395/commits/a96c95a9860f381b9f38e91be28180b9ca84fe99
