### ISSUE TITLE
xSDK: Remove Signal Handlers

### ISSUE THREAD

**Issue by floli** [precice/precice#397]
xSDK required policy M6 mandates:

> M6. Each package should respect the decisions made by other previously called packages regarding system resources and settings. For example, each package may provide an API for changing the floating-point exception (FPE) and signal handlers, and even set them in a particular way by default, but there must be a way to prevent the change. Because it is impossible to determine the current state of the FPE and signal handlers and thus restore them to the current state after changing them, it is recommended that the xSDK packages adopt a common protocol for pushing and popping FPE and signal handlers.

right now, we unconditionally install signal handlers. They are used to delete connection info files and write out EventTimings logs.

**Comment by fsimonis** [comment]
According to [the docs](https://en.cppreference.com/w/cpp/utility/program/signal), installing a signal handler returns the old one.
We could try chain the signal handlers.

**Comment by floli** [comment]
After discussion with @fsimonis and several of my colleagues here, I have come to the conclusion, that we should refrain from using signals at all.

According to https://en.cppreference.com/w/cpp/utility/program/signal, the handler has a number of restrictions:

========================================
The behavior is undefined if any signal handler performs any of the following:

* call to any library function, except the following signal-safe functions (note, in particular, **dynamic allocation is not signal-safe)**: 
  * std::signal with the first argument being the number of the signal currently handled (signal handler can re-register itself, but not other signals).
  * member functions of std::numeric_limits
  * std::_Exit
  *  std::abort
  *  std::quick_exit
  *  The member functions of std::initializer_list and the std::initializer_list overloads of std::begin and std::end
   * std::forward, std::move, std::move_if_noexcept
   * All functions from <type_traits>
   * std::memcpy and std::memmove 
* access to an object with thread storage duration
* a dynamic_cast expression
* a throw expression
* entry to a try block, including function-try-block
* initialization of a static variable that performs dynamic non-local initialization (including delayed until first ODR-use)
* waits for completion of initialization of any variable with static storage duration due to another thread concurrently initializing it 
========================================

Due to the multitude of restrictions and the fact that we rely on calls to complex (boost) library, the current usage of signals is undefined. **For that reason, I vote for completely removing the signal handler as it is.**

**Comment by uekerman** [comment]
OK, sounds dangerous. Which implications would that have? Do we need other solution somewhere?

What I remember:
* (1) If you get a timeout on a cluster, you don't get the event timings
* (2) After a crash during initialization, there could be unwanted connection files
* What else?

With (2), we could probably life as it could happen anyway. For (1), we probably need a different solution, like writing information after init and then every X timesteps.

**Comment by floli** [comment]
Yes, these are the things the handler currently does. Anyway, I am for removing the handler ASAP and

* accept (2) as: If you exit unclean, you exit unclean (and therefore leave garbage around)
* put (1) in a new issue.

Ok?
