### ISSUE TITLE
boost asio::write, full buffer leads to deadlock 

### ISSUE THREAD

**Issue by uekerman** [precice/precice#40]
Verena reported the following problem: if 2 meshes need to be exchanged at initialization (e.g. 2 consistent mappings in master mode), we get a deadlock for a too big mesh size.
After some research, I found that this due to the non-blocking behavior of boost asio::write as soon as the send buffer is full. For small meshes this does not happen (e.g. FSI cases @davidsblom did on SuperMUC) , but for a moderate size this is already a problem. Verena used 3e6 vertices (on the coupling interface).  
A possible workaround would be to somehow increase the buffer size. Some short investigation showed that this typically is only possible with admin rights. We could try this on the MAC Cluster (Roland offered to help) or we could ask SuperMUC support. 
A real solution would be to separate the mesh communication from the mesh decomposition in the implementation and use a blocking variant. This is some work and might overlap with the local mesh communication @floli. I am not sure if it is worth the hassle at the moment, but we should keep an eye on this. 
Please note, that simply changing the MeshContext ordering in ```SolverInterfaceImpl::initialize``` is not enough as we need all ```provided``` meshes first for the preliminary mappings.

**Comment by gk780** [comment]
It would be nice to spend some time to find a workaround. The 'real-world' testcase ( the flow around the sphere) failed after some time without any motivation showing NANs only at the coupling interface ( I think it is not a stability problem of the euler flow in Ateles). Up to now, I thought this is due to the linearization and that the interface is to close at the flow, but also a larger domain could not proof it. Doing the analysis of the mapping, I figured out that using write conservative is bad (already for boundary at the  interface).  The testcase I am talking about has one interface consisting of 4 boundaries of the inner domain. Hence writing conservative could be even  worse. I would like to know if the testcase would work with reading consist....would also be nice for the symposium. Please, increase the priority a little bit ;)

**Comment by uekerman** [comment]
Just to avoid any misunderstanding: if you have matching meshes, consistent = conservative. @gk780 for the sphere testcase, you have strictly non-matching meshes, right?

**Comment by gk780** [comment]
ah ok. I have matching grids, for Ateles - Ateles coupling this is not a problem. 
Ok, hence write conservative should  not  be the problem why these NANs appear. Then priority is not that high ;)

**Comment by uekerman** [comment]
#44 is probably the same problem. i am resolving this one at the moment and then check #44 again.

**Comment by uekerman** [comment]
hopefully resolved, @gk780 can you please give it a try?

**Comment by gk780** [comment]
I recompiled precice and ateles ang get this error:

lineareuler domain:

> 
 Initialize preCICE
 | precice::impl::SolverInterfaceImpl::initialize()        | Setting up master communication to coupling partner/s
Run finished at Mon Feb 15 19:18:53 2016
Global runtime = 2378246ms / 2378s
Event                Count    Total[ms]     Max[ms]     Min[ms]     Avg[ms]   T%
Properties from all Events, accumulated
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::remove: No such file or directory: "/gpfs/work/pr84xu/di98taj2/ateles/testsuite/precice/acoustic_euler/sphere/production/sponge/new/.Ateles_euler-Ateles_acoustic.address"
forrtl: error (69): process interrupted (SIGINT)


euler domain:
> 
Fatal error in MPI_Info_set: Invalid MPI_Info value , error stack:
MPI_Info_set(117): MPI_Info_set(info=0x9c000001, key=romio_aggregator_list, value=0 16 32 48 64 80 96 112 128 144 160 176 192 208 224 240 256 272 288 304 320 336 352 368 384 400 416 432 448 464 480 496 512 528 544 560 576 592 608 624 640 656 672 688 704 720 736 752 768 784
MPI_Info_set(97).: Value is too long
Fatal error in MPI_Info_set: Invalid MPI_Info value , error stack:
MPI_Info_set(117): MPI_Info_set(info=0x9c000001, key=romio_aggregator_list, value=0 16 32 48 64 80 96 112 128 144 160 176 192 208 224 240 256 272 288 304 320 336 352 368 384 400 416 432 448 464 480 496 512 528 544 560 576 592 608 624 640 656 672 688 704 720 736 752 768 784
MPI_Info_set(97).: Value is too long
Fatal error in MPI_Info_set: Invalid MPI_Info value , error stack:
MPI_Info_set(117): MPI_Info_set(info=0x9c000001, key=romio_aggregator_list, value=0 16 32 48 64 80 96 112 128 144 160 176 192 208 224 240 256 272 288 304 320 336 352 368 384 400 416 432 448 464 480 496 512 528 544 560 576 592 608 624 640 656 672 688 704 720 736 752 768 784
MPI_Info_set(97).: Value is too long
Fatal error in MPI_Info_set: Invalid MPI_Info value , error stack:
MPI_Info_set(117): MPI_Info_set(info=0x9c000001, key=romio_aggregator_list, value=0 16 32 48 64 80 96 112 128 144 160 176 192 208 224 240 256 272 288 304 320 336 352 368 384 400 416 432 448 464 480 496 512 528 544 560 576 592 608 624 640 656 672 688 704 720 736 752 768 784
MPI_Info_set(97).: Value is too long
Fatal error in MPI_Info_set: Invalid MPI_Info value , error stack:
> 

I will check it without restarting, but it looks weird.

**Comment by gk780** [comment]
Ok, this was due to restart! WIthout IO is runs :) Guess we can close the ticket. Thanks!

**Comment by gk780** [comment]
Hmmm...maybe not! I still get this strange MPI error with Value to long. I am trying to read a restart file which should work. The last error statement of the euler domain is

> [mpiexec@i12r01a03] control_cb (../../pm/pmiserv/pmiserv_cb.c:773): connection to proxy 20 at host i12r03c40-ib failed
[mpiexec@i12r01a03] HYDT_dmxu_poll_wait_for_event (../../tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@i12r01a03] HYD_pmci_wait_for_completion (../../pm/pmiserv/pmiserv_pmci.c:501): error waiting for event
[mpiexec@i12r01a03] main (../../ui/mpich/mpiexec.c:1059): process manager error waiting for completion

And for the linear euler domain has this problem:

> [proxy:0:150@i12r05c22] HYDU_sock_connect (../../utils/sock/sock.c:268): unable to connect from "i12r05c22" to "i12r04a05" (No route to host)
[proxy:0:150@i12r05c22] main (../../pm/pmiserv/pmip.c:403): unable to connect to server i12r04a05 at port 41085 (check for firewalls!)

WIthout IO its working. Dont know if this is no precice related, but it is strange!

**Comment by uekerman** [comment]
but this has definitely nothing to do with this ticket. i'll close it. if we understand the above problem, let's open a new ticket
