### ISSUE TITLE
non-deterministic behavior of IMVJ PP due to error in Preconditioner

### ISSUE THREAD

**Issue by scheufks** [precice/precice#41]
The IMVJ method shows a non-deterministic behavior, i.e., non-deterministic convergence histories in parallel master-slave mode (for both, serial and vectorial scheme). This problem is not observed for the serial case, where the solvers run on a single processor, neither for the ILS method. 
Some tests have shown, that the non-deterministic behavior is somehow induced by an error in the preconditioner. Unkommenting all statements cotresponding to the precondititoner solves the problem. 
Note: This problem even exists for the serial system where the preconditioner always ought to be a no-op, i.e., identity.
TODO: Some further testing to localize the error (most probably some initialization problem - however, it is only present for the parallel case.)

@uekerman

**Comment by scheufks** [comment]
okay, further tests showed that the non-deterministic behavior persists even if the preconditioner is not active, i.e., uncommented.

**Comment by scheufks** [comment]
Update: 

With extensive testing and debugging, I found the error to be located in the function _multiplyNN() of the ParallelMatrixOperations class, used by IMVJPostProcessing for the multiplication of the Jacobian. This is also the place where the cyclic communication is used.
Test case: 3dTube with QR2 1e-2 filter, Preconditioner is disabled (commented out).

It turned out, that the error happens in the last cylce of the cyclic computation of the Jacobian, where the last rank (2) receives the W_til matrix from the first rank (0) and computes Wtil_0*Z_2. Now, something is going wrong in the asynchronous send or receive operation of Wtil_0 in cycle 1 (done by rank 1, sending/ rank2, receiving). If the error is present, the very last entry of the Wtil_0 matrix will not be sent/received correctly, but we observe a value similar to x.ye-320 (= zero). 
Things I found:
 * the error somehow depends on the timing of operations (the behaviour/frequency/iteration in which the error occurs changes, if debug or printout statements are added)
 * A further idea is that the computation/initialization/etc could somehow interfere with the send/receive operation ... to test this I did some more runs, examining:
  - if the copying of the leftMatrix_rcv is somehow delayed (lazy evaluation, expressions) by Eigen and thus interferes with the send/receive operations. After doing copying the matrix by hand the error persists. 
  - if the re-initialization of the leftMatrix_rcv previous to the aReceive(...) method is somehow delayed and thus overlaid with the receive operation. Tried several things: 
   * If leftMatrix_rcv =Matrix::Zero() is used the error happen quite often. 
   * If leftMatrix = Matrix(...) is used (i.e. no initialization, NaNs by compile flag) the error persists but happens seldomly. 
   * If the Zero(..) initialization is used followed by a no-op with enforced evaluation,  i.e.,  leftMatrix_rcv = (leftMatrix_rcv * 0).eval(), the error persists but happens very seldom.
 - if the leftMatrix_rcv matrix is copied twice, one copy for the aSend(..) and one copy for the block multiplication block = leftMatrix_rcv * rightMatrix, such that the send buffer is not touched by possible changes during the Eigen multiplication, the error persists. (The eigen multiplication is also defined as const function, i.e., there should be no changes....)
 - finally, I tried the following: Adding a sendRequest.wait() statement prior to the multiplication of the local block, i.e., block = leftMatrix_rcv * rightMatrix. This has the same intention than copying the leftMatrix_rcv twice as explained above. Tough, after a excessive testing of 25 runs, the convergence numbers stay the same within the first time step. Switched also to the no-initialization case leftMatrix_rcv = Matrix(r,c). In the very last run I got a floating point exception with this configuration. (no reason obvious, jet).

**Comment by scheufks** [comment]
convergence history for the first time step, that is assumed to be correct:
```
1  1  1.0000000000000000  1.0000000000000000  
1  2  1.0231979756176932  1.0453568981834458  
1  3  1.0735782097415474  4.7831113263641729  
1  4  1.1193520217011392  4.4206280954240729  
1  5  1.0555036017607839  3.1233357517156932  
1  6  0.6782626248577572  1.7653031173072500  
1  7  0.2563552437115172  0.6217832929326826  
1  8  0.1730183336927339  0.2367939282715111  
1  9  0.0384579026664663  0.1105728909422196  
1  10  0.0081300110583061  0.0227567432776649  
1  11  0.0016697012613288  0.0045193909778549  
1  12  0.0003294684666720  0.0008692287072652  
1  13  0.0000619427678035  0.0001621784850257  
1  14  0.0000112850348113  0.0000289478242419
```

**Comment by uekerman** [comment]
good job so far!
should we have a look together next week?
at some point on tuesday?

**Comment by scheufks** [comment]
added a unit test to ParallelMatrixOperationsTests.cpp that multiplies the Z and Wtil matrices from the 3dTube (OF) for the first 5 iterations. The error could be reproduced when the communicator and the cyclic comm were set up again for each multiplication. Not sure if this is the only way the error can be reproduced.

**Comment by floli** [comment]
Just as a side note, ```testVIQNIMVJpp``` always fails on my (and other Arch Linux machines).

**Comment by uekerman** [comment]
Currently, we cannot really reproduce the issue.
