### ISSUE TITLE
Error handling: Eigen assertion fails, if wrong value_index is provided

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#415]
If we provide a wrong `value_index` to the preCICE API, an assertion in Eigen is raised:

```
python3: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:408: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
```

This error occurs for the following functions:

* `read_block_scalar_data`
* `write_block_scalar_data`
* `write_scalar_data`
* `read_scalar_data`

I reproduced this behaviour using the preCICE python API, but I assume that it also occures using other language bindings.

# What we should do

Handle the wrong input (`value_index` is invalid) early and give a useful error message, like for example:
```
The value_index x is invalid for mesh with data_id y and participant z
```

**Comment by BenjaminRueth** [comment]
If the lines with `# --> assertion fail` are active, the above mentioned assertion fail occurs.

https://github.com/precice/precice/blob/f4d554b2d7cc48aa75b2c8c0870f5a65c046622f/src/precice/bindings/python_future/test/solverdummy.py#L89-L97

**Comment by fsimonis** [comment]
We validate the `dataID`s as well as their requirements (use/provide) at the interface.

This looks like you try to access the data values beyond the boundaries `[0, size-1]`. So you [`value_indices`](http://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html#a8e9d02286f930b2cf5cabab75ec5b104) seem to be wrong.

We should probably sanitize the indices too.

**Comment by BenjaminRueth** [comment]
> We validate the `dataID`s as well as their requirements (use/provide) at the interface.
> 
> This looks like you try to access the data values beyond the boundaries `[0, size-1]`. So you [`value_indices`](http://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html#a8e9d02286f930b2cf5cabab75ec5b104) seem to be wrong.
> 
> We should probably sanitize the indices too.

Sorry, I mixed up the wording. I meant the `vertex_id`, like you described. Sanitizing the indices sounds good.
