### ISSUE TITLE
Turn EventTimings into a CMake submodule

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#419]
The [EventTimings project](https://github.com/precice/EventTimings) is a fully fledged CMake project.
We should consider refactoring it out of preCICE by placing it into a submodule.

**Comment by MakisH** [comment]
If we include EventTimings as a submodule, would it then also make sense to do the same for our [`thirdparty/`](https://github.com/precice/precice/tree/develop/thirdparty) dependencies? This should then also more nicely separate the preCICE code from the dependencies code.

**Comment by fsimonis** [comment]
We kind of agreed to take another path by simplifying the project.
