### ISSUE TITLE
3 field coupling with Ateles 

### ISSUE THREAD

**Issue by gk780** [precice/precice#42]
I am trying to run a 3 field coupling with ateles, having a navier-stokes (ns), a euler (ee) and a lineareuler (le) domain, each coupling is one way and parallel explicit

What should happen

Ateles_ns : 	write  rho_ns, v_ns, p_ns
Ateles_ee:  	read rho_ns, v_ns, p_ns
                    	write  rho_ee, v_ee, p_ee
Ateles_le: 	read rho_ee, v_ee, p_ee

What happens (running all domains with 2 mpirank) :

Ateles_ns --> rechnet 2 iterationen, non-physical state (failing is fine, can be due to ateles)
Ateles_ee --> stop direct after start of simulation loop 
Ateles_le --> starts computing, run for more than 200 iteration, then I stoped it manually

I have no idea, why the euler domain does not read from precice the NS values  and why the linear euler domain is running at all.
I copied the testcase into the shared folder: shared_exafsa_work/ns_ee_le including the output files ns.out, ee.out and le.out, which have already debug statements from ateles ( what is read and wrote to precice) as well as precice debug statements.

**Comment by uekerman** [comment]
verena, can you please also add the job-script to the shared folder?
and, if possible, also your executables (maybe you have even compiled precice in debug?)

**Comment by gk780** [comment]
I run it on our local machine, no jobscript...but I can also try it on supermuc, there I have a debug version compiled.

**Comment by uekerman** [comment]
can you please add these debug statements:
```
   <log-filter target="debug" component="" switch="off"/>
   <log-filter target="info"  component="" switch="on"/>
   <log-filter target="debug" component="precice::impl::SolverInterfaceImpl" switch="on"/>
   <log-filter target="debug" component="precice::cplscheme::CompositionalCouplingScheme" switch="on"/>
   <log-filter target="debug" component="precice::cplscheme::ParallelCouplingScheme" switch="on"/>
   <log-output column-separator=" | " log-time-stamp="no"  
               log-time-stamp-human-readable="yes" log-machine-name="no" 
               log-message-type="no" log-trace="yes"/> 
```

**Comment by uekerman** [comment]
thanks!

**Comment by uekerman** [comment]
and please run in serial (as you can also reproduce the problem in serial, it's not a master problem)

**Comment by gk780** [comment]
ok, there is the result of a serial run with precice debug statements in the shared folder now. Additionally there are job scripts and executables ( ateles_debug = ateles with precice debug version).

**Comment by uekerman** [comment]
i reran your case (with your executables) in a couple of different variations. i could not (exactly) reproduce the behavior from above, but get:

**ns**: runs 4 or 5 timesteps, throws an error since sockets connection breaks
**ee**: crashes in ateles after ```initData```, after first ```isReadDataAvailable```, but before first ```readBlockScalarData```,  
**le**: throws error since sockets connection breaks in first ```advance```

the 2 errors in **ns** and **le** are just logical follow-ups from the crash in **ee**. 
@gk780 can you please debug around your very frist read statement in **ee**? i guess you might have a problem around there.

what you observed above is slightly different from my observation, but maybe could also be explained by this. maybe in release **le** still reads zeros from the socket though the connection is already dead.

**Comment by gk780** [comment]
ok, I found the bug in Ateles. Sorry that I did not see it at the beginning....intel gives better debug statements than gcc (which is available on our system) ;). I am running  a test job with more time steps.

**Comment by gk780** [comment]
... but really strange was that in the first runs from my side Ateles_le was running like hell, without Ateles_ee could deliver values at the interface. Did you have an explanation for that? Did you change something in the precice.xml?

**Comment by uekerman** [comment]
not sure why this is the case, i didn't change anything that could concern this point. main difference is that your first case was in release mode. my best guess is, like mentioned above, that then **le** just reads zeros from the socket. keep us posted how the 3-field coupling goes.
if there is another problem, we can also re-open this issue

**Comment by gk780** [comment]
thanks.....the run was successful. I need to fix a bug in parallel Navier-Stokes and then I can run larger testcases and let you know.

**Comment by uekerman** [comment]
hurray, i want videos!
