### ISSUE TITLE
Versioning to differentiate between release, development, and release candidate

### ISSUE THREAD

**Issue by MakisH** [precice/precice#424]
Currently, we increase the version number (displayed at runtime), only for releases.

This causes the following problems:

1. Only by looking at the output, we don't know if a user (or we) uses the respective release (e.g. `1.4.1`) or a later state from another branch (e.g. `develop`, which would be `1.4.1 + changes`).

2. While testing our release candidate, it is not easy to say that we are testing against the correct version.

Both problems are prevalent when we have multiple versions of preCICE installed (in different paths), or a broken previous installation.

I propose the following system:

* `1.4.1-develop` for the develop branch after release 1.4.1 (feel free to adjust for other branches). **Question:** Should we use `past-develop`, or `expected-develop`?
* `1.5.0-RC1` for the release candidate that we are testing. Every time a review is re-requested, `RC++`.
* `1.5.0` only for the specific commit that is released. Immediately afterwards, it should change to `1.5.0-develop`.

I don't have any specific examples from other projects in mind, but I think that this system would be reasonable and it would reduce our stress during testing. What do you think?

**Comment by floli** [comment]
>    1.4.1-develop for the develop branch after release 1.4.1 (feel free to adjust for other branches). Question: Should we use past-develop, or expected-develop?

No, `1.4.1-develop` is fine.

>    1.5.0-RC1 for the release candidate that we are testing. Every time a review is re-requested, RC++.

Use `1.5.0-rc1` in small caps. That is the release candidate **for** 1.5, correct?

>    1.5.0 only for the specific commit that is released. Immediately afterwards, it should change to 1.5.0-develop.

:+1:

**Comment by MakisH** [comment]
I agree with the lowercase `rc1` and yes, `1.5.0-rc1` would be release candidate **for** 1.5.

**Comment by uekerman** [comment]
I completely agree with the suggestion. 

> 1.4.1-develop for the develop branch after release 1.4.1 (feel free to adjust for other branches). Question: Should we use past-develop, or expected-develop?

1.4.1-develop, so `past-develop`

What would be really helpful: If we only had one single location `version.txt` where we would need to update this. Currently we have:
* CMakeLists.txt
* SConstruct
* `src/precice/bindings/python/setup.py `

**Comment by fsimonis** [comment]
xSDK requires us to provide a commit id along the version #261. We could just print this in addition to the preCICE version.

Automatically generating the `-develop` suffix is more tricky. We need a `tag <-> commit` association which we could fetch from git or put in a file somewhere.

I would just print the commit hash. Then everyone knows exactly what version he is dealing with. Everything else requires additional manual steps.

**Comment by MakisH** [comment]
I also like the idea of printing a commit hash (at least for the development variant), but we should make sure that we still have clear version numbers for the releases. If we can get the commit id, then I would say we just change the release number for the precompiled packages (again manually).

Accessing the information from Git could be a bit tricky (especially if the user simply gets the code as an tar/zip archive), so I would be happy just with the aforementioned manual approach. We eitherway do it for every release.

Btw, I have used a code that could display the commit number, but it was built with a custom python script, not with CMake. It should be doable, though, I guess.

**Comment by fsimonis** [comment]
I developed a local prototype which uses the output of `git describe --tags --dirty`.
Using the prototype of this library, the solverdummy outputs the following:
```
Starting SolverDummy...
preCICE: This is preCICE version 1.5.1
preCICE: Revision info: v1.5.0-31-g487e6bf6-dirty
```
The format being:

| | |
| --- | --- |
`v1.5.0`| last tag
`31`| commits since last tag
`g487e6bf6` | hash of last commit 
`dirty` | there are uncommitted changes

Does this check all the boxes for you?

**Comment by MakisH** [comment]
- [x] this
- [x] looks
- [x] great
- [ ] I don't know how you implemented this, but make sure that it would also work for people that got the code as an archive (e.g. no Git) and of course people that just install binaries.
