### ISSUE TITLE
Add BUILD_SHARED_LIBS as option

### ISSUE THREAD

**Issue by floli** [precice/precice#425]
Right now you can explicitly set it when calling cmake
```
cmake -DBUILD_SHARED_LIBS=on
```
but when using a GUI, such as ccmake or cmake-gui it does not appear as an option, even not when enabling advanced options using `t`.

Therefore I propose to add as an option.

@fsimonis  What's your opinion?

**Comment by fsimonis** [comment]
Just realize that they even mention this in the doc.
Good idea, let's do this! 

https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html
