### ISSUE TITLE
Incompatibility with Boost 1.70.0 (Boost Asio)

### ISSUE THREAD

**Issue by MakisH** [precice/precice#426]
I noticed this error when trying to build with Spack using the latest versions of everything and another user got the same while building normally.

[preCICE-Boost170.txt](https://github.com/precice/precice/files/3272107/preCICE-Boost170.txt)

This is also relevant to our CI, since we should have a system to catch any issues from the latest dependencies. We kind of do this when building with Arch, but we still have a fixed Boost version there.

**Comment by fsimonis** [comment]
There are a few issues accumulating here:

1) We unnecessarily used the implementation details of boost asio which lead to the template errors.
2) Boost 1.70.0 generates a CMake Config with a differing set of variables resulting in link errors
3) The FindModule and new Config provide different targets for the header only libraries

I fixed those issues and tested with 1.68.0 and 1.70.0
You can find a potential fix here https://github.com/fsimonis/precice/tree/fix-boost
