### ISSUE TITLE
Replace precice/src/precice/bindings/python_future/test/solverdummy with (mocked) unit tests

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#427]
Currently, this solverdummy is not used for testing at all. It has been introduced in https://github.com/precice/precice/pull/379 for basic testing.

**Comment by BenjaminRueth** [comment]
https://github.com/precice/precice/pull/379 is not merged yet.

**Comment by BenjaminRueth** [comment]
Since #420 introduced unit tests for the bindings and we run the solverdummies in the systemtests anyway: Do we actually still need this test case? Or can we just close this issue and delete everything in `precice/src/precice/bindings/python_future/test/solverdummy`?

**Comment by uekerman** [comment]
Well, we want an automated test of the solverdummy in  `tools/solverdummies`, right?
It's not only to test the bindings, but also to test whether the dummy works. 
Everything in `precice/src/precice/bindings/python_future/test/solverdummy` can probably be deleted.

**Comment by BenjaminRueth** [comment]
I agree that the main purpose of testing the `tools/solverdummies` is to make sure that they can be installed and work. That the bindings are tested by `tools/solverdummies` is a nice side effect but not the main purpose. The `tools/solverdummies` do not provide a comprehensive test of the bindings API anyway (and if they would, they would not be a nice example anymore).

`precice/src/precice/bindings/python_future/test/solverdummy` gives us the possibility to test as much as possible in a "real" setting without a mocked preCICE, since the intention here is not to provide a nice and easy example, but to actually test the bindings. 

Comparing [`tools/solverdummy`](https://github.com/precice/precice/blob/develop/tools/solverdummies/python_future/solverdummy.py), [`precice/src/precice/bindings/python_future/test/solverdummy`](https://github.com/precice/precice/blob/develop/src/precice/bindings/python_future/test/solverdummy/solverdummy.py) and the [unit tests](https://github.com/precice/precice/blob/develop/src/precice/bindings/python_future/test/test_bindings_module.pyx) shows that some functions would not be tested, at all, if we remove `precice/src/precice/bindings/python_future/test/solverdummy`:

* [`set_mesh_vertex`](https://github.com/precice/precice/blob/f6dc80a9410e96a875dace8596a3727b1f24a872/src/precice/bindings/python_future/test/solverdummy/solverdummy.py#L55)

* [`get_mesh_vertex_size`](https://github.com/precice/precice/blob/f6dc80a9410e96a875dace8596a3727b1f24a872/src/precice/bindings/python_future/test/solverdummy/solverdummy.py#L59)

* [`get_mesh_vertices`](https://github.com/precice/precice/blob/f6dc80a9410e96a875dace8596a3727b1f24a872/src/precice/bindings/python_future/test/solverdummy/solverdummy.py#L63)

* [`get_data_id`](https://github.com/precice/precice/blob/f6dc80a9410e96a875dace8596a3727b1f24a872/src/precice/bindings/python_future/test/solverdummy/solverdummy.py#L71)

I see two possibilities:

* add these functions to the unit tests and delete `precice/src/precice/bindings/python_future/test/solverdummy`. This means that all our testing for the bindings will be based on the mocked preCICE interface.
* don't add them to the unit tests and add `precice/src/precice/bindings/python_future/test/solverdummy` to automated testing. In this case we have a more complex testing framework for the bindings, but we also use the "real" preCICE interface, if possible.

**Comment by uekerman** [comment]
> add these functions to the unit tests and delete precice/src/precice/bindings/python_future/test/solverdummy. This means that all our testing for the bindings will be based on the mocked preCICE interface.

... is the cleaner solution, right? (and by clean I mean in particular that it is easier and more sustainable to generalize for all other bindings as well)

In the end, from the view point of the bindings, there should be no difference between the mocked and the real preCICE interface. Otherwise, the mocking is not correct, right?

**Comment by BenjaminRueth** [comment]
The methods I mentioned in https://github.com/precice/precice/issues/427#issuecomment-508676816 are now tested via unit tests. 

@fsimonis It would be interesting to check for the change in test coverage between 050f7bb47aa5e41e9d236a35f669965813867466 (solverdummy removed) and 0907bef96f89e118aad5c29624514fe1da95e9a0 (solverdummy + unit tests exist). If I did everything correctly, there should not be a degradation :crossed_fingers:
