### ISSUE TITLE
Check timings for different mapping configurations

### ISSUE THREAD

**Issue by gk780** [precice/precice#43]
Long time ago, I run an investigation of the Load Balancing by running the same testcase with a fixed number of processes for one participant and then adapt the number of processes for the other participant.  The timings where quite nice, and you could nicely see that for some configuration one participant was idling and dor other configurations the other  participant was idling. You could find the appropriate number of processes to minimize the overall runtime and maximize the efficiency.

![image](https://cloud.githubusercontent.com/assets/16699546/12677206/988c64fe-c697-11e5-9618-0795f861df65.png)

I rerun the testcase with the develop branch, changeset: 617c435 - (HEAD -> develop, origin/develop, origin/HEAD) Add an explicit flush to the EventTimings (11 days ago) <Florian Lindner>. 
Now, the timings which are spend in advance ( measured with Eventtimings.log)  are really bad and you do not see any different for the configurations:

![image](https://cloud.githubusercontent.com/assets/16699546/12677219/ab868c60-c697-11e5-8ced-197928fe3c75.png)

I did not change the testcase, I only rerun the tests. The data mapping is done by the participant acoustic. I copied the testcase to the shared folder: shared_exafsa_work/loadbalancing

Second observation from my side:

I run a 2d testcase which a rather small interface ( 2* 1500 points, matching grid). When I run the testcase with data mapping of each participant ( both do a read consistent) it is quite fast, and for a specific number of processors for each domain, I get a restart file (0.5s of simulation time) in almost 5 minutes. When I change the data mapping to only one particpant ( read consistent, write conservative) , for the same number of processes, one restart file takes now more than 2 h! And also Eventtimings.log state that around 80% of the time is spend in advance.

```
# Run finished at Mon Jan 25 09:40:37 2016
# Eventname Count Total Max Min Avg T%
"GLOBAL" 1 217797 217797 217797 217797 100
"M2N::acceptMasterConnection" 1 16516 16516 16516 16516 7
"MasterSlave::broadcast" 2 0 0 0 0 0
"advance" 2000 176169 259 41 88 80
"broadcast mesh" 1 0 0 0 0 0
"feedback mesh" 1 21 21 21 21 0
"filter mesh" 1 0 0 0 0 0
"initialize" 1 17701 17701 17701 17701 8
"initializeData" 1 13 13 13 13 0
"receive global mesh" 1 12 12 12 12 0

# Run finished at Mon Jan 25 09:40:37 2016
# Eventname Count Total Max Min Avg T%
"GLOBAL" 1 215630 215630 215630 215630 100
"M2N::requestMasterConnection" 1 13 13 13 13 0
"M2N::requestMasterConnection/Publisher::read" 1 13 13 13 13 0
"MasterSlave::broadcast" 2 0 0 0 0 0
"advance" 2000 173611 112 44 86 80
"gather mesh" 1 67 67 67 67 0
"initialize" 1 1223 1223 1223 1223 0
"initialize/PointToPointCommunication::requestConnection/request/Publisher::read" 1 130 130 130 130 0
"initialize/PointToPointCommunication::requestConnection/synchronize/Publisher::read" 1 28 28 28 28 0
"initializeData" 1 74 74 74 74 0
"send global mesh" 1 0 0 0 0 0 
```

I think this is really weird. Can you test the timing and data mapping? Was there any big change?

**Comment by uekerman** [comment]
ok, so this is really weird.
i was able to reproduce the problem.
but i highly assume that this a bug in the time measurement in preCICE. so preCICE is not really slow here. 
i get the correct timings, thought, be simply adding a ```e.stop``` at the end of ```SolverInterfaceImpl::advance```.
@floli can you please have a look at this?

@gk780 can you also please provide the 2d case? i am not so sure if those 2 problems are connected.

**Comment by gk780** [comment]
The 2d testcase is in the shared_folder called jet_2d. It is actually the testcase where I have the problem with the initialization  depending in the mapping #44.

**Comment by floli** [comment]
I see no obvious problem with the EventTimings. My only guess would be to rename the second Event e declaration at line 466 to something else, e.g. e1. Maybe it shadows the first variable and cause problems with the destructor.

precice::testMode should be false during the runs, I assume.

**Comment by uekerman** [comment]
renaming the event did not do the job. actually, i observed that the run time does indeed increase.
for 500 timesteps, with ```stop``` 77s, without 132s. all that time is apparently spend in the destructor?
@floli can you take over this issue?
i will have a look at the 2d testcase. i think that one is not related with the problem. i will report on it at #44 then.

**Comment by floli** [comment]
So what happens if you disable the barriers:
```
Event e("advance");
```

**Comment by uekerman** [comment]
then, it works, i.e. we get the small timings. but why does the barrier influence the timing so much.
@gk780 you have some global barrier in ateles as well, right?

**Comment by gk780** [comment]
In ateles, there is only one barrier after the initialization. I added some barrier for measuring timings, but since precice is doing this job, there are removed.

**Comment by gk780** [comment]
I rerun the testcase mentioned at the beginning with the new version of precice (4bd2831 ). The timings are still not what I have expected. 

![image](https://cloud.githubusercontent.com/assets/16699546/13400755/88fcf21c-df09-11e5-87a2-c1cd45b87d17.png)

Again, what do you see.... I fixed the number of CPU cores for the euler domain and play around with the number of cores for the acoustic domain. Using a lot of cores for the acoustic domain, means less work per cpu and acoustic domain should be fast (--> idling), the less cores used for the acoustic domain the more work is to be done and euler domain should wait for it.  'time in coupling' is the number Eventtimings are measuring for advance. 

Now, everything is faster, nice :) But the timings are strange, or? There is not so much changing...
For 560 core is not understandable (but also I did only one ran, hence don't know how meaningful it is). 

More ideas? Why was is working for the precice version above ( where I don't know which version it was). It now everything so optimize that we don't see a difference?

**Comment by gk780** [comment]
Did you maybe exclude waiting/idling times from Eventtimings.log @floli ?

**Comment by floli** [comment]
No. The code is rather simple, it just counts the time between construction and destruction of the object, resp. it's start() and stop() methods.

**Comment by scheufks** [comment]
maybe it's the missing barrier in the Event!? Why is this Event not a barrier? Is there a reason?

`
double SolverInterfaceImpl:: advance
(
  double computedTimestepLength )
{
  preciceTrace1("advance()", computedTimestepLength);

  Event e("advance");

  m2n::PointToPointCommunication::ScopedSetEventNamePrefix ssenp(
      "advance"
      "/");
`

**Comment by gk780** [comment]
And? Any progress? Could you reproduce the Eventtimings I got? Or do I use / compile preCICE wrong?

**Comment by gk780** [comment]
Florian is working on event timings... he played around with event timings and barriers and now every simulation ( @floli , please correct me) failed at the end of Ateles with

```
 Done with simulation at:
 iterations:           80
 simTime   :    8.0000000000000060E-007
 wallClock :    380.99998116493225     

SUCCESSFUL run!
--------------------------------------------------------------------- 
Operating system error: Cannot allocate memory
Allocation would exceed memory limit
```

I am pretty sure that this is not an Ateles error. I did a lot of memory measurements and Ateles has maximum memory usage during initialization and then constant. 

Anybody know the problem?

**Comment by uekerman** [comment]
if i remember correctly, i got similar errors for the ateles cube. always some kind a overflow errors. those were not deterministic, though. 
in debug mode, it should be easy to determine when exactly this error is thrown, right?

**Comment by uekerman** [comment]
i added the sync for the events [https://github.com/precice/precice/commit/bb3455d9b6403cb75a11505ad9e2c5e1266f075c again]. they sure make no sense without. then, normally, this issue should be fixed. at least it worked for me for the jet testcase.
