### ISSUE TITLE
Hanging at initialize when both participant do mapping

### ISSUE THREAD

**Issue by gk780** [precice/precice#44]
When I use precice, and both participants do the data mapping ( read consistent), often the simulation hangs here: 

 ```
Initialize preCICE
 | precice::impl::SolverInterfaceImpl::initialize()        | Setting up master communication to coupling partner/s
 | precice::impl::SolverInterfaceImpl::initialize()        | Coupling partner/s are connected
 | precice::geometry::CommunicatedGeometry::sendMesh()     | Gather mesh AcousticSurface_euler
 | precice::geometry::CommunicatedGeometry::sendMesh()     | Send global mesh AcousticSurface_euler
 | precice::geometry::CommunicatedGeometry::receiveMesh()  | Receive global mesh AcousticSurface_acoustic
 | precice::geometry::BroadcastFilterDecomposition::broadcast() | Broadcast mesh AcousticSurface_acoustic
 | precice::geometry::BroadcastFilterDecomposition::filter() | Filter mesh AcousticSurface_acoustic
 | precice::geometry::BroadcastFilterDecomposition::feedback() | Feedback mesh AcousticSurface_acoustic
 | precice::impl::SolverInterfaceImpl::initialize()        | Setting up slaves communication to coupling partner/s
 | precice::impl::SolverInterfaceImpl::initialize()        | Slaves are connected
 | precice::impl::SolverInterfaceImpl::initialize()        | it 1 of 1 | dt# 1 of 200000000 | t 0 | dt 1e-05 | max dt 1e-05 | ongoing yes | dt complete no | write-initial-data |
 ```
and the acoustic domain:
 ```
 Initialize preCICE
 | precice::impl::SolverInterfaceImpl::initialize()        | Setting up master communication to coupling partner/s
 | precice::impl::SolverInterfaceImpl::initialize()        | Coupling partner/s are connected
 | precice::geometry::CommunicatedGeometry::sendMesh()     | Gather mesh AcousticSurface_acoustic
 | precice::geometry::CommunicatedGeometry::sendMesh()     | Send global mesh AcousticSurface_acoustic
 | precice::geometry::CommunicatedGeometry::receiveMesh()  | Receive global mesh AcousticSurface_euler
 | precice::geometry::BroadcastFilterDecomposition::broadcast() | Broadcast mesh AcousticSurface_euler
 | precice::geometry::BroadcastFilterDecomposition::filter() | Filter mesh AcousticSurface_euler
 | precice::geometry::BroadcastFilterDecomposition::feedback() | Feedback mesh AcousticSurface_euler
 | precice::impl::SolverInterfaceImpl::initialize()        | Setting up slaves communication to coupling partner/s
 | precice::impl::SolverInterfaceImpl::initialize()        | Slaves are connected
 | precice::impl::SolverInterfaceImpl::initialize()        | it 1 of 1 | dt# 1 of 200000000 | t 0 | dt 1e-05 | max dt 1e-05 | ongoing yes | dt complete no | write-initial-data |
```

It is a rather small testcase,2d with 2*1500 points at the interfaces, matching grids.

Using debug flags, this is a output where it stops: 
```
precice::com::SocketCommunication::acceptConnectionAsServer() | (72) Leaving (file:src/utils/Tracer.cpp,line:27)
 | precice::com::SocketCommunication::getRemoteCommunicatorSize() | (72) Entering  (file:src/utils/Tracer.cpp,line:21)
 | precice::com::SocketCommunication::getRemoteCommunicatorSize() | (72) Leaving (file:src/utils/Tracer.cpp,line:27)
 | precice::com::SocketCommunication::receive(int)         | (72) Entering rankSender=0 (file:src/utils/Tracer.cpp,line:21)
 | precice::com::SocketCommunication::receive(int)         | (72) Leaving (file:src/utils/Tracer.cpp,line:27)
 | precice::m2n::PointToPointCommunication::acceptConnection() | (72) Leaving (file:src/utils/Tracer.cpp,line:27)
 | precice::m2n::M2N::acceptSlavesConnection()             | (72) Leaving (file:src/utils/Tracer.cpp,line:27)
 | precice::cplscheme::ParallelCouplingScheme::initialize() | (72) Entering startTime=0, startTimestep=1 (file:src/utils/Tracer.cpp,line:21)
 | precice::cplscheme::ParallelCouplingScheme::initialize() | (72) Leaving (file:src/utils/Tracer.cpp,line:27)
 | precice::utils::Parallel::synchronizeProcesses()        | (72) Entering  (file:src/utils/Tracer.cpp,line:21)
```

I figured out that for jobs where both participants are < 64 processes, it is running fine.  The strange part is, that same executable, same input files from the solver, same precice config and same job script, it is sometimes running. 

I worked a lot with Mohammed Shaheen (IBM support at LRZ)  on this, but from the machine support, he could not fine any problem. 

I am pretty sure that the problem is due to the data mapping on one participant. When I change the read consistent to write conservative of the other participant, I never have a problem at that point. 

This is quite urgent, since I want to run simulations :) and the data mapping on one participant is really slow ( --> issue 43) .

**Comment by uekerman** [comment]
with your executable, i can reproduce the issue. with mine, however, it crashes here:
```
 +-------------------------------------------+

  - Abort Criteria:
  stop_file:


  steady_state: F

  - Status:
 +-------------------------------------------+
 Loading communication pattern:
 isend_irecv
forrtl: severe (168): Program Exception - illegal instruction
Image              PC                Routine            Line        Source
my_ateles          00000000010A2171  Unknown               Unknown  Unknown
my_ateles          00000000010A08C7  Unknown               Unknown  Unknown
my_ateles          000000000104BED4  Unknown               Unknown  Unknown
my_ateles          000000000104BCE6  Unknown               Unknown  Unknown
my_ateles          0000000000FFB0B6  Unknown               Unknown  Unknown
my_ateles          0000000001000011  Unknown               Unknown  Unknown
libpthread.so.0    00002B2D1558B850  Unknown               Unknown  Unknown
my_ateles          00000000008F23C8  Unknown               Unknown  Unknown
my_ateles          0000000000936959  Unknown               Unknown  Unknown
my_ateles          0000000000504674  Unknown               Unknown  Unknown
my_ateles          00000000004E0578  Unknown               Unknown  Unknown
my_ateles          000000000042DE27  Unknown               Unknown  Unknown
my_ateles          000000000042D94E  Unknown               Unknown  Unknown
libc.so.6          00002B2D157B7C36  Unknown               Unknown  Unknown
my_ateles          000000000042D7E9  Unknown               Unknown  Unknown
```

any idea what happens?

**Comment by gk780** [comment]
I have no idea.  After loading of communication pattern, precice infomation gets loaded like:

```
 Loading precice data
* preCICE asseccor = "Ateles_acoustic"
* preCICE configFile = "precice.xml"
```

and then restart information. Do you have restart folder or comment the restart table out in Ateles.lua? Which version of ateles are you running? Did you compiled it with precice support or without? Can you paste your configure command?

**Comment by uekerman** [comment]
restart is not the issue, i commented the lines in the configs. i use the ateles version from saturday, configure just as you did - with precice. the exact same ateles executable works for the loadbalancing case.

**Comment by gk780** [comment]
Ok, this is strange!

Can you please increase the logging level in the ateles.config to 10 like  `logging = { level = 10 }` and rerun the simulation. At least we get the place where it really crashed.

**Comment by uekerman** [comment]
i don't get more output. do i need ateles in debug to do that?

**Comment by gk780** [comment]
No, not for the output I meant. This 'general' logging output it always there, and depending on the level we get more information or less. You don't get get info about the equation which is loaded? Which participant/domain is the one which fails? Euler or lineareuler? Actually I implemented the linear_euler_2d equation recently, are you on a ateles version later than 2016-01-13 ? (the loadbalancing testcase is an other equation). Nevertheless, Ateles should tell you that this equation is not yet there....are you running on SuperMUC?

**Comment by uekerman** [comment]
i use the most recent ateles (the version from saturday). release build. i increased the logging level, but i do not get more output. both participants crash with the same error. i except that this is some gcc version problem, but the strange thing is that it worked for the loadbalancing case.

**Comment by gk780** [comment]
sorry, you wrote it above...gcc could be, I never use gcc on supermuc, but for our regression check we run gcc 5.3 on our system do not get a problem for the last versions.  I will check it on supermuc.

**Comment by gk780** [comment]
hmm....the problem might come from the changeset: 5424:b0283a2e46a7 where I fixed stuff for oneway coupling. 
Somehow, SuperMUC is slow and I need to clean up my working copy there. Can you try changeset 5385:f5ddf7623692	, this should work, meanwhile I get a new working copy on SuperMUC and try the changeset from saturday.

**Comment by uekerman** [comment]
recompiling ateles again from scratch solved the problem! no idea what happened

**Comment by gk780** [comment]
hmmmm....I run changeset

> changeset:   5477:6a8cd068bc28
parent:      5427:74b74b05e54f
user:        Apes Checker <regressioncheck@sts.nt.uni-siegen.de>
date:        Thu Feb 04 01:07:39 2016 +0100
summary:     Added tag working for changeset 74b74b05e54f

and it is working for me ( it is now at the location where precice setup the communication). I copied the testcase folder from shared. No Idea...I compile with the following modules:

> Currently Loaded Modulefiles:
>  1) admin/1.0         4) intel/15.0        7) mpi.intel/5.0
>  2) tempdir/1.0       5) poe/1.4           8) fftw/serial/3.3
>  3) lrztools/1.0      6) lrz/default       9) gcc/4.9(default)

and compile Ateles with ifort. Anyway, first will update precice and see whats happening with the new version.

**Comment by gk780** [comment]
Ah ok...really strange!

**Comment by uekerman** [comment]
could be that i compiled on the SM2 nodes and ran on SM1, but up to now i never had a problem with this

**Comment by gk780** [comment]
I never compile on home, don't know whats going on there.
I can reproduce the problem with the newest precice version (0ff0e85)  and the ateles from saturday (6a8cd068bc28). With mapping on each domain, it hangs at the initialization, and with mapping on the acoustic domain is start running ( and ends with NANs which is also strange because this testcase should work, but this is another issue ).

**Comment by uekerman** [comment]
when you say "reproduce", you mean that the error is still present, right?
i'll have a look soonish, maybe tomorrow.

**Comment by gk780** [comment]
Yes! As I explained it in the 2 sentence: with mapping on both domain, the simulation is not running and hangsa at 

`| precice::impl::SolverInterfaceImpl::initialize()        | it 1 of 1 | dt# 1 of 200000000 | t 0 | dt 1e-05 | max dt 1e-05 | ongoing yes | dt complete no | write-initial-data |`

for both domains.

**Comment by uekerman** [comment]
i can reproduce the problem now. more news later

**Comment by uekerman** [comment]
this is the same problem as #43, something is weird with the barriers. 
not sure why we never saw that before and why it is so random -- here it even deadlocked.
i commented the barrier in develop. 
now it hangs here ```Setting up the tracking infrastructure```, maybe there is still some process lost during the initialization and ateles has a barrier here. i will do some further testing

**Comment by uekerman** [comment]
ok, looks like there is sth wrong with the p2p communication (that only occurs for 2 meshes)
verena, you can go on working here with ```distribution-type=gather-scatter```. should be fast enough for such a small case. i'll check the problem. 
@floli can you please add an option for the SConstruct to add ```SuperMUC_WORK```. i saw, we still don't have this in develop. this also speeds up things drastically.

**Comment by gk780** [comment]
Thanks! I will use gather-scatter and produce hopefully great mind-blowing videos :D

**Comment by uekerman** [comment]
should be resolved now :) 
the p2p hidden folders (for publishing connection info) were not mesh-unique. now they are. 
@floli thanks for the platform option!
@gk780 p2p now works again, be sure to use the platform option ```scons ... platform=supermuc```
btw, the jet runs into a non-physical state, tss, mind-blowing ;)

**Comment by gk780** [comment]
Great, thanks! I will start simulations tomorrow...

The NANs are really strange, I already mentioned it above. I thought that this configuration of the jet was working (remember the video on the symposium). I will have a closer look tomorrow, can be that I changed the mach number ( to have faster results) or the degree for debugging. Let you know when I have mind-blowing results :D

**Comment by gk780** [comment]
I can not compile the newest version of precice develop branch. I use all the module:

> Currently Loaded Modulefiles:
>  1) admin/1.0                  7) mpi.intel/4.1
>  2) tempdir/1.0                8) fftw/serial/3.3
>  3) lrztools/1.0               9) scons/2.3.0
>  4) intel/15.0                10) python/2.7_anaconda_nompi
>  5) poe/1.4                   11) gcc/4.9(default)
>  6) lrz/default

export all the paths:

> export PATH=$PATH:/home/hpc/pr84xu/di98taj2/lib
export PYTHONPATH=/home/hpc/pr84xu/di98taj2/lib/scons-2.3.0
export PRECICE_BOOST_ROOT=/home/hpc/pr84xu/di98taj2/lib/boost_1_53_0
export CPATH=$HOME/lib/eigen-eigen-c58038c56923:$CPATH

add the line env.Append(CPPDEFINES = ['SuperMUC_WORK']) according to the wiki and use this command:

`scons python=off compiler=mpicxx build=release platform=supermuc petsc=off -j16
`

This error occurs

> /lrz/sys/intel/mpi_41_3_048/intel64/include/mpicxx.h:95:2: error: #error "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
>  #error "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
>   ^

And this is the header from scons:

> (default)  builddir                  = build      Directory holding build files. ( /path/to/builddir )
(modified) build                     = release    Build type, either release or debug (release|debug)
(modified) compiler                  = mpicxx     Compiler to use.
(default)  mpi                       = True       Enables MPI-based communication and running coupling tests. (yes|no)
(default)  sockets                   = True       Enables Socket-based communication. (yes|no)
(default)  boost_inst                = False      Enable if Boost is available compiled and installed. (yes|no)
(default)  spirit2                   = True       Used for parsing VRML file geometries and checkpointing. (yes|no)
(modified) petsc                     = False      Enable use of the Petsc linear algebra library. (yes|no)
(modified) python                    = False      Used for Python scripted solver actions. (yes|no)
(default)  gprof                     = False      Used in detailed performance analysis. (yes|no)
(modified) platform                  = supermuc   Special configuration for certain platforms (none|supermuc)

> 
> Checking whether the C++ compiler works(cached) yes
> Checking for C++ header file Eigen/Dense... (cached) yes
> (modified) PRECICE_BOOST_ROOT        = /home/hpc/pr84xu/di98taj2/lib/boost_1_53_0
> Checking for C++ header file boost/array.hpp... (cached) yes
> (default)  PRECICE_PTHREAD_LIB_PATH  = /usr/lib
> (default)  PRECICE_PTHREAD_LIB       = pthread
> (default)  PRECICE_PTHREAD_INC_PATH  = /usr/include
> Checking for C++ library pthread... (cached) yes
> Checking for C++ header file pthread.h... (cached) yes
> 

What am  I doing wrong?
