### ISSUE TITLE
Python bindings: How strict do we want to be with input argument types?

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#441]
Cython supports types in the signature of our functions. This is an optional feature which allows the following two extremes for `write_block_scalar_data`:

1. **Strict types:** `def write_block_scalar_data (self, const int data_id, const int[:] value_indices, const double[:] values)`
2. **No types:** `def write_block_scalar_data (self, data_id, value_indices, values)`

## Strict types

Using the first option, we always know which type of data the bindings have to deal with. This is especially beneficial when it comes to accessing the cpp interface of preCICE that accepts `double*`, where many things can go wrong, if the python bindings provide wrongly typed numpy arrays. However, this means also that the users have to use the types that are accepted by the bindings, since otherwise a runtime error will be thrown. This is very uncommon for python and makes code on the user side harder to write.

## No types

With the second option, we do not know what kind of data the python bindings have to deal with. Often it becomes necessary to reformat the input data before further processing is possible. 

An example of what can go wrong with wrongly formatted data, can be found [here](https://travis-ci.org/precice/precice/jobs/547845333): the input data is not-c-contiguous, which results in wrong behaviour. A possible solution for this problem is shown [here](https://github.com/precice/precice/blob/43a5a8925934a9142e2433db7f571036c83f7abb/src/precice/bindings/python_future/precice_future.pyx#L197-L202): The non-c-contiguous input is copied into a new np.array, which is c-contiguous and typed correctly.

**notes for implementation:**

* using the type `np.ndarray[double, ndim=1, mode="c"] values` checks whether input data is C-contiguous. A `ValueError: ndarray is not C-contiguous` is thrown, if this is not the case.
* one cannot use `const np.ndarray` in cython
* using a memory view `double[:]` allows us to use the keyword `const`, but we cannot check whether input data is C-contiguous.

**Comment by MakisH** [comment]
How about offering wraper methods that use types? This way, you tell the user "if possible, use the typed version. If not, you can always access one layer below and ommit the type". Related to the discussion about "high-level, opaque methods" vs "open architecture, access to any layer" (or "point and click" vs "professional camera").

However, would it really be so difficult for the user to check for types? An error is always better than wrong results.

**Comment by BenjaminRueth** [comment]
I also thought about adding another layer, even though the other way around: provide the easy-to-use interface without types as the first layer. This layer then calls the typesafe interface after the input has been formatted properly. However, this also introduces another layer on top of the many that already exist in the python bindings...

**Comment by MakisH** [comment]
In that case, I would make the typed (safe) the default option and the non-typed (unsafe) the "use at your own risk" alternative.

Another option would be to check the type of the arguments when they are used and give warnings when they are not as expected. This way we don't enforce anything, but the user gets the hint.

**Comment by uekerman** [comment]
Which variant do we use at the moment?

**Comment by BenjaminRueth** [comment]
@uekerman currently we use variant 2: no types. We make sure that data input is correct inside the bindings (see #448)

**Comment by MakisH** [comment]
We want to not go against the "duck typing" of Python. Therefore, we decide to not ask the user to define types (signatures), but rather do the necessary checks in the intermediate layer. Numpy could help here.

**Comment by fsimonis** [comment]
We could just take everything and stuff it into [`numpy.ascontiguousarray`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ascontiguousarray.html). This way we let numpy do the checking,

**Comment by BenjaminRueth** [comment]
As soon as in the signatures of https://github.com/precice/precice/blob/develop/src/precice/bindings/python_future/precice_future.pyx all types are gone, we can close this issue. I will take care of this.
