### ISSUE TITLE
Remove unnecessary checks in coupling schemes

### ISSUE THREAD

**Issue by uekerman** [precice/precice#442]
https://github.com/precice/precice/blob/develop/src/cplscheme/ParallelCouplingScheme.cpp#L54-L55

should not be necessary. 

To be validated and removed if possible

**Comment by BenjaminRueth** [comment]
I'm currently running some experiments with waveform relaxation and parallel coupling schemes. See [here](https://github.com/precice/tutorials/blob/WaveformBindingsDraft/HT/partitioned-heat/fenics-fenics/experiments/WR12/dT1.0/PARALLEL/precice-config.xml). Here, I had to remove

https://github.com/precice/precice/blob/cc38d61a52c3a00ebf535f897cbcdd6623f5f46c/src/cplscheme/ParallelCouplingScheme.cpp#L54-L55

Everything works as expected for parallel coupling with more than two post-processing data vectors.
