### ISSUE TITLE
`make uninstall` does not remove empty directories

### ISSUE THREAD

**Issue by MakisH** [precice/precice#445]
I am running preCICE from 8b1878ae9b2caacb91ec0f4f136ba00279e218db and I install in a local prefix.

When I do `make uninstall`, the following is left behind, even though this installation created them:
* Empty directory `prefix/include/precice`
* Empty directory `prefix/lib/cmake/precice`
* Empty directory `prefix/share/doc/libprecice1.5.1`
* and maybe other similar cases.

I know this is also a design decision. Should `make uninstall` remove even the `prefix/lib/` if it contains nothing else? Unless we find any best practices or cases where this causes trouble, I think we should at least clean all the `*/precice` empty directories.

**Comment by fsimonis** [comment]
The `uninstall` target already is a  dodgy solution, so I really would not like to invest more into this. The `install` target creates a manifest of which files it created. We use this for the `uninstall` target, but this is not proper ownership tracking.

Tracking ownership is what package managers do.

I would say that everyone who has `sudo` rights should create the debian package and install it.
Everyone else has to create scoped installations. Deleting this one prefix folder should not be a big deal.
