### ISSUE TITLE
Bug with master:sockets when coupling against a serial participant

### ISSUE THREAD

**Issue by Dominanz** [precice/precice#451]
Hi,

I've found that problems occur in preCICE in the following scenario:

- You couple a participant running in parallel against a participant running serially.
- You use the <master:sockets> tag for the parallel participant

An instance of the problem can be reproduced e.g. with the elasticTube1D example: I added a file named `precice-config-hybrid.xml` in the ConfigurationFiles folder. This file is an exact copy of `precice-config-parallel.xml` with the following two exceptions:

- The master tag in the structure solver was removed completely.
- The tag `<master:mpi-single>` in the fluid solver was replaced by `<master:sockets>`.

For convenience, I attached the file. For whatever the hell reason, github told me it doesn't support uploading xml files, so i renamed it to .log: [precice-config-hybrid.log](https://github.com/precice/precice/files/3346140/precice-config-hybrid.log)

Now, if you run the solvers using

- `mpirun -n 2 ./FluidSolverParallel ConfiguonFiles/precice-config-hybrid.xml 100 0.01 100
`
- `mpirun -n 1 ./StructureSolverParallel ConfigurationFiles/precice-config-hybrid.xml 100` or simply `./StructureSolver ConfigurationFiles/precice-config-hybrid.xml 100`

they will run into an incomprehensible error. The message was: "ERROR: Receive failed: vector::_M_default_append".

 If you do the very same without replacing `<master:mpi-single>` by `<master:sockets>` in the fluid solver, it runs just fine.

I had a similar observation with a minimal example I wrote for myself. My example worked properly and as expected with `<master:mpi-single>`. When I switched to `<master:sockets>`, I observed weird mapping behaviour (nearest-neighbor mapping didn't work properly) and the execution terminated on an error stating that `advance()` encountered ambiguous time step lengths. 

I conclude there must be a bug in the implementation of the master tag. I would highly appreciate a hot fix, since I am forced to compile preCICE without MPI due to compatibility problems between MATLAB and MPI.

Thanks in advance!

**Comment by BenjaminRueth** [comment]
I just pushed a minimal example which produces the same error if `<master:sockets/>` is used (see above).

```
(0) 19:27:45 [com::SocketCommunication]:776 in receive: ERROR: Receive failed: vector::_M_default_append
```

Interesting to note. For `<master:mpi-single/>` everything runs through and the mapping looks fine, but I get another error in the very end:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >'
  what():  Failed to set TLS value: Invalid argument
```

Any idea what this means?

**Comment by BenjaminRueth** [comment]
I added a test case in the system tests repository (see [this branch](https://github.com/precice/systemtests/tree/debugMasterSockets)). There we get the same error: [see here](https://travis-ci.org/precice/systemtests/jobs/552949218#L2742).

**Comment by fsimonis** [comment]
This is interesting!

I did some digging, and this error occurs when the `std::vector` internal `_M_default_append`  attempts to grow more than `max_size() - size()`. This is called from functions such as `std::vector::resize`.
`std::vector::max_size()` is the __theoretical limit__ of the vector size based on the index type.

Thus, we most likely (hopefully) have an underflow somewhere.

**Comment by BenjaminRueth** [comment]
This means if we put an assertion at the right place, we can at least replace the `ERROR: Receive failed: vector::_M_default_append` with something more meaningful?

**Comment by BenjaminRueth** [comment]
Does #452 close this issue as soon as it is merged?

**Comment by uekerman** [comment]
Yes.
