### ISSUE TITLE
Use n x d arrays in python bindings

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#458]
This issue originates from https://github.com/precice/precice/pull/448#discussion_r301218086.

As the python bindings are returning and accepting numpy arrays, we can easily use 2-D arrays with dimensionality n x d (degrees of freedom times dimension) instead of 1-D arrays of length d*n. In my opinion this would be easier to use and harder to break than 1-D arrays. 

One example where things can go wrong is the that the user has to decide between C- and Fortran order (column vs. row major) when linearizing a 2-D array. From the perspective of the interface it is impossible to tell whether the right decision has been made by the user, but if user input is wrongly formatted preCICE will have a problem. One could argue that for a 2D array the same confusion can happen if d == n. However, usually n >> d. In these cases the interface can easily detect the correct order of traversal. We could even add a warning cases when d == n, which will most likely never be issued.

There are two possible interfaces:

1. only accept 2D arrays
2. accept 1D and 2D arrays, let the bindings check which case we are dealing with and perform consistency checks.

Possibility 1. would be API breaking, while 2. would not.

**Comment by fsimonis** [comment]
We know the dimension and the size of returning API calls, thus I am in favor of always returning a `n x d` numpy matrix.

This is more difficult for incoming data as we should always be able to accept 1D `list`s/ numpy arrays.
We probably should enforce a layout and check the dimension `d`.

So my proposition:
1. Always return a `n x d` numpy array
2. Always accept a 1D array / list
3. Check the dimension `d` of 2D numpy arrays.
---

> We could even add a warning cases when d == n, which will most likely never be issued.

Lets image a user who works with a 2D interface with edges. So in his adapter code, he could iterate over each edge (AB) and do the following:
1. get the positions of `edge.A` and `edge.B` and put them into a `2x2` matrix `P`
2. create the vertices `a, b = solverinterface.setMeshVertices(P)`
3. set the edge `solverinterface.setMeshEdge(a, b)`

If the interface is 3D then the matrix of vertex-positions whilst iterating over triangles will be `3x3`.

Using this programming style, thus will always issue the warning for `d == n`.

**Comment by BenjaminRueth** [comment]
Since this issue is critical for the python bindings interface, we should keep it in `1.6.0`

**Comment by BenjaminRueth** [comment]
I will implement the following interface:

* we accept everything (1D and 2D arrays)
* if 1D: except that array is shaped as [vx1, vy1, vz1, ... ] and has size n*d
* if 2D: except that array has shape n x d.

**Comment by floli** [comment]
So, the input matrix always has d (usually 1, 2, 3) rows and n (usually something much larger) columns, resulting in a small and wide matrix. Correct? Is there a general convention in numpy to put dimension in rows and vertices in cols or vice versa?

**Comment by BenjaminRueth** [comment]
> So, the input matrix always has d (usually 1, 2, 3) rows and n (usually something much larger) columns, resulting in a small and wide matrix. Correct? Is there a general convention in numpy to put dimension in rows and vertices in cols or vice versa?

Good point. I will check for possibly existing conventions before implementing.

**Comment by BenjaminRueth** [comment]
Some news on the question `n x d` vs. `d x n`:

* I did not find a source stating that there is a convention, so far.
* FEniCS uses a `n x d` array for providing coordinates of a mesh (see (here)[https://fenicsproject.org/docs/dolfin/2017.2.0/python/programmers-reference/cpp/mesh/Mesh.html#dolfin.cpp.mesh.Mesh.coordinates])
* a nice side effect of a `n x d` array is that `my_array.flatten()` gives us the linearized array in "preCICE-order", i.e. `[x1, y1, x2, y2, x3, y3, ...]`.
* The inverse operation of `flatten()` is `reshape((n,d))`, which maps from "preCICE-order" back to a `n x d` numpy array.
* If we use `d x n` instead, the results of `flatten()` and `reshape()` are not consistent with the ordering we use in preCICE

**conclusion:** If we use a `n x d` array everything seems to fit nicely with our datastructures in preCICE.
