### ISSUE TITLE
Passing of Variables before calling initialize() function

### ISSUE THREAD

**Issue by huangq1234553** [precice/precice#464]
I am working on a problem where the buffer size required for one coupled solver depends on the start-up parameters of the other. While there is always the option to hard-code or add this buffer size to the configuration of each side, this will introduce additional checks the user is responsible for during start-up.

This would be solved if there was a way (in the preCICE API) to pass information (starting variables) between solvers prior to calling the initialize function. This would allow for easier synchronization between coupled solvers and make coupling solvers less fiddly.

This can be implemented by writing to a file the preCICE interface from either solver can access (similar to how solvers identify each other at startup).

**Comment by uekerman** [comment]
Could you please give more details of what exactly your situation looks like? For exchanging initial data, there is `initializeData`, but probably you want to influence the shape of the mesh. Maybe, this is a task for the adapter, but hard to say at this point.

**Comment by uekerman** [comment]
A brief summary after our in-person discussion:
* The 1D solid solver uses points (of application) where some rotational forces are computed. These points are fixed throughout a simulation, but can change from simulation to simulation. 
* The 3D fluid solver also needs to know these points to correctly apply the rotational forces. 
* The position of the points could be transferred by a displacement field, but the number of points is problematic.  
* The current workaround is to specify these points in the adapter config of the 3D solver. This works, but is not the best solution. 

Currently, I see two better ways:

(1) Transform the rotational forces into quantities that the 3D solver can directly understand without knowing the points where the force acts. I am not sure whether this is possible or, if possible, desirable. 

(2) Exchange the number of points through #202 after initialize (we need the communication channel to be established). Then, another problem is that we want to redefine the mesh after initialize was called. So, we also need #225. 

(1) needs to be solved in the adapters, for (2) we already have the necessary issues. I will thus close this issue. Feel free to re-open if there are still any doubts.
