### ISSUE TITLE
Provide tool to generate flowchart from config

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#470]
It would be helpful to provide a tool to create figures like the following one (from https://github.com/precice/precice/wiki/Mesh-Exchange-Configuration) directly from the corresponding precice-config.

![](https://raw.githubusercontent.com/wiki/precice/precice/images/mesh-exchange.png)

In my opinion this might be particularly useful for:

* a nice graphical presentation of the configuration
* debugging your configuration
* user support

**Comment by BenjaminRueth** [comment]
@fsimonis do you know a nice tool for creating plots like the above one automatically? My first idea would be tikz, but probably this is not a good idea.

As far as I know the figure above has been created manually using openOffice Draw or similar. Therefore, there are no resources that we could reuse.

**Comment by fsimonis** [comment]
@BenjaminRueth we could generate a simple dot file. This would also allow to import the information into other tools more easily.

**Comment by fsimonis** [comment]
@BenjaminRueth I created a first prototype of the config visualizer.

I used the heat exchanger as an example.
<details><summary>Does this look useful? Click...</summary>

![exchanger](https://user-images.githubusercontent.com/13552216/64020315-9c710780-cb31-11e9-86f8-736eae93904a.png)

</details>

**Comment by MakisH** [comment]
Fancy! :smile:  

I think the heat exchanger example is quite feature-full, but a bit difficult for a first example. How easy would it be to regenerate the same from a simpler tutorial (e.g. heated plate)?

What do the arrows mean here?

I assume that `rectange = participant`, `module = mapping/communication`, and `hexagon = mesh`.

What I particularly like in the hand-written examples is the separation among participants and the consistency in the placement of meshes (top - bottom). Which of these features could we reproduce here?

**Comment by fsimonis** [comment]
The graph I showed was rendered with neato. The top-to-bottom layout can be produced using dot. This looks a bit massive though.

Your assumption about the shapes are right.

I would like to group the nodes too, but I have not found a way of doing this using networkx and pydot yet. Its WIP.

Some more examples with different layout engines:

<details><summary>Exchanger Dot</summary>

![exchanger dot](https://user-images.githubusercontent.com/13552216/64021616-aa745780-cb34-11e9-9f4f-861bbf4ac1fa.png)

</details>
<details><summary>Heated Plate Dot</summary>

![heated-plate dot](https://user-images.githubusercontent.com/13552216/64021620-ae07de80-cb34-11e9-83d0-3420eea62e97.png)

</details>
<details><summary>Heated Plate Neato</summary>

![heated-plate neato](https://user-images.githubusercontent.com/13552216/64021623-af390b80-cb34-11e9-933d-4e41a6dfeaf5.png)

</details>

**Comment by BenjaminRueth** [comment]
Looks nice :) 

Some more ideas:

* What happens if you intentionally provide a wrong/buggy config? Does the visualization help finding the error?
* Is it possible to filter certain parts of the config? E.g. if you only want to investigate the setup of meshes and mapping, is it possible to exclude everything related to the coupling scheme for better overview?

**Comment by fsimonis** [comment]
@BenjaminRueth Broken configs should result in a _very_ broken graph :wink:
We could add filters, but I think the compact form is good enough.

Maybe we could also add a data-flow-only graph.

**Comment by MakisH** [comment]
This is great and a lot easier to understand than before. :+1: :+1: :+1:

**Comment by uekerman** [comment]
Great indeed!

**Comment by fsimonis** [comment]
I published the tool in a separate repository.
Please head to https://github.com/precice/config-visualizer for more information.
