### ISSUE TITLE
Strange results from EventTimings

### ISSUE THREAD

**Issue by uekerman** [precice/precice#48]
I got strange timings for the BroadcastFilterDecomposition::feedback
```
  if (utils::MasterSlave::_slaveMode) {
    utils::MasterSlave::_communication->send(numberOfVertices,0);
    if (numberOfVertices!=0) {
      utils::MasterSlave::_communication->send(filteredVertexPositions.data(),numberOfVertices,0);
    }
  }
  else { // Master
    seed.getVertexDistribution()[0] = filteredVertexPositions;
    for (int rankSlave = 1; rankSlave < utils::MasterSlave::_size; rankSlave++){
      int numberOfVertices = -1;
      utils::MasterSlave::_communication->receive(numberOfVertices,rankSlave);
      std::vector<int> slaveVertexIDs(numberOfVertices,-1);
      if (numberOfVertices!=0) {
        Event e("geo::feedback, receive data " + std::to_string(rankSlave));
        utils::MasterSlave::_communication->receive(slaveVertexIDs.data(),numberOfVertices,rankSlave);
        e.stop();
      }
      seed.getVertexDistribution()[rankSlave] = slaveVertexIDs;
    }
  }
```
i get: 32* 100ms and 96* 0ms

if i change the line to:
```
    Event e("geo::feedback, receive data " + std::to_string(rankSlave) + " " + std::string(5));
```
i get 128* 0ms (which makes much more sense)

@floli any idea what happens?

**Comment by floli** [comment]
Sorry, I have no idea why that change has any effect. Are you sure it's not simply a mesurement error?

**Comment by uekerman** [comment]
changing the clock had no influence. i had a more detailed look. i directly looked at the durations in Event::stop() and the timings were consistent with my observation above. i changed to micro seconds: the timings are not straight 100ms but different values between 100 and 101ms.
in the meanwhile, i think that this is no measurement error, but simply a bad way of communication. i guess that the slaves stop sometimes at the first integer send above till the master receives, once the data size is too big (the master is on the memory edge).  in the case above, we are somehow around that memory size, so changing the Event name has an influence. anywho, we could probably make this code part more efficient by some async communication, but it does the job for the moment and will be altered anyway soon. so, i'll not tune it further and close the issue.
