### ISSUE TITLE
Overweight Mesh Primitives

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#483]
Our mesh primitives are remarkably big. We should definitely consider to reduce their size to reduce the overall memory consumption of preCICE.

Primitive | Size [B] | Add. dynamically allocated
--- | --- | ---
`Triangle` | 144 | vertexMap
`Edge` | 128 |
`Vertex` | 136 |

Their common base class `Propertycontainer` is quite heavy weight at `88 Bytes`  as it stores:
* A _private_ logger
* vector of parents
* map of properties

Note that those all dynamically allocate even more memory on top of the numbers in the table above.

**Comment by floli** [comment]
I agree that these classes are too fat.

The logger can be removed, as far I as I can tell by a quick scan-through. The classes do not make use of them, with the exception of `PropertyMeshContainer.hpp:145`.

Furthermore, I think that the entire system of attaching properties to vertex is not in use.

**Comment by fsimonis** [comment]
I just ran preCICE with a NP testcase using ASTE. I ran the example first using 3772b9b98a455adb7d62a4479b26778e08001803 and then just deleted the logger in the Propertycontainer. This is the "default" testcase of the config in ASTE.
I run using 2x2 ranks and use meshes:
* A 100x100 fully connected with data  (x+y+z)
* B 200x200 fully connected

## Memory Consumption
_for the master rank of B (most work)_

### Before

![image](https://user-images.githubusercontent.com/13552216/62880250-462c5800-bd2d-11e9-8eed-3fa1bd988292.png)

* The 3 bottom slates _alone_ are `boost::log` related

### After

![image](https://user-images.githubusercontent.com/13552216/62880287-5ba18200-bd2d-11e9-935d-578dd1521905.png)

* The bottom orange slate is the `rtree`
* The next slate is 'mesh::createEdge()`

### Conclusion

* The logger in the `Propertycontainer` is responsible for a majority of the memory consumption.
* Removing this logger resulted in a peak memory reduction of __over 50%__, for this little testcase alone!

**Comment by fsimonis** [comment]
We decided to make the logger static instead of completely removing it in bf6f4b62. This essentially has the same effect as removing it but gives us the possibility to log in the base class.
This is just one step in reducing the impact of the PropertyContainer.

**Comment by floli** [comment]
Could you briefly comment in the source code why we made an exempt from the rule and use a static logger there?

**Comment by fsimonis** [comment]
After the refactoring of the mesh namespace in #585, the situation looks as follows:


Primitive | Size [B] | Add. dynamically allocated
-- | -- | --
Triangle | 56 | vertexMap
Edge | 40 |  
Vertex | 48

**Comment by fsimonis** [comment]
The current state of the benchmark described in https://github.com/precice/precice/issues/483#issuecomment-520494968 for precice ac4ea996c4cad6228fe98b2c98ebd2206d80c447 and https://github.com/precice/aste/commit/5779e38dd75d79ef735907a91023c5f07a5fe406 is:

![image](https://user-images.githubusercontent.com/13552216/80710235-d1818f80-8aee-11ea-829a-45d604d9ed01.png)

**Comment by uekerman** [comment]
Nice factor :+1:
We should not only show these plots in issues, but eventually also in papers :smirk:

**Comment by fsimonis** [comment]
Let's revisit this issue again based on 28da0e8c8693999b6ac72173beef947ec7071ae0.

The above size claims are wrong as `Eigen::VectorXd` dynamically allocates the memory, which impacts coordinates and normals. The following table is for a 3D interface.

Primitive | Size [B] | Add. dynamically allocated [B] | Total [B]
-- | -- | -- | --
Triangle | 48 |  24 | 72
Edge | 40 |  24 | 64
Vertex | 48 | 2x 24 | 96

I can see 2 possible memory improvements:
* Calculate normals on-demand. This would reduce the required memory by 48B for all primitives
* Save the coordinates using fixed size `std::array<double, 3>` and use an `Eigen::Map<Eigen::VectorXd>` or similar to interface with it. This would prevent dynamic allocations (24B).

If we implement both above strategies, we could end up with:

Primitive | Size [B] 
-- | -- 
Triangle | 24
Edge | 6
Vertex | 24

The changes will shift more work to the runtime, but also improve data locality. So, I rather not crystal-ball the performance. We need to profile the behaviour and compare.

**Comment by fsimonis** [comment]
The new behaviour of combining both #1000 and #1006:

Mesh | Vertices  | Triangles
--- | ---  | ---
A | 330 139 | 665 329
B | 628 898 | 1257 391

Rank 0 of Participant A (2 ranks)  and B (4 ranks). NP on B.
|  | Old | New
--- | --- | ---
A | ![image](https://user-images.githubusercontent.com/13552216/116388706-6612f080-a81c-11eb-99fb-36d644ef97b2.png) | ![image](https://user-images.githubusercontent.com/13552216/116389091-dde11b00-a81c-11eb-9469-44adcadfc3af.png)
B | ![image](https://user-images.githubusercontent.com/13552216/116389292-1123aa00-a81d-11eb-8349-300b8a23a02a.png) | ![image](https://user-images.githubusercontent.com/13552216/116389249-06691500-a81d-11eb-8dd8-12d2836acc09.png)

**Comment by fsimonis** [comment]
At this point, we pretty tweaked the mesh primitives to a point where we would need to make severe changes to the data structures in order to improve efficiency, such as using struct of arrays or similar.

This is most likely not worth the effort.

**If you as a user run into memory problems with preCICE, then please open a new issue**
