### ISSUE TITLE
Add Contiguous Mapping

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#489]
## Scenario

Two solvers share a mesh that is not only identical (same vertex order and positions), but the participants also own contiguous sections of it.
This is the case when solvers partition their mesh uniformly.

## Problem

Using nearest neighbour mapping is the best we can do, but it is not aware of the contiguity. It thus has to generate an index tree, probe it and build a mapping.
This is costly during initialization and adds an overhead at each time-step.

## Proposal

We add a `contiguous` mapping, which makes the following assumptions:
1. Vertices are in identical order on all instances (participant masters and slaves).
2. Master and slaves own a section of this total order.
3. The position of vertices are identical for both meshes.

preCICE stores the data as a contiguous block of memory in the vertex order.
We can thus reduce `computeMap` to the problem of finding the overlap of two ranges.
Furthermore for consistent mappings, `map` becomes the identity and simply has to copy a block of memory. Conservative mappings have to add up blocks of contiguous memory, making vectorizers very happy.

![contiguous-mapping](https://user-images.githubusercontent.com/13552216/63504382-baa38b80-c4d1-11e9-9aba-23f88dd86e56.png)

**Comment by BenjaminRueth** [comment]
The main use case for the contiguous mapping is if there are two identical meshes (like in your drawing). There should be a check to make sure that the data provided to the contiguous mapping is as expected and point 3 in your proposal is satisfied: The vertices that map to each other actually have the same coordinates (I will call these pairs of vertices siblings). 

If we want to avoid mapping cost, we cannot find the sibling of a node automatically. Therefore we rely on the user to provide the nodes in contiguous order. In this case finding the siblings is possible without mapping. During initialization we should perform a check whether the siblings actually have the same coordinates to avoid wrong user input to the contiguous mapping:

```
for vertex_id in range(n_vertices):
    assert(coordinates_mesh_A[vertex_id_mesh_A] == coordinates_mesh_B[vertex_id])
```

**Comment by uekerman** [comment]
I guess that the suggestion comes out of @Dominanz 's application, right? There, however, we would not only have matching meshes and matching global order of vertices, but also matching partitions, right? Is there a _real_ use case, where would have matching meshes, matching global order, but not matching partitions (like the situation you sketched above)?  
I don't see ASTE as a _real_ case here :wink: 

If we have matching partitions we can also get around the complete repartitioning, which is the real expensive part. Already a warning here: implementation-wise this sounds easier than it is. 

Another setting I could imagine would be matching meshes, but no contiguous order and non-matching partitions.

**Comment by fsimonis** [comment]
Let's say the application from @Dominanz was the trigger. IIRC the partitions were not matching in his use-case.

After a discussion with @uekerman:

The idea of this mapping is to minimise the cost of the mapping and the communication in terms of both computation, memory consumption, so that _power users_ have the choice to trade flexibility for performance.
This mapping requires the vertices to be identical and in a global order.
It follows, that finding one mesh in the other will always succeed as long as those conditions are met! Thus, we have to simply find the first element of one range in the other and then verify that all remaining elements are equal. Every other case is a user error.

We then simply have to remember the begin and the length of the range and copy that part during the `map` call.

As we cannot use the vertex ids to compare vertices of different meshes, we have to rely on the geometric comparison of the vertex coordinates.

To cover the case of matching contiguous meshes with non-consistent vertex order, we should add a `boolean sort, default: false` attribute to the mesh configuration. This would internally sort the mesh vertices at the end of the initialisation phase. And simplify the use of the mapping.
This is yet another trade-off as sorting the vertices requires additional bookkeeping (`id` -> `position`).

**Comment by fsimonis** [comment]
The introduction of [direct mesh access](https://precice.org/couple-your-code-direct-acces) eliminates this exact use-case.

Use a pseudo-mesh in one participant and use direct access in the other. Then create a mapping from the local to the remote buffer entries, based on the vertex positions provided by preCICE.
This mapping should be contiguous, hence trivial to execute.
