### ISSUE TITLE
I installed gcc-5 and it seems to work.

### ISSUE THREAD

**Issue by bitronTeofil** [precice/precice#492]

**Comment by floli** [comment]
Could you expand upon what your issue is?

**Comment by bitronTeofil** [comment]
Sorry for late reply, but I didn't think I already had submitted the new topic.

Was for the last three days I’m trying to compile preCICE, and I found many trouble due to my difficulties in manage Linux environment.

Finally, I was able to solve all the dependencies. In the attached file you could find the complete cmake log.

Now I have the problem about the gcc 4.8 limit in manage the C++ 11 feature. For this reason I installed gcc-5 version 5.3.1. Here is the compiling error:

-- Found Git: /usr/bin/git (found version "2.13.7")
-- Revision status: v1.5.2-125-g675a2425
[  0%] Built target GitRevision
[  0%] Building CXX object CMakeFiles/precice.dir/src/utils/EventUtils.cpp.o
/home/alessandro/downloads/fem/preCICE/precice/src/utils/EventUtils.cpp: In function ‘std::string precice::utils::timepoint_to_string(std::chrono::_V2::system_clock::time_point)’:
/home/alessandro/downloads/fem/preCICE/precice/src/utils/EventUtils.cpp:33:9: error: ‘put_time’ is not a member of ‘std’
   ss << std::put_time(std::localtime(&ts), "%FT%T") << "." << std::setw(3) << std::setfill('0') << ms.count();
         ^
CMakeFiles/precice.dir/build.make:1557: set di istruzioni per l'obiettivo "CMakeFiles/precice.dir/src/utils/EventUtils.cpp.o" non riuscito
make[2]: *** [CMakeFiles/precice.dir/src/utils/EventUtils.cpp.o] Errore 1
CMakeFiles/Makefile2:88: set di istruzioni per l'obiettivo "CMakeFiles/precice.dir/all" non riuscito
make[1]: *** [CMakeFiles/precice.dir/all] Errore 2
Makefile:162: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

Also in the cmake log file, it seems that preCICE still find the 4.8 version of gcc:

-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info – done
…
…

How could I fix it?
Many thanks in advance for your help



Cordiali saluti,

Alessandro Rovera

BITRON S.p.A. unità di Dronero
via I Maggio n°10
12025 Dronero (CN)
FEA Analyst
Tel. 0171 912758 - Fax. 0171 912799
alessandro.rovera@dro.bitron-ind.com<mailto:alessandro.rovera@dro.bitron-ind.com>



Da: Florian Lindner [mailto:notifications@github.com]
Inviato: giovedì 22 agosto 2019 14:54
A: precice/precice
Cc: Rovera Alessandro; Author
Oggetto: Re: [precice/precice] I installed gcc-5 and it seems to work. (#492)


Could you expand upon what your issue is?

**Comment by MakisH** [comment]
You say that you installed gcc-5 version 5.3.1, but in the CMake output you still get `-- The CXX compiler identification is GNU 4.8.5`. You currently have both compilers installed and you need to [select the one you want CMake to use](https://stackoverflow.com/questions/17275348/how-to-specify-new-gcc-path-for-cmake).

We only use issues for bug reports and feature requests and the best place to get help regarding building preCICE would be on our [Gitter chatroom](https://gitter.im/precice/Lobby). We are very active there as well! :-) We can continue there if you need and I am closing this now.
