### ISSUE TITLE
PETSc tests fail during configuration

### ISSUE THREAD

**Issue by moravveji** [precice/precice#495]
Hey guys,

I am trying to build preCICE v. 1.5.2 on our compute nodes (SkyLake + CentOS 7.6) for a cluster we run. I have an error of the following form, which I do not know how to resolve easily:

```bash
-- Found Boost components:
   filesystem;log;log_setup;program_options;system;thread;unit_test_framework
CMake Error at cmake/modules/FindEigen3.cmake:50 (file):
  file failed to open for reading (No such file or directory):

    /myApps/software/Eigen/3.3.5-GCCcore-6.4.0/Eigen/src/Core/util/Macros.h
Call Stack (most recent call first):
  cmake/modules/FindEigen3.cmake:76 (_eigen3_check_version)
  CMakeLists.txt:87 (find_package)


-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.1")
-- Found MPI_CXX: /myApps/software/OpenMPI/2.1.2-GCC-6.4.0-2.28/bin/mpicxx (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- petsc_lib_dir /myApps/software/PETSc/3.11.1-foss-2018a/lib
-- Recognized PETSc install with single library for all packages
-- Performing Test MULTIPASS_TEST_1_petsc_works_minimal
-- Performing Test MULTIPASS_TEST_1_petsc_works_minimal - Failed
-- Performing Test MULTIPASS_TEST_2_petsc_works_allincludes
-- Performing Test MULTIPASS_TEST_2_petsc_works_allincludes - Failed
-- Performing Test MULTIPASS_TEST_3_petsc_works_alllibraries
-- Performing Test MULTIPASS_TEST_3_petsc_works_alllibraries - Failed
-- Performing Test MULTIPASS_TEST_4_petsc_works_all
-- Performing Test MULTIPASS_TEST_4_petsc_works_all - Failed
-- PETSc could not be used, maybe the install is broken.
CMake Error at /myApps/software/CMake/3.13.3/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  PETSc could not be found.  Be sure to set PETSC_DIR and PETSC_ARCH.
  (missing: PETSC_EXECUTABLE_RUNS) (found suitable version "3.11.1", minimum
  required is "3.6")
Call Stack (most recent call first):
  /myApps/software/CMake/3.13.3/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPETSc.cmake:345 (find_package_handle_standard_args)
  CMakeLists.txt:103 (find_package)
```
I have attached a tarball that contains the build script, the redirected stderr/stdout, and CMake output/error files.

I would be grateful to know how to resolve the PETSc error. I have to mention that the installed PETSc module is been widely used as a dependency for building other modules. So, I am a bit curious what this comment really means: 
`PETSc could not be used, maybe the install is broken`

Kind regards,
Ehsan
[compile.zip](https://github.com/precice/precice/files/3559066/compile.zip)

**Comment by fsimonis** [comment]
Hi @moravveji, thank you for the report.

> I have attached a tarball that contains the build script, the redirected stderr/stdout, and CMake output/error files.

The attached zip does not contain the files you mentioned.

Based on the given snipped I can give you limited advice:

This PETSc problem is unusual. Can you try setting the env  `CXX` to the MPI compiler wrapper and try to configure preCICE from scratch?

There seems to be a problem with `Eigen` as well. Please set the env `Eigen_ROOT` to the location of the extracted eigen3 folder prior to reconfiguring.

**Comment by moravveji** [comment]
@fsimonis: thanks for your reply. I attach the logs/script again! Hopefully it is Oke.

I retried exporting the two env. vars. `CXX` and `Eigen_ROOT`, and the error message is the same. 
[logs.tar.gz](https://github.com/precice/precice/files/3559453/logs.tar.gz)

**Comment by moravveji** [comment]
@fsimonis : any idea how to proceed?

**Comment by fsimonis** [comment]
@moravveji 

You missed out the `-D` in front of the install prefix option:
```diff
-opt_inst="CMAKE_INSTALL_PREFIX=$dir_install"
+opt_inst="-DCMAKE_INSTALL_PREFIX=$dir_install"
```

Also, please set `Eigen3_ROOT` to the directory containing the file `signature_of_eigen3_matrix_library` or the `Eigen/` directory.

I am a bit puzzled about the PETSc error. Can you send us the directory structure (e.g. `tree`) of this `EBROOTPETSC`?

**Comment by moravveji** [comment]
Excellent typo catch Frédéric! I just fixed the missing "-D". However, the PETSc error is still there. 
I have attached the output of "tree -d".
[petsc.zip](https://github.com/precice/precice/files/3590573/petsc.zip)

**Comment by fsimonis** [comment]
Unfortunately, I cannot extract the file. Can you reupload it please?
```
$ unzip petsc.zip
Archive:  petsc.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of petsc.zip or
        petsc.zip.zip, and cannot find petsc.zip.ZIP, period.
```

**Comment by moravveji** [comment]
sorry for that!
Please try this one, then. This is a directory tree under which PETSc is installed.
[petsc.tar.gz](https://github.com/precice/precice/files/3594311/petsc.tar.gz)

**Comment by fsimonis** [comment]
Can you please provide me with a list of commands to rebuild your environment?
I see that you use easybuild, something I have never used.
This would help immensely to resolve this issue.

This problem has to do with the FindPETSc module we use.
Maybe you can get help in the original repository https://github.com/jedbrown/cmake-modules

**Comment by moravveji** [comment]
@fsimonis: Apologies in replying. This item totally skipped under my radar. 

I have attached a zip file with the export of my environment variables right before configuring preCICE (i.e. before calling `cmake`). The path to the top-level PETSc installation is properly defined in my environment as `EBROOTPETSC`. 

The reason for this strange-looking env. var. is that when we install some `<package>`(s) using EasyBuild [predefined EasyConfig files](https://github.com/easybuilders/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/p/PETSc), the module file contains the full path to the installed `<package>` following the internala EasyBuild naming convention like `EBROOT<package>` (all in capital letters). Therefore, the full path to the PETSc installation folder is available in my env; perhaps, it does not propagate well to the FindPETSc module. This is our standard practice, and we hardly have an issue with it.

Please let me know if I have to provide more inputs.

[envs.tar.gz](https://github.com/precice/precice/files/3651027/envs.tar.gz)

**Comment by moravveji** [comment]
Just an update: I supressed all use of PETSc and then the compilation succeeded.

**Comment by fsimonis** [comment]
@moravveji I will leave this issue open until we have a wiki entry that addresses this issue.

**Comment by fsimonis** [comment]
This issue should have been solved by the migration of the FindPETSc module  #551.
