### ISSUE TITLE
Attempt to get MPI_Comm_rank() in serial simulations with PETSc

### ISSUE THREAD

**Issue by MakisH** [precice/precice#499]
With ~~https://github.com/precice/precice/pull/382~~ https://github.com/precice/precice/commit/ae1a747aeed7950cc3aa800bbb59ac2024ff760a, an error for serial simulations that use PetRBF was introduced:

```
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[Magdalena:6012] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

Parallel simulations work fine.

You can reproduce this using any solver dummy or adapter and setting PetRBF mapping, e.g.:
```xml
      <mapping:petrbf-thin-plate-splines direction="write" from="MeshTwo" to="MeshOne" constraint="conservative"/>
      <mapping:petrbf-thin-plate-splines direction="read"  from="MeshOne" to="MeshTwo" constraint="consistent" />
```
This also affects our current FSI tutorials. This passed through as we don't yet have a system test that checks PetRBF, the first of which we are going to introduce in https://github.com/precice/systemtests/pull/85.

Could maybe the error originate from this?

https://github.com/fsimonis/precice/blob/51542b11e39f67cb55e60a7a7d0041af96bf0308/src/utils/Petsc.cpp#L66

**Comment by fsimonis** [comment]
@MakisH This is required for PETSc to use the provided communicator:
> https://github.com/fsimonis/precice/blob/51542b11e39f67cb55e60a7a7d0041af96bf0308/src/utils/Petsc.cpp#L66

@uekerman Didn't we find out that PETSc is used during configuration to preallocate things?
In that case the initialization should never have worked for solvers that don't inititalize MPI themselves *and* use PETSc.
We currently initialize MPI at the end of the configuration:
https://github.com/fsimonis/precice/blob/51542b11e39f67cb55e60a7a7d0041af96bf0308/src/precice/impl/SolverInterfaceImpl.cpp#L189
has to go to the top like here:
https://github.com/fsimonis/precice/blob/51542b11e39f67cb55e60a7a7d0041af96bf0308/src/precice/impl/SolverInterfaceImpl.cpp#L133

@MakisH can you try if this fixes the problem?

**Comment by MakisH** [comment]
I ran a full git bisect and the first bad commit is actually https://github.com/precice/precice/commit/ae1a747aeed7950cc3aa800bbb59ac2024ff760a (the one before).

Moving the initialization did not help:
```c++
  PRECICE_CHECK(not (_accessor->useServer() && _accessor->useMaster()), "You cannot use a server and a master.");
  PRECICE_CHECK(_accessorCommunicatorSize==1 || _accessor->useMaster() || _accessor->useServer(),
        "A parallel participant needs either a master or a server communication configured");

  utils::Parallel::initializeMPI(nullptr, nullptr);

  _clientMode = (not _serverMode) && _accessor->useServer();
```
But I also believe that this has something to do with the order of MPI / PETSc initialization.

**Comment by fsimonis** [comment]
@MakisH Sorry, I missed something.

Can you try to move the mpi initialization to the this line:

https://github.com/fsimonis/precice/blob/51542b11e39f67cb55e60a7a7d0041af96bf0308/src/precice/impl/SolverInterfaceImpl.cpp#L103

**Comment by MakisH** [comment]
@fsimonis yes, this works!
