### ISSUE TITLE
feature request: with full debug output, show also PETSc output

### ISSUE THREAD

**Issue by davidsblom** [precice/precice#50]

**Comment by floli** [comment]
Use a quick workaround, put a file ```.petscrc``` in your home. There are a large number of petsc options to set, example:
```
% cat ~/.petscrc 
# -info
-log_summary
# -info -mat_view ::ascii_info
-ksp_view -ksp_converged_reason -ksp_final_residual -ksp_monitor_true_residual
```

**Comment by davidsblom** [comment]
I tried using the MUMPS solver for the linear system as follows:

```
# -info
-log_summary
# -info -mat_view ::ascii_info
-ksp_view -ksp_converged_reason -ksp_final_residual -ksp_monitor_true_residual
-pc_factor_mat_solver_package mumps
```

But the solver always uses the block-Jacobi preconditioning. Couldn't find the call to `PCSetFromOptions` in the code, so maybe that's it.

**Comment by floli** [comment]
Do you get messages like these?
```
WARNING! There are options you set that were not used!
WARNING! could be spelling mistake, etc!
```

PCSetFromOptions should be called by KSPSetFromOptions, so this should not be a problem.

**Comment by davidsblom** [comment]
Thanks! Just tried again on a different test case, but run into a new problem #52

**Comment by davidsblom** [comment]
with commit bf229baa804349c0adb436d3d3c0159c4d07eb83 it works like a charm. I'm using the MUMPS direct solver, now only 1 GMRES iteration is needed :+1: 

```
davidblom@tud276993:~$ cat ~/.petscrc
# -info
# -log_summary
#-ksp_final_residual -ksp_monitor
-pc_type cholesky 
-pc_factor_mat_solver_package mumps
```

**Comment by floli** [comment]
Yeah, forgot to mention this issue in the commit, could #52 be closed then?

**Comment by davidsblom** [comment]
I just tried again, and also got an error from MUMPS.

```
[0]PETSC ERROR: MatFactorNumeric_MUMPS() line 1172 in /home/davidblom/repositories/openfoam/davidblom-3.1-ext/src/thirdParty/petsc-3.6.4/src/mat/impls/aij/mpi/mumps/mumps.c
    Error reported by MUMPS in numerical factorization phase: INFO(1)=-10, INFO(2)=0
```

Do you have any ideas?

**Comment by davidsblom** [comment]
I just tried to use the old RBF implementation, and apparently the matrix is singular:

```
(0) 10:53:42 [precice::mapping::RadialBasisFctMapping]:238 in computeMapping: Interpolation matrix C has determinant of 0, e.g. is not regular
```

**Comment by floli** [comment]
The method we use to determine if its singular or not may not be reliable, see #59
