### ISSUE TITLE
Restructure tools and bindings

### ISSUE THREAD

**Issue by MakisH** [precice/precice#512]
With v2.0.0 we want to clean-up a few relics and to also better organize the (increasing) bindings and tools.

We decide on the following:
- [x] Move Python bindings into a separate repository: [`precice/python-bindings`](https://github.com/precice/python-bindings). Repository name consistent with adapters' repositories.
- [x] Move Matlab bindings into a separate repository: [`precice/matlab-bindings`](https://github.com/precice/matlab-bindings). Repository name consistent with adapters' repositories.
- [x] Move C, Fortran90, and Fortran2003 bindings to `extras/bindings`.
- [x] Move `tools/` to `extras/tools`.
- [x] Split the `tools/` and move the solverdummies to `extras/solverdummies`.

**Comment by uekerman** [comment]
While doing this we should also look out for deprecated tools and remove them.

**Comment by BenjaminRueth** [comment]
Note: Naming the bindings repository `precice/python-bindings` is fine. But we should name the package `precice`, since the user using python should see that he is interacting with preCICE:

We want to call `import precice` inside python **not** `import python_bindings`.

**Comment by fsimonis** [comment]
Remember to copy the license when you move a tool to a separate repository.

**Comment by BenjaminRueth** [comment]
I added two new repositories for the MATLAB and python bindings:

* https://github.com/precice/matlab-bindings
* https://github.com/precice/python-bindings

**Comment by MakisH** [comment]
> Remember to copy the license when you move a tool to a separate repository.

We should also acknowledge the contributors somehow.

**Comment by BenjaminRueth** [comment]
> > Remember to copy the license when you move a tool to a separate repository.
> 
> We should also acknowledge the contributors somehow.

We could do it in the `README.md`?

**Comment by BenjaminRueth** [comment]
> > > Remember to copy the license when you move a tool to a separate repository.
> > 
> > 
> > We should also acknowledge the contributors somehow.
> 
> We could do it in the `README.md`?

I added a contributors list to both `README.md` files.

* https://github.com/precice/matlab-bindings/blob/develop/README.md#contributors
* https://github.com/precice/python-bindings/blob/develop/README.md#contributors

If you see your name on the list and you think this is too much appreciation, feel free to remove it. I was following a very open policy. If I forgot somebody, feel free to add the name.

**Comment by BenjaminRueth** [comment]
Matlab bindings are moved now. See https://github.com/precice/matlab-bindings/pull/5

**Comment by uekerman** [comment]
Which tools do we want to keep? Please comment below, I'll then try to keep this entry as an overview up-to-date.

As minimal requirements to keep a tool I suggest:
1. It has a `README.md` explaining what it is and how to use it.
2. It works. 
3. It has an entry on the [tools wiki page](https://github.com/precice/precice/wiki/Tools-included-in-preCICE).

Currently we have the following in `tools`:
* `cad_converter` "geometry parser to prepare CAD files for preCICE" -> deprecated, **let's remove it**
* `formatting`
  * [ ] needs a wiki entry
* `packaging`: is this still used?
  * [ ] needs a wiki entry
  * [ ] needs a `README.md`
* Let's move all travis scripts into a subfolder `travis`:
  * scripts:
    * `travis-bindings-test.sh`
    * `travis-build-test.sh`
    * `travis-coverage.sh`
    * `travis-install-dependencies.sh`
  * [ ] needs a wiki entry
  * [ ] needs a `README.md`
* `updateSourceFiles.py`
  * [ ] needs a wiki entry
* `communication_dummies`  
  * I guess it could still be helpful (if e.g. used as a system test), but currently does not build and still uses scons.
  * Anyone wants to have a look or do we remove it?
* `JobCommandFiles` -> only one file for deprecated SuperMUC, **let's remove it** (should better go into the wiki anyway)
* `rbfShape.py`
  * [ ] helpful, but needs some documentation in the [RBF config documentation](https://github.com/precice/precice/wiki/Mapping-Configuration#radial-basis-function-mapping)
* `compileAndTest.py`
  * is it still fully functional?
* `livegraph` "visualizes the coupling convergence etc. at runtime"
  * still functional?
  * [ ] needs wiki entry
* `solverdummies` -> **move to `extras/solverdummies`**
* `conda_building`
  * deprecated, does it still work? Should we remove it?
* `mpi`
  * could still be useful to test whether MPI ports is properly supported by a certain MPI version
  * [ ] needs a wiki entry
* `structure0815`  
  * Currently probably not working and does not have enough documentation.
  * I would really like to see this solver revived (by a student project etc.). Could make a really nice part of a tutorial and could also be very useful for some of our users if documented properly.
  * Should we move it to a separate repository? Or directly to a tutorial (branch)?

**Comment by fsimonis** [comment]
@uekerman Some notes on some of the points:

* `formatting` should really be mentioned in the developer documentation, probably both under tooling and conventions.
* `packaging` contains files required for the packaging, thus no tools as such.
  Does this really need a README?
* `compileAndTest.py` I migrated it to CMake in efeebbfebc294cc0c8631e115c6a48d703ef4d8d, so it is functional.
* `structure0815` Lets move it to another repo as it is a stand-alone tool.

Additional notes:
* Don't we want to move everything to `extra/`?
* Do we need the `formatting` directory? We could move all developer tools to a single folder such as `extra/dev/`.

**Comment by uekerman** [comment]
>     * `packaging` contains files required for the packaging, thus no tools as such.
>       Does this really need a README?

If it has no README we (some of us) will just be wondering again what this is exactly.

> Additional notes:
> 
>     * Don't we want to move everything to `extra/`?
yes, `tools` will become `extra/tools`, 

> 
>     * Do we need the `formatting` directory? We could move all developer tools to a single folder such as `extra/dev/`.

I am not sure if we want to distinguish between user and dev tools. Most of them are somehow in between, right?

**Comment by fsimonis** [comment]
> I am not sure if we want to distinguish between user and dev tools. Most of them are somehow in between, right?

Is a user ever going to reformat the precice code-base, or update the source/header files for CMake?

**Comment by uekerman** [comment]
> Is a user ever going to reformat the precice code-base, or update the source/header files for CMake?

No, but I guess this was rhetorical :wink: 
But where do you want to draw the line and, more important, why do we need to draw a line?

Which structure would you suggest in `extras`?
* `solverdummies`
* `dev`
* `ci`
* `packaging`
* `building`
* `misc` 
?

**Comment by MakisH** [comment]
Shouldn't the Travis and CMake files (i.e. tightly bound to the source code) be in a separate directory than user-helping tools (i.e. not in `extras`)? I could imagine `extras` being a directory that we ship in a preCICE package, but not the currently assumed as `dev` directory.

**Comment by uekerman** [comment]
Maybe let's do the opposite list. What is really sth that a user could use and that we want to keep:
* `rbfShape.py`
* `livegraph` (if it still works)
* `solverdummies`

Where should the rest go?

**Comment by uekerman** [comment]
I moved `Structure0815` to an own repo: https://github.com/precice/6dof-rigid-body-solver

**Comment by fsimonis** [comment]
Regarding restructuring, I could not find the original layout description that I had in mind anymore.

I found something very similar, which ticks all the boxes, except that they also use a `tools/` folder for developer scripts.

The layout is called [The Pitchfork Layout](https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs#tld) and seems to be pretty well documented.

I vote to adopt this layout :hand:

**Comment by MakisH** [comment]
Having a closer look at our Fortran bindings, I think that we should also move the "Fortran 2003" bindings to a separate repository. They are just using our "Fortran-compatible C-named C++ interface", which is defined in SolverInterfaceFortran.[hpp|cpp] (with `extern "C"`) and compiled into the library.

They have a separate building procedure, which is pretty much like building the Fortran 90 solverdummy (linking to the library, which provides compatible names). This then produces a Fortran module, which we can use to compile any modern Fortran solver. We currently even suggest that the user builds the bindings at the same time as the solver (which is not needed).

To me, it looks like exactly the same case as our Cython-based Python bindings, so we could treat them the same way.

**Comment by MakisH** [comment]
And a rough schematic overview (according to my understanding):

![FortranBindings](https://user-images.githubusercontent.com/4943683/73143218-a9216980-4097-11ea-841b-c0dc62a8ceb0.png)

I still don't understand where the name conversion between `precicef_create_` and `precicef_create` in the "old Fortran" bindings happens (I don't see any explicit `bind` call). In the "modern Fortran" bindings, there is an explicit `bind` to the respective "old Fortran" bindings names.

**Comment by uekerman** [comment]
OK and understandable for me to move the f2003 module as well.
Small mistake in the picture: the old fortran bindings call the C++
interface, not `impl`.
Otherwise, nice and helpful drawing, let's include it in doxygen!
No real expert, but I always thought that the ending underscore is some
kind of necessary function ending which gets stripped ending when using a C
function in Fortran.

**Comment by MakisH** [comment]
Indeed, the names are a bit confusing:
```c++
impl = new precice::SolverInterface(stringAccessorName,
                                      *solverProcessIndex, *solverProcessSize);
```

Here is an updated version:

![FortranBindings](https://user-images.githubusercontent.com/4943683/73161236-5c677e00-40eb-11ea-9b30-43dc723f0035.png)

**Comment by fsimonis** [comment]
According to the pitchfork layout, we should move developer tools to `tools/`.

**Comment by MakisH** [comment]
The "Fortran 2003 bindings" are now renamed to "Fortran module" and moved to https://github.com/precice/fortran-module.
