### ISSUE TITLE
Remove Scons support

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#521]
_No description required._

**Comment by fsimonis** [comment]
Does this include SCons in other projects?

```
tools/solverdummies/fortran/SConstruct
tools/solverdummies/c/SConstruct
tools/structure0815/SConstruct-Linux
tools/structure0815/SConstruct-Windows
tools/structure0815/SConstruct
tools/communication_dummies/SConstruct
tools/cad_converter/SConstruct
```

They would of course have to be replaced by CMake/Make.

**Comment by MakisH** [comment]
Yes, I can remove SCons from everywhere. We will eitherway probably get rid of some of these tools.

**Comment by fsimonis** [comment]
Conclusion:
* Remove SCons for solverdummies
* Remove CAD Converter
* Move structure0815 into own repository
