### ISSUE TITLE
Let EventLog also print number of ranks

### ISSUE THREAD

**Issue by floli** [precice/precice#53]
@gk780 requested to let the EventLog print the number of ranks (from each participant) after the run.

**Comment by floli** [comment]
Verena reported procs = 1 for m2n socket and participant MPI.

**Comment by gk780** [comment]
I crossed checked it with 16 and 32 mpi ranks per domain, and always get  # Number of processors: 1 in Eventtimings. I am running on supermuc.

**Comment by gk780** [comment]
Last fix is working for me:
# Number of processors: 256
Thanks!

**Comment by gk780** [comment]
... want to close the ticket, dont find a button....may be I have no right to do that, leave it for @floli :)
