### ISSUE TITLE
Python solverdummy is still in Python 2

### ISSUE THREAD

**Issue by MakisH** [precice/precice#537]
Or at least [Python 2 to 3!](https://pythonconverter.com/) suggests that [this line](https://github.com/precice/precice/blob/cdc7dcdbbb2d3c62be7ebbb72f48fc29e3c1f0e7/src/precice/bindings/python/test/solverdummy.py#L52):

```python
interface.get_mesh_vertices(mesh_id, n+1, np.array(range(n+1)), position)
```
should be:
```python
interface.get_mesh_vertices(mesh_id, n+1, np.array(list(range(n+1))), position)
```

**Comment by BenjaminRueth** [comment]
I do not really understand, why this change is needed. For a `np.array()` a `range` is as good as a `list`, as far as I know. `list(range(...))` might even introduce overhead that is not even necessary. Do you have an idea why the tool suggest this conversion?

**Comment by MakisH** [comment]
This is indeed a false alarm. I guess the tool just always suggests to wrap a `range()` within a `list()`.
