### ISSUE TITLE
Solver dummies do not include read and write functions

### ISSUE THREAD

**Issue by KyleDavisSA** [precice/precice#538]
Currently, the solver dummies do not include any kind of read or write functionality. This is understandable as it is desired to be able to run a python solver dummy with a C solver dummy. But this can also make it difficult to troubleshoot problems when writing a new adapter for a new solver. It would be helpful if all solver dummies had a set input that can read and write data. An example could be:

- Each solver dummy would come with 2 solvers, A and B, and the config file. The solver dummy A can work with any other language solver B.
- Each solver has 3 vertices
- Each reads in data from the other solver and adds 1
- This can be read by the other solver and checked to see if the data transfer was correct (for simple nearest neighbor mapping with exactly the same vertices)

This way, the solver dummy can always be reviewed when writing a new adapter.

**Comment by uekerman** [comment]
> This is understandable as it is desired to be able to run a python solver dummy with a C solver dummy

I guess there is a misunderstanding here. You can still couple different solver dummies when data is exchanged. Is that what you meant?

Still, I agree that extending the dummies here could be helpful. 

> Each solver dummy would come with 2 solvers, A and B, and the config file. 

Just to double-check, both "solvers" would come in the same file, right? So, A or B is passed via a command line argument as it is the case already now.

Rest sounds good.

**Comment by BenjaminRueth** [comment]
> > Each solver dummy would come with 2 solvers, A and B, and the config file.
> 
> Just to double-check, both "solvers" would come in the same file, right? So, A or B is passed via a command line argument as it is the case already now.

See https://github.com/precice/precice/pull/540#issuecomment-546355879
