### ISSUE TITLE
setMeshVertices error if no vertex on the rank in python binding

### ISSUE THREAD

**Issue by yuxianglin** [precice/precice#543]
Hi:

In python bindings of preCICE, if there are not vertices on that rank,  if I ran set_mesh_vertices(_mesh_id, 0,np.array([]),np.array([])), it will prompt error showing
_File "precice_future.pyx", line 133, in precice_future.Interface.set_mesh_vertices
IndexError: Out of bounds on buffer access (axis 0)_

**Comment by BenjaminRueth** [comment]
Thanks for the bug report! I just pushed a fix to the `develop` branch. If you want to try the fix, you can simply clone the current version of develop. 

I will close this issue now. In case the fix does not help, please feel free to reopen the issue.
