### ISSUE TITLE
terminate called after throwing an instance of 'char const*'

### ISSUE THREAD

**Issue by venkcy** [precice/precice#544]
Dear peers,
[precice-config_parallel.xml.pdf](https://github.com/precice/precice/files/3802954/precice-config_parallel.xml.pdf)
[Fluid.log.pdf](https://github.com/precice/precice/files/3802959/Fluid.log.pdf)

I am trying to validate the cylinderFlap case by refining the mesh given in the tutorial. The `mapping configuration:petrbf-thin-plate-splines` does not manage to give accurate results. I got approximately 50% error in the displacement. On the advice of peers available on gitter, I changed the mapping configuration to `petrbf-gaussian` with `shape-parameter="float"`. Now, the simulation does not run and throws an error saying `terminate called after throwing an instance of 'char const*'`

The log and the configuration files are attached.

Your inputs are highly valuable to me.

Thanks!

**Comment by fsimonis** [comment]
The error is misleading, but the cause is simple:

You write `shape-parameter="float"`, however, the shape parameter **is** a floating point value e.g. `1.23`. `shape-parameter="1.2"` would be valid.
Have a look at this [overview of basis funtions](https://xgm.de/precice/docs/develop/BasisFunctions_8hpp.html) in order to find required configurations.

We definitely need additional documentation for this part.

**Comment by venkcy** [comment]
Thanks for your reply!
The case is still running. I will revert back in this thread.

**Comment by venkcy** [comment]
Thanks for your time! 
Are there any criteria for selecting a `shape-parameter`? I get the following error 

`terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >'
  what():  Failed to set TLS value: Invalid argument`

**Comment by fsimonis** [comment]
This is a common problem in the initialization phase of preCICE.
The library _sadly_ cannot detect faulty address files from a previous execution that crashed while connecting the communication endpoints. 
The simple solution is to remove the `precice-run` folder if it exists or `*address`  files for older versions.

For further details please have a look at our [troubleshooting guide](https://github.com/precice/precice/wiki/Problems-with-Establishing-the-Communication).

**Comment by venkcy** [comment]
I tested the `petrbf-gaussian` mapping scheme with `shape-parameter=1` in the tutorial file for cylinderFlap. I do get the same error even in a fresh case. While exploring, `petrbf-gaussian` does not works while reading from `calculix` to `fluid mesh`. 
For your reference, the following throws the above error,
        `<mapping:petrbf-thin-plate-splines direction="write" from="Fluid-Mesh-Faces" to="Calculix_Mesh" constraint="conservative" z-dead="true" />
        <mapping:petrbf-gaussian shape-parameter="1.0" direction="read" from="Calculix_Mesh" to="Fluid-Mesh-Nodes" constraint="consistent" />`
while, the following works
`        <mapping:petrbf-gaussian shape-parameter="1.0" direction="write" from="Fluid-Mesh-Faces" to="Calculix_Mesh" constraint="conservative" z-dead="true" />
        <mapping:petrbf-thin-plate-splines direction="read" from="Calculix_Mesh" to="Fluid-Mesh-Nodes" constraint="consistent" />`.

My objective is to validate the cylinderFlap (Turek  Hron FSI benchmark) with fine mesh.

Thanks for your timely response!

**Comment by MakisH** [comment]
@venkcy this is very strange, as mapping has nothing to do with establishing a TLS connection.
Could you please repeat your observation and see if your observation holds? If yes, then please open a separate issue with more details (and the complete error log).

**Comment by venkcy** [comment]
Are there any criteria for choosing the `shape-parameter`? I ran the tested with three values `0.05,1,50`. All three failed to run.

**Comment by fsimonis** [comment]
The shape parameter has to be positive.

Your error, however. is related to the initialization of the communication.
Please create a debug build, make the logger print debug statements and run the simulation again.

**Comment by venkcy** [comment]
Thanks! I will try uploading the log files by tomorrow.
