### ISSUE TITLE
C++ API: Rename fulfilledAction

### ISSUE THREAD

**Issue by ajaust** [precice/precice#546]
Hi,

While writing some code/adapter for a solver I was a bit confused by the function `fulfilledAction` as it appears to me that its intent is not as clear from its name as for other API calls. [All API](http://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html) calls are actions/verbs or start with a simple verb that makes clear what the function does. However, `fulfilledAction` did appear too vague compared to the other functions as I seem to have several interpretations of "fulfilled".

Example:
`bool isActionRequired(const std::string &action)`: "Is an action required?" -> It will check if the supplied action `action` is required.

`void fulfilledAction (const std::string &action)`: "Is the action fulfilled?" or "The action is fulfilled!" -> At least to me the name leaves a some room for interpretation what is going on. Maybe I am bad at interpreting "fulfilled" in this context.

Maybe if would be help to rename the function?

Some suggestions:

- `actionIsFulfilled`: Clear what is does, but breaks the current approach that functions start with a verb.
- `performedAction`, `executedAction`: Short, but maybe somewhat vague?!
- `announceActionFulfilled`: Longer and clear.  Consistent with `isActionRequired` which is also rather long.
- `announceFulfilledAction`: Longer and clear, but inconsistent.

What are your thoughts about that?

Thank you!

**Comment by uekerman** [comment]
I fully agree. I already had a bad feeling about this for some time.
From your suggestions, I like `announceActionFulfilled` the most, but I'll add another suggestion: What about removing the function and the connected safeguard functionality altogether? I am not yet sure about this. Opinions?

**Comment by ajaust** [comment]
I would be fine with the function being removed. I am not sure how helpful it is to others. How often did this trigger an error because someone forgot some action (read/write checkpoint)? Can you do some of the checks within preCICE even without the safeguard?

**Comment by fsimonis** [comment]
@ajaust I agree that the name `fulfilledAction` is vague and misleading.
But, instead of `announceActionFulfilled`, we could also simply call it `notifyActionFullfilled`.
```cpp
if(si.isActionRequired(X)) {
  // perform action
  si.notifyActionFullfilled(X);
}
```

Alternatively, we could move to a more transactional style:
```cpp
if(si.isActionRequired(X)) {
  // perform action
  si.commitAction(X);
}
```

Furthermore, we could switch from passive to active:
```cpp
if(si.requireAction(X)) {
  // perform action
  si.commitAction(X);
}
```
( And add this snipped to the doxgen of both functions. )

**Comment by uekerman** [comment]
* I guess `commitAction` is hard to understand and also a bit misleading. One could understand that the action gets performed in `commitAction`. 
* `requireAction` is the opposite function. https://github.com/precice/precice/blob/develop/src/cplscheme/CouplingScheme.hpp#L190
* `notifyActionFullfilled` sounds good as well

> Can you do some of the checks within preCICE even without the safeguard?

In general no, as preCICE does not know what the solver did in the meanwhile. For `initialDataRequired` probably yes. 

>  How often did this trigger an error because someone forgot some action (read/write checkpoint)?

This is the important question ... hard to say.

**Comment by uekerman** [comment]
I suggest to rename the function to `announceActionFulfilled`. Protests?
Please note that this will be a breaking change again, requiring updates on all bindings and adapters.
