### ISSUE TITLE
Clarify CMake Variables 

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#553]
# Problem

The main configuration variables for preCICE are: `MPI`, `PETSc`, and `PYTHON`.

While the first two are relatively straight forward, it is not clear that they (hopefully only) affect preCICE.
The latter is a common and very effective source of confusion as it solely relates to the module enabling user-provided python actions. It does not affect the python bindings.

# Proposition

1. Prefix all variables with `PRECICE_`. This clarifies that these variables are related to preCICE and also displays them as a neat group in the CMake GUI.
2. Rename the `PYTHON` variable to `PRECICE_PYTHONACTIONS` to prevent future misunderstandings and confusion.
3. Keep backwards compatibility by detecting the old variables and using their values. We should add a depreciation message in such cases.

**Comment by uekerman** [comment]
Is (1) a standard procedure? 
(2) sounds reasonable to me. Though the problem might disappear when we "outsource" the Python bindings.
I would not be concerned so much with the backwards compatibility here if we introduce this with v2.0.

**Comment by fsimonis** [comment]
1. Let's say that it is best-practice.

    > Try to establish a variable naming convention early. For cache variables, consider grouping related variables under a common prefix followed by an underscore to take advantage of how CMake GUI groups variables based on the same prefix automatically.

    Section 5.10 from "Professional CMake: A Practical Guide" [go and get it](https://crascit.com/professional-cmake/)

2. I fear that this will stay a pain as long as we have python bindings.  
    You are right regarding backwards compatibility. So it will be a 2.0 feature.
    This should not be difficult to print as we have the variable output at the beginning.
