### ISSUE TITLE
Improve Debug information for mapping

### ISSUE THREAD

**Issue by uekerman** [precice/precice#556]
Instead of just giving the first 10 mapped values as debugging information, such as here ...

https://github.com/precice/precice/blob/91fafe7a90db8a0985ccef0a0131624dcdc8ff85/src/precice/impl/SolverInterfaceImpl.cpp#L997

... it would be better to give the first two to three, the last two to three, the max and the min value.

**Comment by fsimonis** [comment]
So we really need some preview object for `Eigen::VectorXd` / ranges.
