### ISSUE TITLE
More context required in com::Communication

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#570]
# Problem

When implementing the 2-phase initialization, there can be cases where the communication build-up for meshes between the same participants mix up. This leads to a deadlock.

An example being the elastic1d-case:

![1d](https://user-images.githubusercontent.com/13552216/69421959-b8e0a280-0d22-11ea-9660-cd0fbd473e17.png)

The single M2N has 2 `m2n::DistributedCommunication` instances for the 2 meshes.
Running with 4 solid and 3 fluid ranks, the communication map looks as follows:

Solid | Fluid
--- | ---
0 | 0,1
1 | 0,1,2,3
2 | 2,3

The mix-up happens in this loop in both the accept and request variants:

https://github.com/precice/precice/blob/e7bd717e8e58e034a4a347baa68c3247a7bb7751/src/m2n/M2N.cpp#L135-L138

# Solution

The communication-buildup is lacking context. It knows the participants and the rank of the requester involved in the the connection, but lacks the additional information of what `m2n::DistantCommunication` it is connecting.
We need to forward this information to the Communicator, so that we can incorporate it into the `com::ConncectionInfoPublisher`.

Directly related to #142

**Comment by uekerman** [comment]
Doesn't the hash already include the mesh name? Or what exactly means mix-up?

**Comment by fsimonis** [comment]
> Doesn't the hash already include the mesh name?

No as it is not available that far down the line. This information is lost outside the `m2n` package.

**Comment by uekerman** [comment]
I currently face another problem, which seems connected to this one. Main difference is that it already happens with the current develop branch, so without the two-phase initialization.

I am using the Alya Flap testcase and the following config:

```
      <participant name="NASTIN">
         <master:A/>
         ...
      </participant>
      
      <participant name="SOLIDZ">
         <master:B/>
	   ...    
     </participant>
      
      <m2n:sockets from="NASTIN" to="SOLIDZ"  exchange-directory="../"/>
```

* For A=`mpi-single` and B=`mpi-single`, everything works fine
* For A=`sockets` and B=`mpi-single`, also everything works fine
* For A=`mpi-single` and B=`sockets`, I get the following error **for NASTIN**

```
*** An error occurred in MPI_Allreduce
*** reported by process [3424256001,3]
*** on communicator MPI_COMM_WORLD
*** MPI_ERR_OTHER: known error not in list
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

So far I could not reproduce this problem with any other testcase, but the pure fact that changing a configuration for SOLIDZ makes the communication of NASTIN crash is very awkward.
