### ISSUE TITLE
Remove Server Mode

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#574]
# Description
It is time to remove the server mode.

# Rational

It is a large and unused feature of the code.
It forces us to rewrite every function in the interface multiple times and requires additional logic:
* Every interface function X additionally requires:
  1. `RequestManager::requestX`
  2. `RequestManager::handleX`
  3.  An new enum value `RequestManager::Request::X`
  4. A case in `RequestManager::handlereques()` handling the above
* Calls to interface functions need to do different things depending on `client/serverMode`

Removing it:
* Reduces :ghost:-code
* Reduces the size of the interface functions and makes them easier to implement.
* Reduces the hooks one _has to think of_

**Comment by uekerman** [comment]
Doing this, we should also keep an eye on features that only work in the server mode, i.e. have not yet been parallelized.
