### ISSUE TITLE
Serial RBF: Check for invertable matrix is correct?

### ISSUE THREAD

**Issue by floli** [precice/precice#59]
Is the method to check if the matrix in invertable (using partialPivLU and determinate()) correct?

@uekerman

**Comment by davidsblom** [comment]
the manual of Eigen sheds some light on this:

### Computing inverse and determinant

First of all, make sure that you really want this. While inverse and determinant are fundamental mathematical concepts, in numerical linear algebra they are not as popular as in pure mathematics. Inverse computations are often advantageously replaced by solve() operations, and the determinant is often not a good way of checking if a matrix is invertible.
