### ISSUE TITLE
Resolve cyclic deadlocks for compositional coupling schemes

### ISSUE THREAD

**Issue by uekerman** [precice/precice#593]
On [Discourse](https://precice.discourse.group/t/deadlock-using-three-solver-explicit-coupling-scheme/114/6), @patelrohan008 reported a deadlock for a cyclic dependence of three participants when using serial coupling schemes. I guess that this problem could be solved by sorting coupling schemes where the accessing participant is "first" over those where it is "second" in 
https://github.com/precice/precice/blob/36ebf6983cfba568d9f59308770c732eba724f49/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L312-L314

I have not tested this assumption, however. Further integration tests would be necessary.

A more general study of this could also make a nice student thesis.

**Comment by fsimonis** [comment]
I added a cyclic test to #1462 and these cyclic steps are working now.

**Comment by davidscn** [comment]
Resolved via #1462
