### ISSUE TITLE
Default values of CMake options are confusing

### ISSUE THREAD

**Issue by ajaust** [precice/precice#596]
Hi,

I had some students compiling preCICE today and we ran into some problems. This came from the fact that the students had *not* specified `-DBUILD_SHARED_LIBS=ON` when running CMake. I was not of aware that this could be a problem as I have set this flag in a script that I use for compiling preCICE so I had forgotten about that. 

At the same time, optional dependencies have there flags set to `ON` (PETSc, Python and MPI). Should it not rather be the other way around: Sane standard settings that lead to a reasonable build and optional settings should be turned on by the users if they need them? The option `CMAKE_BUILD_TYPE` only allows for three options, but none of them is specified as default?

Regarding `BUILD_SHARED_LIBS` the wiki in says several times that one should create the shared libraries and that the static library is even unsupported. From my experience today is also that the static library does not work well (or at all?!). Is there a reason why `BUILD_SHARED_LIBS` is not set to `ON` by default?  If it is not possible to set it to `ON` by default I would suggest that the parts about recommending the shared library a bit more visible by making it bold or so.

Parts of this issue have been part of #283, but nothing was changed.

Best,
Alex

**Comment by fsimonis** [comment]
@ajaust Thank you opening this issue. I am sure that this is a common question among users. I'll grab the opportunity and give a longer answer.

## Our commitments

* Stick to the CMake defaults __(aka do not surprise users)__.
* Do not enforce what's unnecessary.
* Value and refine documentation.
* Provide a wide range of features by default.
* Stay consistent.

## Building shared vs static

We do not officially support building preCICE as a static library as the CMake configuration overhead becomes immense.
When linking to a static library target, the privately linked targets are transitively fowarded via the link interface. This means that a target using a staticaly-configured preCICE has to know **all** of its internal dependency targets as well. This can be done, but it is something we are not willing to support nor encourage.
The only usable alternative we came up with is to generate a list of required libraries as part of the pkg-config file and let it assemble the required flags for you. You can find a prototype here: #313 Feedback is always welcome!

Sadly, CMake defines libraries as static by default, thus we encourage configuring preCICE with `-DBUILD_SHARED_LIBS=ON`.
This means that configuring is in "expert mode" by default.

However, we should definitely expose `BUILD_SHARED_LIBS` as an option in case the user did not explicitly set it. This way, `cmake-gui` or `ccmake` will clearly display the option.

## The build type

There is no default `CMAKE_BUILD_TYPE`. This results in an _unoptimized non-debug build_, a valid but questionable use-case.
While we want to stick with the default, we agree that this is quite silly.

Our idea for handling this scenario:
1. Emit a warning stating that `CMAKE_BUILD_TYPE` was not set.
2. Register it as a cache variable with the various options as choices.
3. Set its value to `Debug`

This way, the user will see the choices in its GUI and will have a save build by default.

## Optional dependencies

We regard `MPI` and `PETSc` as crucial dependencies, which may be optional, but will dramatically limit the use case of preCICE when disabled.
Thus, we decided to enable them by default and make the configuration fail if a required package was not found. So the user has the choice to _consciously_ disable dependencies if they are not found on the system.

The option `PYTHON` enables the support for user-provided python actions which is a misleadingly named and (to our knowledge) unused feature of preCICE.
We leave this option on for the sake of consistency.

---

I constantly experiment with methods on the CMake side of the project to improve conveying information to the user.
Displaying information relevant to the user and required by the developers (for support) without being overly verbose is quite a challenge though.
I am currently looking into [FeatureSummary](https://cmake.org/cmake/help/v3.10/module/FeatureSummary.html), which seems to tick all of the boxes.

Expect some improvements soon!
