### ISSUE TITLE
Tests with multiple sockets connections hang on Travis

### ISSUE THREAD

**Issue by uekerman** [precice/precice#599]
In #572, I had to enforce gather-scatter communications in integration test that use a `m2n:sockets`, see https://github.com/precice/precice/pull/572/commits/cb764b1e5e12735009072d74bd0984f9b4bf5fef . Otherwise, the tests would hang on Travis. I, however, cannot reproduce this locally (Ubuntu 18.04). This applies to the following tests:
* `PreciceTests/Parallel/TestQN`
* `PreciceTests/Parallel/CouplingOnLine`

Previously (i.e. before #572), these tests needed to use a gather-scatter scheme as at least one of the participants is serial. So, we did not observe the problem, but we simply did not and could not test it.

Strangely, `M2NTests/SocketCommunication` do not give problems.

Rough guess is that this could either be a Travis or an Ubuntu 16.04 "feature". We could test it by comparing it to GitHub actions or running it locally on Ubuntu 16.04. To test, just pull #572, and remove `enforce-gather-scatter="true"` in one of the configs used in these tests.

**Comment by fsimonis** [comment]
Resolved by #702

**Comment by uekerman** [comment]
Let's test if this is actually resolved. I can do that.

**Comment by fsimonis** [comment]
Given the [latest pass](https://travis-ci.org/github/precice/precice/builds/703829100) of develop on Travis, this seems not to be a problem anymore.

@uekerman Can you please validate this and close this issue?

**Comment by uekerman** [comment]
Yes, works now :+1:
See https://github.com/precice/precice/pull/784
