### ISSUE TITLE
interface function hasReadData and hasWriteData necessary

### ISSUE THREAD

**Issue by uekerman** [precice/precice#60]
If two solvers of the same type -- let's say OpenFOAM-OpenFOAM (fluid-fluid) -- are coupled, we need API functions such as `hasReadData` and `hasWriteData` to distinguish both solvers. Imagine they use a Dirichlet-Neumann coupling, meaning they are supposed to do different things.
Only `hasData` is not sufficient in such a situation.

**Comment by davidsblom** [comment]
:+1:

**Comment by uekerman** [comment]
We tackle this now through the adapter configuration. Hence this issue is obsolete.
https://github.com/precice/openfoam-adapter/wiki/Configuration
