### ISSUE TITLE
Rename isTimestepComplete

### ISSUE THREAD

**Issue by uekerman** [precice/precice#602]
In my opinion it might be a good idea to rename our API function `isTimestepComplete`

https://github.com/precice/precice/blob/efeebbfebc294cc0c8631e115c6a48d703ef4d8d/src/precice/SolverInterface.hpp#L253-L265

to sth like `isTimeWindowComplete` as from solver perspective, it's a complete time window, not a single timestep.

Opinions?

**Comment by BenjaminRueth** [comment]
Maybe `isCouplingWindowComplete`? What we are doing inside the window is one coupling step (with QN and everything).

**Comment by MakisH** [comment]
I think we don't use the term "time window" anywhere until now (but if it a standard term, why not). We always use "coupling time step". The natural name then would be `isCouplingTimeStepComplete`.

Notice also how I used "time step" and not "timestep". If we use "timestep" everywhere, then let's keep it like this.

**Comment by BenjaminRueth** [comment]
I think we have to ask ourselves the question how and what the user has to understand the API. Some background:

* Within our research on multirate timestepping we found the term "window" to be fitting for the scenario, where the solvers do multiple (not necessary the same number of) timesteps and they are synchronized only at the end of the window.
* Currently preCICE supports subcycling, which allows multiple (solver-)timesteps within one (preCICE-)timestep. In our current naming convention the word timestep is used twice: Once for the actual timestep of the solver and once for the timestep from one synchronization point to the next. This is not ideal.

How much of this background story do we want our users to understand? Which are the proper terms to distinguish between what timestep means for the solver and for preCICE?

Here, I think the term `window` is a good choice: It avoids confusion with the term timestep that is probably already used by the solver (Example: Solver performs n implicit euler timesteps).

It might also be a good idea to postpone this discussion until our API for consistent time stepping is more finalized and the terms that we are going to use are more clear.

**Comment by MakisH** [comment]
The above was very helpful additional information! I would also say let's postpone this until we actually need to change it, when the time interpolation get integrated.

**Comment by uekerman** [comment]
We would vote against postponing it as the current version is kind of wrong (mixing up both "timesteps") and leads to misunderstandings, as [here](https://github.com/precice/calculix-adapter/pull/23).

We already use the term window in our [documentation](https://github.com/precice/precice/wiki/Adapter's-Time-Step-Sizes). 

> Maybe isCouplingWindowComplete? What we are doing inside the window is one coupling step (with QN and everything).

I think we should avoid "coupling" as it is kind of redundant and everything we do is "coupling" :wink:
Just to be sure: currently `istTimestepComplete`return true when the end of the window is reached **and** the implicit coupling is converged.

**Comment by MakisH** [comment]
I cannot argue if this will stay stable, but if you are confident that this will not need to change again in with time interpolation added, then ok! Just keep in mind that this will break all adapters, bindings, dummies, and every in-house solver adapted.

I would prefer a solution where we still keep a (very thin) wrapper `isTimestepComplete` that redirects to the actual method, but throws a "deprecated" warning (with suggestion) at compile time and remove it later.

**Comment by BenjaminRueth** [comment]
> Just to be sure: currently `isTimestepComplete`returns true when the end of the window is reached **and** the implicit coupling is converged.

A comment on this: If you want to know whether you reached the end of the window, but it did not converge, you can use `isActionRequired(actionReadIterationCheckpoint())`. This usually means: Solver reached the end of the window, but preCICE tells the solver to rollback and repeat the window, since the coupling has not converged yet.

**Comment by BenjaminRueth** [comment]
Conclusion: Let's use the name `isTimeWindowComplete` and keep a wrapper `isTimestepComplete` that redirects to the method (+ deprecated warning). Now we only need to implement this ;)

**Comment by BenjaminRueth** [comment]
> Conclusion: Let's use the name `isTimeWindowComplete` and keep a wrapper `isTimestepComplete` that redirects to the method (+ deprecated warning). Now we only need to implement this ;)

I think we still need a clear decision (some discussion going on in https://github.com/precice/precice/pull/619#discussion_r368572705):

1) Deprecate `isTimestepComplete` and throw a warning
2) Delete `isTimestepComplete`

Let's keep the discussion in this issue, since this is a more fitting place (not in #619).

**Comment by KyleDavisSA** [comment]
> Deprecate isTimestepComplete and throw a warning
   Delete isTimestepComplete


If there is going to be breaking changes anyways in https://github.com/precice/precice/pull/614, then I would go with option 2. Otherwise I would go with option 1.

**Comment by uekerman** [comment]
I also vote for option 2. I guess that `isTimestepComplete` is also not used by too many adapters / users as you only need it when supporting subcycling + implicit coupling.

**Comment by BenjaminRueth** [comment]
As far as I know `isTimestepComplete` is also not mentioned in the [Adapter Example](https://github.com/precice/precice/wiki/Adapter-Example). This should also limit the actual relevance of this function for our users.

**Comment by fsimonis** [comment]
Closed by #619
