### ISSUE TITLE
Regression in computeNormals for Nearest-Projection in 3D

### ISSUE THREAD

**Issue by MakisH** [precice/precice#603]
Trying to run our `FSI/3D_Tube/OpenFOAM-CalculiX` tutorial (which uses 3D solvers and nearest-projection mapping), preCICE crashes without an error message in develop (v1.6.1-184-g[f5ce579](https://github.com/precice/precice/tree/f5ce5799fc7aa052bff58498cb07cedd9aeff3c5)
) and all the way since at least v1.4.1. I also tried with tutorials from `master` and `develop`. I have definitely ran this tutorial successfully in the past, but I don't believe it was before v1.4.1.

[Fluid.log](https://github.com/precice/precice/files/3989038/Fluid.log)
[Solid.log](https://github.com/precice/precice/files/3989039/Solid.log)
[precice-config_serial.xml.txt](https://github.com/precice/precice/files/3989041/precice-config_serial.xml.txt)

**Comment by fsimonis** [comment]
The problem likely originates from:

https://github.com/precice/precice/blob/301f7893d34214e6ba9ce3519cd8e96938e8499f/src/mesh/Mesh.cpp#L273-L282

According to the docs of [normalized()](http://eigen.tuxfamily.org/dox/classEigen_1_1MatrixBase.html#a5cf2fd4c57e59604fd4116158fd34308), this should return the vector itself if its norm is close enough to zero.
[This example](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:14,positionColumn:2,positionLineNumber:14,selectionStartColumn:2,selectionStartLineNumber:14,startColumn:2,startLineNumber:14),source:'%23include+%3CEigen/Core%3E%0A%23include+%3Ciostream%3E%0A%0A//+Type+your+code+here,+or+load+an+example.%0Aint+main()+%7B%0A++Eigen::Vector3d+a+%3D+Eigen::Vector3d::Ones()%3B%0A++for+(int+i+%3D+0%3B+i+%3C+170%3B+%2B%2Bi,+a+/%3D+10)+%7B%0A++++Eigen::Vector3d+n%3B%0A++++n+%3D+a.normalized()%3B%0A++++std::cout+%3C%3C+i+%3C%3C+!'%3B!'+%3C%3C++a.squaredNorm()+%3C%3C+!'%3B!'+%3C%3C+n.squaredNorm()+%3C%3C+!'%5Cn!'%3B%0A++%7D%0A%0A++return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang600,filters:(b:'1',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),fontScale:14,j:1,lang:c%2B%2B,libs:!((name:eigen,ver:'334')),options:'-DNDEBUG',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'x86-64+clang+6.0.0+(Editor+%231,+Compiler+%231)+C%2B%2B',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,wrap:'1'),l:'5',n:'0',o:'%231+with+x86-64+clang+6.0.0',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) displays nicely that this does not lead to problems even with very small values.

These normals are all initialized to 0.

**Comment by uekerman** [comment]
@MakisH which Eigen version do you use?

**Comment by MakisH** [comment]
The edges and vertices seem indeed to be quite close to zero:
[Fluid.log](https://github.com/precice/precice/files/4046896/Fluid.log)
[Solid.log](https://github.com/precice/precice/files/4046897/Solid.log)

It looks like the error depends on the Eigen version. The above errors are with [Eigen 3.3-beta1](http://eigen.tuxfamily.org/index.php?title=News:Eigen3.3-beta1_released!) (Ubuntu 16.04 package `libeigen3-dev`, version 3.3~beta1-2). Getting the latest Eigen 3.3.7 (as well as 3.3.0) works as expected.

Note that our tests (at least in 1.6.1) don't complain.

**Comment by MakisH** [comment]
I updated the documentation for Ubuntu 16.04. Unless it makes sense to add a test or dependency requirement, we can close this issue as `wont-fix`.

**Comment by uekerman** [comment]
We could also easily work around the problem. Just setting the normal to 0 instead of normalizing it if it is too small.

**Comment by uekerman** [comment]
After discussion with @fsimonis, we decided to indeed close this as wont-fix. We documented it, should be enough here.
