### ISSUE TITLE
Assertion Failure instead of error message: IQNILSAcceleration::removeMatrixColumn(int)

### ISSUE THREAD

**Issue by IshaanDesai** [precice/precice#616]
I got the following assertion failure from preCICE:
```
ASSERTION FAILED
  Location:          virtual void precice::acceleration::IQNILSAcceleration::removeMatrixColumn(int)
  File:              /home/ishaan/precice/src/acceleration/IQNILSAcceleration.cpp:266
  Rank:              0
  Failed expression: _matrixV.cols() > 1
```
when I run `./Allrun` on the code commit: https://github.com/precice/elastictube1d/pull/22/commits/d912f37454256af86fc94500aa77eeb19e9dea44 of the `elastictube1d/python`. 
We can have a better error message here because it is hard to find out what exactly went wrong.
The [precice configuration file](https://github.com/precice/elastictube1d/pull/22/commits/d912f37454256af86fc94500aa77eeb19e9dea44#diff-712326e3d0b77e0f875874a88a388dc6) is used.   

The complete log file of this error is: 
[Structure.log](https://github.com/precice/precice/files/4076214/Structure.log)

**Comment by BenjaminRueth** [comment]
Might be a similar problem as #223

**Comment by IshaanDesai** [comment]
This assertion failure was avoided by correcting a mistake in the code where the API function `read_block_scalar_data` returns values back into the correct variable. The correction commit is: https://github.com/precice/elastictube1d/pull/22/commits/ab9e2e39eed950796a54abde5477f10064ae8c3c 
In the earlier commit which hit the assertion the correct arrays were not updated and hence totally nonsense values were passed to the QN iteration.

**Comment by BenjaminRueth** [comment]
Then two questions arise:

1. Can we avoid this wrong usage of the bindings and help the user in some way? As far as I understand you did not correctly follow the signature and ignored the return value. In C++ there is [nodiscard](https://en.cppreference.com/w/cpp/language/attributes/nodiscard), which exactly implements what we want (if the user ignores the return value, the compiler issues a warning). Can we also implement this for the python bindings? Thanks to @fsimonis for the hint.
2. Can we close this issue?

**Comment by uekerman** [comment]
>     2\. Can we close this issue?

No, we need to throw a good error message in preCICE. Please don't remove the elastic tube branch, such that I can reproduce the (erroneous) behavior and figure out where exactly we should catch this.

**Comment by BenjaminRueth** [comment]
> Please don't remove the elastic tube branch

I created a new branch (https://github.com/precice/elastictube1d/tree/related_to_precice_issue_616). This means we can remove the elastictube branch, as soon as https://github.com/precice/elastictube1d/pull/22 is merged and we do not loose the relevant commit https://github.com/precice/elastictube1d/commit/ab9e2e39eed950796a54abde5477f10064ae8c3c.

**Comment by uekerman** [comment]
With #787 we now get: 

```
(0) 19:11:51 [acceleration::BaseQNAcceleration]:188 in updateDifferenceMatrices: ERROR: The coupling residual equals zero. There is probably something wrong in your adapter. Maybe you always write the same data or you call advance without providing new data first or you do not use available read data.
```

@IshaanDesai That should have prevented the problem, right?

**Comment by IshaanDesai** [comment]
@uekerman yes! That error message would help in pointing to the correct location of the problem which was the `read` functionality coupling (in the case of the elastictube1d it was wrong usage of `read_block_scalar_data`)
