### ISSUE TITLE
Preventing Changelog conflicts

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#621]
As a core developer, I often add to the Changelog. This however results in frequent trivial merge conflicts, which prevents merge via rebase from the web interface. This is really annoying.

I once read about a method to prevent this:

1. Every PR adds its changelog to `docs/changelog/123.md` with `123` being the PR number.
    This file  contains only list entries `*  Like this one` (easy to check)
2. On release, a script merges the content of all changelog files and prepends them to the main `Changelog.md`.

This is a trivial operation and could be added to the release script I prepared in https://github.com/precice/precice/pull/577/files#diff-50217223f5ebf99159d0bc59220f19dd.

Shall we use the same method in preCICE?

**Comment by uekerman** [comment]
Yes, I find that annoying, too. Sounds like a doable solution. But let's do this after v2.0, OK?

**Comment by MakisH** [comment]
Sounds like a good idea!

Additional points:
- Add a Git hook so that we cannot commit changes to the `CHANGELOG.md`
- Have a bot (see #391) to check if the PR contains this file.
