### ISSUE TITLE
AUR package is missing Eigen

### ISSUE THREAD

**Issue by MakisH** [precice/precice#626]
Our [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=precice) does not specify Eigen as a dependency:
```
depends=('openmpi' 'boost')
```
The fix is easy:
```
depends=('openmpi' 'boost' 'eigen')
```

**Comment by fsimonis** [comment]
We need eigen only at build-time, so the fix would be:
`makedepends=('cmake' 'eigen')`
