### ISSUE TITLE
Deliver solver dummies as examples

### ISSUE THREAD

**Issue by MakisH** [precice/precice#627]
Alongside preCICE, it would be nice that we also install our solver dummies code (and the corresponding preCICE configuration file) as examples.

This would avoid the cases where one has to separately obtain th preCICE sources to:
- build the C++/C/Fortran solver dummy
- run a separately-provided solver dummy without duplicating the `precice-config.xml`

**Comment by BenjaminRueth** [comment]
Related to https://github.com/precice/python-bindings/issues/24
