### ISSUE TITLE
AUR package is missing PETSc

### ISSUE THREAD

**Issue by MakisH** [precice/precice#628]
Our [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=precice) does not specify PETSc as a dependency:

```
depends=('openmpi' 'boost')
```

It also builds with `PETSc=off`:
```
cmake . \
	  -DCMAKE_BUILD_TYPE=Release \
	  -DCMAKE_INSTALL_PREFIX=/usr \
          -DBUILD_SHARED_LIBS=ON \
          -DPETSC=off \
          -DPYTHON=off
```
this means that somebody that installs preCICE from AUR would not be able to immediately run an RBF-mapping tutorial.

I am not sure if this was skipped because of compatibility issues with PETSc, but would also give us useful insights in our CI.

Related to #626.

**Comment by MakisH** [comment]
I vote to close this issue, with the following arguments:
- We can now (v2.1) do RBF in parallel with Eigen, which should be enough for small/medium cases.
- Probably no cluster runs Arch, so large cases are not relevant.
- We reduce (i.e. don't add) dependencies, making the package more stable in a rolling release environment.
- It is not related to this repository in any case. The respective recipe should only be seen as a template.

In our system tests, however, we should check with PETSc enabled.

Any opinion?

**Comment by fsimonis** [comment]
I would vouch to enable all dependencies in the package.
There is an AUR package for petsc too.
This way we stay consistent with the ubuntu packages.
