### ISSUE TITLE
Python Adapter fails with dynamic module does not define module export function

### ISSUE THREAD

**Issue by floli** [precice/precice#63]
All steps according to https://github.com/precice/precice/tree/develop/src/precice/adapters/python.

Step 5 fails:
```
>>> import PySolverInterface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_PySolverInterface)
```

**Comment by uekerman** [comment]
Unfortunately, I cannot reproduce this problem. It works for me. With ```elastictube1d/PythonDummy/StructureSolver.py```, but also in the "shell-mode" of python. 

I use preCICE as a shared library, cython 0.23.4, python 2.7.6

There are tons of post for such problems, maybe [this](http://stackoverflow.com/questions/8024805/cython-compiled-c-extension-importerror-dynamic-module-does-not-define-init-fu) helps?
I also found some indication that it might be a python 2 vs 3 problem and that you have to be sure to use the same python for ```python setup.py build_ext --inplace``` and for calling your code later.
Any idea?

**Comment by floli** [comment]
Seems to work now. Maybe it was a python2 / 3 problem. On my system python3 is already the default, we should also convert the adapter to python3.
