### ISSUE TITLE
Incorrect path for boost_1_65_1 on CoolLMUC page

### ISSUE THREAD

**Issue by Amin-CFD** [precice/precice#640]
See section "Boost and yaml-cpp"
Suggestions: 
"path/to/boost_install/lib" should be change to "path/to/boost_install/libs"
"path/to/boost_install/include" should be change to "path/to/boost_install/boost"

This issue can be solved by creating a separate installation folder at the same level as the folder 
boost_1_65_1, if the user does not have access to /usr.  
Set this created new folder in --prefix=/path/to/installation/target.
Then the suggested steps on section "Boost and yaml-cpp" should work.

The problem is the given command still compile even if "path/to/boost_install" is provided.
Perhaps change to an invalid path to prevent any confusion.

**Comment by MakisH** [comment]
Thank you, @Amin-CFD! Feel free to edit the wiki page directly (I hope you have permissions).

**Comment by MakisH** [comment]
Just to clarify:

The paths
```
path/to/boost_install/libs
path/to/boost_install/boost
```
refer to the **source** of Boost.

The paths
```
path/to/boost_install/lib
path/to/boost_install/include
```
refer to the **installation** directory of Boost. Indeed, one can skip the installation part, or install to a different path than the default (which is usually not user-writtable).

I added a hint in the [CooLMUC2 page](https://github.com/precice/precice/wiki/CooLMUC).
