### ISSUE TITLE
Coupling for python code

### ISSUE THREAD

**Issue by yuxianglin** [precice/precice#66]
Hi,

I am new to preCICE, and wondering if I could couple two python code, i.e proteus for fluid part, and fenics for solid part using preCICE.

Any advise would be appreciated.

Yuxiang

**Comment by uekerman** [comment]
Hi Yuxiang,

welcome to preCICE!
This should in principle be possible. The preCICE API also exists in Python and we have, for example, coupled Code_Aster in Python. 
However, there are no adapter yet for Proteus and FEniCS. Thus, you would have to write those yourself, which requires some knowledge about the Code, but which is not an extremely difficult task. To get a feeling how this could work, have a look at our adapter example (C++)
https://github.com/precice/precice/wiki/Adapter-Example

Btw, such messages are better asked via the mailing list 
https://mailman.informatik.uni-stuttgart.de/mailman/listinfo/precice

Issues are meant to report on bugs or new features etc.

Best,
Benjamin

**Comment by yuxianglin** [comment]
Great, thanks for your advise Benjamin.

Best,
Yuxiang
