### ISSUE TITLE
Introduce a Tweakable Assertion Policy

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#663]
# Problem description

Currently, assertions are disabled in non-debug builds.

Using assertions in release builds is a trade-off between:
* higher security and trust in the results at the cost of additional work
* less work and checks at the cost of security.

What a user/developer prefers depends on the use-case and we should not enforce a choice.

# Potential Solution

Provide the additional CMake Variable `PRECICE_ASSERTION_POLICY`:

 Choice | Comment
--- | --- 
`ON` | Always enable assertions
`DEBUG` | Enable assertions on debug builds only **default**
`OFF` |  Never enable assertions

**Comment by uekerman** [comment]
Mmh, I thought we have `CMAKE_BUILD_TYPE` exactly for this. Doesn't that variable then become useless? Isn't that a bit over-engineered?

**Comment by MakisH** [comment]
Isn't it standard and expected that Release builds (of any software) do not have assertions? Don't they increase the computations? Is there any example out there that does the same?

**Comment by fsimonis** [comment]
Enabling assertions can make release builds easier to debug.
Furthermore, the presence of assertions has side-effects that can influence the optimizer. Thus testing release+assertions vs release-assertions can produce different results. A tweakable assertion policy can expose such problems.

> Don't they increase the computations?

Yes. The choice is weather or not it is reasonable to invest computations into additional security.

> Isn't it standard and expected that Release builds (of any software) do not have assertions?

Yes, but for safety-critical applications like satellites, mars rovers, etc..
Disabling assertions requires confidence that your software is bug-free.
Enabling assertions allows to ensure that one does not waste resources once the program hits an unexpected internal state.
