### ISSUE TITLE
Why do we run our unit tests against the latest release, if our baseline is PETSc 3.12?

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#665]
See:

https://github.com/precice/precice/blob/4f03e9464280670f3445e13eec587dd444af90e5/tools/ci/travis-install-dependencies.sh#L51

Problem with this approach: We only see it very late, if the our baseline verison of PETSc does not support the latests revision of preCICE anymore.

**Comment by MakisH** [comment]
Now our baseline is PETSc 3.12, changed the title.

**Comment by fsimonis** [comment]
The ci images used in the WIP github actions install petsc 3.12.4 from source on ubuntu 18.04 and centos7.
Ubuntu 2004 uses the system packages (3.12.4).

So this issue will be resolved once we merge the github actions.

**Comment by fsimonis** [comment]
Solved by #843. See #713 for full rational.
