### ISSUE TITLE
Test baseline and latest version of dependencies

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#667]
Our tests for this repository do not test the baseline version of our dependencies (example: #665). This is bad, because we only observe at a very late stage (`precice/systemtests`), if a commit has introduced a compatibility problem. I would suggest to test following things:

* test latest version of dependencies on all operating systems that we recommend to users: *important to be aware of possible future problems*
* test baseline version of dependencies on all operating systems that we recommend to users: *important to be aware of compatibility problems with baseline version*
* test whatever we need in order to create the debian package: *important, if we want to be able to release a debian package*

Note that to some degree the above-mentioned tests overlap with what we are already testing in the systemtests. However, in order to make sure that we are aware of a regression as soon as possible, we should consider moving these tests into `precice/precice`.

**Outlook:** We might also consider creating the docker images that are needed by the systemtests in the CI of `precice/precice` (compare to [the stages used by pyMOR](https://zivgitlab.uni-muenster.de/pymor/pymor/pipelines/45660)). Then we have to push the images to dockerhub where the systemtests can access them. This would allow us to entirely get rid of the `building precice` stage in the systemtests. Note that a consistent labelling procedure is a must in this case (see ).

**Comment by MakisH** [comment]
Yes, we should be doing that. This is, in principle, why we are testing Ubuntu 16.04 (minimum), 18.04 (baseline), and Arch (latest). But we probably need to check if we are actually doing this as we want.

**Comment by uekerman** [comment]
The point of this issue is that we should these tests as part of the preCICE tests, not the system tests. The system tests should be for checking the adapters and tutorials, not the dependencies of preCICE. So, we just need to move those tests (Ubuntu 16.04 (minimum), 18.04 (baseline), and Arch (latest)) to the CI of `precice/precice`.

**Comment by fsimonis** [comment]
Solved by #843. More information here: #713
