### ISSUE TITLE
Ubuntu 19.10 Eoan package error in finalize

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#671]
# Problem Description

The ubuntu 19.10 package seems to call `MPI_Barrier` after `MPI_Finalize`.
The usual suspect is the Event Timings package. 

We need to investigate this further.

**Comment by MakisH** [comment]
@fsimonis at what stage did you observe this behavior? Any information on how to reproduce it?

**Comment by fsimonis** [comment]
It was observable with the 2.0.0 package for eoan.
Running the example codes during the workshop displayed an MPI message after `preCICE: finalize` was logged.

**Comment by uekerman** [comment]
@fsimonis Isn't this problem fixed in the meanwhile? (in develop, not in the 19.10 package).

**Comment by fsimonis** [comment]
This could have been a symptom of the lifetime problems we fixed in #768 and #772.
We should run the example code from the workshop on Ubuntu 20.04 to check this.

**Comment by MakisH** [comment]
I just tried the example code from the workshop (complete solution) on Ubuntu 19.10 with preCICE v2.0.1, but I cannot reproduce this. There is no error/warning/anything weird at the end.

Any other hint to reproduce it?

**Comment by fsimonis** [comment]
Good. Let's consider this issue fixed.
