### ISSUE TITLE
Nearest Neighbour and Projection Mappings crash for empty Partitions

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#679]
# Problem Description

Running a simulation with a partition including ranks that do not share a coupled mesh will result in a crash on some machines.
This happens due to the unconditional printing of the statistics output here:
https://github.com/precice/precice/blob/56832a9fe7ac2a06c756b78a3c2cf0e0a96c3dac/src/utils/Statistics.hpp#L66-L74

# Workaround

Repartition the problem so that every rank shares some vertices on of the mesh.

# Proposed Solution

Fix `precice::utils::statistics::DistanceAccumulator::mean`

_edit 1: Added source of error_

**Comment by uekerman** [comment]
Can you specify more precisely when a crash occurs? Our tests include many cases with empty ranks and NN or NP mapping and do not crash (many integration tests, some application tests, e.g. Alya Flap). 
To understand this better is a prerequisite to decide whether we need an urgent bugfix release or not.
And where we need additional integration tests to catch such problems in the future.
The workaround above does not seem feasible I am afraid of.

**Comment by fsimonis** [comment]
This happens on _some_ systems and is probably compiler dependant too.
So it is probably worth a bug fix especially as we could thnen fix #673 and #678 too.

**Comment by fsimonis** [comment]
Resolved by #681
