### ISSUE TITLE
Port python bindings to python3

### ISSUE THREAD

**Issue by floli** [precice/precice#68]
Should be rather easy. However, python2 and 3 adaptors should coexist. With some ```from __future__``` calls they may even share the same code.
```
% python3 setup.py build_ext --inplace 
  File "setup.py", line 11
    print "ERROR: PRECICE_ROOT not defined!"
                                           ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by floli** [comment]
Needs to be reopened, since we have string decode issues, e.g. with the python solver dummy:
```
Traceback (most recent call last):
  File "solverdummy.py", line 41, in <module>
    interface = PySolverInterface(participantName, solverProcessIndex, solverProcessSize)
  File "PySolverInterface.pyx", line 95, in PySolverInterface.PySolverInterface.__cinit__
    def __cinit__ (self, string solverName, int solverProcessIndex, int solverProcessSize):
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, str found
```

**Comment by BenjaminRueth** [comment]
I got the same error using python 3.5.2.

**Comment by BenjaminRueth** [comment]
Here a few lines of code for reproducing the error from command line:
```
import PySolverInterface  # if PySolverInterface is in PYTHONPATH
PySolverInterface.PySolverInterface("dummy", 1, 0)
```

**Comment by BenjaminRueth** [comment]
With the new commit the decoding issues are gone. However, we now use implicit duck typing instead of explicit typing for strings. To my knowledge there is not a baseclass of byte and string that we could use instead (in python 3)?

**Comment by BenjaminRueth** [comment]
Just tested running `precice/tools/solverdummies/python` with 5b88d7fe7498d72171bce4c7a7c463e0a76764d7. Works with `python3` as well. As soon as #146 is merged into `develop`, we can close this issue, too.

**Comment by BenjaminRueth** [comment]
#146 closed. We can also close this one.
