### ISSUE TITLE
Unclear error message on writable data

### ISSUE THREAD

**Issue by maierbn** [precice/precice#680]
I errornously tried to call `writeBlockVectorData` on a data id that was defined as `read-data` for the participant. The error message is 

`ERROR: Data is not marked as write! 3`

It would be more helpful if it also stated the data id and/or name of the data field.

**Comment by maierbn** [comment]
The displayed `3` was the data ID in my case.

**Comment by fsimonis** [comment]
@maierbn Thank you for opening the issue!

This is definitely a very bad error message. I am working on rewording all messages regarding input validation.
Expect an update soon!
