### ISSUE TITLE
preCICE depends on python3-numpy (not python-numpy)

### ISSUE THREAD

**Issue by RPGP1** [precice/precice#693]
I exec `docker build -t image_name .` with the following Dockerfile, and the 2nd test "precice.action" of `make test_base` failed.
Replacing `python-numpy` with `python3-numpy` did well.

Please change [Wiki page "Dependencies#Ubuntu 18.04 or newer"](https://github.com/precice/precice/wiki/Dependencies#ubuntu-1804-or-newer), which told me to use `python-numpy`.

```dockerfile
FROM ubuntu:18.04

RUN apt update \
    && apt install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    cmake \
    git \
    libboost-filesystem-dev \
    libboost-log-dev \
    libboost-program-options-dev \
    libboost-regex-dev \
    libboost-system-dev \
    libboost-test-dev \
    libboost-thread-dev \
    libeigen3-dev \
    libxml2-dev \
    petsc-dev \
    python-numpy \
    python3-dev \
    ssh \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

ARG CACHEBUST

ARG branch=develop
ARG build_type=RelWithDebInfo
ARG always_validate_libs=ON
ARG ctest_mpi_flags=""

RUN set -x \
    && : "installing preCICE" \
    && git clone --branch ${branch} --depth 1 https://github.com/precice/precice.git /tmp/precice \
    && mkdir /tmp/precice/build \
    && cd /tmp/precice/build \
    && cmake /tmp/precice \
    -DCMAKE_BUILD_TYPE=${build_type} \
    -DPRECICE_ALWAYS_VALIDATE_LIBS=${always_validate_libs} \
    -DPRECICE_CTEST_MPI_FLAGS=${ctest_mpi_flags} \
    -DBUILD_SHARED_LIBS=ON \
    && make install -j$(($(nproc) + 1)) \
    && chmod -R o+w /tmp/precice  \
    && useradd tester \
    && su -c "make test_base" tester \
    && userdel tester \
    && cd / \
    && rm -rf /tmp/precice

CMD ["/bin/bash"]
```

**Comment by BenjaminRueth** [comment]
Thanks for making us aware of the inconsistency in the documentation. I fixed it.

*Note:* python is an optional dependency for preCICE that you only need if you want to use the python actions. You can turn off the python actions using the [cmake option `PRECICE_PythonActions`](https://github.com/precice/precice/wiki/Building:-Using-CMake#options). As far as I know, the python actions work with python2 as well as with python3; python3 is recommended. A mixture, of course, does not work (like `python3-dev python-numpy`).

**Comment by BenjaminRueth** [comment]
[Here](https://github.com/precice/precice/wiki/Dependencies#python-optional) is some more documentation on the python actions.

**Comment by fsimonis** [comment]
The PR #708 should now further catch this issue during the configuration.
