### ISSUE TITLE
File export for Paraview Glance

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#694]
**Please describe the problem you are trying to solve?**
I would like to export and visualize the interface meshes of a participant using [paraview glance](https://kitware.github.io/paraview-glance/).
This is currently not possible as the legacy vtk files are not supported.

**Describe the solution you propose.**
Add an additional export format which can be imported into glance.

**Describe alternatives you've considered**
Conversion using an external tool, which is inconvenient.

**Comment by uekerman** [comment]
Would it help to move to a newer vtk version instead? So, no additional export, but to replace the current one?

**Comment by fsimonis** [comment]
It looks like we would have to implement the VTK Polydata `.vtp` format.

The [supported formats are fairly limited](https://kitware.github.io/paraview-glance/doc/readers.html).
