### ISSUE TITLE
Summation action

### ISSUE THREAD

**Issue by uekerman** [precice/precice#699]
**Please describe the problem you are trying to solve**

In certain three-field coupled problems, (conservative) data values need to be summed up. A typical examples are forces. Solver A receives forces from solvers B and C on the same geometry (let's say electromagnetic forces and mechanical forces). Currently, this can be solved by having two force data values in solver A and summing them up in the adapter of solver A. The drawback of this approach that we need to modify the adapter of A. Having an action would circumvent this modification. The situation is also motivated in [Alban Rousset's talk at the preCICE Workshop 2020](https://www.youtube.com/watch?v=3FP8y1Zjqns).

**Describe the solution you propose.**

Implement an action that sums up n source data values and writes them to a target data value on the same mesh.

```xml
<participant name="SolverA"> 
    <use-mesh name="MeshA" provide="yes"/> 
    <read-data name="ForcesA" mesh="MeshA"/> 
    ...
    <action:sum mesh="MeshA" timing="on-exchange-post">
        <source-data name="ForcesB"/>
        <source-data name="ForcesC"/>
        <target-data name="ForcesA"/>
    </action:sum>
    ...
</participant>
```

Currently, an action can only have one `source-data`. We need to relax this general restriction in the configuration and enforce it instead via `PRECICE_CHECK` for all other actions.

**Comment by oguzziya** [comment]
I am not sure which one is more convenient to implement for the multiple source data in configuration:

- Changing `sourceDataID` to vector, modifying every action accordingly in their implementation
- Changing `sourceDataID` to vector, modifying only `createAction()` method in configuration (seems more maintainable for me )
- Or something other than using vector (not so sure)

**Comment by uekerman** [comment]
`std::vector` is the right data structure. I would recommend the second option. Ideally, you should not need to edit the other actions at all.

In the configuration, you can create a specific tag
https://github.com/precice/precice/blob/3eb896b45ca90cdbe98c5ec2292a26b3bb04e8cf/src/action/config/ActionConfiguration.cpp#L39
for the new action and change `OCCUR_ONCE` to `OCCUR_ONCE_OR_MORE`.
