### ISSUE TITLE
Sort out (outdated) action timings

### ISSUE THREAD

**Issue by uekerman** [precice/precice#711]
Actions can currently be executed at 5 different occasions (see [wiki](https://github.com/precice/precice/wiki/Actions-Configuration#basics-and-pre-implemented-actions)):

* `regular-prior`: 
* `regular-post`: 
* `on-exchange-prior`: 
* `on-exchange-post`: 
* `on-time-window-complete-post`: 

Their meaning is roughly:
* `prior` and `post` means before or after communication.
* The difference between `regular` and `on-exchange` is whether data is exchanged or not. So, meaning whether the end of the time window is already reached or not. 
* I currently don't understand why `on-time-window-complete-post` is needed.

A further problem is that we don't distinguish whether the action is executed before or after a potential corresponding mapping. Actually, there is even a crucial difference here (looks like a bug):

In **initialize**:
https://github.com/precice/precice/blob/04bef9d14afdc94229f6788b2e29be5d465f9abd/src/precice/impl/SolverInterfaceImpl.cpp#L257-L264

In **advance**:
https://github.com/precice/precice/blob/04bef9d14afdc94229f6788b2e29be5d465f9abd/src/precice/impl/SolverInterfaceImpl.cpp#L368-L379

Purpose of this issue is to properly discuss and define which timings we actually need and to then implement them. Depending on the outcome of the discussion, we need to be careful about backwards compatibility, though I believe that actions are not used a lot currently.

**Comment by uekerman** [comment]
The bug described above is also reflected in the integration test `testExplicitWithDataScaling`, which was disabled for a long time. Re-enabling it, I had to duplicate the action as the result is checked after initialize and after advance.

https://github.com/precice/precice/blob/9127da26faca2f89803fc45fe15b551112056d0d/src/precice/tests/explicit-datascaling.xml#L29-L42

**Comment by KyleDavisSA** [comment]
The wiki says that `regular`timings can be used for subcycling cases as well, but `on-exchange` is only when there is data to be exchanged (so every iteration where data is exchanged). Are there subcycling cases where the action timings need to be run without exchanging data? I would think there is more of a case for having `on-exchange` and `on-time-window-complete-post` as maybe data only needs to be exchanged at the end of a time window, but not at every iteration? 

But I have not used the action timings before, and I honestly don't know why I would need to pick `regular` over `on-exchange`. I think how to use them is definitely unclear.

> The difference between regular and on-exchange is whether data is exchanged or not. So, meaning whether the end of the time window is already reached or not.

Isn't this wrong? `on-exchange` will exchange data every iteration and not just at the end of the time window?

**Comment by uekerman** [comment]
I understood `on-time-window-complete-post` the wrong way. 
As I see it now, **we currently have:**

* `regular-prior`: always before the cplscheme is advanced (even in subcycling timesteps) 
* `regular-post`: always after the cplscheme is advanced (even in subcycling timesteps)
* `on-exchange-prior`: before the cplscheme is advanced, at the end of a time window, but in every iteration
* `on-exchange-post`: after the cplscheme is advanced, at the end of a time window, but in every iteration
* `on-time-window-complete-post`: after the cplscheme is advanced, at the end of a time window and only after convergence

I guess there could be case where regular is chosen over on-exchange. If a Python action writes sth to a file and you want all the information, for example. Not extremely realistic, though.

But what we need to distinguish clearly is whether the action happens before or after the mapping. That's the main problem with the current options. It is currently undefined. 

**First new attempt:**
* `write-mapping-prior`: directly before each `mapWriteData`
* `write-mapping-post`: directly after each `mapWriteData`
* `on-exchange-prior`: only when data is exchanged, directly before cplscheme is advanced (so after write mapping)
* `on-exchange-post`: only when data is exchanged, directly after cplscheme is advanced (so before read mapping)
* `read-mapping-prior`: directly before each `mapReadData`
* `read-mapping-post`: directly after each `mapReadData`
* `on-time-window-complete-post`: at the end of a time window, only if converged, after read mapping

So, `regular-prior/post` are replaced by the mapping variants.

**Comment by KyleDavisSA** [comment]
So how would this work now? 

```
double SolverInterfaceImpl::advance(

....

  std::set<action::Action::Timing> timings;

  timings.insert(action::Action::WRITE_MAPPING_PRIOR);             // Before mapWriteData
 
  mapWrittenData();

  timings.insert(action::Action::WRITE_MAPPING_POST);              // After mapWriteData
  if (_couplingScheme->willDataBeExchanged(0.0)) {
    timings.insert(action::Action::ON_EXCHANGE_PRIOR);            //before advanced
  }

  performDataActions(timings, time, computedTimestepLength, timeWindowComputedPart, timeWindowSize);

  PRECICE_DEBUG("Advance coupling scheme");
  _couplingScheme->advance();

  timings.clear();
  timings.insert(action::Action::READ_MAPPING_PRIOR);
  if (_couplingScheme->hasDataBeenExchanged()) {
    timings.insert(action::Action::ON_EXCHANGE_POST);
  }
  if (_couplingScheme->isTimeWindowComplete()) {
    timings.insert(action::Action::ON_TIME_WINDOW_COMPLETE_POST);
  }
  performDataActions(timings, time, computedTimestepLength, timeWindowComputedPart, timeWindowSize);

  if (_couplingScheme->hasDataBeenExchanged()) {
    mapReadData(); 
  }

  timings.insert(action::Action::READ_MAPPING_POST);

```
Shouldn't the mapReadData be outside the if statement like the mapWriteData?

**Comment by uekerman** [comment]
> I like the proposed scheme, `regular` was not very self-explaining before. Could we somehow keep the old options to work until preCICE v3? Would `reguar-prior` be mapped to `write-mapping-prior` and `regular-post` to `read-mapping-post`?

The problem with keeping the old ones was that they were not well-defined concerning the mapping. We had a different behavior in `intialize` and `advance`. So, when keeping them, we need to also fix that. So, the meaning of them will change anyway. I would not want to keep the undefined behavior. One option would indeed be the one that you describe.

**Comment by uekerman** [comment]
> Shouldn't the mapReadData be outside the if statement like the mapWriteData?

That raises a good point. Alternative to that would be to also move `mapWrittenData` into `willDataBeExchanged` and then deprecate  `on-exchange-prior/post` as well.

**Comment by KyleDavisSA** [comment]
The `exchange-prior/post` would still be there as it is in reference to the advance coupling scheme. We could also keep the name `regular-prior/post`, but it would simply use `write-mapping-prior/post` and `read-mapping-prior/post` with:
```
if (_configuredAction.timing == VALUE_REGULAR_PRIOR) {
    timing = action::Action::WRITE_MAPPING_PRIOR;
} else if (_configuredAction.timing == VALUE_REGULAR_POST) {
    timing = action::Action::READ_MAPPING_PRIOR;
```

**Comment by KyleDavisSA** [comment]
In `Initialize`, the `PerformDataActions` comes after `mapReadData`, but it's the opposite in `advance`. Is this correct or is one of them wrong? And which way should it be?

**Comment by uekerman** [comment]
see [above](https://github.com/precice/precice/issues/711#issue-593430558) :smile:

**Comment by fsimonis** [comment]
Maybe add a warning along the lines of:  
`The action timing regular-prior is not clearly defined and deprecated. Use read/write mapping prior/post instead.`
