### ISSUE TITLE
Install missing dependencies with CMake

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#716]
**Please describe the problem you are trying to solve?**
Installing dependencies such as PETSc or Boost solely for preCICE can be tedious on some systems.

**Describe the solution you propose.**
When CMake cannot find an enabled dependency, download, build and install the dependency using CMake [ExternalProject](https://cmake.org/cmake/help/v3.10/module/ExternalProject.html).

**Describe alternatives you've considered**
_Don't change anything_

**Additional context**
This is feedback from the Workshop 2020.

**Comment by MakisH** [comment]
We decided to not fix this or go into this direction. As preCICE is a library, we would introduce additional complexity by installing dependencies that will be propagated to the solvers. Additionally, it would complicate our CMake configuration a lot.

We understand the problem behind this issue, but we want to keep fighting it using package managers and not gradually turn preCICE into a package manager itself.
