### ISSUE TITLE
replace isActionRequired(action) with explicit calls

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#719]
The preCICE Interface offers a set of functions and actions to allow the user to query whether a checkpoint or initial data has to be written/read and report, if the actions have been completed. I would like to propose an alternative interface, which is in my opinion easier to use.

## Current state

The following functions belong to the current interface:

https://github.com/precice/precice/blob/8bd11debde201d3a0ce78327808570ddb24127ce/src/precice/SolverInterface.hpp#L302-L317

https://github.com/precice/precice/blob/8bd11debde201d3a0ce78327808570ddb24127ce/src/precice/SolverInterface.hpp#L319-L329

https://github.com/precice/precice/blob/8bd11debde201d3a0ce78327808570ddb24127ce/src/precice/SolverInterface.hpp#L834-L841

## Proposed interface

I would prefer a more explicit interface. For example:

* `bool writingInitialDataIsRequired()`
* `void initialDataHasBeenWritten()`
* `bool readingCheckpointIsRequired()`
* `void checkpointHasBeenRead()`
* `bool writingCheckpointIsRequired()`
* `void checkpointHasBeenWritten()`

### Testing

The main reason, why I would prefer this implementation is that it makes testing much more easier. Currently I always have to define a return value, if isActionRequired receives a certain action:

def is_action_required_behavior(py_action):
    if py_action == action_read_iteration_checkpoint():
        return False
    elif py_action == action_write_iteration_checkpoint():
        return True

Interface.is_action_required = MagicMock(side_effect=is_action_required_behavior)

Providing a different Interface allows me to write this differently:

Interface.reading_checkpoint_is_required = MagicMock(return_value=False)
Interface.writing_checkpoint_is_required = MagicMock(return_value=True)

### More reasons?

Do you have more ideas where the proposed interface might be helpful?

## Are there also drawbacks?

First of all, this is an API breaking change. But are there also additional (functional) drawbacks?

Looking forward to your replies and ideas!

## Additional context

(conversation with @uekerman) 

Bernhard's thesis, page 115:

*Finally, we consider some auxiliary API methods shown in Algorithm 3.8. The methods in lines 1–4 can be used by a solver to get additional information about the couplingstate, e.g., to find out whether coupling data should be written or read. The method `isActionRequired` is used as an extensible means to convey required actions to a solver. E.g., coupling iterations for implicit equation coupling require a solver to store and load iteration checkpoints, i.e., old timestep states, while iterating. A solver has to query for the actions write-iteration-checkpoint and read-iteration-checkpoint, and confirm their execution by using the method fulfilledAction. Other coupling tools often have a dedicated method ”iterate” to signal a solver to perform a coupling iteration. However, when subcycling is included and implemented in the coupling library, this is not sufficient. Further actions are provided for synchronized checkpoint writing and reading, as well as regular data output writing. The mechanism is easy to extend by further required solver actions and a solver needs to implement only those actions which correspond to used functionality. In order to avoid errors from not properly adapted solvers, fulfilledAction acts as a checking mechanism. In case a solver does not fulfill a required action, preCICE can detect the missing call of fulfilledAction and report an error. All required action names are gathered in the namespace precice::constants.*

Historic note: In the past, there were more solver actions that we got rid of (e.g. read/write-simulation-checkpoint, writing output). Additionally, the hope *The mechanism is easy to extend by further required solver actions* did not pay off as so far we never did this. For example, we are currently also not considering this interface for the mesh requirement #467. 

The reason for the unpopularity of the solver action interface could be that it feels too heavy. I have seen multiple times that our users do not understand it properly and hack around it. Maybe also sometimes, we don't understand it properly. In particular, the `fulfilledAction` did not pay off so far, in my opinion.

Thus, we could think about how to improve the situation. In my opinion, the reason, however, should not (only) be testing, but usability. Just transforming the interface to explicit calls does not solve the bigger problem. If we touch this, we should think about a proper solution (incorporating what we have learned the last 5 years by watching users doing it wrong). To be honest, I don't yet see a good solution, other then just dropping `fulfilledAction` and finding different names.

**Comment by fsimonis** [comment]
This is not _really_ a breaking change in terms of the interface as:
* `bool writingInitialDataIsRequired()` can be implemented in terms of `bool isActionRequired(action)`.
* `void markActionFulfilled(action)` can be implemented in terms of `void initialDataHasBeenWritten()`.

But this will make our interface internally ugly until preCICE 3.

**Comment by fsimonis** [comment]
@uekerman and I had a discussion about our action interface, also taking into account the proposition from #715. The potential solution also digs a bit deeper.

**Why do we need `markActionFulfilled`?**

Currently, we force the user to explicitly mark an action as fulfilled.
This allows us to perform checks about the state in `advance()`.

**Problem with the current interface**

Currently, adding an action requires to add 1 function to receive the action name in every flavour of our bindings. Thus adding actions is easy from the perspective of an implementer, but tedious for users as they need to fetch and handle this string somehow.
This is obvious even in our own adapter example:
```cpp
const std::string& cowic = precice::constants::actionWriteIterationCheckpoint(); 
/// ...
while (precice.isCouplingOngoing()){
	if(precice.isActionRequired(cowic)){ // <---- cowic ?
		saveOldState(); // save checkpoint
		precice.markActionFulfilled(cowic);  // <---- cowic ?!?
	}
``` 

**Problem with explicit calls**

Using explicit calls for checking and marking the action as fulfilled requires 2 new functions in every binding. This will be more work for implementers but will be a drastic improvement for users. The code for the implementers will be easier to work with though.
Biggest Pro is that C/Fortran users don't have to juggle with pointers to action names anymore.

Back to the adapter example:
```cpp
while (precice.isCouplingOngoing()){
	if(precice.writingCheckpointIsRequired()) // <--- check
		saveOldState(); // save checkpoint
                checkpointHasBeenWritten();  // <--- commit
	}
```

**Poposed Solution**

Require the user to fulfil an action once checked.

```cpp
while (precice.isCouplingOngoing()){
	if(precice.isWritingCheckpointRequired()) // <--- check it and do it!
		saveOldState(); // save checkpoint
	}
```

The direct result is that each action has exactly 1 explicit call of the shape `bool isACTIONRequired()`.
This
* is easier to use, implement and maintain, as there is only one call to worry about
* does not require to explicitly mark the action as fulfilled, thus preventing users to forget it
* simplifies the documentation as there is no need for cross-referencing
* results in a uniform representation of checks: `isWriteDataRequire()`, `isWriteCheckpointRequired`, `isCouplingOnGoing()`, ...
* allows users to naturally extend adapters by implementing actions.
  This is also consistent with other status checks such as `isReadDataAvailable()` and `isWriteDataRequired()`, which are simple checks that the user may use to prevent unnecessary work.
* allows us to raise error messages more easily if the user code does not fulfil the requirement.
  If the user never calls `isWriteCheckpointRequired()` then we know that he will fulfil this action and can thus not use the code in implicit coupling. The same holds for writing initial data.

**Comment by MakisH** [comment]
Great job!  :+1:

One question regarding the
```c++
if(precice.isWritingCheckpointRequired()) // <--- check it and do it!
```
Is there maybe any situation where we really want to wait until an action has been fulfilled before moving on? I assume this was the initial motivation for splitting the "is this required?" and "done" parts: a situation similar to asynchronous MPI communication, where one checks if buffers have been consumed before overwriting them.

**Comment by uekerman** [comment]
> Is there maybe any situation where we really want to wait until an action has been fulfilled before moving on? I assume this was the initial motivation for splitting the "is this required?" and "done" parts: a situation similar to asynchronous MPI communication, where one checks if buffers have been consumed before overwriting them.

Yes, could have been the original motivation. But I can't think of any use case where you would ask `isRequired` and then only later fulfill the action. Definitely you need to do this before calling `advance` again. Theoretically we lose some safeguarding with this, but in practice it should be 0%.

**Comment by BenjaminRodenberg** [comment]
> Great job! +1
> 
> One question regarding the
> 
> ```c++
> if(precice.isWritingCheckpointRequired()) // <--- check it and do it!
> ```
> 
> Is there maybe any situation where we really want to wait until an action has been fulfilled before moving on? I assume this was the initial motivation for splitting the "is this required?" and "done" parts: a situation similar to asynchronous MPI communication, where one checks if buffers have been consumed before overwriting them.

I was also a bit worried about this part, when seeing this in #1457. We can also make the safeguarding optional by having an optional argument: `isWritingCheckpoingRequired(doCheck=true)`, where `doCheck=false` will not do the checking and the user still has to do the checking manually. If we do it this way we have the possibility to allow users that need this additional safeguard from preCICE to explicitly ask for it. They will then have to explicitly do the check. Alternatively this could be an option in the configuration file.

For 99% of the users (maybe even 100%) I think they are happy if they don't have to worry (therefore default `doCheck=true`). This is something we can add in a non-breaking fashion at a later point in time, if we find out that it is needed. Let's go without the complicated additional argument for now and keep it simple. If we see that we need the explicit safeguard, we can still add it.

**Comment by fsimonis** [comment]
Checkpointing is purely in solver-land and out of the hands of preCICE. We can only tell the adapter to read or write it, but we have no way of verifying that the adapter actually performed this request.

If an adapter asks preCICE whether it needs to write a checkpoint, but ignores this request, then we cannot do anything about it. Reading or writing a checkpoint is not optional.

Adding an explicit confirmation from the adapter still doesn't allow preCICE to verify if the adapter actually did something useful.

IMHO forcing the adapter to check this requirement in case of implicit coupling is good enough.

Making this check optional makes things more complicated than necessary.

**Comment by fsimonis** [comment]
Final point to decide on the names of the three calls.
I put suggestions in the context of pseudo-python code for better reasoning. 

## InitializeData

We dropped `SolverInterface::initializeData()`, which means that `isInitializeDataRequired` is now a name, stripped of its meaning.
It would be a good idea to fix the name of the explicit call.

Here some suggestions focused on readability:
```py
SolverInterface participant
participant.setMeshVertices()

if participant.requiresInitalData():
  participant.writeData()

if participant.needsInitalData():
  participant.writeData()

if participant.initalizesData():
  participant.writeData()


participant.initialize()
```

## Checkpointing

We have two actions: `isReadIterationCheckpointRequired` and `isWriteIterationCheckpointRequired`.

Moving to explicit calls may be an opportunity to replace the word checkpoint by state or similar. In HPC, the term checkpoint is used for saving the simulation to allow continuation at a later point or to provide fall-backs in case of hardware errors. ( Which becomes increasingly important. )

```py
while (participant.isCouplingOngoing()):

  if participant.isWriteIterationCheckpointRequired():
    saveCheckpoint()

  if participant.isWritingCheckpointRequired():
    saveCheckpoint()

  if participant.requiresWritingCheckpoint():
    saveCheckpoint()

  if participant.requiresWritingState():
    saveCheckpoint()

  if participant.requiresStateSave():
    saveCheckpoint()
 
  if participant.savesSolverState():
    saveCheckpoint()

  if participant.savesCheckpoint():
    saveCheckpoint()

  participant.readData()
  participant.writeData()
  participant.advance()
  
  if participant.isReadIterationCheckpointRequired():
    readCheckpoint()

  if participant.isReadingCheckpointRequired():
    readCheckpoint()

  if participant.requiresReadingCheckpoint():
    readCheckpoint()

  if participant.requiresRestoringCheckpoint():
    readCheckpoint()

  if participant.restoresCheckpoint():
    readCheckpoint()

  if participant.needsReverting():
    readCheckpoint()

  if participant.restoresState():
    readCheckpoint()

  if participant.loadsCheckpoint():
    readCheckpoint()

  if participant.loadsSolverState():
    readCheckpoint()
  else:
    t += dt;
```

**Comment by fsimonis** [comment]
I like:
* initalizesData, requiresInitalData
* requiresWritingState
* requiresRestoringState

**Comment by MakisH** [comment]
I like using the `requires` (or `needs`) everywhere consistently. It is shorter than `is...Required` and it reads nicely with `participant.requires` (subject.verb).

Regarding checkpointing, I like the term "state", but I am a bit skeptical regarding the change. So far, I am not aware of any users confusing this with solver restart points. At the same time, we already have quite a lot of literature using the term "checkpointing". At the end of the day, aren't they really... checkpoints to restore to from a faulty state? They may not be written on the disk, but they serve a very similar purpose. And I know of one case where restart points are used for checkpointing.

**Comment by uekerman** [comment]
Good push :+1: 
I agree with what @MakisH says:
- `requiresInitialData`
- `requiresWritingCheckpoint`
- `requiresReadingCheckpoint`

**Comment by BenjaminRodenberg** [comment]
In the FEniCS adapter we actually use both words. Checkpoint and state. Not sure whether this is the best solution, but the idea was the following:

* checkpoint refers to the preCICE wording
* state describes the state of the solver or simulation (see [here](https://github.com/precice/fenics-adapter/blob/develop/fenicsprecice/fenicsprecice.py#L466) and [here](https://github.com/precice/fenics-adapter/blob/9aa3e22496117725ba993ac677a1239dc6f156f8/fenicsprecice/solverstate.py)).

I introduced the object `SolverState`, because it was easy to mess up things in FEniCS and therefore I wanted to put the necessary operations into an independent class.

However, from the outside perspective you do not really see `SolverState`: See https://github.com/precice/tutorials/blob/0482e5b4d3e1604dd031d2b113a2aaa63733c9a8/partitioned-heat-conduction/fenics/heat.py#L179

**Comment by fsimonis** [comment]
This naming scheme is inconsistent with `isMeshConnectivityRequired(Mesh)` and `isGradientDataRequired(data)`.

@uekerman @davidscn Should we rename them to `requiresMeshConnetivityFor(Mesh)` and `requiresGradientDataFor(Data)`?

**Comment by davidscn** [comment]
No strong opinion.

Pro changing it: keeping consistency with the other functions.
Contra changing: the connectivity and gradient getters are used in a different context and not required by the 'standard' cases. Having them in a slightly different scheme might highlight that a bit.

**Comment by uekerman** [comment]
I am slighlty pro changing.

**Comment by fsimonis** [comment]
This makes me realize that `isMeshConnectivityRequired` is a misleading name.
Connectivity is not required, but will be used by preCICE due to some configuration (projection mapping, watch interval)

`usesMeshConnectivityFor()` would be a better name.

Am I overthinking this? Otherwise, suggestions welcome.

```py
part.setMeshVertices("MeshA")

if part.usesMeshConnectivityFor("MeshA):
  parti.setMeshTriangles("MeshA")

if part.requiresInitialData():
  part.writeData()

part.initialize()
```

**Comment by MakisH** [comment]
The exact same argument holds for initializing data. I think `requires` is fine, because it will only be `true` if the configuration specifies it.

I guess your point is mainly "if it is not provided, preCICE will not complain, but silently use the closest available option". I would say that still it is required and the fallback is only a fallback we want to avoid.

Another problem I see, however, is that now that you used `part.` in your examples, the `requires` makes less sense. It is not this participant that requires initial data, but the other one. Maybe we should make it `requiresWritingInitialData`. Similarly, `requiresDefiningMeshConnectivity`.

**Comment by uekerman** [comment]
> The exact same argument holds for initializing data. I think requires is fine, because it will only be true if the configuration specifies it.

:+1:

> It is not this participant that requires initial data, but the other one. 

True, but you could argue that "this participant" requires initial data to send it to the other one. "writing" should be implicitly clear, it's the only way how to give data to preCICE.

**Comment by fsimonis** [comment]
Would `participant.providesInitialData()` be a better name then?

**Comment by MakisH** [comment]
> Would `participant.providesInitialData()` be a better name then?

Not sure... I can imagine a thought: "If it already provides initial data, why do I need to write data?"

Let's stick with https://github.com/precice/precice/issues/719#issuecomment-1326030278, or discuss in the next telco.
