### ISSUE TITLE
Refactoring of mesh re-partitioning to also include RBF filter

### ISSUE THREAD

**Issue by uekerman** [precice/precice#74]
Background: I implemented a hacky version of the RBF filter already for the measurement in my dissertation. Now we need a proper one. Therefore, however, a refactoring of the re-partitioning is necessary. Later, the parallel initialization will again interfere with the re-partitioning.

Design decisions: 
- Decomposition must be independent of the mappings. No access to the mappings should be possible.
- Instead, filtering can be based on two things: A bounding box (BB) or information directly at the vertex.
- The latter information will be generated by the mappings.  

The big steps will be implements in `SolverInterfaceImpl`:
 - `prepareGeo` and `createGeo` have to be sorted out. 
 - `decompose` will be a function of `SolverInterfaceImpl` handling the re-partitioning logic.

The main steps of the re-partitioning will be:
1. In `geometry`: Pre-BB-Filter (either at the master in a pre-filter sense or at each slave after a broadcast)
2. In `mapping`: Tagging of vertices (which ones could be owned by this rank). NN/NP: TODO, RBF: Step I
3. In `mesh`: Set `owner`. Must be independent of mapping.
4. In `mapping`: Mark vertices for filtering. NN/NP: TODO, RBF: Step III
5. In `geometry`: Filter mesh according to mark
6. Compute distribution (except `owner`)

**Comment by uekerman** [comment]
I might give a bigger refactoring a chance: to get rid of geometries (they are mainly built around features we no longer use as they only work in serial) and replace them with partitions. 
A `Partition` comes in two flavors: `ProvidedPartition` and `ReceivedPartition`. All relevant information currently stored directly at the mesh should go there. `partition` need access to `m2n`, `mapping` and `mesh`. It will be part of `MeshContext`. 

This could be a decent starting point for the parallel initialization. `geometry` will remain as a package for the moment, but deprecated.

**Comment by uekerman** [comment]
In principle, this is done and validated. However, currently it is still commented as we rely on PETSc bugfix. We should try if the Ubuntu 18.04 PETSc (3.7.7) does the job. @floli thinks we need at least 3.8

**Comment by floli** [comment]
We could check the version on build time and using conditional compiling to include or not that feature.

**Comment by floli** [comment]
PETSc 3.8 was released Sep 26, 2017, according to https://bitbucket.org/petsc/petsc/pull-requests/764/fix-bug-in-sequential-dense-multiply-and/ the patch was merged 2017-11-04. Therefore we even need PETSc 3.9 (which was released Apr 7, 2018).

Release history of PETSc: https://www.mcs.anl.gov/petsc/documentation/changes/index.html

**Comment by uekerman** [comment]
this is unfortunate :/ 
should we introduce a preprocessor flag for the PETSc version then?

**Comment by floli** [comment]
How would you suggest doing it?
* `#if PETSC_MAJOR >= 3 and PETSC_MINOR >= 9`
* `#ifndef PETSC_EMPTY_RANKS_BUG`
* `#ifdef PETSC_NO_EMPTY_RANKS_BUG`
* `#ifdef PETSC_3.9`

I tend to favor the last variant. It needs just one `#define` and has same level of generality.

For SCons there is some programming involved to get the version string. For CMake its provided by the module, it should be quite easy.

**Comment by uekerman** [comment]
Well, the disadvantage of the last one is that at some point, there will be a PETSc 3.10. I agree that the second and the third option are not explicit enough. 
What about `#if (PETSC_MAJOR >= 3 and PETSC_MINOR >= 9=) or PETSC_MAJOR >= 4`
