### ISSUE TITLE
Implement ScaleByArea for 3D Meshes

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#752]
**Please describe the problem you are trying to solve.**
The ScaleByArea action is implemented only for the 2D case. It would be nice to have a working and tested implementation to handle the 3D case as well.

**Describe the solution you propose.**
Implement handling of the 3D case in following function:

https://github.com/precice/precice/blob/47747abf9babb977a6b45edbe16ac69ec8d6948b/src/action/ScaleByAreaAction.cpp#L20-L24

**Describe alternatives you've considered**
_do nothing_

**Additional context**
The PR https://github.com/precice/precice/pull/727 already ran into issues when enforcing 2D-only on a configuration-basis.

**Comment by uekerman** [comment]
@mhmdkanj great! We are very happy for any contribution.

Edges are built from vertices. Triangles are built from edges. Edge exist in 2D and 3D. Triangles only exist in 3D.
For this issue, you will only need to consider triangles. They define the "(surface) area" in 3D.

For your second question, I guess you can use or borrow some ideas from:

https://github.com/precice/precice/blob/63b22a271785ed769a123c94270a2bdb33bc5868/src/mesh/Utils.cpp#L10-L37
