### ISSUE TITLE
Option to force program termination on divergence/lack of convergence

### ISSUE THREAD

**Issue by ajaust** [precice/precice#761]
**Please describe the problem you are trying to solve.**
I want to run a parameter study of different couplings and settings for one of my problems. It is very likely that not all settings work out, i.e. that the coupling will not converge in a time step. If the coupling has not converged, it is very likely that the solution is wrong and the simulation will crash in a few time steps. Moreover, I might not trust the result anymore. Therefore, it would be nice if the simulation would be stopped as soon as the coupling does not converge.

**Describe the solution you propose.**
It would be nice, if one could tell preCICE to be strict on the convergence/divergence behavior. This could be a new input parameter in the input file that does not break the current interface. One might consider an option after how many diverged time steps/time windows one wants the simulation to be aborted. 

The parameter could be a new property of the `xxx-convergence-measure` tags. This would give the user the ability to be strict on certain convergence measures they deem important. One possible name would be `strict`. If one wants to allow the coupling to diverge/not converge in at most `n` time steps/windows one could also call it `strict_after_n_time_windows=n`. The default values could be `0` to indicate that preCICE will not abort ever (current behavior).

I would suggest to only implement one of the two options. I came up with the names spontaneously so there is possibly room for improvement. :)

**Comment by uekerman** [comment]
I like the suggestion. Should be easy to implement and could be quite helpful.
In case of non-convergence we could then simply throw a `PRECICE_ERROR` with a meaningful message.

We could handle the functionality here:
https://github.com/precice/precice/blob/657f7596b1428d5b26c97eeaa9c26c13b4a32d9e/src/cplscheme/BaseCouplingScheme.hpp#L340

Config could look like this

```xml
<relative-convergence-measure limit="1e-3" data="Displacements" mesh="SolidMesh" strict="true"/>
```

I am not too sure about the "after n time windows" yet. @ajaust is there really a use case where you would be OK with non-convergence once, but not twice? 

One thing we have to be careful about is to clearly sort out the behavior with `suffice`. If convergence measure A has `suffice="true"` and convergence measure B has `strict="true"`, what is the behavior if A converges after 5 iterations, but B not yet? Which condition dominates? I would suggest that in this case `strict` should overrule `suffice` (and we could throw a warning that `suffice` is ignored). The alternative would be to forbid this completely: combining both in one config is not allowed.

**Comment by ajaust** [comment]
> I am not too sure about the "after n time windows" yet. @ajaust is there really a use case where you would be OK with non-convergence once, but not twice?

I personally would never be fine with that. :smile: 
I was thinking of applications where people are not worried about bad convergence that much. I have seen people doing simulations where "does not explode (too much)" seemed to be good enough. However, I see now that the people would probable not use strict at all.

> One thing we have to be careful about is to clearly sort out the behavior with `suffice`. If convergence measure A has `suffice="true"` and convergence measure B has `strict="true"`, what is the behavior if A converges after 5 iterations, but B not yet? Which condition dominates? I would suggest that in this case `strict` should overrule `suffice` (and we could throw a warning that `suffice` is ignored). The alternative would be to forbid this completely: combining both in one config is not allowed.

I have not used `suffice` yet. Thus I am not sure what users (or I) would expect, but your proposal sounds reasonable.
