### ISSUE TITLE
Calculation of shape-parameter Gaussian RBF from support-radius

### ISSUE THREAD

**Issue by KyleDavisSA** [precice/precice#765]
**Please describe the problem you are trying to solve.**
Using the Gaussian RBF, it is difficult to specify a shape parameter for any given mesh as this is a function of the Gaussian decay and mesh width.

**Describe the solution you propose.**
A python script is available in preCICE to determine the shape parameter [here](https://github.com/precice/precice/tree/develop/extras/rbfShape). This formula is dependent on the Gaussian decay, number of points that is desired inside a radius around the vertex, and the average mesh width. This equation is desired in situations when you only want a limited amount of vertices to be included in the local RBF interpolation. It would be better for the support radius defined in the `precice-config.xml` file and have preCICE determine the shape parameter internally as a function of the support radius. The Gaussian can then be used by specifying either the shape-parameter or support-radius.

**Comment by uekerman** [comment]
Another interesting use case of letting preCICE determine the mesh width is to only specify the "number of points desired to cover" and then compute an "adaptive" decay for each shape function.

**Comment by KyleDavisSA** [comment]
A naive approach for the mesh width is to find the nearest neighbour for each point and the distance between them, and then set the support radius as a function of this value (say 2 or 3 times this value). Conditioning of the RBF matrix will need to be looked at, but probably will probable be okay if the mesh width changes "gradually".

**Comment by uekerman** [comment]
If the nearest neighbor is easier to get (meaning to implement) and cheaper than the k-nearest neighbors then this could be a good compromise, yes.

**Comment by fsimonis** [comment]
The rbf tagging requires the vertex index tree too. So it has to be generated at some point.
Once it exists, querying it should not be overly expensive.
