### ISSUE TITLE
Configuration of <acceleration:...> allows <data ... /> with identical names

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#766]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 18.04_
preCICE Version: v2.0.2-109-g4bf74dc8

**Describe the problem**

The following configuration does not lead to an error or warning.
```
      <acceleration:IQN-ILS> 
         <data name="Forces" mesh="MeshFluid"/>
         <data name="Forces" mesh="MeshFluid"/>
         <data name="Forces" mesh="MeshFluid"/>
         <initial-relaxation value="0.01"/>
         <max-used-iterations value="3"/>
         <time-windows-reused value="1"/>
         <filter type="QR2" limit="1e-3"/>
      </acceleration:IQN-ILS>
```

**Expected behaviour**

- [x] For preCICE `v2` a warning is expected. https://github.com/precice/precice/pull/767 (not necessary, since it is not a breaking change)
- [x] ~~For preCICE `v3` and later~~ an error is expected (~~breaking change!~~).

**Additional context**

* I will provide a PR to implement a warning soon and refer to it in this issue.
* Let's keep the issue open until we implemented the error for the next major release.

**Comment by BenjaminRueth** [comment]
https://github.com/precice/precice/pull/767 resolves the first todo of this issue.

**Comment by fsimonis** [comment]
Wouldn't it be simpler to always throw an error in this case?
We don't change the interface or anything. We just enforce the semantics of the configuration.

**Comment by uekerman** [comment]
That's not a breaking change to me. It just catches an error. There is no use case for duplicating data vectors in an acceleration.
