### ISSUE TITLE
Improve test coverage for WatchPoint

### ISSUE THREAD

**Issue by uekerman** [precice/precice#781]
We currently don't test for cases **without** mesh connectivity. And, we don't test for parallel (distributed) meshes.
Current tests: https://github.com/precice/precice/blob/develop/src/precice/tests/WatchPointTest.cpp

**Comment by KyleDavisSA** [comment]
So the aim here is firstly to recreate this test but without connectivity (so without `createEdge`)?

https://github.com/precice/precice/blob/7618982a33a340a151c6964430799048314d3bdd/src/precice/tests/WatchPointTest.cpp#L43-L55

**Comment by uekerman** [comment]
> So the aim here is firstly to recreate this test but without connectivity (so without createEdge)?

yes. Then, the watchpoint should use a NN mapping.
