### ISSUE TITLE
Errors during testing preCICE

### ISSUE THREAD

**Issue by henry-yang93** [precice/precice#782]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 19.10_
preCICE Version: 2.0.2
MPICH Version: 3.3
 GCC Version: 9.2.0
 PETSc Version: 3.11.4
 Boost Version: 1.72.0

Add the versions/commit hashes of further adapter and/or bindings.

**Describe the problem**
When I tested  preCICE, errors appeared, errors thrown as:
The following tests FAILED: 2 - precice.action (Timeout) 16 - precice.parallel (Timeout).
After that, I created a debug build of preCICE by passing -DCMAKE_BUILD_TYPE=Debug to cmake. And then ran the tests with this command BOOST_TEST_LOG_LEVEL=all ctest -VV -R precice.parallel 2>&1 > parallel2.log. The file parallel2.log is attached below.

**Step To Reproduce**
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON ..  
make -j4
BOOST_TEST_LOG_LEVEL=all ctest -VV -R precice.parallel 2>&1 > parallel2.log

**Expected
[parallel2.log](https://github.com/precice/precice/files/4865203/parallel2.log)
 behaviour**

**Additional context**
Attach relevant logs and files to this issue.
Format your text (and especially any output/error messages) (see the [GitHub Markdown guide](https://guides.github.com/features/mastering-markdown/)

**Comment by fsimonis** [comment]
Related to #684

**Comment by fsimonis** [comment]
This issue should have been resolved in preCICE version 2.2.0.
@henry-yang93 Can you please try the new version?

**Comment by fsimonis** [comment]
This issue is not reproducible and was most likely fixed in 2.2.0.
