### ISSUE TITLE
False assertion in TXTTableWriter

### ISSUE THREAD

**Issue by uekerman** [precice/precice#786]
Is this assertion really needed?

https://github.com/precice/precice/blob/fa5e664ea6dc464f29341b356d27a425787346a1/src/io/TXTTableWriter.cpp#L33

It prevents the definition of multiple convergence measures for one data field, for example:
```xml
         <absolute-convergence-measure limit="1e-5" data="DataTwo" mesh="MeshOne"/>
         <relative-convergence-measure limit="1e-3" data="DataTwo" mesh="MeshOne"/>
```

If yes, we should find a solution to nevertheless allow for that. Or, in the worst case, prevent false usage in the configuration.

**Comment by fsimonis** [comment]
The assertion makes sense as it forces us to produce a unambiguous output. :wink:

The above would create convergence and iteration files with the following headers:

```
precice-One-iterations.log
---
TimeWindow  TotalIterations Iterations Convergence AvgConvRate(DataTwo) AvgConvRate(DataTwo)
```

```
precice-One-convergence.log
---
TimeWindow  Iteration  ResNorm(DataTwo)  ResNorm(DataTwo)
```

We could add a prefix to each `ResNorm` and `AvgConvRate`. Something like `AbsCM` and `RelCM`:

This would result in something like this:
```
precice-One-iterations.log
---
TimeWindow  TotalIterations Iterations Convergence AbsCMAvgConvRate(DataTwo) RelCMAvgConvRate(DataTwo)
```

```
precice-One-convergence.log
---
TimeWindow  Iteration  AbsCMResNorm(DataTwo)  RelCMResNorm(DataTwo)
```

Not pretty by any means, but at least unambiguous. So it is maybe a good point to rethink the naming of the headers.

**Comment by uekerman** [comment]
Good point, but actually, I guess it's even simpler: Not only the headers will be duplicated, but also the columns if I see it right. We should not use an assertion there, but simply a "return".
