### ISSUE TITLE
Make structure0815 usable again

### ISSUE THREAD

**Issue by floli** [precice/precice#79]
Currently fails with
```
mpicxx -o main.o -c -g3 -O0 -DPRECICE_USE_MPI -Dtarch=tarchp2 -DSTRUCTURE_DEBUG_MODE -DDebug -DAsserts -I/home/florian/precice/src main.cpp
main.cpp:8:10: fatal error: tarch/la/WrappedVector.h: No such file or directory
 #include "tarch/la/WrappedVector.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by floli** [comment]
Also remove obsolete cruft like ```PRECICE_USE_MPI``` and ```'tarch=tarchp2```

**Comment by uekerman** [comment]
+1
A follow-up TODO would probably be to also test this "solver" again, since it has not been used since Bernhard's thesis, I suppose.

**Comment by uekerman** [comment]
Further follow-up: Use the solver in a tutorial.

**Comment by fsimonis** [comment]
Closed as it was moved to its own repository https://github.com/precice/6dof-rigid-body-solver

**Comment by MakisH** [comment]
> Closed as it was moved to its own repository https://github.com/precice/6dof-rigid-body-solver

GitHub also has a "move issue" feature. I understand that the problem still exists, so I assume we can move it and keep it open.
