### ISSUE TITLE
Build is unsupported by default

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#801]
**Please describe the problem you are trying to solve.**
When configuring preCICE, the resulting library will be static by default.
We currently do not support using preCICE as a static library as both the CMake config and the pkg-config files do not support the static library. ( The current CMake config is missing depending targets)

Thus our build system is **unsupported by default**.

**Describe the solution you propose.**

There are many solutions to this problem (ranked by workload):

1) Always build a shared library and forget about static libraries altogether.   
  _This obviously prevents to use preCICE as a static library, which is unreasonable._
4) Set `BUILD_SHARED_LIBS` to `ON` if not explicitly specified. PR: #796 
  _This will change a CMake default and may surprise users. This could be regarded as a breaking change._
2) Always build both shared and static libraries and only directly support the shared case.
  Requires to build preCICE internally as an object library first to prevent recompilation. This is required for hidden symbol visibility, so we should do it at some point anyhow.
3) Extend the CMake script to fully support static libraries.
  This requires to export some internal dependencies and requires to propagate the dependencies to the dependant.

**Additional context**
* The solverdummy tests currently fail when building static. Due to the same issue as #716 .
* Static pkg-config #313 
* User running into problems with static CMake #716 
* The default for xSDK is to build as a shared library. However, this requirement will be shifted from CMake to Spack in the future.

**Comment by MakisH** [comment]
>     2. Set `BUILD_SHARED_LIBS` to `ON` if not explicitly specified. PR: #796
>        _This will change a CMake default and may surprise users. This could be regarded as a breaking change._
Until now we had the the definition that _"breaking == breaking the API or configuration"_. We also had the rule that _"if nobody uses a hidden feature, killing it (if possible with some deprecation placeholder) is ok"_. We have also changed already a few times things in the build system and location of files during 1.x. This was, of course, terribly ugly, but I think in this case it doesn't make sense to think of it as breaking. Breaking the broken default?

>     3. Always build both shared and static libraries and only directly support the shared case.
>        Requires to build preCICE internally as an object library first to prevent recompilation. This is required for hidden symbol visibility, so we should do it at some point anyhow.

I don't like this idea, for two reasons:
- When both the static and the shared library are present, the linker often prefers the static, which can cause difficult-to-debug issues. Please correct me if I am wrong.
- Building both by default would increase the building time a lot, making us prefer again a non-default setting.

**Comment by uekerman** [comment]
> Until now we had the the definition that "breaking == breaking the API or configuration". We also had the rule that "if nobody uses a hidden feature, killing it (if possible with some deprecation placeholder) is ok". We have also changed already a few times things in the build system and location of files during 1.x. This was, of course, terribly ugly, but I think in this case it doesn't make sense to think of it as breaking. Breaking the broken default?

Yes, I agree. I would neither see this as "breaking enough". We should just avoid changing things in the build system with every release. 

Discussed with @fsimonis today, leaning towards option 4. That's why we moved it to v2.2.

**Comment by fsimonis** [comment]
Update:

Implementing and testing the static library support on all platforms is a major hassle. Writing correct configuration files for CMake and pkg-config makes this even more complicated. Current versions of proposed solutions #313 #973 are fiddly and fragile.

My proposition to finally get rid of this problem: Make `BUILD_SHARED_LIBS` default to `ON`.

Switching the default shared libraries has some major upsides:
* We have to deal with symbol visibility soon #623 to simplify the windows port.
This will improve the binary size as well as potential for link-time-optimization.
* We won't have issues with conflicting versions of internal dependencies such as fmtlib or json, as their symbols are hidden.
* No need to relink the solver software after library updates.
