### ISSUE TITLE
Clearly define and enforce allowed states and transitions in SolverInterfaceImpl

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#816]
**Please describe the problem you are trying to solve.**

Our user interface currently offers many possible ways how the user can interact with it. Flexibility is, of course, nice, but some of the currently allowed workflows do not have an obvious use-case (e.g. calling `finalize()` without `initialize()`). If we limit the scope of allowed workflows this will help us to limit the number of things that can possibly go wrong and it will help our users to not run into dead-ends.

**Describe the solution you propose.**

`SolverInterfaceImpl` provides different [states](https://github.com/precice/precice/blob/4aa6a302def46bb2fbc85bcd7263d4c08fe16183/src/precice/impl/SolverInterfaceImpl.hpp#L553-L558) that we already use to check for correct transition between states. #806 added some more checks. I would propose to

1. clearly define which states and transitions are allowed. (read/write before initialize? finalize without initialize?...)
2. add `PRECICE_CHECKS` to avoid invalid transitions and (if necessary) update the tests correspondingly.

Note that especially the second point might cause a lot of work. Example: If we decide to forbid `State::Construction -> State::Finalized`, we will also have to update [this test](https://github.com/precice/precice/blob/4aa6a302def46bb2fbc85bcd7263d4c08fe16183/src/precice/tests/SerialTests.cpp#L161-L171).

**Additional context**

Note that we will end up with a more restrictive execution model for preCICE. Before restricting allowed usage of preCICE, we should carefully evaluate the restrictions that we introduce. We don't want to removing actual functionality, but only execution paths without a real use-case.

See also [this figure](https://github.com/precice/precice/pull/806#pullrequestreview-449720594).

**Comment by uekerman** [comment]
Not breaking in my opinion if we don't restrict real use cases.

**Comment by uekerman** [comment]
connected to #225

**Comment by fsimonis** [comment]
This was mostly resolved by the resource cleanup #772

**Comment by BenjaminRodenberg** [comment]
@fsimonis Can we close this issue? If not, let's move it to 3.x.x, because it does not sound critical for 3.0.0.

**Comment by fsimonis** [comment]
This was resolved by #806 and updated in #1350
