### ISSUE TITLE
Deprecate API method getMeshIDs

### ISSUE THREAD

**Issue by MakisH** [precice/precice#821]
As discussed in https://github.com/precice/precice/pull/813, there seems to be no clear use case for `getMeshIDs`. Moreover, this currently returns an `std::set<int>`, which is a bit tricky to map to other languages.

Unless there is a clear use case for this, we should deprecate it and later remove it, to avoid additional complexity.

**Comment by fsimonis** [comment]
We could add `PRECICE_DEPRECATED()` as a log macro and always print a message like this:
`The called function "getMeshID()" is deprecated and will be removed in a future release.`.

Then the question is which log level to pick  for this: warning, info, or debug?

**Comment by MakisH** [comment]
That would be indeed very handy, but we don't currently have anything, do we? It should be an info message, I think: warning would mean that something could go wrong in the simulation, which is not the case, while debug many people don't look at.

**Comment by uekerman** [comment]
I like that, too :+1: 
Would be great if that could also be used in the bindings then. We already have some deprecated functions there now. 
And this way we can easily search the code base for things to delete when releasing v3.0. 
`debug` is not enough. I would vote even for `warning`. Then, users are reminded that they need to change sth. `info` gets easily overlooked. But no strong opinion.

**Comment by MakisH** [comment]
Actually, that message should be shown at build time, so a warning would be best.
