### ISSUE TITLE
Remove deprecated API functions in fortran bindings

### ISSUE THREAD

**Issue by IshaanDesai** [precice/precice#822]
In https://github.com/precice/precice/pull/815 the following function names were changed in the fortran bindings to make them consistent with the C++ API:

1. `precicef_ongoing_()` --> `precicef_is_coupling_ongoing_()`
2. `precicef_write_data_required_()` --> `precicef_is_write_data_required_()`
3. `precicef_read_data_available_()` --> `precicef_is_read_data_available_()`
4. `precicef_action_required_()` --> `precicef_is_action_required_()`

Old functions are deprecated for `v2.1.0`. The deprecated functions need to be removed in a major release.

**Comment by mardom1** [comment]
I am interested in working on this issue. Looking at the pull request, I gathered the following steps:

- remove the function declarations in `extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp` 
- remove the function definitions in `extras/bindings/fortran/src/SolverInterfaceFortran.cpp`
- update changelog

Did I miss something?

**Comment by IshaanDesai** [comment]
Should be the two locations you have mentioned should be the ones :+1:
The last three deprecated functions have probably already been removed, please check once.

**Comment by mardom1** [comment]
You are correct, only `precicef_ongoing_()` is still there.

**Comment by IshaanDesai** [comment]
> You are correct, only `precicef_ongoing_()` is still there.

Okay. Removing it would be helpful!
