### ISSUE TITLE
MPI initialization does not work for multiple SolverInterfaces

### ISSUE THREAD

**Issue by uekerman** [precice/precice#828]
When creating two SolverInterfaces from one Python script, one runs into this problem: 

```c++
ASSERTION FAILED
  Location:          static void precice::utils::Parallel::initializeManagedMPI(int*, char***)
  File:              /home/jaustar/software/compilescripts/precice/precice-82cf90a/src/utils/Parallel.cpp:196
  Rank:              0
  Failed expression: !_isInitialized
  Argument 0: A managed MPI session already exists.
```

Could also be a general problem, not sure if this is related to the Python bindings. 
Reported by @ajaust, I have not yet tried to reproduce it.

**Comment by ajaust** [comment]
Just for reference. This was tested with preCICE commit `82cf90a` and Python bindings in version `v2.0.2.1`.

**Comment by fsimonis** [comment]
Related to #655
