### ISSUE TITLE
Remove meshName from solverdummies input arguments

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#829]
See comment https://github.com/precice/precice/pull/750#discussion_r457119970.

Let's remove `meshName` from the solverdummies input arguments, since it is somehow redundant to the `solverName`and hardcode it.

This will also require us to update our tests accordingly.

**Comment by BenjaminRueth** [comment]
Since 2.2.0 is a minor release we should try to avoid breaking code. I would suggest to use a reasonable default, if `meshName` is not provided. If a user provides `meshName` we can accept it, but throw a deprecation warning. We can then finally remove `meshName` in 3.0.0.
