### ISSUE TITLE
Test Action Timings

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#831]
**Please describe the problem you are trying to solve.**
We cannot test if, when and how often actions have been triggered by preCICE.

**Describe the solution you propose.**
Add a `CountingAction`, which contains a `static std::map<Timing, int>`.
Everytime `performAction()` is called, it increments the counter of its timing.
This map can be accessed by `CountingAction::count(Timing::XXX)` and `CountingAction::resetCounter()`.

We can configure this action in integration tests and check the counters after each invocation of interface functions.

Related to #823 and #711

**Comment by fsimonis** [comment]
Better solution than counting is to keep a list of timings.
This allows us to check if the actions were fired in the correct orderer.

**Comment by uekerman** [comment]
closed by #823
