### ISSUE TITLE
FSI with interFoam and CalculiX

### ISSUE THREAD

**Issue by jianzhou722** [precice/precice#833]
**Please describe the problem you are trying to solve.**
I am trying to use preCICE to numerically investigate the flow dynamics of a density current interacting with a bottom-mounted elastic thin plate.

**Describe the solution you propose.**
I am thinking of whether InterFoam (the VOF multiphase OpenFOAM solver) can be coupled with CalculiX with the capacity of dynamic meshing. Would it be a similar route to this link (https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-OpenFOAM-and-CalculiX)? Thanks!

**Comment by MakisH** [comment]
Thank you for your interest, @jianzhou722! Please ask your question again in [our forum](https://precice.discourse.group/c/what-is/9), where we can discuss in more detail and more people will see it. In preCICE we use the issues only for bug reports and feature requests. :-)
