### ISSUE TITLE
Porting all boost tests to template style

### ISSUE THREAD

**Issue by uekerman** [precice/precice#84]
@floli set up some nice template tests in `testing/boosttests/ExampleTests`.
We should port all existing tests now to these templates. Afterwards we should also try to execute the test in arbitrary order. 

Before doing this, two small TODOs. (otherwise the templates should be good to go in my opinion)
 * Can we add an example for logging output etc. in one of the test examples?
 * Do we have a place where we can add methods that should always be executed when entering and leaving a test, like a default fixture?

When entering: we need: `precice::testMode = true;`

When leaving, we need to reset all static variables. Here are those that I have on my radar:
```c++
  mesh::Mesh::resetGeometryIDsGlobally();
  mesh::Data::resetDataCount();
  impl::Participant::resetParticipantCount();
  precice::utils::EventRegistry::clear();
  utils::MasterSlave::reset();
  MasterSlave::_communication.reset();
  utils::Parallel::clearGroups();
```

**Comment by uekerman** [comment]
I also will add a further example showing how to deal with 2 participants and individual global communicators

**Comment by floli** [comment]
Did I understand you correctly, these calls should be executed at the beginning and leaving of each test?

```precice::testMode = true;``` needs to be set only once, not?

**Comment by uekerman** [comment]
> `precice::testMode = true;` needs to be set only once, not?
You are right. This only needs to be set once. The reset statements however, we have to do for every test. How should we do that? (Is there a possibility without adding explicitly another fixture?)

**Comment by uekerman** [comment]
I added furthers examples. These still look pretty complicated. I still think this should go in the examples to avoid that people have to figure out these nasty details over and over again. However, can we improve this? Move stuff to fixtures?

**Comment by floli** [comment]
Current state is that I have no idea how to add a fixture to **all** tests. I've posted a question on the boost mailing lists, but I don't expect any replies there.
