### ISSUE TITLE
Misleading error message "Data X is currently not exchanged"

### ISSUE THREAD

**Issue by MakisH** [precice/precice#842]
Example situation:

```xml
<exchange data="Pressure" mesh="Fluid1-Mesh" from="Fluid1" to="Fluid2"/>
<exchange data="Velocity" mesh="Fluid2-Mesh" from="Fluid2" to="Fluid1"/>

<relative-convergence-measure limit="1.0e-3" data="Pressure" mesh="Fluid2-Mesh"/>
<relative-convergence-measure limit="1.0e-3" data="Velocity" mesh="Fluid2-Mesh"/>
```

This will lead to the following error message:
```
ERROR:  You need to exchange every data that you use for convergence measures and/or the iteration acceleration. Data "Pressure" is currently not exchanged, but used for convergence measures and/or iteration acceleration. Please check the <exchange ... /> and <...-convergence-measure ... /> tags in the <coupling-scheme:... /> of your precice-config.xml.
```

A user here would get confused, as the the data is actually exchanged, but not over the respective mesh.

We should include the name of the mesh here (which is currently not directly available in the scope):
https://github.com/precice/precice/blob/42abc38c9d82a719db0f6982548b6d979931ccf6/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L1091-L1096

**Comment by uekerman** [comment]
Extending

**Comment by MakisH** [comment]
> Extending
> 
> https://github.com/precice/precice/blob/42abc38c9d82a719db0f6982548b6d979931ccf6/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L736
> 
> should do the job.
> 
> The method was solely implemented for this error message anyway IIRC.

Actually, I am not sure if this would be trivial. If I understand the data structures correctly, from here I could indeed return an `std::pair` of the `data` and the `mesh`, but this `mesh` would be the one associated with the `data` globally, not the one used for the `exchange` of this `data`. I would need to again iterate over the exchanges, find which mesh the `data` actually is exchanged over, etc.

I prefered to make the error message more specific, instead of introducing additional machinery that we don't really need.

**Comment by uekerman** [comment]
Sounds like you could at least give the actual needed mesh then? Would improve the error message already.
