### ISSUE TITLE
TestOutput missing tests log / debug output

### ISSUE THREAD

**Issue by MakisH** [precice/precice#848]
**Please describe the problem you are trying to solve.**
When running tests with `make test`, one gets a quick overview of which test suites fail (already very important and much better than before), but not much information apart from this. One usually needs to dig deeper into available options in CTest, find which exact tests are failing, and get more information.

**Describe the solution you propose.**
We already have a folder `TestOutput/` which is essentially the working directory for each test suite. In there, we have the usual log files (e.g. events), but not the tests output one would get in debug mode.

I propose that we always include there:
- A preCICE logger with debug level (i.e. modify the `precice-config.xml`)
- The output of the tests itself (if possible, not sure how)

**Describe alternatives you've considered**
We currently handle this with [documentation](https://github.com/precice/precice/wiki/Tests), but this is not really enough. We could still extend the documentation, with a clear workflow for understanding a failing test. This could also be useful as a reference for our [contributing guide](https://github.com/precice/precice/blob/develop/docs/CONTRIBUTING.md).

**Additional context**
Mainly triggered by #847, where `TestOutput/` does not have anything more than the `precice-run` for the failing `partition/` tests.

**Comment by uekerman** [comment]
Clear upvote on the problem. We could then also ask users to send us their output if tests fail.

> A preCICE logger with debug level (i.e. modify the precice-config.xml)

I guess you mean a `log.conf` file, right? For the tests, there is no single `precice-config.xml`.
But why should that be in the `TestOutput` folder? Then, you still need to run everything again.
Better would be ...

> The output of the tests itself (if possible, not sure how)

And even better could be to have a separate output file for each package.

And just to be sure: the terminal output should not be changed in my opinion.

**Comment by fsimonis** [comment]
@MakisH Does #880 address all of these problems?

**Comment by MakisH** [comment]
> @MakisH Does #880 address all of these problems?

@fsimonis no, #880 does not increase the log level, so the problem remains. I would still need to modify this manually and run commands different than the default `make test` to understand what is going on.

What we want here is to just tell somebody "oh you got a failure in the partition tests? Please send us the file `TestOutput/partition/test.log` and this should have information that we can use to debug the issue without asking for more information.

I see #880 as an improvement to the formatting, but this issue remains open.

**Comment by fsimonis** [comment]
@MakisH Right!
We could also hardcode the log level of the file output to debug. This would make the log less useful though.
Another option would be to add a third logger which always outputs trace information to a `test.trace.log`. This would contain _all_ available information.

**Comment by MakisH** [comment]
I guess one only checks these logs if things go wrong and we only run these tests once, so let the logs be as informative as possible. Multiple loggers could be helpful as well.

**Comment by fsimonis** [comment]
There is a problem with using only the logger though. The test messages and assertions do not appear in the output.

**Comment by fsimonis** [comment]
https://github.com/precice/precice/blob/00589fe951f9715174eafbd66657294e0d8eb8e4/src/testing/main.cpp#L56-L76
