### ISSUE TITLE
Refactor rank and size variables

### ISSUE THREAD

**Issue by floli** [precice/precice#85]
We have the convention, that private members are prefixed by an _underscore, public ones are not. There are various places, where we have public members with an underscore. These should be either private or the _underscore should be removed.

@uekerman I think most of these were introduced by you. One of the most prominent examples is ```utils::MasterSlave::_rank / _size```. It is unclear how ```_rank``` differs from ```utils::Parallel::getProcessRank()``` and why we have both.

Please decide if we fix the underscore or make it public. I'm happy to help you fixing the underscore in the code base by casting a magic Emacs global-search-and-replace spell upon thy sinners whose hath used the _underscore.

* [x] replace `_rank` and `_size` by `getRank()` and `getSize()`
* [ ] replace `_masterMode` and `_slaveMode` by `isMaster()` and `isSlave()`

**Comment by BenjaminRueth** [comment]
![skizze](https://user-images.githubusercontent.com/5740604/38878395-2303bad2-4261-11e8-9ad7-a5c8fed27019.png)

Both ways to access the rank do not return the same value.

**Comment by uekerman** [comment]
Suggestion:
 * rename MasterSlave::_rank / _size to sth like getRank / getSize
 * get completely rid of the methods in utils::Parallel
 * use only IDs to distinguish different participants in tests
 * also rename _masterMode, _slaveMode

**Comment by uekerman** [comment]
Last bits were done in #702
