### ISSUE TITLE
Check to prevent duplicated entries in acceleration config is too strict

### ISSUE THREAD

**Issue by ajaust** [precice/precice#850]
Hi,

I ran into the following problem and was wondering whether your assertions are too strict or whether I did something wrong the whole time.

**Describe your setup**

- Ubuntu 18.04 LTS
- preCICE v2.1.0 installed together with the Python bindings version v2.1.0.1. 
- The solver the I invoke is written in Python using FEniCS 2019.1.0. 
- All packages have been installed via Spack with gcc@9.3.0.

**Describe the problem**

When starting the simulation it complaints about the duplicate occurence of the data tag `Displacement`. 

```
<class '__main__.InputParameters'>
Configuring preCICE
(0) 12:31:40 [acceleration::AccelerationConfiguration]:154 in xmlTagCallback: ERROR: You have provided a subtag <data name="Displacement" ... /> more than once in your <acceleration:.../>. Please remove the duplicated entry.
```

This configuration has been valid in preCICE v2.0.X and (with some changes regarding keywords) in v1.6.X.

**Step To Reproduce**

Run the simulation with the attached configuration or with some keyword that appears twice. 

This is related to my coupling described on discourse:
- https://precice.discourse.group/t/two-couplings-to-one-interface-mixed-dimensional-coupling/68/5
- https://precice.discourse.group/t/two-couplings-to-one-interface-reloaded/260/10

**Expected behaviour**
I expect the simulation to run as normally with duplicate data name tags as before since the mappings are all between different meshes.

**Additional context**

Possibly related to https://github.com/precice/precice/issues/698

**Attachements**

- [precice-config.xml.txt](https://github.com/precice/precice/files/5145089/precice-config.xml.txt)

**Comment by ajaust** [comment]
Just for completenes: Changing the configuration to for the Displacements to have different identifiers `DisplacementTop` and `DisplacementBottom` fixes the problem. It is still unclear to me whether the first configuration that I have used before is actually illegal.

**Attachements**
- [precice-config-modified.xml.txt](https://github.com/precice/precice/files/5145152/precice-config-modified.xml.txt)

**Comment by uekerman** [comment]
The error we introduced in https://github.com/precice/precice/commit/7b9fb630f5929ecf04b84593e72ea73bb6a819df is too strict. Identical data names on different meshes should be allowed.
@ajaust: As far as I see your config is legal.

**Comment by BenjaminRueth** [comment]
Does this mean that we should revert https://github.com/precice/precice/pull/767? I am a bit unsure whether this is the right approach. If renaming duplicate names solves the issue there is a solution to this issue. Is the naming `DisplacementTop`/`DisplacementBottom` that we currently enforce through the error a better one than the naming with identical names that was used previously? 

* Yes: Then I think it makes sense to enforce the use of unique names by raising an error, if identical names are detected. 
* No: If the use of unique names is only a work-around to avoid the error message without improving the configuration, then it would be better to allow duplicate names.

Is there a real use-case for duplicate entries in the acceleration config?

In the end it is also a question whether duplicate names were legal before (then https://github.com/precice/precice/pull/767 is technically a breaking change) or whether duplicate names were always illegal (then https://github.com/precice/precice/pull/767 is a bugfix).

**Comment by BenjaminRueth** [comment]
After personal discussion with @uekerman we are now able to define the legal and illegal cases:

### case 1

```
<data name="Displacement" mesh="FractureMeshTop"/> 
<data name="Displacement" mesh="FractureMeshBottom"/> 
```

Is **legal**, but raises an exception. This is a bug that has to be fixed.

### case 2

```
<data name="Displacement" mesh="FractureMeshTop"/> 
<data name="Displacement" mesh="FractureMeshTop"/> 
```

Is **illegal** and raises an exception since #767 

### case 3

```
<data name="DisplacementTop" mesh="FractureMeshTop"/> 
<data name="DisplacementBottom" mesh="FractureMeshBottom"/> 
```

is **legal**, but a workaround for the buggy case 1 from above. Better use the suggested config from case 1.

**Comment by BenjaminRueth** [comment]
@ajaust If you want, you can take a look at #863. I think that the new implementation should work with the config you provided above.

**Comment by ajaust** [comment]
@BenjaminRueth I have tested it with my solver (via the Python bindings) and it worked nicely. :-) Thanks for the fix!
