### ISSUE TITLE
preCICE erroneously expects cyclic communicator for IMVJ with restart

### ISSUE THREAD

**Issue by ajaust** [precice/precice#851]
I ran into a problem when using preCICE's IMVJ acceleration in parallel together with FEniCS (Dolfin). It seems it tries to set up a communicator that is cyclic even though it does not want/need one?!

I open the issue here as it seems related to the preCICE core and not to the preCICE Python bindings.

**Describe your setup**

- Ubuntu 18.04 LTS
- preCICE v2.1.0 installed together with the Python bindings version v2.1.0.1. 
- The solver the I invoke is written in Python using FEniCS 2019.1.0. 
- All packages have been installed via Spack with gcc@9.3.0.

You can build the environment via spack. Some packages are not in the official Spack repository, but can be found in the GitHub repository mentioned in the attachements.

**Describe the problem**

When I run preCICE from Python in conjunction with FEniCS I run into a problem, iff I use IMVJ acceleration and the participant computing the acceleration is running in parallel. The simulation either hangs when being finalized or it crashes on initialization.

**Step To Reproduce**

I have setup a minimal example in the repository below. 

1. Install preCICE and FEniCS via Spack given the configuration in the attachement.
2. Load the environment. I generate a module file with `spack env loads -r` and source the resulting module file in a fresh shell.
3. Start the two solvers 
```
mpirun -n 2 ./dummydolfinsolver.py precice-config-IMVJ.xml SolverA MeshA
mpirun -n 2 ./dummydolfinsolver.py precice-config-IMVJ.xml SolverB MeshB
```
4. The simulation will fail:
    1. If you run a release build of preCICE, `SolverB` will hang in `interface.finalize()`. `SolverA` finishes normally.
    2. If you run a debug build of preCICE, `SolverB` crashes while `SolverA` might crash and/or hang. All ranks of `SolverB` show the following error message:
```
ASSERTION FAILED
  Location:          void precice::acceleration::impl::ParallelMatrixOperations::establishCircularCommunication()
  File:              /tmp/jaustar/spack-stage/spack-stage-precice-2.1.0-hhsl5io7wrmayaqdc53b4bu57uo3o67y/spack-src/src/acceleration/impl/ParallelMatrixOperations.cpp:33
  Rank:              0
  Failed expression: _needCyclicComm
```
I could reproduce the problem on two different machines (Laptop + Server).

**Expected behaviour**

The simulation finishes nicely. 

**Additional context**

- The problem **only** occurs if `SolverB` runs in parallel. If `SolverB` is run with `mpirun -n 1` it finishes nicely. I guess that is related with the acceleration being computed on `SolverB`.
- The number of threads for `SolverA` seems to be irrelevant.
- If ILS acceleration is used, everything is fine. A corresponding preCICE configuration is in the repository.

**Attachements**

- Repository for reproducing the error: https://github.com/ajaust/precice-dolfin-imvj-parallel-bug

**Comment by ajaust** [comment]
I am currently debugging this a bit further and made the following oberservation:

I have FEniCS and preCICE also installed on the laptop installed where FEniCS is installed via the system's package manager (apt) and preCICE is compiled by hand. I had several preCICE versions on the machine. 

1. The test case runs normally, if I preCICE v2.0.2. 
2. I get the same error as above if preCICE v2.1.0. I only tested the debug build.

I will check tomorrow if I can confirm this behavior in a Spack environment.

**Comment by uekerman** [comment]
Looks like a bug we introduced in https://github.com/precice/precice/commit/6e7207ed32ca3d3e4fc9f41e7370886f93bb9a01

The following looks suspicious:

https://github.com/precice/precice/blob/54fcdb83f9bef91c2cb22125eaa5d9f179ae2b67/src/acceleration/impl/ParallelMatrixOperations.cpp#L10-L20

Should rather be:
```c++
if (needCyclicComm && (utils::MasterSlave::isMaster() || utils::MasterSlave::isSlave())) {
  _needCyclicComm = needCyclicComm;
  establishCircularCommunication();
} else {
  _needCyclicComm = false;
}
```

so

```diff
+ if (needCyclicComm && (utils::MasterSlave::isMaster() || utils::MasterSlave::isSlave())) {
- if (utils::MasterSlave::isMaster() || utils::MasterSlave::isSlave()) {
```

@ajaust Could you please give that a try?

**Comment by ajaust** [comment]
This seems to fix it for me. I have opened a PR: https://github.com/precice/precice/pull/852

**Comment by fsimonis** [comment]
@ajaust Thanks for the bug report and the fix! Yes, this bug was introduced by the refactor in #747.

We need more tests to catch bugs like these.
