### ISSUE TITLE
Travis CI fails due to Eigen being fetched from deleted Bitbucket repository

### ISSUE THREAD

**Issue by ajaust** [precice/precice#853]
Travis CI in #852 fails with 
```
+wget -nv http://bitbucket.org/eigen/eigen/get/3.3.2.tar.bz2 -O -
+tar xj -C /home/travis/local/eigen3 --strip-components=1 eigen-eigen-da9b4e14c255
https://bitbucket.org/eigen/eigen/get/3.3.2.tar.bz2:
2020-09-02 06:59:10 ERROR 403: Forbidden.
```

It seems that the Eigen project has abandonded their BItbucket repository and moved to GitLab so maybe you want to change the download link to:
https://gitlab.com/libeigen/eigen/-/archive/3.3.2/eigen-3.3.2.tar.bz2

**Comment by fsimonis** [comment]
Thanks for reporting the issue. This was fixed in e6949ed.
