### ISSUE TITLE
Remove deprecated API functions mapWriteDataFrom and mapReadDataTo

### ISSUE THREAD

**Issue by uekerman** [precice/precice#859]
... and also the associated mapping timing.

There is currently no use case for these functions.

**Comment by BenjaminRodenberg** [comment]
Thought the same when working on #1038. When removing these functions: We should also revise `DataContext`.

**Comment by BenjaminRodenberg** [comment]
I added the `[[deprecated]]` attribute to these functions. See commit above.

**Comment by BenjaminRodenberg** [comment]
#1222 is now merged into the breaking branch `precice:develop-v3.0.0`.
