### ISSUE TITLE
Cleanup preallocation options for PETSc RBF Mappings

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#873]
We currently have a quite low test coverage in the [PETSc radial-basis function mapping](https://github.com/precice/precice/blob/develop/src/mapping/PetRadialBasisFctMapping.hpp).

To be more precise, we only test the `Tree` preallocation strategy. All remaining strategies `Compute`, `Save`, `Estimate`, `None` are not tested at all.

See the file on [CodeCov](https://codecov.io/gh/precice/precice/src/develop/src/mapping/PetRadialBasisFctMapping.hpp)

**Comment by fsimonis** [comment]
Check if there is a clear preference and remove obvious candidates.

**Comment by davidscn** [comment]
It seems that only the `preallocation=tree` and `preallocation=save` is working as expected right now. All other preallocations failed with respect to the rescaling and resulted in a quite huge error.
