### ISSUE TITLE
HierarchicalAitkenPostProcessingTest is not doing any testing

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#88]
In HierarchicalAitkenPostProcessingTest.cpp there is no BOOST_TEST being performed. See https://github.com/precice/precice/blob/e450c2d1753bac6b60dddb73fac54ea25320f53f/src/cplscheme/boosttests/HierarchicalAitkenPostProcessingTest.cpp::50

**Comment by floli** [comment]
That is the case with some tests. It's still better than no test at all, because the code runs at least. If you can make up a suitable test, that would be great.
Maybe @scheufks has some input?

**Comment by uekerman** [comment]
I fully agree with Florian (e.g. we also have many assertions in the code, which are tested) though in this particular case you should not invest more time. Hierarchical Aitken was something Bernhard tried out long time ago and to my best knowledge, it has never properly worked for test applications. 
Fyi, the link above does not work. What works nicely is to directly copy the link to the commit https://github.com/precice/precice/commit/f35bfabad18d3368928e62e59d402e8dcb447a31
