### ISSUE TITLE
Extending error sub-vector of residual-sum preconditioner "numerically zero"

### ISSUE THREAD

**Issue by ajaust** [precice/precice#882]
**Please describe the problem you are trying to solve.**

The error message leaves out other possible solution and could be more informative.

Current message:
```
[acceleration::ResidualSumPreconditioner]:53 in _update_: ERROR: A sub-vector in the residual-sum preconditioner became numerically zero. Thus, the preconditioner is no longer stable. Please try the value preconditioner instead.
```

**Describe the solution you propose.**

I would like to suggest the following extensions:
1. At the moment the suggested solution to a near zero `residual-sum` preconditioner is the `value` preconditioner.  An alternative would be to stick to the `residual-sum` preconditioner and to use the `freeze-after` option.
2. Maybe print the the current value of the current `residual-sum` that is considered "numerically zero" and the limit you use. At least that would be nice to know
    1. Trusting your choice of what "numerically zero" is, i.e. is your limit `1e-14` or `1e-6`?
    1. I (personally) want as much information as possible to potentially track down which part of the residual goes to zero too quickly. 

The new error message could look like that:

```
[acceleration::ResidualSumPreconditioner]:53 in _update_: ERROR: A sub-vector in the residual-sum preconditioner became numerically zero (1.42425e-22 < 1e-14). Thus, the preconditioner is no longer stable. Please try the freeze-after option or the value preconditioner instead.
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ajaust** [comment]
I looked into the Benjamin Uekermann's PhD thesis since I ran into this problem of a sub-vector becoming zero again.

Now I have some further questions/remarks:

- From the formulation of the error message I do not really understand which sub-vector parts becomes zero. Is it the `\tilde{x}^j - x^j` part or rather the numerator of the fraction (see p. 51 in the thesis)?
- Why is it a problem, if a sub-vector becomes zero? Am I not happy that some part of the solution is converged? 
- If a sub-vector is zero, could we decide to neglect this part when computing the residual sum. This parts does not need nor introduce anything to the scaling so I guess we are happy? Miriam suggested something like neglecting such parts in a recent meeting.
- The thesis mentions the work by Marks and Luke who use the square root of the sum as scaling factor to avoid overscaling. Is it an option in preCICE to use the square-root or is it not implemented? I am not completely sure about the implications yet, but I would be curious about it. The thesis mentions that it did not yield any benefit for FSI simulations, but it might be beneficial for other simulations.

**Comment by KyleDavisSA** [comment]
> Trusting your choice of what "numerically zero" is, i.e. is your limit 1e-14 or 1e-6?

In the residual-sum preconditioner, we use the check 
```
PRECICE_CHECK(not math::equals(X, 0.0), ....
```
should the `0.0` be changed to something else? This is to check if `X = 0.0`

**Comment by KyleDavisSA** [comment]
We compute the sum of each sub-vector as this sum cannot be zero as we need to divide by this value

```
PRECICE_CHECK(not math::equals(_residualSum[k], 0.0)

_weights[i + offset]    = 1 / _residualSum[k];
_invWeights[i + offset] = _residualSum[k];
``` 

We could change the check to a warning, and only update the weights if `_residualSum[k] != 0.0`, else the weights remain constant and are initialized to `1.0`

**Comment by KyleDavisSA** [comment]
PR https://github.com/precice/precice/pull/946 is an initial fix for this problem.
