### ISSUE TITLE
Remove finalize from example code

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#893]
Calling `finalize` is optional, since it is implicitly called by the destructor:

https://github.com/precice/precice/blob/6f5596f80dd522f8e3734beb4d0774a165c0bb66/src/precice/impl/SolverInterfaceImpl.cpp#L142-L148

However, currently we are calling `finalize` in our solverdummies: 

https://github.com/precice/precice/blob/6f5596f80dd522f8e3734beb4d0774a165c0bb66/examples/solverdummies/cpp/solverdummy.cpp#L96

This suggest to our users that `finalize` has to be called. Wouldn't it be better to only call `finalize`, if needed and otherwise let the destructor do the work? I suggest to remove `finalize` from all solverdummies, since it is not needed. If we agree that this makes sense, then we also should modify the other examples (language bindings solverdummies & tutorials).

**Comment by uekerman** [comment]
I am not sure if we need to remove `finalize` here. In the end, it is still allowed to call `finalize`. 

> This suggest to our users that finalize has to be called.

In my opinion this should not be the job of the solverdummies, but of the documentation (new section "how to couple your code"). The solverdummies should just be programs to copy from or to quickly test things.

Short: with `finalize` or without `finalize` both are OK, but we currently have it with `finalize` already, so let's keep it and focus on more important things :smile: 

(different argumentation for the FEniCS adapter paper: there we want things to be as compact as possible)

**Comment by BenjaminRueth** [comment]
Ok :+1: I agree and close this issue.
