### ISSUE TITLE
Error while setting up connection between solvers running parallel master-slave mode

### ISSUE THREAD

**Issue by scheufks** [precice/precice#9]
I recently tried to run precice for the 3dTube scenario in parallel using the master-slave mode. 
Apparently, the connection between the solvers fails with the following error-message:

```
 | 13:16:47     | precice::impl::SolverInterfaceImpl::configure()         | [PRECICE] Run in coupling mode
 | 13:16:47     | precice::impl::SolverInterfaceImpl::configure()         | [PRECICE] Run in coupling mode
 | 13:16:47     | precice::impl::SolverInterfaceImpl::configure()         | [PRECICE] Run in coupling mode
 | 13:16:47     | precice::impl::SolverInterfaceImpl::initialize()        | Setting up master communication to coupling partner/s 
 | 13:16:47     | precice::impl::SolverInterfaceImpl::initialize()        | Setting up master communication to coupling partner/s 
 | 13:16:47     | precice::impl::SolverInterfaceImpl::initialize()        | Setting up master communication to coupling partner/s 
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::remove: No such file or directory: "../.Fluid_Solver-Structure_Solver.address"
 | 13:16:47     | precice::com::SocketCommunication::acceptConnection()   | (0)  [PRECICE] ERROR: Accepting connection at port 37889 failed: boost::filesystem::rename: No such file or directory: "../.Fluid_Solver-Structure_Solver.address~", "../.Fluid_Solver-Structure_Solver.address"
```

Indeed, there are no *.address files in the scenario directory. Also, if *.address files are created manually before the simulation is executed, they appear to be deleted during the initialization process. 
The relevant configuration in the preCICE.xml is given below: 
  
```
   <participant name="Fluid_Solver">
            <master:mpi-single/>
            <use-mesh name="Fluid_Nodes" provide="yes" />
            <use-mesh name="Fluid_CellCenters" provide="yes" />
            <use-mesh name="Structure_Nodes" from="Structure_Solver" />
            <use-mesh name="Structure_CellCenters" from="Structure_Solver" />
            <write-data mesh="Fluid_CellCenters" name="Stresses" />
            <read-data mesh="Fluid_Nodes" name="Displacements" />
            <mapping:nearest-projection direction="write" from="Fluid_CellCenters" to="Structure_CellCenters" constraint="conservative" timing="initial"/>
            <mapping:nearest-projection direction="read" from="Structure_Nodes" to="Fluid_Nodes" constraint="consistent" timing="initial"/>
        </participant>

        <participant name="Structure_Solver">
            <use-mesh name="Structure_Nodes" provide="yes"/>
            <use-mesh name="Structure_CellCenters" provide="yes"/>
            <write-data mesh="Structure_Nodes" name="Displacements" />
            <read-data mesh="Structure_CellCenters" name="Stresses" />
        </participant>

        <m2n:sockets port="0" from="Fluid_Solver" to="Structure_Solver"  exchange-directory="../"/>
```

Let me know if you can reproduce this behaviour and whether this is a bug in preCICE or due to wrong configuration/execution. 
@Haroogan @floli @uekerman

**Comment by Haroogan** [comment]
There should be no `.*.address*` files in the exchange directory before the start of simulation.  So it is recommended to run the `rm -rf .*.address*` command before running the simulation.  preCICE itself during initialization will create `../.Fluid_Solver-Structure_Solver.address~`, then rename it to `../.Fluid_Solver-Structure_Solver.address`, and then delete it.  This is needed to establish connection between two independently running solver executables.  So if you didn't have `.*.address*` files prior running the simulation which could interfere with the ones written by preCICE, then I have no idea how something like this could happen.  Try to apply my recommendations and rerun.

**Comment by uekerman** [comment]
i was able to reproduce that problem. i erased all files beforehand. the problem already occurs when i only start the "accepting" participant. will do some debugging as soon as i find some time :)

**Comment by uekerman** [comment]
fixed my problem. @scheufks are you sure that both your parallel participants have the master tag specified?

**Comment by Haroogan** [comment]
@uekerman, for the posted configuration, this is clearly not the case, i.e. `<master:mpi-single/>` is missing between the `<participant name="Structure_Solver">` and `</participant>` tags.

**Comment by uekerman** [comment]
yeah, somehow i didn't see that klaudius had already posted the config :) sry.
anyway, this is no bug, but a feature. I will add a decent error message!

**Comment by scheufks** [comment]
ok, fixed my problem. It occurred due to the missing <master:mpi-single/> tag. Thank you guys!!
