### ISSUE TITLE
Refactoring cplscheme/boosttests

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#90]
I think that in cplscheme/boosttests there is some potential for refactoring with respect to duplicate code:

* an identical ```connect``` function is in 
    * CompositionalCouplingSchemeTest.cpp
    * ParallelImplicitCouplingSchemeTest.cpp
    * SerialImplicitCouplingSchemeTest.cpp
    * ExplicitCouplingSchemeTest.cpp

  **can we move this into a common fixture?**

* In CompositionalCouplingSchemeTest.cpp the first two lines of many tests are the following:
    ```
    std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint());
    std::string readIterationCheckpoint(constants::actionReadIterationCheckpoint());
    ```

  **can we move this into a common fixture?**

# Progress

- [x] CompositionalCouplingSchemeTest.cpp moved to #145 
- [x] ParallelImplicitCouplingSchemeTest.cpp https://github.com/precice/precice/commit/609302b79a87d044cfc4acb3645beae1a1e08b69
- [x] `SerialImplicitCouplingSchemeTest.cpp` https://github.com/precice/precice/commit/46d737281050302983ca5c0848c4a5f651ba9c3a
- [x] `ExplicitCouplingSchemeTest.cpp` nothing further to be done https://github.com/precice/precice/issues/90#issuecomment-416169022
- [x] merge `refactoringTestsWRTM2NFixture` in `develop`

**Comment by floli** [comment]
I want to take some points into consideration before making the code a common fixture:
- Discoverability: We have quite some fixtures in Testing.hpp and for me it's still unclear when to use which
- General value: MasterComFixture is currently used in two files (both in cplscheme), M2NFixture isn't used at all. I know when one works on parallel tests, one may think that almost every other test needs that setup code. But most tests probably don't
- Testing.hpp is included in **every** test file. It already includes 
```
#include "utils/MasterSlave.hpp"
#include "com/Communication.hpp"
#include "com/MPIDirectCommunication.hpp"
#include "m2n/M2N.hpp"
#include "m2n/GatherScatterComFactory.hpp"
#include "m2n/SharedPointer.hpp"
```
among others. More fixtures to be added there likely need more include, blowing up compile and linking times, as well as the binary size

Fixtures are just normal classes, please consider wether you could also add them to a file in ```./boosttests/```. We could also think about moving the fixtures which setup communication to a separate file in ```testing```.

**Comment by uekerman** [comment]
We actually don't need a new fixture here. This is the standard case for the `M2NFixture`. I refactored `SerialImplicitCouplingSchemeTest` in this regard (see commit above). 
@BenjaminRueth Can you please refactor the other test classes the same way?

Please note that I did not replace the `connect` functionality in `testConfiguredAbsConvergenceMeasureSynchronized` as this test actually tests the instantiation of a `M2N` communication through the configuration. 

@floli I think, we will not need more fixtures than we already have and those will appear in many packages (e.g. I still have to port the `partition` tests). Still, I agree that compilation time is becoming a problem. Maybe we can move these advanced features in another header and include this header only for parallel tests? Probably this is a story for another issue.

**Comment by uekerman** [comment]
I forgot: for the constants I would recommend to always use directly the constants API, `constants::actionWriteIterationCheckpoint()`. This is not much longer than writing `writeIterationCheckpoint`, right?

**Comment by floli** [comment]
See #91 
This issue can be closed wrt me.

**Comment by uekerman** [comment]
I would wait until @BenjaminRueth refactored the other tests as well before we close the issue.

**Comment by floli** [comment]
What's the state on that issue? I think it could be closed. Testing.hpp just pulls in minimal dependencies.

**Comment by floli** [comment]
@BenjaminRueth  Could you please go through the code and remove or adapt the parts that reference that issue:
```
20 candidates:
./src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp:45:  void connect( // TODO this function occurs in multiple tests. Move this to a common fixture? see https://github.com/precice/precice/issues/90
./src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp:253:  void connect( // TODO this function occurs in multiple tests. Move this to a common fixture? see https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:198:  void connect // TODO this function occurs in multiple tests. Move this to a common fixture? see https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:223:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:245:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:266:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:293:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:324:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:359:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:397:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:435:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:485:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:519:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:553:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:589:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:623:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:662:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:707:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:750:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
./src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp:800:  std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint()); // TODO can we move this into a common fixture? See https://github.com/precice/precice/issues/90
```

**Comment by BenjaminRueth** [comment]
I'm removing `connect` from `ParallelImplicitCouplingSchemeTest, ExplicitCouplingSchemeTest, CompositionalCouplingSchemeTest` like suggested in https://github.com/precice/precice/issues/90#issuecomment-352041537 by @uekerman above.

However, I am not 100% sure yet what to do with `std::string writeIterationCheckpoint(constants::actionWriteIterationCheckpoint());` in `CompositionalCouplingSchemeTest`. Maybe it was just a former misunderstanding by me and the todo could just be removed.

**Comment by BenjaminRueth** [comment]
In some tests of `ExplicitCouplingSchemeTest.cpp` I could not remove `connect` by using the M2NFixture (see https://github.com/precice/precice/commit/55a62a2b3aae8274c2705b815a44cb057036b0c0). Does anybody know a solution? As soon as `connect` has been removed from `ExplicitCouplingSchemeTest.cpp`, we could close this issue.

Since for `CompositionalCouplingSchemeTest.cpp`, I assume that removing `connect` and using the M2NFixture will be a bit more involved, I opened a follow up issue #145.

**Comment by BenjaminRueth** [comment]
I removed the todos in `CompositionalCouplingSchemeTest.cpp` related to `writeIterationCheckpoint(constants::actionWriteIterationCheckpoint());` (see https://github.com/precice/precice/commit/ff4c2d7332cdbf1801664b83fcabe13f570e16da). Using a fixture seems to me a bit like an overkill.

**Comment by BenjaminRueth** [comment]
cd69661a4388f50b9da44789856950756cb54a8b closes this issue
