### ISSUE TITLE
Assertion in QR Factorization triggered in a parallel setup

### ISSUE THREAD

**Issue by IshaanDesai** [precice/precice#901]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 18.04_
preCICE Version: 2.1.1

FEniCS-Adapter commit https://github.com/precice/fenics-adapter/commit/61166ffd27ddb3d9808bc442c4e8d5f02cce75ea is used to reproduce this issue.

The IQN-ILS acceleration scheme triggers the assertion. The coupling scheme configuration is as follows:
```
      <coupling-scheme:serial-implicit>
         <participants first="HeatDirichlet" second="HeatNeumann"/>
         <max-time value="1"/>
         <time-window-size value=".1" valid-digits="8"/>
         <max-iterations value="100"/>
         <exchange data="Flux"        mesh="DirichletNodes" from="HeatDirichlet" to="HeatNeumann" />
         <exchange data="Temperature" mesh="NeumannNodes" from="HeatNeumann"   to="HeatDirichlet" initialize="true"/>
         <relative-convergence-measure data="Flux"        mesh="DirichletNodes" limit="1e-4"/>
         <relative-convergence-measure data="Temperature" mesh="NeumannNodes" limit="1e-4"/>
	 <acceleration:IQN-ILS> 
            <data name="Temperature" mesh="NeumannNodes"/>
            <initial-relaxation value="0.01"/>
            <max-used-iterations value="3"/>
            <time-windows-reused value="1"/>
            <filter type="QR2" limit="1e-3"/>
	 </acceleration:IQN-ILS>
	<acceleration:aitken>
            <data name="Temperature" mesh="NeumannNodes"/>
	    <initial-relaxation value="0.1"/>
	</acceleration:aitken>
      </coupling-scheme:serial-implicit>
```
The assertion is not triggered when Aitken acceleration is used:
```
<acceleration:aitken>
   <data name="Temperature" mesh="NeumannNodes"/>
   <initial-relaxation value="0.1"/>
</acceleration:aitken>
```

**Describe the problem**
In https://github.com/precice/fenics-adapter/commit/61166ffd27ddb3d9808bc442c4e8d5f02cce75ea there is a folder `prototyping_parallel/` which runs the `HT/paritioned-heat/fenics-fenics` tutorial in a parallel manner. When both participants (Dirichlet and Neumann) are run with two processors, the following assertion is triggered in the first time window:
```
ASSERTION FAILED
  Location:          int precice::acceleration::impl::QRFactorization::orthogonalize(Eigen::VectorXd&, Eigen::VectorXd&, double&, int)
  File:              /home/ishaan/precice/src/acceleration/impl/QRFactorization.cpp:322
  Rank:              1
  Failed expression: _globalRows != _rows
  Argument 0: 6
  Argument 1: 6
  Argument 2: 1
```
The convergence log is as follows:
```
TimeWindow  Iteration  ResRel(Flux)  ResRel(Temperature)
1  1  1.0000000000000000  0.0491716871394381
1  2  0.0049482890250160  0.0482578821093446
```
**Note**: The domain decomposition in FEniCS for this particular case is done in such a way that one only rank on either participants has the complete coupling boundary. The other rank on either participants has an empty mesh.

**Step To Reproduce**
1. *FEniCS*, *Python bindings for preCICE* and *FEniCS-Adapter for preCICE* need to be pre-installed to reproduce this issue.
1. Open the folder `prototyping_parallel/` in https://github.com/precice/fenics-adapter/commit/61166ffd27ddb3d9808bc442c4e8d5f02cce75ea in two separate terminals
2. In one terminal run: `mpirun -np 2 python3 heat.py -d`
3. In the other terminal run: `mpirun -np 2 python3 heat.py -n`
4. Observe that the assertion is triggered in the second terminal

**Expected behaviour**
The coupling case is expected to run smoothly.

**Comment by IshaanDesai** [comment]
@uekerman can provide a more detailed explanation why this assertion is triggered for this particular way of domain decomposition.

**Comment by oguzziya** [comment]
Until @uekerman gives more detailed theoretical information, I tried to reproduce it and it appears that it assumes that all the partitions have mesh, which does not have to be true as in this case. In addition, QN tests do not cover empty partition cases. I am not sure about the theoretical background but I make it run by commenting out the assertion in the corresponding line with a test that contains the same setup as yours.

**Comment by uekerman** [comment]
There are enough details already provided :smile: 
I think that the assertion is simply wrong and unnecessary.

@oguzziya Thanks for looking into this. Could you please provide a patch for this? Removing this assertion (and checking if there are more this kind) and maybe adding a test with an empty rank either directly on the QR decomposition level or in the QN tests (so a unit test that runs into the assertion, but still gives correct results when removing the assertion).

**Comment by oguzziya** [comment]
Sure 👍
