### ISSUE TITLE
precice.m2n.mpiports test fails on Intel MPI (with possible solution)

### ISSUE THREAD

**Issue by mennodeij** [precice/precice#923]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _CentOS 8_
Intel 2020u1 compiler
Intel 2020u1 MPI

preCICE Version: develop-branch, v2.1.1-129-g9aaa60bb (personal fork)

**Describe the problem**
When running tests after a build with ctest, all tests pass except for the precice.m2n.mpiports tests. 

**Step To Reproduce**
1. build with shared libs on
2. ctest

**Expected behaviour**
All tests pass

**Possible solution**
The tests are run with MPIEXEC_EXECUTABLE (see cmake/CTestConfig.cmake). If I substitute `mpirun` for `mpiexec` in the test command, the precice.m2n.mpiports test pass. `mpirun` is a shell wrapper around `mpiexec` that sets all sort of environment variables. You may want to consider to change `CTestConfig` to use `mpirun`.

**Comment by fsimonis** [comment]
Thank you for opening this issue.
We rely on the [`FindMPI`](https://cmake.org/cmake/help/v3.10/module/FindMPI.html#usage-of-mpiexec)  module for detecting MPI.
However, I just noticed that we pass the postflags after the arguments to `testprecice`. 

https://github.com/precice/precice/blob/3195955bbe35b5c52d81fb1c1543eb4b4d9d718c/cmake/CTestConfig.cmake#L51-L53

Maybe this is only noticeable with the Intel implementation.
Could you please try if the following change works?

```diff
   add_test(NAME ${PAT_FULL_NAME}
-    COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} 4 ${PRECICE_CTEST_MPI_FLAGS} ${MPIEXEC_PREFLAGS} $<TARGET_FILE:testprecice> ${PAT_ARGUMENTS} ${MPIEXEC_POSTFLAGS}
+    COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} 4 ${PRECICE_CTEST_MPI_FLAGS} ${MPIEXEC_PREFLAGS} $<TARGET_FILE:testprecice> ${MPIEXEC_POSTFLAGS} ${PAT_ARGUMENTS}
     )
```

**Comment by mennodeij** [comment]
Yes that works with Intel MPI. Thanks for finding that 👍
