### ISSUE TITLE
ScaleByDtAction with SCALING_BY_DT is misleading

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#934]
In preCICE the term "dt" has multiple meanings:

* time window size (what we provide in the config, time between two couplings)
* time step size (actual time step size a participant does, what goes into `advance(dt)`)

While working on #639 I observed that the `_scaling` option `SCALE_BY_DT` of `ScaleByDtAction` is very confusing:

The scaling is performed based on `fullDt` (i.e. the time window size):

https://github.com/precice/precice/blob/3195955bbe35b5c52d81fb1c1543eb4b4d9d718c/src/action/ScaleByDtAction.cpp#L45-L50

Documentation talks about the (computed) time step, which sounds for me like the actual time step:

https://github.com/precice/precice/blob/3195955bbe35b5c52d81fb1c1543eb4b4d9d718c/src/action/ScaleByDtAction.hpp#L16-L17

Finally in configuration it also sounds more like the time step:

https://github.com/precice/precice/blob/3195955bbe35b5c52d81fb1c1543eb4b4d9d718c/src/action/config/ActionConfiguration.cpp#L95-L102

### My Suggestion:

Since the implementation uses the time window size, I would suggest to follow the implementation and fix the documentation correspondingly (I'm already preparing a bigger PR for #639). However, we should update the name of the actual actions to something less confusing. 

https://github.com/precice/precice/blob/3195955bbe35b5c52d81fb1c1543eb4b4d9d718c/src/action/config/ActionConfiguration.cpp#L28-L30

are no good names. I propose:

```
NAME_SCALING_BY_TIME_STEP_TO_TIME_WINDOW_RATIO("scale-by-time-step-to-time-window-ratio"), 
NAME_SCALING_BY_COMPUTED_TIME_WINDOW_PART_RATIO("scale-by-computed-time-window-part-ratio"), 
NAME_SCALING_BY_TIME_WINDOW_SIZE("scale-by-time-window-size"), 
NAME_SCALING_BY_TIME_STEP_SIZE("scale-by-time-step-size"), 
```

If we want to make this a non-breaking change, we will need some aliases, as well. Please note that I introduced a fourth option for the time step scaling, as well.

For #639 I'm already modifying the names in the code, but keep the actual tags in the configuration the same, since I don't want to break existing code (i.e. `NAME_SCALING_BY_TIME_WINDOW_SIZE("scale-by-dt")`).

**Comment by BenjaminRodenberg** [comment]
Let's try to implement this soon and use aliases in the configuration for making it non-breaking. We can deprecate the old configuration tags remove them in the next major release.

**Comment by ChatBot-2021** [comment]
https://github.com/ChatBot-2021/ChatBot/discussions

Have websites/games chat that needs watching. Click this link go to general and tell me if and where you need me. Also just come to relax and chat with other users.

**Comment by uekerman** [comment]
Small detail: So far, we mostly used "timestep" in preCICE, not "time step" (in contrast to "time window"), meaning it should be `scale-by-timestep-size`.

**Comment by fsimonis** [comment]
Moving this to version 3.

We either rework and reword it, or we remove it altogether.

**Comment by BenjaminRodenberg** [comment]
This action is removed in the context of #1358. So we will be able to close this issue with v3.
