### ISSUE TITLE
Broken link "preCICE overview" in README.md

### ISSUE THREAD

**Issue by caro314** [precice/precice#938]
**Describe the problem**
There is a link called "[preCICE overview](https://camo.githubusercontent.com/b272f4efcb409fbf5fbe05a1d34bc94177a031cc21fd8f80eb3298f9a21f9d53/68747470733a2f2f7777772e707265636963652e6f72672f6173736574732f707265636963655f6f766572766965772e706e67)" in the [README.md ](https://github.com/precice/precice/blob/develop/docs/README.md) which forwards to a "Not Found" webpage when clicking on it. Already checked this on another laptop, of course.
Also by the way, in my Safari, I only see a question mark where I am supposed to read "preCICE overview" in another browser. Screenshot:
<img width="868" alt="Bildschirmfoto 2021-01-15 um 22 21 50" src="https://user-images.githubusercontent.com/54809072/104780370-fa32dd80-5780-11eb-9312-d08e60d4ef99.png">

**Comment by MakisH** [comment]
Thanks a lot for noticing and reporting this, @caro314! Fixed in #936.
