### ISSUE TITLE
Add commit hash to xml reference generated by binprecice md

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#952]
**Please describe the problem you are trying to solve.**

`precice/build/binprecice md > reference.md` generates the configuration reference:

```
# precice-configuration

Main tag containing preCICE configuration.
...
```

Adding the version/commit hash of the generating `binprecice` helps us to quickly find out to which revision a `reference.md` belongs to. For a possible use-case see https://github.com/precice/precice.github.io/pull/13#issuecomment-762981414.

**Describe the solution you propose.**

Depending on what we want, we can either print the version/commit hash

```
# precice-configuration for preCICE v2.1.1-168-gcab21ce5

Main tag containing preCICE configuration.
...
```

or just add a comment

```
<!--This file was generated by binprecice v2.1.1-168-gcab21ce5 -->
# precice-configuration

Main tag containing preCICE configuration.
...
```

I hope that implementing this is not complicated. I personally have no idea, but assume something similar is already there, since precice already prints the current revision via its logger:

```
---[precice]  This is preCICE version 2.2.0
---[precice]  Revision info: v2.1.1-168-gcab21ce5
---[precice]  Configuration: Debug
---[precice]  Configuring preCICE with configuration "/home/benjamin/tutorials/HT/partitioned-heat/fenics-fenics/precice-config.xml"
---[precice]  I am participant "HeatDirichlet"
---[precice]  Setting up master communication to coupling partner/s
```

If it is complicated it's probably not worth it.

**Comment by fsimonis** [comment]
This is not difficult, but we currently are quite far in the release process. Let's implement this on develop.

**Comment by uekerman** [comment]
:+1: 
I like the comment version better. I see no use case for having this public to the reader. For them, it should already be clear that the reference always belongs to the last release.
