### ISSUE TITLE
C++ Solverproxy does not build

### ISSUE THREAD

**Issue by floli** [precice/precice#97]
```
scons: Reading SConscript files ...

scons: warning: Can't find Intel compiler top dir for version='None', abi='x86_64'
File "/home/florian/precice/tools/solverproxies/cpp/SConstruct", line 43, in <module>
scons: done reading SConscript files.
scons: Building targets ...
icc -o solverproxy-debug main.cpp -L/home/florian/precice/build/debug -lprecice -lpython2.7 -lpthread
main.cpp(94): error: identifier "actionReadSimulationCheckpoint" is undefined
    if (interface.isActionRequired(actionReadSimulationCheckpoint())){
                                   ^

main.cpp(185): error: identifier "actionWriteSimulationCheckpoint" is undefined
      if (interface.isActionRequired(actionWriteSimulationCheckpoint())){
                                     ^

compilation aborted for main.cpp (code 2)
scons: *** [solverproxy-debug] Error 2
scons: building terminated because of errors.
```

**Comment by uekerman** [comment]
I just updated the Fortran proxy. #111 
I would recommend to follow the same scheme for all proxies:
 * Assume that preCICE is built as dynamic lib
 * Use the same `precice-config.xml`

I will also add a few lines in the wiki.

**Comment by floli** [comment]
The C++ solver proxy is just one file, I doubt it actually needs a build system, for me, some changes and the command line `mpic++ -I$PRECICE_ROOT/src main.cpp -lprecice -o proxy` successfully built it.
I am for deleting the SConstruct files, add the compile command line as a comment in main.cpp.
The exiting SConstruct files are highly tailored to some specific system.
