### ISSUE TITLE
CMake fails to find PETSc with pkg-config 0.29.2 and CPATH defined

### ISSUE THREAD

**Issue by besserox** [precice/precice#972]
**Describe your setup**

Initially discovered when installing preCICE using EasyBuild https://github.com/easybuilders/easybuild-easyconfigs/pull/12270
but reproduced in a Docker image of Ubuntu 20.10 Groovy

Operating system (e.g. Linux distribution and version): _Ubuntu 20.10_
preCICE Version: 2.2.0

**Describe the problem**

- The FindPETSc.cmake delivered with preCICE heavily relies on `pkg-config` to find PETSc.
- With new version 0.29.2, `pkg-config` will not return the required flags `-I` if already set in the `CPATH` environment variable (https://github.com/frida/pkg-config/commit/4ade8fc90115c4932bc198a500a1efd13f243cd4)
- So if `CPATH` contains the include path to the PETSc headers, preCICE will not be able to find PETSc and fails with error

```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Detecting additional PETSc prefixes
-- pkg-config will search the following paths:
-- Checking for module 'PETSc>=3.12'
--   Found PETSc, version 3.13.4
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PETSc (missing: PETSc_INCLUDE_DIRS) (found suitable version
  "3.13.4", minimum required is "3.12")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPETSc.cmake:229 (find_package_handle_standard_args)
  CMakeLists.txt:216 (find_package)
```

**Step To Reproduce**

1. Start a Docker of Ubuntu 20.10 because it provides `pkg-config` 0.29.2
```
docker run -ti ubuntu:groovy
```

2. Install requirements for preCICE
```
apt install wget cmake build-essential libboost-all-dev libeigen3-dev libxml2-dev python3-numpy petsc-dev
```

3. Download preCICE
```
wget https://github.com/precice/precice/archive/v2.2.0.tar.gz
tar -xvzf v2.2.0.tar.gz
mkdir build
```

4. Run CMake without `CPATH` -> It works
```
cd build
cmake ../precice-2.2.0/ -DPRECICE_PETScMapping=ON
```
```
# This commands returns the correct include path
pkg-config --cflags-only-I PETSc
```

5. Run CMake with `CPATH` defined -> It fails
```
# clean build directory first
export CPATH=/usr/lib/petscdir/petsc3.13/x86_64-linux-gnu-real/include
cmake ../precice-2.2.0/ -DPRECICE_PETScMapping=ON
```
```
# Reason: this command returns nothing
pkg-config --cflags-only-I PETSc
```

**Additional context**

This was initially discovered when using EasyBuild because the module created for PETSc sets the `CPATH` to the PETSc headers. A workaround has been implemented in https://github.com/easybuilders/easybuild-easyconfigs/pull/12270 to disable this new behavior of `pkg-config`.

I believe that this bug comes from the FindPETSc.cmake shipped with preCICE because libXML2 is impacted in the same way, but CMake still manage to detect it properly. 
A bug fix could probably take inspiration from the way it is done for libXML2 https://github.com/Kitware/CMake/blob/master/Modules/FindLibXml2.cmake

**Comment by besserox** [comment]
An additional comment here:
Using `PETSc_DIR` to tell CMake where to find PETSc does not work either.

**Comment by fsimonis** [comment]
I wasn't aware of _this_ issue with pkg-config.
Have you tried if it works when using pkgconf instead?

[pkgconf](https://packages.ubuntu.com/focal/pkgconf) is a rewrite of [pkg-config](https://packages.ubuntu.com/focal/pkg-config) which is a drop-in replacement (both packages install `/usr/bin/pkg-config`) and handles for example transitive dependencies more reliably. It is also the preferred version on spack.

I am not sure how to deal with this error. The point of pkg-config is to expose these flags, not hide them.
As a walkaround one can always manually define the cache variable `PETSc_INCLUDE_DIRS`.

> 5. Run CMake with CPATH defined -> It fails

```
export CPATH=/usr/lib/petscdir/petsc3.13/x86_64-linux-gnu-real/include
cmake ../precice-2.2.0/ -DPRECICE_PETScMapping=ON -DPETSc_INCLUDE_DIRS=/usr/lib/petscdir/petsc3.13/x86_64-linux-gnu-real/include
```

**Comment by besserox** [comment]
I have not tried with `pkgcong`. 

The workaround I use to [build preCICE with EasyBuild](https://github.com/easybuilders/easybuild-easyconfigs/pull/12270)
is to define the environment variable `PR PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1` which tells pkg-config to not strip the `-I` cflags. 



I'm not sure how it should be fixed, but the main problem in the logic of [FindPETSc.cmake](https://github.com/precice/precice/blob/develop/cmake/modules/FindPETSc.cmake) is that it completely relies `pkg-config`.
If `pkg-config` is not installed or is wrong, then finding PETSc will simply fail, even if `PETSc_DIR` is provided.

IMO, `pkg-config` should only be used to find hints about where to find PETSc. Then the hints provided by `pkg-config`, and others hint likes `PETSc_DIR` should be used to search for PETSc (using `find_path()`, `find_library()`). 

This is kind of what is done in [FindLibXml2.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindLibXml2.cmake).

**Comment by fsimonis** [comment]
@besserox Can you please check if PR #993 fixes the issue for you?

Detecting PETSc libraries and include directories on various distributions is a huge pain as the packaging methods and directories vary strongly. Relying (and enforcing) what pkg-config contains is the only sane way to reliably find PETSc. (Except CentOS, but that is another story)

A PETSc-provided `PETSc-Config.cmake` would be a long term solution, but we have to make due with the pkg-config until that becomes reality (and for backwards compatibility).

**Comment by besserox** [comment]
@fsimonis Yes, that solves the issue for me. Thanks!
