### ISSUE TITLE
Print norm differences consistently using fixed width scientific notation

### ISSUE THREAD

**Issue by ajaust** [precice/precice#975]
**Please describe the problem you are trying to solve.**

The `relative two-norm diff` changes formatting during simulations which makes it hart to read. All other numbers concerning the residual use scientific notation with fixed width. However, the difference (`diff`) starts with decimal notation and then moves back and forth between scientific notation and decimal notation depending on the size of the difference. That makes it hard to compare how close I am actually to the limit. 

See this example here:
```
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 1, limit = 1e-06, normalization = 3.6512e-09, conv = false
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = inf, limit = 1e-06, normalization = 0, conv = true
(0) 17:05:57 [impl::SolverInterfaceImpl]:439 in advance: iteration: 2 of 100, time-window: 1, time: 0 of 1, time-window-size: 1, max-timestep-length: 1, ongoing: yes, time-window-complete: no, read-iteration-checkpoint 
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 0.9, limit = 1e-06, normalization = 3.6512e-09, conv = false
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 1, limit = 1e-06, normalization = 6.19228e-13, conv = false
(0) 17:05:57 [impl::SolverInterfaceImpl]:439 in advance: iteration: 3 of 100, time-window: 1, time: 0 of 1, time-window-size: 1, max-timestep-length: 1, ongoing: yes, time-window-complete: no, read-iteration-checkpoint 
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 2.50793e-05, limit = 1e-06, normalization = 3.65118e-09, conv = false
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 2.87627e-06, limit = 1e-06, normalization = 6.19228e-12, conv = false
(0) 17:05:57 [impl::SolverInterfaceImpl]:439 in advance: iteration: 4 of 100, time-window: 1, time: 0 of 1, time-window-size: 1, max-timestep-length: 1, ongoing: yes, time-window-complete: no, read-iteration-checkpoint 
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 5.15467e-09, limit = 1e-06, normalization = 3.65118e-09, conv = true
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 0.000430767, limit = 1e-06, normalization = 6.19158e-12, conv = false
```
See how the notation changes back to decimal notation in the last line.

I find it hart to compare decimal notation errors to the limit since the formatting is different. 

**Describe the solution you propose.**

Set all errors (potentially also the limit) to the same fixed width scientific representation for printing on the screen. I have not checked the log files if this is an issue there as well.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ajaust** [comment]
Since I started the discussion on the formatting... 

I would suggest to also change formatting of the residual norms in the `precice-XXX-convergence.log` files. I would suggest fixed width scientific notation with something like six to eight digits.

Here is an example from a simulation:

```
Timestep  Iteration  resNorm(0)  resNorm(1)  
1  1  1.0000000000000000  1.0000000000000000  
1  2  0.0000025079268111  0.8999988697110500  
1  3  0.0000225239851804  0.0000018852670476  
1  4  0.0000000003783936  0.0000000113240367  
1  5  0.0000000000024410  0.0000000000168999 
```

I do not see the benefit by printing all digits at the moment:
- There is no guarantee that you are accurate up to all significant digits in the participants that you are using. There is probably some iterative procedure in these participants that only solves up to a certain accuracy. This would also affect the meaningfulness of digits in preCICE.
 - Having decimal fixed width notation makes you lose accuracy as the scheme converges. In my example, the residual norm only contains **five to six** digits that actually carry information. The others are all zero.
- These long numbers are hard to read.
- The numbers are hard to interpret. Example: Is ` 0.0000000003783936` below my convergence limit of `1e-8`? I cannot judge that easily without actually counting digits and maybe doing this wrong as well.
- The log files get quite large compared to the actual content due to excessive amount of digits/characters being used.

Here is an example how it could look like with fixed width scientific notation:
```
Timestep Iteration resNorm(0) resNorm(1)
1 1 1.000000E+00 1.000000E+00
1 2 2.507927E-06 8.999989E-01
1 3 2.252399E-05 1.885267E-06
1 4 3.783936E-10 1.132404E-08
1 5 2.441000E-12 1.689990E-11
```

**Bonus**: If one would have fixed width notation (does not have to be scientific in this case) for the `Timestep` and `Iteration` set to something reasonably large (maybe 3-5 digits for `Timestep` and 3 for `Iteration`?) one would have a very nicely formatted file. The line length would stay constant for many simulation setups.

**Comment by uekerman** [comment]
Not yet sure about the bonus, but clear upvote on everything else :+1: 
Thanks for the detailed description.

**Comment by ajaust** [comment]
I am not so sure about the bonus myself anymore, but the rest should be useful. ;)

**Comment by DavidSCN** [comment]
For documentation purpose: we fixed now all floating point numbers to scientific notation. This affects not only the convergence file, but also potentially watchpoint files.
