### ISSUE TITLE
Added zero-vector throws error in very last coupling iteration

### ISSUE THREAD

**Issue by ajaust** [precice/precice#976]
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 18.04_
preCICE Version: 2.2.0

**Describe the problem**

I have a test case with very tight convergence measure and very small values (0 up to 1e-12) that are exchanged. These small values are not uncommon for velocities in porous media. The difference matrix is updated with a (almost) zero vector which lets preCICE issue error that crashes the simulation. However, the convergence measures are fulfilled and this is the only coupling time-windows (steady-state simulation). However, I assume that this applies to the last time window in general. 

```
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 6.7474e-08, limit = 1e-06, normalization = 3.65118e-09, conv = true
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:559 in measureConvergence: relative convergence measure: relative two-norm diff = 3.64636e-07, limit = 1e-06, normalization = 6.19158e-12, conv = true
(0) 17:05:57 [cplscheme::BaseCouplingScheme]:563 in measureConvergence: All converged
(0) 17:05:57 [acceleration::BaseQNAcceleration]:201 in updateDifferenceMatrices: WARNING: The coupling residual equals almost zero. There is maybe something wrong in your adapter. Maybe you always write the same data or you call advance without providing new data first or you do not use available read data. Or you just converge much further than actually necessary.
(0) 17:05:57 [acceleration::BaseQNAcceleration]:230 in updateDifferenceMatrices: ERROR: Attempting to add a zero vector to the quasi-Newton V matrix. This means that the residual in two consecutive iterations is identical. There is probably something wrong in your adapter. Maybe you always write the same (or only incremented) data or you call advance without providing  new data first.
```

The overall simulation hangs since the other solver is not informed about this error.

**Step To Reproduce**

1. Set up a simulation with tight convergence measure such that you get (nearly) zero difference vectors
2. Taylor your convergence measure such that it is fullfilled when the simulation aborts due to zero-difference vectors

Example configuration: [precice-config-parallel-implicit.xml.txt](https://github.com/precice/precice/files/6124775/precice-config-parallel-implicit.xml.txt)

**Expected behaviour**

Since this is the very last coupling step, preCICE ignores the last difference vector, i.e. does not update the matrix as it will not be used anymore anyway, and terminates the simulation normally.

**Additional context**
This error appeared after updating a some code to use preCICE 2.2.0 instead of preCICE 1.6.X. It seems that the old versions had a different definition of what is "zero" and the old version was less likely to kill the simulation.

**Comment by ajaust** [comment]
I am not sure if the following is worth a separate issue as it is also related to the `zero vector` error. 

As mentioned on Gitter, I have a general "problem" with the new definition of what is `zero` in some cases. I ported an older code from preCICE 1.6.1 to 2.2.0. Now, I have the problem that I cannot reproduce the old results. The overall result is still fine, but I had done a convergence study with very strict convergence measures on preCICE 1.6.1. When running the same simulation with preCICE 2.2.0 I get the error above. 

In my application some of the exchanged data is very small (absolute norm) so the differences are also very small. The relative differences/changes are reasonably large. Thus my question would be whether one could
- Influence the definition of zero in an easy way
- Maybe not check **absolute** differences but rather **relative** differences and/or derive a formulation of the problem using the relative differences. 
I thought that the preconditioning should somewhat safe me, but I have to look into the literature a bit more. 

You can find the test case that I am trying to port here: https://git.iws.uni-stuttgart.de/dumux-pub/jaust2020a

**Comment by fsimonis** [comment]
After a discussion. we decided go for a relative check `l2(deltaR)/l2(values)` and use the absolute `l2(deltaR)` as fallback.

**Comment by BenjaminRodenberg** [comment]
Reopening this issue until we have concluded here (https://github.com/precice/precice/pull/1092#issuecomment-934472790) or opened a new issue.

**Comment by BenjaminRodenberg** [comment]
Closing this issue. Refer to https://github.com/precice/precice/issues/1107 for follow-up.
