### ISSUE TITLE
Implementation of BoundingBox Communication Methods

### ISSUE THREAD

**Issue by atotoun** [precice/precice#98]
Implement communication methods for bounding boxes in `CommunicateMesh`. More information will follow.

**Comment by uekerman** [comment]
Hi Amin,

I had an overview look at your code. Good thing that your started to push code, but we have to be careful to not try to solve too many things at once. I suggest to focus first on the communication operations in `com` and later implement the missing parts in `partition`. I would, anyway, recommend a design with everything handled in the existing classes `ProvidedPartion` and `ReceivedPartition`, e.g. an API `communicateBoundingBoxes`, `communicateMeshes`, `compute` ... but we should sketch this first before implementing. 

Concerning the implementation in `CommunicateMesh`, I would favor a further class `communicateBoundingBox`. Some remarks in arbitrary order:
 - `GlobalBoundingBox` is probably not the best name. What about `BoundingBoxMap`?
 - `sendBB` and `receiveBB`, why do the functions work differently concerning the loop over the dimensions?
 - In `receiveBB`, we should add an assertion to check whether the data structure is already set up.
 - `sendBoundingBoxSet` should then be `sendBoundingBoxMap`
 - We probably never need to communicate the dimension. You can access it through the `mesh`. 
 - `receiveBBSet` will not work currently. You always clear the values in `container_box`
 - Btw, `container_box` is also a misleading name, and we use [CamelCase](https://ipvs.informatik.uni-stuttgart.de/sgs/precice/docs/develop/conventions.html)!  
 - Why don you not use `send/receiveBB` in `sendBBSet` ?
 - `sendBoundingBoxFeedBack` is over-engineered. Do we really need extra methods for this?

 We can discuss all these points tomorrow. Once we have proper implementations for the bounding box communication method, we should implement tests in `mesh/com/tests/CommunicateBoundingBoxTests` as a next step. Only afterwards we have a look at the `partition` part again.

**Comment by atotoun** [comment]
Hi Benjamin, 

I am done with the points and now I am working on the test.
Should I commit the communications so you can see them?

**Comment by uekerman** [comment]
Yes, if your code compiles please push it to a new branch and paste your
commit here. I'll have a look then.

**Comment by uekerman** [comment]
I boiled down your implementations a bit. Please have a careful look at my changes: https://github.com/precice/precice/commit/dc6a02f03e0ba8e946d15d9e2c1273d1585e3ba5

In particular, I think it is better to separate here creation of bounding box data structures from their communication, meaning that the receiving methods should assume that the necessary data structures already exist.
