### ISSUE TITLE
Writing to a data field without a 'write-data' tag is not Asserted

### ISSUE THREAD

**Issue by DavidSCN** [precice/precice#989]
**Describe the problem**
Writing data via one of the 'write' functionalities, where no mapping is defined leads to a failure in the following lines of code

https://github.com/precice/precice/blob/6d27ad5db42997bbc06ff97b39eb4999196295b7/src/precice/impl/Participant.cpp#L156-L162

since the `dataContext` is `nullptr`. However, this is either a misconfiguration of the user or of the adapter developer and we should capture it before and provide a more descriptive error message.

**Step To Reproduce**
Configure your data:
```
const int dataID = couplingInterface.getDataID("myData", meshID);
```
and write with this data
```
        couplingInterface.writeBlockScalarData(dataID, writeData.size(), ids.data(), writeData.data());
```

without specifying a mapping for "myData" in the config file.

**Comment by uekerman** [comment]
Could you add the config file for which this breaks? I thought we were catching all possible mistakes already.

**Comment by DavidSCN** [comment]
Using the force data on the second participant as described:
```cpp
    const int dataID = couplingInterface.getDataID("Forces", meshID);
    .
    .
    .
    couplingInterface.writeBlockScalarData(dataID, writeData.size(), ids.data(), writeData.data());
```
in the following config
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
<solver-interface dimensions="2">
    <data:scalar name="Forces" />
    <data:scalar name="Velocities" />

    <mesh name="Test-Square">
      <use-data name="Forces" />
      <use-data name="Velocities" />
    </mesh>

    <mesh name="MeshOne">
      <use-data name="Forces" />
      <use-data name="Velocities" />
    </mesh>

    <participant name="SolverOne">
      <use-mesh name="MeshOne" provide="yes" />
      <use-mesh name="Test-Square" from="SolverTwo" />
      <read-data name="Velocities" mesh="MeshOne" />
      <mapping:nearest-neighbor
        direction="read"
        from="Test-Square"
        to="MeshOne"
        constraint="consistent" />
    </participant>

    <participant name="SolverTwo">
      <use-mesh name="Test-Square" provide="yes" />
      <write-data name="Velocities" mesh="Test-Square" />
    </participant>

    <m2n:sockets from="SolverOne" to="SolverTwo" />

    <coupling-scheme:serial-explicit>
      <participants first="SolverOne" second="SolverTwo" />
      <max-time-windows value="10" />
      <time-window-size value="1.0" />
      <exchange data="Velocities" mesh="Test-Square" from="SolverTwo" to="SolverOne" />
    </coupling-scheme:serial-explicit>
  </solver-interface>
</precice-configuration>
```

**Comment by uekerman** [comment]
OK, I see. The problem is that `Forces` is not defined as a `write-data` in `SolverTwo`. We should indeed catch such problems. But should have nothing to do with a missing mapping.

**Comment by fsimonis** [comment]
Let's solve this problem by refactoring the logic out of the SolverInterface and into the Participant, where it belongs.

Used of the `_dataIDs` are:
* SolverInterfaceImpl::hasData()
* SolverInterfaceImpl::getDataID()
* Validation macros

**Comment by DavidSCN** [comment]
After the refactoring in #1016 I receive the following error message when trying to write coupling data:
```
The dataID 0 is invalid.
...lengthy stacktrace...
Aborted (core dumped)
``` 
Hence, we are not yet done.
