### ISSUE TITLE
Speed up Nearest Projection queries

### ISSUE THREAD

**Issue by floli** [precice/precice#99]
Possibly using the already existing ```boost.geometry``` package for spatial indexing.

**Comment by fsimonis** [comment]
I am currently working on this in my fork of precice.

To use `boost.geometry` as a spatial index for the classes `Edge`, `Triangle` and `Quad`, one must provide adaptors for them. Adapting each class requires to meet the specifications of its concept. The following table is a short summary of the concepts and status:

preCICE | boost.geometry concept | Status
--- | --- | ---
`Vertex` | [Point](https://www.boost.org/doc/libs/1_67_0/libs/geometry/doc/html/geometry/reference/concepts/concept_point.html) | Implemented by @floli 
`Edge` | [Segment](https://www.boost.org/doc/libs/1_67_0/libs/geometry/doc/html/geometry/reference/concepts/concept_segment.html) | Done
`Triangle` | [Ring](https://www.boost.org/doc/libs/1_67_0/libs/geometry/doc/html/geometry/reference/concepts/concept_ring.html) | _In progress_
`Quad` | [Ring](https://www.boost.org/doc/libs/1_67_0/libs/geometry/doc/html/geometry/reference/concepts/concept_ring.html) | _In progress_

Note that `Triangle`and `Quad` model the concept of `Rings` in `boost.geometry` as they are filled polygons _without holes_. `Rings` have to meet the requirements of [Boost.Random Access Range](https://www.boost.org/doc/libs/1_67_0/libs/range/doc/html/range/concepts/random_access_range.html).
I am currently implementing the necessary boilerplate of index-based random access iterators but it takes some time.

**Comment by floli** [comment]
Have you already pushed the changes somewhere in a branch?

**Comment by fsimonis** [comment]
My changes are in the branch [speedup-nearest-projection-mapping](https://github.com/fsimonis/precice/tree/speedup-nearest-projection-mapping). There is cleanup to be done though.

I have seen the `PtrVectorIndexable`. The problem of the `Triangle`and `Quad` classes is that the vertex access is done through the `::vertex(int)` member function.
Is there a direct access that I am not aware of?

**Comment by floli** [comment]
You mean that you can iterate through all vertices in a Quad/Edge?

Without diving into that, just some random (access iterator) thoughts:

* Maybe that even makes sense to be put into Edge / Triangles classes itself?
* You're commit for the Range adaptor seems to contain quite a few boiler plate code. Maybe there is something from boost you can use? Anything that works with boost 1.60 is fine to use.
* IIRC the Quad class is more or less informally deprecated. Maybe @uekerman can elaborate on that?

**Comment by fsimonis** [comment]
Closed through #156
